### ISSUE TITLE
the plugin is based on knxd?

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#1]
Hi @Supergiovane ,your plugin is very useful to me.
the plugin is based on knxd?

i was found the plugin Frequently dropped, if use tp wire Would it be better?

Best Regards

**Comment by Supergiovane** [comment]
Thank you. 
No the node is based on  the native knx.js javascript implementation. 
Tp wire is the way to go. What are you using as transport medium? Radio frequency?

**Comment by songzh96** [comment]
i use ip port is 3671, 
i was use homebridge-knx，it based on knxd，it's very stable.
my home has nearly a thousand group addresses, i was use node-red-contrib-knx-easy,but it often lost connection.

so if use knxd to make a nr plugin,use TP wire or IP,  I think the connect will be stable.
