### ISSUE TITLE
Virtual KNX connection error

### ISSUE THREAD

**Issue by jmfdzolm** [Supergiovane/node-red-contrib-knx-ultimate#100]
Hello,

I have been trying to use the Virtual KNX software supplied by the KNX association with node-red:
https://www.knx.org/knx-es/para-profesionales/empiece-ahora/knx-virtual/

I have reached to use the virtual knx with the NetX OPC server so I think that this emulates a real knx gateway.

When I try to turn on and off a virtual lamp, I get this error:

[debug] 17/11/2020 21:27:00 KnxUltimate-API: useTunneling=true
[debug] 17/11/2020 21:27:00 KnxUltimate-API: Connecting via 192.168.1.35...
[debug] 17/11/2020 21:27:03 KnxUltimate-API: useTunneling=true
[debug] 17/11/2020 21:27:03 KnxUltimate-API: Connecting via 192.168.1.35...
[warn] 17/11/2020 21:27:03 KnxUltimate-API: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
[warn] 17/11/2020 21:27:03 KnxUltimate-API: connection timed out, retrying... 1
[warn] 17/11/2020 21:27:06 KnxUltimate-API: connection timed out, retrying... 1
[warn] 17/11/2020 21:27:06 KnxUltimate-API: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
[warn] 17/11/2020 21:27:06 KnxUltimate-API: connection timed out, retrying... 2
[warn] 17/11/2020 21:27:09 KnxUltimate-API: connection timed out, retrying... 2
[warn] 17/11/2020 21:27:09 KnxUltimate-API: Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

¿Any idea to solve this problem?

Thank for your help,

**Comment by Supergiovane** [comment]
Ho JM
Knx Virtual doesn’t allow external connections. It works only with ETS.  Otherwise it either crashes or doesn’t connect. 
This is a known issue.
