### ISSUE TITLE
 Sending raw value without dpt

### ISSUE THREAD

**Issue by Sven0507** [Supergiovane/node-red-contrib-knx-ultimate#101]
Hello,

Is it possible to implement the function that you can send raw values directly without specifying dpt?
For example: To dim up to 100% of a 4-bit telegram, you have to send value 9.

**Comment by Supergiovane** [comment]
Hello
that's a good question. You intend RAW not really as RAW (a series of HEX) but instead an integer.
You can try by yourself using a knx-node set as universal node.

**Comment by Sven0507** [comment]
Hello
thank you for your answer.
Yes, I mean the HEX RAW. 
If I set the knx node as a universal node, the dpt must still be set, otherwise the message "msg.dpt not set" appears.

**Comment by Supergiovane** [comment]
Mmmmm... i neet do ditch into it, but before i must release another of my nodes...
in the meantime, you could try others KNX nodes. I think "node-red-controb-KNX" node should do what you're asking for...

**Comment by Supergiovane** [comment]
Hi Sven
raw value send will be out with 1.1.94 in about 1 hour.
See the Wiki https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/4.-Messages-to-the-node in about 1 hour, to learn how to use it.

**Comment by Sven0507** [comment]
Hi Supergiovane
thanks for adding the raw value send function.
Unfortunately, the message "msg.dpt not set" appears when the node is in universal mode.

**Comment by Supergiovane** [comment]
Aspetta che guardo...

**Comment by Supergiovane** [comment]
Si, hai ragione, aspetta un attimo... lo sto correggendo.

**Comment by Supergiovane** [comment]
Ok, fixed in v.1.1.95. Out in about 10 minutes.

**Comment by Supergiovane** [comment]
PS: you're one of the very rare people, that starts a message with "Hello". There are so many users, that doesn't even says "Hi".
This is driving me crazy.

**Comment by Sven0507** [comment]
Thank you, works exactly as it should. 😀
