### ISSUE TITLE
Memory leak on many reconnects

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#102]
Hi Supergiovane

Thanks again for this great library! It works very well!

One more thing. If the IP address was wrong, Node-RED stopped after many reconnects because of a memory leak. I know this is not common, but could you take a look at this?

[logs_20201202.log](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5628131/logs_20201202.log)

Tested with version 1.1.82

Regards Heleon

**Comment by Supergiovane** [comment]
Hi Heleon
i'll take a look as soon as possible. Currently i'm a little busy with hikvision-ultimate node.

**Comment by Supergiovane** [comment]
I suspect a leak in the API, not in the node itself...

**Comment by Supergiovane** [comment]
The more speedy way, is to check that the IP4 and IP6 are valid, throug regex...
I'm working on it now.

**Comment by Supergiovane** [comment]
Hi Heleon
can you unzip this file into the **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder and restart nodered? Please let me know if it fixed the issue. Thanks.
[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5628311/knxUltimate-config.js.zip)

**Comment by Supergiovane** [comment]
Hello Heleon
you can direclty install the v.1.1.94. This version has many fixes for deprecated API methods as well as RAW send data to the bus, as well as your memory fix.

**Comment by heleon19** [comment]
Hello Supergiovane
Thank you for your update, will update to this version.
Regards Heleon
