### ISSUE TITLE
Implement status address inside a node

### ISSUE THREAD

**Issue by tuxtof** [Supergiovane/node-red-contrib-knx-ultimate#104]
**Is your feature request related to a problem? Please describe.**
i want control roller shutter and i need multiple nodes:
 - up/down
 - stop
 - set position
- up/down status
 - position status

**Describe the solution you'd like**

It will be wonderfull if we can add multiple GA inside a single node
at least for a command and his status ( same DPT)

ex:
- up/down + up/down status
- set position + position status

**Describe alternatives you've considered**
alternative is to create subflow but it is less confortable to configure and manipulate

**Comment by Supergiovane** [comment]
Hello Tux,
so you want a thing like the node "scene controller", where you can control all the things in a single knx-ultimate node, right?

**Comment by tuxtof** [comment]
Hello Supergiovane

ok let me try to explain a little bit more

first yes i have multiple physical KNX shutter device i want to control

a device have all this GA

![image](https://user-images.githubusercontent.com/180613/102082399-31c10980-3e12-11eb-9a32-ed3aff223502.png)

this KNX device need to be controlled from Node-RED event

today we can do something like this

![image](https://user-images.githubusercontent.com/180613/102084267-3804b500-3e15-11eb-975a-6bc7bf8936e1.png)

my goal would be to have something more simple without using function and universal mode

having node where we can at least group the action GA and the status GA (same DPT)
or even having node relative to device (roller shutter, light, .....) with multiple GA (of different DPT type) and multiple input/output
will be great

what do you think ?

**Comment by Supergiovane** [comment]
Hi Tux,
having a single KNXUltimate shutter node, is a thing that i can implement, but the usefullness of having the status GA inside this shutter node is only, for example, to avoid sending a "down" command if the shutter is already fully closed. This should be already implemented in the physical KNX actuator, as well as sending the status feedback after a movement. This all should be already packed into the physical knx actuator.

About grouping the status in a single node, the work to do this is way more complex than simply add a node and set it to the status GA.
I have done some similar with the scene controller, but in this case, the scene controller is a fully functional stand alone device, useful if you don't have any scene controller in your installation.
Making a single KNXultimate node shutter is a copy of your already installed knx shutter controller.
Other than that, there are shutter controller capable of handling many types of shutter, with up and down travelling times, position of lamellas, orientation of shades etc.
As you for sure understand, if i make a single KNXultimate node shutter, i must implements all these things, even if you don't use that.
This is unfortunately a very very time consuming task! :-(
