### ISSUE TITLE
Interface error

### ISSUE THREAD

**Issue by Dominik2000** [Supergiovane/node-red-contrib-knx-ultimate#105]
**Salutation (i'll not respond to user that at least says "Hello")**
Hello, I installed your knx ultimate node, and I appreciate your very good work 👍.

**Describe the bug**
I installed the newest version of your knx ultimate node. Sadly I cannot listen to any KNX adress because of the error in the screenshot. I have an MDT IP Router and tried it with multicast 224.0.23.12 and ip adress of the gateway.

**To Reproduce**
1. Add the knx device node to a flow
2. Add a new knx gateway. Give it the ip address of the device or the multicast address
3. Import group addresses with CSV file
4. Take one group address
5. Deploy it and wait.
6. There are errors

**Expected behavior**
There are no errors, I have screenshot the error message

**Screenshots**
https://ibb.co/4JfbZbV
https://ibb.co/n8PjK4v
https://ibb.co/d7XFTCH

**Knx-Ultimate Version**
1.1.97

**Are you running node-red behind homematic, docker or anything similar?**
Node red on lxc container in proxmox 6.3-2

**Comment by Supergiovane** [comment]
Hello
Thank you!
There is some “ghost” config node. In the first screenshot, i see an interface “en9” having no ip or that doesn’t exist. 
Please restart nodered and see if it fixes the issue.

**Comment by Dominik2000** [comment]
Sadly this doesn't fix the issue :( I have restarted nodered several times :(

**Comment by Dominik2000** [comment]
But you're right, I get error messages even if I delete the temperature node.

**Comment by Supergiovane** [comment]
Look at the right, in the node-red menu, there is an option to view the configuration nodes. Search for an unused knxultimate GATEWAY node and delete it!

**Comment by Dominik2000** [comment]
Ok, yeah, I have cleared the knx configs, then restarted node red, and... it works :) Thank you very, very much!

**Comment by Supergiovane** [comment]
Thank you to you for using one of my nodes.

**Comment by Dominik2000** [comment]
Thank you for working on this very helpful nodes! And for your quick an friendly support.
