### ISSUE TITLE
Circular reference protection shouldn't kick in when different message types are used

### ISSUE THREAD

**Issue by ChristianMayer** [Supergiovane/node-red-contrib-knx-ultimate#107]
Hi Supergiovane,

trying to make Node-RED remember states on the bus (e.g. switching a logic between automatic and manual mode) I want to be able to read that state from the KNX. By distinguishing between Write, Read and Response this is easily doable.

**Describe the bug**
Doing that in a trivial way will trigger the circular reference protection, although it can not cause a loop (a Response is not triggering a Read so there's no infinite loop)

**To Reproduce**
Just create a flow like this:
![Screenshot_20201226_123814](https://user-images.githubusercontent.com/10218721/103150764-5d7bb200-4777-11eb-8897-70aa3ce1572d.png)
(As expected: the upper left node is reacting only to writes, the lower left one only to read requests and the right node sends an response)

**Expected behavior**
![Screenshot_20201226_123853](https://user-images.githubusercontent.com/10218721/103150766-64a2c000-4777-11eb-8aa2-3bf9a275cead.png)
As seen in the screenshot - but without the fiddling with the `msg.knx` that I had to do in the lower yellow node to circumvent the circular reference protection:
![Screenshot_20201226_124012](https://user-images.githubusercontent.com/10218721/103150782-8b60f680-4777-11eb-80ec-44b5027761b9.png)

**Knx-Ultimate Version**
 - 1.1.92

**Are you running node-red behind homematic, docker or anything similar?**
 - Running on Docker

**Additional context**
It would also be great to have that functionality within one node, i.e. a node that listens to a KNX GA and has an internal state that is set by it's input, gives a new output when a KNX write message to that GA was sent and answers read requests automatically. The state should also be persistent, i.e. remember its value when the Node-RED is restarted.

**Comment by Supergiovane** [comment]
Hi Chris
About This
`Additional context
It would also be great to have that functionality within one node, i.e. a node that listens to a KNX GA and has an internal state that is set by it's input, gives a new output when a KNX write message to that GA was sent and answers read requests automatically. The state should also be persistent, i.e. remember its value when the Node-RED is restarted.`
You can use the VIRTUAL DEVICE. Please see the samples in the GitHub WIKI. There is a Virtual Device sample.

About circular protection, i'll will take a look but in the meantime, use this code to get rit of that. 
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Protections
See below in the page.
Cheers.

**Comment by Supergiovane** [comment]
Hi Chris
please replace the .node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate.js with the content of this zip, then restart node-red and tell me if the circular protection issue has gone.
[knxUltimate.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5743103/knxUltimate.js.zip)

**Comment by ChristianMayer** [comment]
Yes, it's working now. 
But as the complete circular protection was commented out I did expect that to happen.

As the circular protection is helpful I'd suggest to check around line 215 whether the message was a GroupValue_Read and the output is a GroupValue_Response and then skip the protection, otherwise do the protection as before.

**Comment by Supergiovane** [comment]
Yes Chris,
i'll do it Monday, because yet i'm very tired...

**Comment by ChristianMayer** [comment]
No need to hurry, I've got a work around.

Buon Natale!

**Comment by ChristianMayer** [comment]
> > Additional context It would also be great to have that functionality within one node, i.e. a node that listens to a KNX GA and has an internal state that is set by it's input, gives a new output when a KNX write message to that GA was sent and answers read requests automatically. The state should also be persistent, i.e. remember its value when the Node-RED is restarted.

> You can use the VIRTUAL DEVICE. Please see the samples in the GitHub WIKI. There is a Virtual Device sample. See if it helps or if you need something else. It works only by responding to a request.

The virtual device has the drawbacks:
- no link to a context variable, like `global.foo` or `flow.bar`
- this also makes the "initial" value after a restart of Node-RED not being the last one from before the restart

With my 5 nodes from the screenshots above that is covered.
But I'm confident that the KNX Device node could be extended with a context so that it would become a "virtual device with state"

**Comment by Supergiovane** [comment]
> Yes, it's working now.
> But as the complete circular protection was commented out I did expect that to happen.
> 
> As the circular protection is helpful I'd suggest to check around line 215 whether the message was a GroupValue_Read and the output is a GroupValue_Response and then skip the protection, otherwise do the protection as before.

Hi Christian
Can you try the attached file? Thanks.
[knxUltimate.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5750667/knxUltimate.js.zip)

**Comment by Supergiovane** [comment]
SORRY, THIS ONE:
[knxUltimate.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5750869/knxUltimate.js.zip)

**Comment by ChristianMayer** [comment]
Hi Giovane,

that change is looking fine. Thank you!

**Comment by Supergiovane** [comment]
Ok, i'll leave that running on my system for a while to check and then i'll post a new version.
In the meantime, you can live with the fix, it should be totally OK and it covers all scenarios, even with the node set to "universal".

About the "enhanced" virtual device, can you open another different issue for that?
I'll take a look at this at the beginning of 2021.
This year is very awful.
Thanks.

**Comment by Supergiovane** [comment]
Christian
there is a big issue with datapoint not correctly set. It threats all with DPT1.001
Please use the attached file, it has been fixed.
[knxUltimate.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5751349/knxUltimate.js.zip)
