### ISSUE TITLE
Version 1.2.3, no connection to KNXD or Siemens Router

### ISSUE THREAD

**Issue by gregor-samosir** [Supergiovane/node-red-contrib-knx-ultimate#108]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**

After updating today to version 1.2.3 without any more changes on my Node-Red its not possible for me to connect to KNX.

**To Reproduce**

**Expected behavior**

No connection to KNXD or Siemens Router.

**Screenshots**

Trace Log on ioBroker:
2021-01-01 20:12:27.896  - warn: node-red.0 (781) [warn] 2021-1-1 20:12:27 KnxUltimate-API: connection timed out, retrying... 2
[trace] 2021-1-1 20:12:27 KnxUltimate-API: (connecting): Sending CONNECT_REQUEST ==> {"header_length":6,"protocol_version":16,"service_type":517,"total_length":26,"hpai":{"protocol_type":1,"tunnel_endpoint":"172.17.0.4:57765"},"tunn":{"protocol_type":1,"tunnel_endpoint":"172.17.0.4:57765"},"cri":{"connection_type":4,"knx_layer":2,"unused":0},"connstate":{"state":0}}

(I don't use this IP 172.17.0.4:57765 in my setup)

Log from KNXD:
Jan  1 20:21:05 raspberrypi knxd[2018]: Layer 0 [713:log/tunnel           8321.471] State start
Jan  1 20:21:05 raspberrypi knxd[2018]: Layer 0 [713:log/tunnel           8321.471] State started
Jan  1 20:21:07 raspberrypi knxd[2018]: Layer 0 [713:log/tunnel           8322.981] Send L_Data low from 1.1.44 to 6/6/1 hops: 05 T_Data_Group A_GroupValue_Write 41 90 37 21
Jan  1 20:21:08 raspberrypi knxd[2018]: Layer 0 [717:log/tunnel           8324.474] State setup
Jan  1 20:21:08 raspberrypi knxd[2018]: Layer 0 [717:log/tunnel           8324.474] State start
Jan  1 20:21:08 raspberrypi knxd[2018]: Layer 0 [717:log/tunnel           8324.474] State started
Jan  1 20:21:08 raspberrypi knxd[2018]: Layer 0 [717:log/tunnel           8324.569] Send L_Data low from 1.1.41 to 8/1/9 hops: 05 T_Data_Group A_GroupValue_Write 00 00 4E C1
Jan  1 20:21:09 raspberrypi knxd[2018]: Layer 0 [713:log/tunnel           8324.983] State errored
Jan  1 20:21:10 raspberrypi knxd[2018]: Layer 0 [717:log/tunnel           8326.570] State errored

**Knx-Ultimate Version**
 Version 1.2.3

**Are you running node-red behind homematic, docker or anything similar?**
 Node-Red running  on docker with ioBroker

**Additional context**

**Comment by Supergiovane** [comment]
Hi gregor
You haven’t wrote “Hello”, as requested. 
Anyway...
Have you pasted some nodes in your flow?
There is such IP and port 5776 that are wrong. 
Check the config node. Port should be 3776 and IP should be 127.0.0.1 if you use knxd, or the ip of your siemens.

**Comment by Supergiovane** [comment]
Then, reboot node-red.

**Comment by gregor-samosir** [comment]
Hi,
and sorry to missing the Hello:

I am a little bit under pressure on an not running setup.
I have nothing changed on my flows. only updated to your latest version 1.2.3

My KNXD are running on IP 192.168.2.198 with port 3671 since some month. Nothing changed on this.
(I don't use this IP 172.17.0.4:57765 in my setup)

**Comment by Supergiovane** [comment]
Check your config node! Post a screenshot! Reset the io and port on 192.168.2.198 and 3671, then restart nodered

**Comment by Supergiovane** [comment]
Nothing has changed in 1.2.3, there is only a new datapoint.

**Comment by gregor-samosir** [comment]
![Bildschirmfoto 2021-01-01 um 20 43 29](https://user-images.githubusercontent.com/56981167/103445246-0479b580-4c72-11eb-894f-e278e8e30d3d.png)

Attached the setup. I can see trying to connect on KNXD, but it failed.
From where are the  IP 172.17.0.4:57765 I see in my travelog?

**Comment by Supergiovane** [comment]
I can suppose, it’s some type of natting by iobroker. Please look at it. 
Have you restarted nodered?

**Comment by Supergiovane** [comment]
Or docker, if you run iobroker dockerized.

**Comment by gregor-samosir** [comment]
Have checked it with node-red-contrib-knx-easy to test the connection, no problem.
No natting on the docker, its running with an IP in the same network as the KNXD.

But will build up an fresh setup on an not used node-red to test.

**Comment by Supergiovane** [comment]
Other than that, check wheter you have “ghost” unised knx-ultimate gateway nodes, by looking on the right of nodered UI.

**Comment by Supergiovane** [comment]
Another thing you can do, is to add another gateway config node, and set it as default server node for the knx-ultimate nodes. 
I had an user, the last week, that clicked “merge” in nodered and all they nodes were going crazy.

**Comment by Supergiovane** [comment]
Or... you can post here your json file. I'll take a look. These numbers must be wrote somewhere...

**Comment by gregor-samosir** [comment]
Have tested it on an other server and it works.
Now I have a problem.....

Thanks for your help, looks like a long night for me.

**Comment by Supergiovane** [comment]
Look inside the json file of node red.
Send me your file if you want. I'll help you.

**Comment by Supergiovane** [comment]
The user that "merged" two flows in node-red, has invalidated some node IDs, so the json file was OK, but all the node IDs were wrong, so node-red has gone crazy. Try to simply add another gateway node and set it as server for one knx-ultimate, to see if it works.

**Comment by gregor-samosir** [comment]
Can not attach the flow file on GitHub, hop it works here



Alexander Kunz

**Comment by Supergiovane** [comment]
Zip it. But before, search by yourself into the json, if you find that IP and port.

**Comment by Supergiovane** [comment]
And please, follow my advices i wrote above in this thread.

**Comment by gregor-samosir** [comment]
Now its back to running with an playback from backup. 
Everything with KNS are fine.

Have to go deeper on an other session.

Alexander Kunz

**Comment by Supergiovane** [comment]
Hi Alex
Have you tried to do this?
`Try to simply add another gateway node and set it as server for one knx-ultimate, to see if it works.
`

**Comment by gregor-samosir** [comment]
To add a other gateway node does not work.

I have restored the project from the state before the update to 1.2.3 and everything works fine.

If I update only knx ultimate on this restored project I can reproduce the same error. No connection after the update.

Must not bee an error on knx ultimate, but now I am lost in space.

**Comment by Supergiovane** [comment]
Hi
Zip the json and post it here. It can be a unicode char hidden in your file. Until you don’t touch anything, it works, as soon as the json changes, the unicode char let all gone crazy.

**Comment by gregor-samosir** [comment]
Hello Supergiovane,

please find attached the flows.json from the running config before the update to version 1.2.3
Have checked the .json, but found nothing that is not expected.
Later I will do a another try to update and send the flows.json after the update.

Thanks again for your patient help
Alexander

[flows_noupdate.json.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5760461/flows_noupdate.json.zip)

**Comment by Supergiovane** [comment]
Thank you,
you noted for sure this, right? 
` {
        "id": "a2f**57765**.6fae2",
        "type": "comment",
        "z": "9ef2b507.0c981",
        "name": "elektrisch",
        "info": "",
        "x": 160,
        "y": 200,
        "wires": []
    },`

How many chances does one have, to find the same number sequence of the wrong port?
I'll wait for your updated flows, please send it asap, because otherwise i must check it starting from tomorrow.

**Comment by gregor-samosir** [comment]
Hello,

hm, searched only for this wrong IP. 
What you found is a comment only, will delete it.

Unfortunately, I can't take the test at the moment, so let's postpone it until tomorrow.

Alexander

**Comment by Supergiovane** [comment]
Ok. Tomorrow. 
Don’t touch anything. Don’t delete anything. All must remain the same.

**Comment by gregor-samosir** [comment]
Will do a new export of the flows before the update.
So we have this two files from near the same time.


Alexander

**Comment by gregor-samosir** [comment]
Hi Supergiovane,

today I have saved the flows.json before and after the try to update KNXultimate to version 1.2.3.

It does crash in the same way as the last days. Broken connection to knxd.
And nothing changes on the flows.json. Completely untouched.

So I have played back from my backup the complete
node-red/node_modules/node-red-contrib-knx-ultimate/*
restart Node-Red and it works again.

Any hints to debug?
Alexander

**Comment by Supergiovane** [comment]
Hi
i need you to give me all this infos:
From what version have you updated knx-ultimate to 1.2.3?
What version of node have you installed (please issue a node -v command in a console window where nodered is installed)
What version of nodered have you installed?
I need both json files. Even if it seems identical. You cannot see unicode files in your editor.

**Comment by gregor-samosir** [comment]
Here are the infos you are requested:
> i need you to give me all this infos:
> From what version have you updated knx-ultimate to 1.2.3?
> 
From version 1.1.99
> What version of node have you installed (please issue a node -v command in a console window where nodered is installed)
> 
node -v 
v12.20.0

npm -v
6.14.8

> What version of nodered have you installed?
> 
Version 1.2.6
> I need both json files. Even if it seems identical. You cannot see unicode files in your editor.
> 
> 




Thanks for your help.
Alexander

**Comment by Supergiovane** [comment]
Ok, we begin to do the right things to checkup the issue.
When able, tomorrow as well, if you want, no hurry, you need to do this, in the exact order:

- Update again to 1.2.3
- Restart node red
- Once restarted, unzip the content (file Connection.js) of the attached zip and copy it to your **.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api/src** folder. It'll replace the older one.
- Restart node-red and check if it works.

[Connection.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5761922/Connection.js.zip)

**Comment by gregor-samosir** [comment]
Will do this, but now is family time.

**Comment by metaneutrons** [comment]
Hi there, I'm experiencing the same issue. The last working version for me is v1.1.99. When I install it with npm manually (`npm install node-red-contrib-knx-ultimat@1.1.99`) everything is working perfectly well. So the change to look for seems to be in v1.2.0.

If I can assist you, please let me know!

**Comment by Supergiovane** [comment]
Hi Fabian
Yes, thanks.
Please download the file Connection.js.zip an do the things described in the post.
Do you ue KNXD?
Tank you.

**Comment by matthiazzz** [comment]
Alright, had the same issue with a Gira S1 and a dockerized version of Node-red. After updating from 1.1.x (don't remember the actual sub-version) to the current version 1.2.3, the KNX nodes just stated "Disconnected". Nothing has changed besides the updated knx-ultimate palette. 

Docker network was set to "bridge" and only needed ports were exposed to my local network (where the S1 resides). Turns out that setting network to "host" and exposing all ports made the knx-ultimate work again. Fortunatelly, all my ports were free on my host, otherwise macVLAN would have been the route for an independent IP adress for the container.

So it is definatelly the way knx-ultimate commuicates with the gateway. 

**Question**: What has change here between version 1.1.x and 1.2.3? Maybe broadcast, UDP instead of TCP, additional port, ...?

**Comment by Supergiovane** [comment]
Hi,
please, can you try to do this? https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/108#issuecomment-753645523

In the 1.2.0 i have introduced the compatibility with KNX Virtual. Maybe it's related to this, but many users haven't had any issue.

**Comment by matthiazzz** [comment]
Alright, replacing the conncetion.js did the trick and it is working as before with docker network set to "bridge".

**Comment by Supergiovane** [comment]
Ok Mat,
thank you. I'll roll-out immediately a quickfix.
V 1.2.4 is out in about 30 mins.

**Comment by Supergiovane** [comment]
Ok, 1.2.4 is out.
I've signed as deprecated, all version between 1.2.0 and 1.2.3

**Comment by matthiazzz** [comment]
All good! 👍 

Sucessfully updated to 1.2.4 and can confirm it working.

Thank you for fixing this instantaniously. 🥇

**Comment by gregor-samosir** [comment]
Hi Supergiovane,

a little bit late from my site, but thanks for fixing this so fast. Version 1.2.4 is working for me.

Alexander

**Comment by Supergiovane** [comment]
Hello @HLeithner 
yes, but as far as i can see, there is a compatibility issue (bug) in KNX Virtual. It crashes when it receives a particular connection setup.
Most probably, i'll add a configuration property, user-selectable, to enable the KNX Virtual until the related crash has been adressed.

**Comment by HLeithner** [comment]
Thanks for the info and of course Hello ;-)

**Comment by Supergiovane** [comment]
> Thanks for the info and of course Hello ;-)

No needs for salutation if you don't need help! :-)

**Comment by Supergiovane** [comment]
> Hi Supergiovane, a little bit late from my site, but thanks for fixing this so fast. Version 1.2.4 is working for me. Alexander
> […](#)

Thank you Alexander for your donation!! Very appreciated!
