### ISSUE TITLE
New Datapoint

### ISSUE THREAD

**Issue by megahorst** [Supergiovane/node-red-contrib-knx-ultimate#109]
Hi Supergiovane!
I like your knx-ultimate very much and use it very intersive.
Therefore I would like to ask kindly if it is possible for you to ad 213.100 as a new datapoint.
This DPT is used by my Hager HVAC actuator TXM646R
![image](https://user-images.githubusercontent.com/60320976/103783324-dcef6800-5038-11eb-9265-58d162f2ea85.png)

If you need morfe information regarding the actor, you can find them here:
https://www.hager.de/files/download/0/23841094_1/0/PD_6LE005603B_TXM646T_TXM646R_ETS_EASY_HEIZUNGSAKTOR_DE.PDF

Thx in advance

**Comment by Supergiovane** [comment]
Hi
Yes, off course. 
Tomorrow will do it.

**Comment by Supergiovane** [comment]
Hi
v.1.2.6 with this DPT will be out in about 1 hour.
Cheers and... please ***star*** the node ;-)

**Comment by Supergiovane** [comment]
PS: i cannot test this datapoint, because i either doesn't have a suitable actuator and in ETS, this datapoint 213 is simply non existant.

**Comment by megahorst** [comment]
Hello,
I have made a quick test. Everything seems to be fine :-).

Thanks a lot for your effort.
