### ISSUE TITLE
Datapoint 237,600

### ISSUE THREAD

**Issue by croghostrider** [Supergiovane/node-red-contrib-knx-ultimate#111]
Hii Supergiovane, could you please add the DPT 237,600?

![image](https://user-images.githubusercontent.com/8603272/104136505-efe69d00-5396-11eb-9b97-c4cdd2c26cf1.png)

thanks.

**Comment by Supergiovane** [comment]
Hi Crog,
v. 1.2.7 is out with this new datapoint. 
[See here.](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---DPT237)

**Comment by croghostrider** [comment]
you are amazing !!!!

**Comment by croghostrider** [comment]
you have a typo in the wiki it should be true
![image](https://user-images.githubusercontent.com/8603272/104208613-fa557500-5430-11eb-9b94-00e2ae653d3f.png)

**Comment by Supergiovane** [comment]
Yup... i’ll correct it tomorrow. Thanks.
