### ISSUE TITLE
Time to bus: 

### ISSUE THREAD

**Issue by Grogson** [Supergiovane/node-red-contrib-knx-ultimate#112]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Grogson** [comment]
Hi! 
Copy/Paste this into your configuration node.
If i paste ist in the Funktion Node. An Red Flag was the resoult.

What are the correct words to get the Date/Time in the Bus system ?

Thanks

**Comment by Supergiovane** [comment]
Hi Grogson
Have you seen the WIKI?
Please look at this: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---DateTime-to-BUS
You need to change the group address and gateway according to your KNX configuration.

**Comment by Grogson** [comment]
I seen it. That´s why im here. 
The input is not the Problem. (Datapoint and co)
My Problem is the convertion of the Injet Module "Time inforation" to an KNX readable 10.001/11.001/19.001 code. 
I Perefere the 19.001 code. My Gruppeadesses are 19.001 objects. MDT Glastaster and Dimmaktor:

Other Words:
What is in the "Function" Module

**Comment by Supergiovane** [comment]
Ok, yet i've understood.
Please try this:
msg.payload = new Date();
return msg;

**Comment by Grogson** [comment]
Sounds very easy. But dit no work.
I dit my best. Sorry my englisch is not the best.

My MDT Glastaster dit not respond an Time Code.
So i choose this way. 
Whats wrong ? 

![Time to Bus 2](https://user-images.githubusercontent.com/77251783/104920330-e7debc80-5997-11eb-92dd-845b26f2a12c.JPG)

**Comment by Supergiovane** [comment]
Hi,
Yes, i see that your english is a little bit crazy :-)
Are you sure you are using the last knx-ultimate node?
You are using KNX-EASY !!
Please ask the knx-easy developer, as i cannot give you any assistance on this one.

**Comment by Grogson** [comment]
Sorry i use both.
Now the correct one.
But there is no correct Time on the Display

There is Connetion. Positive on your out node. 
But The return node shows nothing.
![Time to Bus 4](https://user-images.githubusercontent.com/77251783/104925282-e95fb300-599e-11eb-8137-1717ceebf1a8.JPG)

**Comment by Supergiovane** [comment]
Hi
Are you sure you are using knx-ultimate?
I think you installed ALL but knx-ultimate !!! :-)

**Comment by Supergiovane** [comment]
I saw you're German.
This is a very helpful german forum to start with KNX: https://knx-user-forum.de

**Comment by Grogson** [comment]
OK 
Thanks for your time.
