### ISSUE TITLE
RBE blocks even when not checked

### ISSUE THREAD

**Issue by danube** [Supergiovane/node-red-contrib-knx-ultimate#113]
Hey there! What an awwsome node, thanks so much. I see just a little bug (or maybe something I just don't understand).

Eventhough RBE filter in the node is inactive, the status message of a device node writes "rbe block" after sending the same value twice. Didn't check the bus yet but I guess no values are being written too.

node-red-contrib-knx-ultimate 1.2.8
node-red 1.2.6
platform: Raspberry Pi 4B with Raspberry Pi OS (dunno version, but pretty actual)

![grafik](https://user-images.githubusercontent.com/1183829/105325391-d5999400-5bcc-11eb-833f-32e578a37c48.png)
![grafik](https://user-images.githubusercontent.com/1183829/105325473-ec3feb00-5bcc-11eb-8d90-80469e9eca79.png)

If I find some time, I probably going to have a look at the code by myself, just because I'm curious, but that's all for now I can see.

All the best! Tom

**Comment by Supergiovane** [comment]
Hi Danube!
You have still set the "send payload to BUS only if changed" in the "OUTPUT" section.
OUTPUT section handles the incoming msg from flow, directed to the KNX bus.
INPUT section, vice versa.

**Comment by danube** [comment]
god so stupid, i was looking at the INPUT, but of course relevant is the OUTPUT... sorry for that...
