### ISSUE TITLE
Multicast does not receive any telegrams

### ISSUE THREAD

**Issue by Namakemono93** [Supergiovane/node-red-contrib-knx-ultimate#116]
Hi Supergiovane

I hope you’re doing well. 
I tried to set up a KNX connection over multicast, but it seems like your node doesn't receive any telegrams from the KNX bus.

Here is my setup:
There are 3 KNX lines, each has an "ABB  IPR/S 3.1.1". The Node-Red set up in a Docker container on a Raspberry Pi.
The KNX-Ultimate is on the latest version (1.2.13).
All is connected over an unmanaged Netgear (GS108LP) switch.

First, I tried to run it with normal network settings (Only routing the ports) for the container, which didn't work. 
After I set the network to "Host" I was able to send telegrams to the KNX bus, but the KNK Node didn't receive any telegram from the bus.

I opened the "Net'n Node" bus monitor to check if the KNX router is sending the telegram back to the multicast Address and it did.
When is set the address from multicast to a direct tunnel address from one of the KNX routers, everything works fine, but I suppose that setting a multicast address in the KNX Node should work aswell?

Node-Red:

![2021-03-18 13_08_55-hbVisu Editor - ekey Testaufbau – Mozilla Firefox](https://user-images.githubusercontent.com/52327137/111627202-1db0ed80-87ef-11eb-84b6-957dc5d8d861.png)

![2021-03-18 13_10_59-hbVisu Editor - ekey Testaufbau – Mozilla Firefox](https://user-images.githubusercontent.com/52327137/111627242-27d2ec00-87ef-11eb-8306-794feb955e3d.png)

Net'n Node Bus Monitor:
![2021-03-18 13_05_55-Net'n Node Busmonitor](https://user-images.githubusercontent.com/52327137/111627072-feb25b80-87ee-11eb-964e-5f51ce57d0cd.png)

KNX-Ultimate Logger:
![2021-03-18 13_13_44-pi@hbVisu_ ~](https://user-images.githubusercontent.com/52327137/111627516-6bc5f100-87ef-11eb-9ece-cbad1688c2bc.png)

Do you have any idea what could be the problem?
Many thanks,
Simon

**Comment by Supergiovane** [comment]
Hi,
has this setup ever worked?
I know that dockerized node-red has many issues in handling multicast messages.
Try to simplify the installation. 
If you run netgear, i tell you i have had issues with multicast. I had issues with unifi AP as well, not only with KNX, but also with IP TV Streaming.
Anyway... if you have a spare raspberryPI, install node-red directly on the raspbian OS, don't use docker.
Then double check the telegram filters in the ABB IPR/S 3.1.1 
Your setup is way complex. Having 3 lines, is a bit hard to debug if you don't try to figure out the issue step by step.

**Comment by Namakemono93** [comment]
Hi Supergiovane
You were right. I set up a node.red without docker and it worked.
Guess I have to figure out how to get this working under docker.
Anyway, thanks for your help!
