### ISSUE TITLE
The connection error from issue #108 is back in Version 1.2.16

### ISSUE THREAD

**Issue by gregor-samosir** [Supergiovane/node-red-contrib-knx-ultimate#118]
Hello Supergiovane,

Update to 1.2.16 today and get the same error as described and fixed in 
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/108#issuecomment-753645523

Running on docker and connecting to KNXD outside of the container. The connection goes down.

Maybe its missing the fix in Connections.js on the new api2?

`// add the control udp local endpoint. UPDATE: not needed apparnently?
FSM.prototype.AddHPAI = function (datagram) {
  datagram.hpai = {
    protocol_type: 1, // UDP
    //tunnel_endpoint: this.localAddress + ":" + this.socket.address().port // 29/12/2020 Supergiovane added on tips https://bitbucket.org/ekarak/knx.js/issues/76/knx-virtual-is-crashed-right-after 
    tunnel_endpoint: '0.0.0.0:0'
  };
}

// add the tunneling udp local endpoint UPDATE: not needed apparently?
FSM.prototype.AddTunn = function (datagram) {
  datagram.tunn = {
    protocol_type: 1, // UDP
    //tunnel_endpoint: this.localAddress + ":" + this.socket.address().port // 29/12/2020 Supergiovane added on tips https://bitbucket.org/ekarak/knx.js/issues/76/knx-virtual-is-crashed-right-after 
    tunnel_endpoint: '0.0.0.0:0'
  };
}`

Alexander

**Comment by Supergiovane** [comment]
Hi Alex
Please temporaty revert to 1.2.14 or below. 
npm install node-red-contrib-knx-ultimate@1.2.14
Tomorrow i’ll take a look

**Comment by Supergiovane** [comment]
Hi Alex
Can you unzip the zip file into the .node-red/node_modules/node-red-contrib-knx-ultimate/ folder and restart nodered?
This is the new version with API v2 and a fix for your issue.
It should work. If not, please revert again to 1.2.14.

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6276239/Archivio.zip)

**Comment by gregor-samosir** [comment]
Hi Supergiovane,

it's working as expected. Thanks for this fast fix.

Alexander

**Comment by Supergiovane** [comment]
Ok, good.
Sorry for the mistake.
V. 1.2.18 will be out today with that fix and with some other checks on bad telegrams coming from KNX BUS.
