### ISSUE TITLE
Send warning/errors to debug panel from the correct node

### ISSUE THREAD

**Issue by Webbeh** [Supergiovane/node-red-contrib-knx-ultimate#120]
Hi everyone !

We are using a LOT of KNX nodes, and we get spammed in the DEBUG panel constantly with timeouts, connection lost, etc.

![image](https://user-images.githubusercontent.com/1530837/114137299-43bc4000-990c-11eb-9f9c-03f2179aadbe.png)

Now, it wouldn't be as annoying if the filtering in the DEBUG panel worked with your messages, but since those messages are not emitted from a node, the filtering doesn't work, and the messages show regardless of which flow you're currently editing.

Would it be possible to change this ?

Thank you very much !

**Comment by Supergiovane** [comment]
Hi
You've problem with the IP Interface not responding in time.
Sure i can avoid printing that, but you should fix the issue first.
The IP Interface doesn't respond to connection state requests, thus the connection goes down.
Please check your switches and possibly disable the UDP storm protection.
Then check your IP Interface and assure you've the latest firmware and update knx-ultimate to the latest version as well.
Also try to select "Suppress ACK request" in the [gateway config window](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/1.-Gateway-configuration)

**Comment by Webbeh** [comment]
The issue comes from the gateways that are behind a very slow 3G connection on some of them, and we have about 600 KNX gateways, so some of them are bound to give connection errors. It's almost unavoidable in our case, and we are fine with receiving the errors.

The issue is not being able to filter them :)

**Comment by Supergiovane** [comment]
Ah, ok. Understood!
I'm already working on that. A new version will be out today.

**Comment by Webbeh** [comment]
Wow, that's quick! Impressive! Thank you!

**Comment by Supergiovane** [comment]
V 1.2.19 is out with the fix and the option to totally disable logging. You should see it in the palette's menu in minutes.
If not already done, please STAR my node ;-)
If you're a professional and you wish to be mentioned in the README page of knx-ultimate, please send me your website and give me the authorization to mention you.
Thanks.

**Comment by Webbeh** [comment]
No need for mentioning, but thanks for the update !
