### ISSUE TITLE
Sending telegrams to the KNX bus stops working shortly after reboot

### ISSUE THREAD

**Issue by Podler** [Supergiovane/node-red-contrib-knx-ultimate#121]
*Hello Supergiovane,

since I updated my node red base system to the latest releases (linux + node red - knx ultimate) I have the issue, that shortly after the reboot the knx bus does not receive any updates from your node any more. The initial values are sent to the bus but no changes do appear on the bus. Did I mess up with any settings or what can be the cause of the problem? Your help is very much appreciated!

**Comment by Supergiovane** [comment]
Hi Podler
please check again the gateway config window and be sure that all options are correctly set.
Also be sure that **Suppress ACK request** is enabled, then follow these steps https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/5.-FAQ-Troubleshoot
Also please do a reboot of your PC and tell me if you're connecting via IP Router or IP Interface. Thanks

**Comment by Supergiovane** [comment]
PS: please also check the option “echo local messages...” and assure it’s enabled.

**Comment by Podler** [comment]
Hi Supergiovanne,

enabling „Suppress ACK request“ resolved the issue. Fyi: CPU load dropped from 25% to 2% on my raspberry as soon as I enabled it. 

Your help is very much appreciated! Your knx node is very good and very helpful!

**Comment by Supergiovane** [comment]
Hi Podler, 
thank you for your donation!! Much appreciated!!

**Comment by Podler** [comment]
Hi Supergiovane,

sadly the issue is back. After running at 2% CPU load for nearly the whole day the load jumped to 25% again and the telegrams no longer reach the knx bus. I already tested the flow with another knx ip interface but with no effect. Do you have any suggestion?

**Comment by Podler** [comment]
Update: The device objects stay in state "Writing". When I restart all flows they work for a short time and then stay in "writing" state.

**Comment by Supergiovane** [comment]
Hi Podler
"Writing" state means that a telegram has been sent from the node to the KNX/IP gateway, but the gateway has either not accepted the telegram to be sent, or denied the tunnel connection (if it's an IP Interface).
i need you to give me more infos.
You're using an IP Interface or an IP Router?
Have you changed something else in your network topology, after upgrading linux? (For example, upgraded a switch, changed a cable or something similar)?

**Comment by Podler** [comment]
Good Morning. My standard gateway is a GIRA 2167 00 IP Router. I also tested with the GIRA 2089 00 S1 and the GIRA 2096 00 X1. All show the same behaviour. Nothing else changed in the network topology. I am from the IT industry but not a linux guy :-)

**Comment by Supergiovane** [comment]
Hi
You're connecting to the IP Router wit the standard 224.0.23.12 multicast address, i suppose.
If yes, please look at the IP Router and disable ALL telegram filtering. After that, there is no reason it won't work. Please check the that the UDP Storm protection in your switch (if it's managed) and disable it.
If you're using one tunnel of your IP Router (that means, you're connecting using the real IP Address of the IP Router), be sure that you haven't reach the maximum tunnel allowed. Change the KNX Physical Address in the gateway config node and restart node-red and the Gira, to clean the Gira's memory. 
When possible, always use the 224.0.23.12 multicast address.

**Comment by Supergiovane** [comment]
Hi Wizart
please unzip that zip in the usual folder and restart nodered.
The fix for you issue has been done, with correct attribution of "duration" to "fielddetection".
If you've time, you can continue ditching into the camera issue or... enjoy the node.
Cheers.

[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6377174/Archivio.zip)

**Comment by Podler** [comment]
Hi, I changed the physical address of the node and use the multicast address now. I also checked the network switch for storm protection. No events there. All components restarted. The IP router has no telegram filtering in place. Sadly the issue is still there. Do you have any additional idea? Is there any additional logging I can provide? I also set up a complete new installation of my raspberry (on another sd-card) and imported the flows. Same issue. I did that because I wanted to make sure the linux installation is ok.

**Comment by Supergiovane** [comment]
Hi Podler
now i need to view your flow.
Please paste it here, so i can replicate your things and check.

**Comment by Podler** [comment]
This is one of my flows. Do you need more?

[sonstiges_flows.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6413916/sonstiges_flows.zip)

**Comment by Supergiovane** [comment]
Hi Podler
are you sure you're using the multicast IP? I see an unicast IP here:

<img width="478" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/116860186-7a326580-ac01-11eb-9deb-2f81866edc12.png">

**Comment by Podler** [comment]
![image](https://user-images.githubusercontent.com/83112937/116860314-a8b04080-ac01-11eb-96a5-705837bda6dd.png)

**Comment by Podler** [comment]
Sorry, I sent you an older export wich I took a few days ago while testing.

Here is the latest one:

[flows.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6413971/flows.zip)

**Comment by Supergiovane** [comment]
Hi Podler
i checked the flow and (despite the IP address, where i put the multicast IP), it works without issue.
Can you please write "EMULATE" instead of the multicast IP and restart node-red?
This enables the emulation mode and nothing will be written on the BUS. You whould'nt see any "Writing" status remaining. If this works, well go to the next step.

**Comment by Podler** [comment]
![image](https://user-images.githubusercontent.com/83112937/116861170-fda08680-ac02-11eb-8e97-49248dfaabd9.png)

**Comment by Supergiovane** [comment]
Ok perfect. It Works, so the nodes and flow doesn't contain any misconfiguration.
Next step:
On the raspberry PI you set up, please delete all flows and the gateway config node (this is hidden, you should delete it from the node-red right menu).
Then restart the PI.
Then create from SCRATCH a gateway node and a device node, like done here: https://www.facebook.com/SupergiovaneDev/videos/3836998093043742

Then attach a inject node to the device node, deploy and see what happens.

**Comment by Podler** [comment]
I cannot watch the video as I do not have a facebook account... But I deleted all flows and the config node on my test raspberry. Then rebooted and deployed a test flow with standard settings. The flow seems to work (does not say "writing") but no telegram does reach the knx bus (checked in ETS group monitor).

![image](https://user-images.githubusercontent.com/83112937/116865734-7eaf4c00-ac0a-11eb-8068-a8f7455c8a8a.png)

![image](https://user-images.githubusercontent.com/83112937/116865756-8a027780-ac0a-11eb-87b8-dc2c337e76af.png)

![image](https://user-images.githubusercontent.com/83112937/116865860-bc13d980-ac0a-11eb-8cc5-0fce94c91aa8.png)

**Comment by Podler** [comment]
In the meantime I did factory-reset the ip-router and completely reprogrammed it. No result. This is one of the errors we love in it. I am very sorry to annoy you and consume your time! Your help is very much appreciated.

**Comment by Supergiovane** [comment]
Hi Podler
Please disable the WIFI card of the rPI or simply disconnect it from any network. We need to only have 1 ethernet interface.
The fact that you don't see "Writing" anymore, means that the KNX router has accepted your telegram but fails to forward it to the bus.
Please check your router config **again** and assure that ADDRESS FILTERING is active and that the forwarding is allowed between all physical addresses.

After all is done but still now work:
Directly connect the Gira IP Router to the rPi (or use a very dummy switch, those inexpensive 4 ports are fine).

I'm trying to isolate where the issue is and to fix it, because there's no meaning it won't work!

**Comment by Supergiovane** [comment]
PS: it can be that ETS won't trap the telegrams, but they still flowing through the KNX BUS. You should try using a lightbulb or a switch socket to physically see what happens.

**Comment by Podler** [comment]
The seems to be no bus communication at all. I set up a device node, that listens to a group address which reports values every second. Nothing happens in nodered.

![image](https://user-images.githubusercontent.com/83112937/116878390-91804b80-ac1f-11eb-9311-b2cfb6262e0f.png)

The router does not filter any telegrams and forwards them:

![image](https://user-images.githubusercontent.com/83112937/116878553-d1473300-ac1f-11eb-8509-f00345da9f82.png)

**Comment by Supergiovane** [comment]
Hi Podler
is the 5/0/4 setup to reacts to Write and Response telegrams?

**Comment by Podler** [comment]
5/0/4 reacts to Write Telegrams only. Configured it to react to Response telegrams too now. No change.
Yes. BUS -> IP is same as IP -> Bus
The WIFI interface of the raspberry is not connected to any wifi network.

Would it be an option to have an Microsoft teams session to look onto my system? Of course I would pay for your support!

**Comment by Supergiovane** [comment]
Hi Podler
yes a remote session whould help. I'll download ms teams. In the meantime, please tell me your topology.
For example: 

rPI --> switch --> Gira KNX

**Comment by Supergiovane** [comment]
Ok downloaded. Have you a teams code to give me ?

**Comment by Podler** [comment]
I can send you an invitation for a remote meeting. I need the email-address please you used for your teams account.

**Comment by Supergiovane** [comment]
info@saccani.services
Can MS Teams do a remote desktop sessions?

**Comment by Podler** [comment]
Yes!

**Comment by Podler** [comment]
I will keep youe email confidential! You can send me your address via email to honemeyer@insys.de

**Comment by Supergiovane** [comment]
Done

**Comment by Podler** [comment]
Invitation on its way.

**Comment by Podler** [comment]
Our mailserver is eating ZIPs. So I send it here. Please confirm the download so that I can delete this post here. I don't know if this conversation is public?

[flows.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6415440/flows.zip)

**Comment by Supergiovane** [comment]
Hi Podler
Anbei.
Please give it a try, because my node-red won't start. I've many extra node missing.
There is a Bad Guy gateway config node, you can safely remove.
[flows.json.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/6415542/flows.json.zip)

**Comment by Podler** [comment]
I downloaded it. Can you please delete the post to keep the flow confidential?

**Comment by Podler** [comment]
What do I have to do? Delete all existing flows and configuration nodes and then import?

**Comment by Supergiovane** [comment]
You can either stop node-red and replace the whole file, or select all on your flows, delete (delete the configuration nodes as well) and paste the file.
Achtung: in any case, you probably loose all the username/password in email nodes, alexa etc. Because they're sensible data, they won't be exported.

**Comment by Supergiovane** [comment]
The json file is located in your pi/.node-red folder

**Comment by Supergiovane** [comment]
I suggest the second way. Select all and delete.
OR: there is another way. You can find/replace by yourself... this will leave the passwords in place.

**Comment by Supergiovane** [comment]
Do you have file access (or FTP access) to your rPI? If yes, i can do it for you in a ms teams session again.

**Comment by Podler** [comment]
Would you mind to delete the post with the flow zip file?

**Comment by Supergiovane** [comment]
I've already delete all.

**Comment by Supergiovane** [comment]
Hi Podler
is your rPI you totally exploded?

**Comment by Podler** [comment]
I manually replaced all existing gateways with the one we configured and deleted the old ones. After a short period of time the issue came back :-( All objects in "Writing" state again if I use a unicast gateway. If I use a new multicast gateway no telegrams reach the bus.

**Comment by Supergiovane** [comment]
Wish you do another ms teams session?
Maybe the ip tunnel o the Gira is remained stuck.

**Comment by Podler** [comment]
I will reboot the Gira and write again. When I restart all flows it works for 30 seconds and then stops.

**Comment by Supergiovane** [comment]
Ok, good. We're returned to the very first issue.
Change the physical address of the gateway config node to match the 1.0.0 of the gira, for example 1.0.50

**Comment by Supergiovane** [comment]
Also... keep the ETS closed and retry.

**Comment by Podler** [comment]
ETS is closed now. ETS uses a different IP Gateway (192.168.1.6, Gira S1) to connect to the bus. Changed physical address of config node to 1.0.50 matching the line of the gira. No change. Still stops sending after 30 secs.

**Comment by Supergiovane** [comment]
Have you tried to check and disable all inject nodes? Maybe one of these does bad things.

**Comment by Podler** [comment]
Currently I am trying with the Gira S1 as Gateway and the BAB App Module as Gateway to take the GIRA IP Router out of the game...

**Comment by Podler** [comment]
I manually changed all devicenodes to the Gira S1. And after some time it stopd working again. May the problem be related to the number of objects talking to the router? I have 67 devices in all flows.

**Comment by Podler** [comment]
I changed flow by flow and it seemed as if it stopped working after I changed all objects in another flow. I will check and reduce the number of objects and devide them to two gateways. Let's see..

**Comment by Supergiovane** [comment]
Ok, let me know. I've more than 300 Group addresses bond on only 1 Enertex IP Interface, without issue since years. I'll check if i had the same group address, bond to two different gateways. This may lead to looping, thus the Gira may take the tunnel down.
Please in the meaning check wether you have KNX Secure enabled. This may lead to issues (mixing unsecured and secured datagrams can be a bit tricky)

**Comment by Podler** [comment]
Maybe I found the issue! When transferring object by object to the other gateway one by one I noticed that after one specific device the bus communication failed. So I further investigated the object. The device was sending information in datatype 16.001 (ISO-8859-1) instead of 1.002 (boolean). The knx group address is configured to boolean. Sending in the wrong data type seems to kill the whole gateway communication.

**Comment by Supergiovane** [comment]
Holy crap.
I'll take a look at it immediately.
You should import the ETS group address export file, to be sure to use the right datapoint.

**Comment by Podler** [comment]
I must have changed the datatype accidentially without noticing it during working with node red. I can completely reproduce the error when setting the datatype of the object back to 16.001.

**Comment by Supergiovane** [comment]
Hi Podler
i set up a KNX Node with Datapoint 1.002 and, from the ETS Diagnostic window, i've sent a string 16.001.
This is the result from the log:

`[error] 3/5/2021, 18:31:30 knxUltimate-config: buildInputMessage: received a wrong datagram form KNX BUS, from device 0.0.1 Destination 0/1/2 Event GroupValue_Write RawValue ciao bello � GA's Datapoint 1.001 Devicename (Attuatori luci->Luci piano terra) Applique taverna Topic 0/1/2`

As you can see, the issue is trapped by the error handler and the flow still receive all telegrams.

I've done something wrong or misunderstood what you said?

**Comment by Podler** [comment]
No, I think you understood me right. As the issue is reproducable, how can I give you the logging from my system?

**Comment by Podler** [comment]
want to look onto my system via teams again?

**Comment by Supergiovane** [comment]
Yup... this whould be great.

**Comment by Podler** [comment]
ok, rejoin the meeting...

**Comment by Supergiovane** [comment]
Ok, i can now reproduce the issue by myself!
Thank you. Tomorrow i'll fix that glitch and i'll post an updated version. This will protect other users as well.
I'll post here as soon as the new version is out.
Thanks again.

**Comment by Supergiovane** [comment]
Hi Podler
V. 1.2.28 is out with the fix.
Thank you for sharing your mind with me, like Spock.
