### ISSUE TITLE
Manual reconnection

### ISSUE THREAD

**Issue by Webbeh** [Supergiovane/node-red-contrib-knx-ultimate#122]
Hi there.

**Is your feature request related to a problem? Please describe.**
We've got some KNX interfaces that can potentially be polled from multiple sources at the same time.
This has the effect of disconnecting the KNXUltimate node from said interface, and, after a while, KNXUltimate seems to just give up on reconnecting to the interface and simply displays a "Disconnected." status.

**Describe the solution you'd like**
Having the possibility to send a control message to the node with, for example, `msg.connect=true`, that would trigger a reconnect of the node, could allow us a better control on which node we want to connect manually to and when.

This idea could be extended on with a `msg.connect=false` triggering a manual disconnect to the interface, allowing us to actually fix the issue of the interfaces being polled by multiple devices at the same time, by disconnecting them when we know they'll be polled by something else.

**Describe alternatives you've considered**
I have considered those options, which are not really adequate to our workflow : 
- Sending a read request to the bus
- Writing a message to the bus
- Restarting the flow
- 
The reason those are not really considered adequate to us is that, in the first two cases, we often place nodes on customer's infrastructures. Some of them are quite extensive and we do not want to pollute/overload the bus with "useless" messages. I know it will most likely be an edge case issue, but if we can avoid it altogether, it would be preferred.

As for restarting the flow, it might work well for restarting the disconnected KNXUltimate node, but, as you can imagine, it restarts everything else. Not the best option.

Thank you very much !

**Comment by Supergiovane** [comment]
Hi Webbeh,
KNX-Ultimate tries several times to reconnect if, for example, it find the tunnel unavaiable.
After some amount of time, the interval between each reconnection attempt becomes longer and longer, to reduce LAN traffic.
They never give up.
Your request will be added in the next version, along with some other little things.
If possible, already today.

FYI, you can also use the Watchdog node that, along other options, it allows to trigger a new connection to a gateway, by passing custom config. See here. https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---WatchDog

PS: if you're a PRO, i can put your logo and webpage link, to the main README page in gitHub, if you wish. Totally free.

**Comment by Webbeh** [comment]
Thank you. Didn't think of using the watchdog node. However, if I understand properly, it only works if the device is actually down (doesn't respond to ping). Our interfaces are still pingable, you just can't connect to it because another device is currently connected to it.

For the increasing timeout, I guess that makes sense. Guess I'm just really unlucky with the reconnection attempts not getting through 😄 

For the logo, I'll get back to you. I don't have authority for that kind of decision, but thanks for the offer :)

**Comment by Supergiovane** [comment]
Hi Webbeh,
yes you can do it with watchdog node. This is able to check a real KNX device as well, by sending a read request to a GA. If the GA didn't respond, the watchdog triggers a msg.

But you are asking a different thing, because currently, knx-ultimate is UNABLE to remain disconnected. It tries forever to connect!
Thus, msg.disconnect = true can be implemented

**Comment by Supergiovane** [comment]
Hi Webbeh
i received your logo and link.
Will add that to the README page with the upcoming new release.
Thanks.

**Comment by Supergiovane** [comment]
Hi Webbeh,
V. 1.2.29 is out (you should see it in about 10-20 minutes in the palette).
See here, scroll all way down: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---WatchDog

**Comment by Webbeh** [comment]
Hi again.

Didn't really try until today, and it doesn't seem to have any effect.

A disconnected node will not connect by sending a "msg.connectGateway: true", and a connected one will not disconnect when sending the "msg.connectGateway: false" message.

Am I right to send them to the "watchdog" node ?

**Comment by Supergiovane** [comment]
Hi,
Yes, send it to the watchdog node.
I've tested with the sample and it works:
https://user-images.githubusercontent.com/37666636/118962305-863e5700-b965-11eb-8574-d1ba4019c1e7.mov
Have you copied the code in the sample page?

**Comment by Webbeh** [comment]
Well, you have a look :)

https://youtu.be/cEDrOCvt7DM

**Comment by Supergiovane** [comment]
Hi
it seems that the message doesn't even reach the Watchdog node.
I've tested again with the same chain as you and it works. I've tested with a KNX Router and with a KNX Interface.
<img width="725" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/118972685-1cc44580-b971-11eb-9363-b5f9046fc94f.png">

Can you please paste this code into one of your flow and test again?
`
[
    {
        "id": "dd477184.629648",
        "type": "inject",
        "z": "5c2de561.6a0de4",
        "name": "Disconnect",
        "props": [
            {
                "p": "connectGateway",
                "v": "false",
                "vt": "bool"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 150,
        "y": 220,
        "wires": [
            [
                "a3c04888.03a6d"
            ]
        ]
    },
    {
        "id": "a3c04888.03a6d",
        "type": "knxUltimateWatchDog",
        "z": "5c2de561.6a0de4",
        "topic": "12/0/0",
        "maxRetry": 6,
        "retryInterval": 10,
        "name": "",
        "autoStart": true,
        "checkLevel": "Ethernet",
        "x": 360,
        "y": 220,
        "wires": [
            []
        ]
    }
]
`

**Comment by Webbeh** [comment]
Exactly the same result. I tested it with a few different interfaces.

![image](https://user-images.githubusercontent.com/1530837/118994468-a8949c80-b986-11eb-97e2-2c6c1dcb6e21.png)

There's nothing visible in the logs either.

**Comment by Webbeh** [comment]
Also, tried with a different options : 
- tried changing the "bind to local interface" from Auto to a specific one
- Tried suppressing/unsuppressing the ACK requests
- Tried changing the KNX Phys Address
- Tried having the logs to "Trace" : nothing in the log there either.

Here's the current configuration : 
![image](https://user-images.githubusercontent.com/1530837/118995080-2789d500-b987-11eb-8875-ddae16ff14f1.png)
![image](https://user-images.githubusercontent.com/1530837/118995254-48eac100-b987-11eb-88a6-d632bfdd7648.png)

**Comment by Supergiovane** [comment]
Hi
it seems that the message won't event reach the watchdog.
If you watch my video, you'll see that as soon as i click the Inject button, the watchdog turns grey then yellow.
In you case, the watchdog don't react. This is strange. It seems that you're using an older version of knx-ultimate instead of the latest.

**Comment by Webbeh** [comment]
![image](https://user-images.githubusercontent.com/1530837/119000520-79ccf500-b98b-11eb-9b6a-aa9f52d141c8.png)

NodeRed v. 1.3.3

I restarted nodered for good measure but still nothing sadly.

I'll try to re-create a new interface, see if that helps.

**Comment by Webbeh** [comment]
node v15.12.0
node-red v1.3.3
knxultimate 1.2.32

**Comment by Supergiovane** [comment]
As a last resort, you can try to install again knx-ultimate.
Open a prompt command, enter into the **.node-red** folder (in your home directory), then issue a command **npm install node-red-contrib-knx-ultimate**
Then restart node-red.

**Comment by Webbeh** [comment]
Apparently, re-installing it from console seems to have done the trick, and the nodes are working as expected now.

![image](https://user-images.githubusercontent.com/1530837/119471754-de9c9c80-bd49-11eb-83f0-5b4a4bbdd6f2.png)

Maybe adding a warning to the wiki that they might need a reinstall ?

In any case, thank you very much :)

**Comment by Supergiovane** [comment]
Hi
Node-Red palette manager performs exactly the install sequence you've done by hands.
This is the first time i saw a thing like that.
Good that it worked.

**Comment by Webbeh** [comment]
I don't understand it either, but who cares, it works now :P 

Thank you again !
