### ISSUE TITLE
null DTP unknown

### ISSUE THREAD

**Issue by Makrador** [Supergiovane/node-red-contrib-knx-ultimate#124]
Hi,

great node BTW. appreciate your work...

Since yesterday evening i am getting the error null DTP unknown on all (ALL) nodes that should only read from bus.
even the connection (green) marker vanished for that node.....

I am not sure if it is a Node Problem right now.... but it looks strange that only the READ from bus nodes are affected....
after Reboot / Restart i get feedback for 30s - 1 minute after that the green marker vanishes and i only get in the debug 
output "null" .
I can still write to the bus and get the information echoed back...

This happens using a IP router as well as using a tcp bus connector as a target.

at the moment i am using multicast 224.0.23.12:3671 and a node-red snap installation on proxmox with daily image backup.
what I tried so far:
restore a version from 2 days ago.... no change
updated the knx ultimate node to 1.2.32 ... no change
rebooted the knx router ... no change
checked the switch for storm protection ... no change

I use more than knx all over my installation.... but for now only knx is effected
still getting shelly infos, unifi information and from my solaredge environment all infos... 

worked for at least 12 Month..... until yesterday....

any ideas ?

cheers
Mak
seems I cannot upload the screenshots....."Something went really wrong and we can't process that file.....
tried ,jpg and .png...

**Comment by Supergiovane** [comment]
Hi,
have you changed something before it happens?
The READ from bus doesn't need any datapoint and if the node is set to react to READ telegrams, it outputs null.
Please tell me the node version (issue a node -v command in a prompt window), and node-red version.

**Comment by Makrador** [comment]
Hi,

no din't change anything.... just mentions no temp on dashboardscreen.....

# snap list
Name      Version   Rev    Tracking         Publisher     Notes
core      16-2.50   11081  latest/stable    canonical✓    core
core18    20210507  2066   latest/stable    canonical✓    base
lxd       4.14      20450  latest/stable/…  canonical✓    -
node-red  1.2.9     675    latest/stable    noderedteam✓  -

cannot find a node command, its maybe within the snap package ?

**Comment by Makrador** [comment]
I uploaded the screenshots here.....

https://ibb.co/VjcW35y
https://ibb.co/K9ryQv2
https://ibb.co/gr4HBsV
https://ibb.co/QHNk7jw

**Comment by Supergiovane** [comment]
Hi
if the nodes are set to react to READ requests, it's normal to have null/unknown, because a READ request doesn't contain any data.
If all works as expected, simply ignore that status message.
I don't know what is snap package, so i cannot help with that!
Other that that, it's very difficult to debug your issue not having images embedded in the messages nor having your flow exported.
If you can at least export your nodes and paste it here into the "code" tags (<>), at least i can test it on my mac.

**Comment by Makrador** [comment]
https://snapcraft.io/store.  her you should find some infos about snap packages.....

i restored a version from 25th of April... same Problem...
still not sure about the error origin... 

i can export the flow... but that will be huge.... i will post it on pastebin... to make sure the code will be correct...
https://pastebin.com/WqppKzjw.  

if you need more let me know...

**Comment by Makrador** [comment]
got a step further.....
I set the node configuration to "debug" and get the following error msg:
"KNXUltimate-config: Error in instantiating knxConnection Interface en9 not found or has no useful IPv4 address!. Node undefined"

the strange thing about is that in the config "auto" is used, if i choose the network adapter it it named en18 not en9...... could be a verry old setting.... everything used to run on a raspberry years ago....

**Comment by Supergiovane** [comment]
Good
Change the interface to en18 and tell me if it works

**Comment by Makrador** [comment]
hmmm... seems to work at least for more than 10 minutes now... but the error msg is still there.... complaining about en9...
did you hard code en9 into the node ? I checked my old raspi... that is using en3.... where is the en9 coming from ?

**Comment by Supergiovane** [comment]
Hi
Please check whether you have an old, unused configuration node somewhere, as i cannot find en9 in your pastebin json file.
You need to restart node-red after changing the interface.

**Comment by Makrador** [comment]
hmmm no en9 anywhere.... strange.....
but after using manually interface configuration setting it to en9, restart node-red setting back to auto and restarting, the error is gone.... funny.....
Still no clue where this en9 is coming from.. but looks like is working now.... even without errors.....
I will look after it today, if there are no problems, we can close the issue.....

**Comment by Supergiovane** [comment]
A similar issue happened to my with an Alexa node during a node-red migration from a machine to another. I had to delete the Alexa credential configuration node and create a new one.
Please let me know.

**Comment by Makrador** [comment]
so error is back....
looks like the reading nodes are loosing the connection to the knx bus...
after altering the node config node config it works for a few seconds... green dot... after a while it changes to blue dot  and than to a gray dot......

**Comment by Supergiovane** [comment]
No, no limits.
Blue dot means that the node is reacting to response telegrams.
Grey dot means that it's reacting to a read telegram.
It's a normal behaviour.
See here, at the bottom of the page
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-2.-Node-Configuration

**Comment by Makrador** [comment]
so, I think I found the problem.....
Like expected it was not your node ;) 

I found, after switching from Multicast to unicast for testing that a older Unifi Switch was trying to "enhance Multicast" so after going to the whole config there I found a way to not "enhance" it, I need to talk to that guy who installed that switch anyway .... 

Switching back to multicast and without "Enhancement" it lokks good again...

Cheers and thx for your time....

**Comment by Supergiovane** [comment]
Hi
Yes i have unifi as well and totally disabled any kind of “magic” option, otherwise unicast is blocked. 
On unifi forum, there are many users complaining about that.
