### ISSUE TITLE
improve KNX logger node

### ISSUE THREAD

**Issue by slev1n** [Supergiovane/node-red-contrib-knx-ultimate#125]
**Is your feature request related to a problem? Please describe.**
I cannot see messages which a send from nodered knx device node.

**Describe the solution you'd like**
Log messages from nodered too.

**Comment by slev1n** [comment]
Hi, yes i followed the sample and it worked except messages from nodered.
It did not log messages which are triggered from a nodered flow. 
The ETS log these messages:

# | Zeit | Quelladresse | Quellname | Zieladresse | Zielname | DPT | Info
-- | -- | -- | -- | -- | -- | -- | --
51 | 10.06.2021&nbsp;16:56:42,145 | 1.1.252 | &nbsp; | 7/0/4 | A1/A2 - Fassade/Garage - Helligkeitssensor - Helligkeit Westen | 9.004 Lux (Lux) | 66 D4 \| 71598,08 Lux


1.1.252 is the address from the nodered instance
 
But the log from knx logger did not show the message:
<CommunicationLog xmlns="http://knx.org/xml/telegrams/01">
  <Telegram Timestamp="2021-06-10T14:56:42.0762088Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900BCD0120938030300806613" />
  <Telegram Timestamp="2021-06-10T14:56:43.438106Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="2900BCD0120138000300805C5D" />
<RecordStop Timestamp="2021-06-10T14:56:51.153Z" />
</CommunicationLog>

**Comment by Supergiovane** [comment]
Hi
have you installed the latest knx-ultimate version?

**Comment by slev1n** [comment]
Hi, sry for my late reply. U are right after upgrading to the latest version it worked for me.

**Comment by Supergiovane** [comment]
Perfect. Please star my node if you like it.
