### ISSUE TITLE
Figure out the correct datapoint

### ISSUE THREAD

**Issue by wi-th** [Supergiovane/node-red-contrib-knx-ultimate#127]
Hi Supergiovane!
First of all congrats to this great library and thank you that you offer it to everyone!
I am not 100% sure if you see it as a bug but it is not acting as I expect and therefore I report a bug instead of a feature request.

**Bug description**
When using the node in universal mode and receiving a dimming command from KNX, the message is showing the datapoint 5.001 (percentage) what is wrong, because the group address is part of the ETS import with the datapoint 3.007.

**How to reproduce it**
1. place a knx-ultimate node
2. import the ETS group address (group address with datapoint 3.007)
3. dimm on the knx-switch
4. See the message received from the knx-ultimate node with datapoint 5.001

**Expected behavior**
In universal mode it is mandatory to do the ETS group address import.
Therefore my expectation was, that it takes the needed information out from the ETS info to build the message.
So if the received group address is part of the import it should take the configured datapoint instead of "guess" it.

**Screenshots**
![image](https://user-images.githubusercontent.com/67182162/123795251-1a47fa80-d8e4-11eb-825e-77b85f555d0a.png)

**Knx-Ultimate Version**
 1.2.34

**Are you running node-red behind homematic, docker or anything similar?**
node-red is running on a windows pc

**Additional context**
I want to use the knx-ultimate node in universal mode to just have one node for the communication from and to knx.
The idea is to control a system depending on actions on e.g. knx switches.

**Comment by Supergiovane** [comment]
Hi
thank you to you.
That's very strange behaviour. 
It enters this "trytofigureout..." function, wenever either it doesn't find the datapoint from the ETS import, or if there's no imported file at all. 
Can you sen me your ETS import file you pasted into the knx-ultimate gateway node?
Thanks

**Comment by wi-th** [comment]
Thank you for your quick response.
The issue was on the group address "1/2/4".
Here the Info I pasted in the node:

"Trainingswand"	"1/-/-"	""	""	""	""	"Auto"
"Schalten / Dimmen"	"1/1/-"	""	""	""	""	"Auto"
"Zentral EIN/AUS"	"1/1/1"	""	""	""	"DPST-1-1"	"Auto"
"Schalten Relay 1"	"1/1/2"	""	""	""	"DPST-1-1"	"Auto"
"Schalten Relay 2"	"1/1/3"	""	""	""	"DPST-1-1"	"Auto"
"Schalten Leuchte 1"	"1/1/4"	""	""	""	""	"Auto"
"Schalten Leuchte 2"	"1/1/5"	""	""	""	""	"Auto"
"Schalten Kanal A"	"1/1/6"	""	""	""	""	"Auto"
"Schalten Kanal B"	"1/1/7"	""	""	""	""	"Auto"
"Dimmen Leuchte 1"	"1/1/11"	""	""	""	""	"Auto"
"Dimmen Leuchte 2"	"1/1/12"	""	""	""	""	"Auto"
"Dimmen Kanal A"	"1/1/13"	""	""	""	""	"Auto"
"Dimmen Kanal B"	"1/1/14"	""	""	""	""	"Auto"
"Taster"	"1/2/-"	""	""	""	""	"Auto"
"Wippe 1 schalten"	"1/2/1"	""	""	""	"DPST-1-1"	"Auto"
"Wippe 2 schalten"	"1/2/2"	""	""	""	"DPST-1-1"	"Auto"
"Wippe 3 schalten"	"1/2/3"	""	""	""	"DPST-1-1"	"Auto"
"Wippe 1 Dimmen"	"1/2/4"	""	""	""	"DPST-3-7"	"Auto"
"Wippe 2 Dimmen"	"1/2/5"	""	""	""	"DPST-3-7"	"Auto"
"Wippe 3 Dimmen"	"1/2/6"	""	""	""	"DPST-3-7"	"Auto"
"Wippe 1 Status links"	"1/2/7"	""	""	""	""	"Auto"
"Wippe 1 Status rechts"	"1/2/8"	""	""	""	""	"Auto"
"Wippe 2 Status links"	"1/2/9"	""	""	""	""	"Auto"
"Wippe 2 Status rechts"	"1/2/10"	""	""	""	""	"Auto"
"Wippe 3 Status links"	"1/2/11"	""	""	""	""	"Auto"
"Wippe 3 Status rechts"	"1/2/12"	""	""	""	""	"Auto"

**Comment by Supergiovane** [comment]
Hi 
i se two issues:
the first, there is no header row, like this:
**"Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"**

The second one, the separator is not a tabulator.
Please see here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/1.-Gateway-configuration by scrolling down to the page, there is a description on how to export the ETS file.
Please try again exporting the file and let me know.

**Comment by Supergiovane** [comment]
Hi 
I use the header line to identify the file type, so it’s mandatory. Let me know.

**Comment by wi-th** [comment]
Hello,
it seems to work properly if I have the header line in. 
Many thanks for your very quick responses and help!

**Comment by Supergiovane** [comment]
Good!
Bye!
