### ISSUE TITLE
Can't Writing

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#129]
Hello ,This is a great node, which helped me a lot, but now I have a problem

The data cannot be written to the knx node, the node-red process must be restarted, and then this bug will appear

**Screenshots**
![node](https://user-images.githubusercontent.com/26770241/125250741-3064aa80-e329-11eb-92bb-c4a6067ecccd.png)
![node config](https://user-images.githubusercontent.com/26770241/125251784-432baf00-e32a-11eb-9cf5-27d083258638.png)

**Knx-Ultimate Version:1.2.34**

**Are you running node-red behind homematic, docker or anything similar?**
- KNXD 
- Node-Red running alone in RaspberryPi

**Additional context**
- There is no problem with KNXD, because I can use it normally on ETS
- 
![image](https://user-images.githubusercontent.com/26770241/125251650-1f686900-e32a-11eb-9d30-1fb851743251.png)

**Error Logs**
```
[error] 7/12/2021, 15:48:04 knxUltimate-config: Send Fail Callback: Error while sending a message Invalid KNX source address ("")!
0|node-red | BANANA FIGA ERRORE! localEchoInTunneling TypeError: Cannot read property 'toString' of null
0|node-red |     at fsm._onEnter (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/FSM.js:474:44)
0|node-red |     at fsm.transition (/home/pi/.node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:175:1)
0|node-red |     at fsm.Fsm.<computed> [as transition] (/home/pi/.node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
0|node-red |     at fsm.outbound_TUNNELING_REQUEST (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/FSM.js:316:16)
0|node-red |     at fsm.handle (/home/pi/.node-red/node_modules/machina/lib/webpack:/src/BehavioralFsm.js:135:1)
0|node-red |     at fsm.Fsm.<computed> [as handle] (/home/pi/.node-red/node_modules/machina/lib/webpack:/src/Fsm.js:80:1)
0|node-red |     at fsm.Request (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/Connection.js:166:8)
0|node-red |     at fsm.write (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src/Connection.js:266:8)
0|node-red |     at Timeout.handleTelegramQueue [as _onTimeout] (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:1059:48)
0|node-red |     at listOnTimeout (internal/timers.js:554:17)
```

**Comment by Supergiovane** [comment]
Hi again Songzh.
This is the culprit _Send Fail Callback: Error while sending a message Invalid KNX source address ("")
There is no source address specified.
Can you paste here the affected nodes, so i can check what you're sending to knx-ultmate nodes?

**Comment by songzh96** [comment]
AHa

I find the bug reason
the scenenumber can't use 1, it will  cause the node interruption
{"save_recall":1,"scenenumber":1}

Thanks

Best Regards 
Songzh
