### ISSUE TITLE
Trouble with KNXUltimate

### ISSUE THREAD

**Issue by GeorgiyPSK** [Supergiovane/node-red-contrib-knx-ultimate#130]
Hello!
I made a small project, everything works, but an error is displayed in the Node-Red log every five seconds "KNXUltimate-config: Error in instantiating knxConnection INVALID IP. Check the IP in Config node.. Node Multicast KNX Gateway"
Everything works well, I can't figure out what's the matter.
I use version 1.2.34
Thanks in advance for your help!

PS: KNX Device config
[{"id":"b4b74bea.9e0748","type":"knxUltimate","z":"89267608.681a18","server":"997542da.2ad6f","topic":"0/0/6","outputtopic":"","dpt":"1.008","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"test","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":400,"y":40,"wires":[["c740f61.8cbfc08"]]},{"id":"997542da.2ad6f","type":"knxUltimate-config","host":"192.168.11.110","port":"3671","physAddr":"15.15.22","suppressACKRequest":true,"csv":"","KNXEthInterface":"Ethernet","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"silent","name":"Multicast KNX Gateway","localEchoInTunneling":true,"delaybetweentelegrams":"40","delaybetweentelegramsfurtherdelayREAD":"1","ignoreTelegramsWithRepeatedFlag":false}]

**Comment by Supergiovane** [comment]
Hi
Are you sure not to have other forgotten configuration nodes, not configured?
Have you tried to restart nodered?

**Comment by GeorgiyPSK** [comment]
Reboot helped...
Felt like a fool)))
Thank you!
