### ISSUE TITLE
knxUltimate node stops producing knx datagrams after some time

### ISSUE THREAD

**Issue by funkpunkt** [Supergiovane/node-red-contrib-knx-ultimate#133]
Hello everyone!
I've been using node-red-contrib-knx-ultimate for a while now and I think I discovered a bug.

**Describe the bug**
A knxUltimate node stops producing knx datagrams after some time.

**To Reproduce**
I am using 3 *identical* knxUltimate nodes (created by copy/paste) inside a sub flow in a parallel setup. When the sub flow is started with a set of data from outside, the incoming data is distributed to 3 branches and turned into 3 parameter sets by function nodes. Each of the knxUltimate nodes is primed with its own parameter set. The params looks like this:

```
msg.destination = "0/0/100";
msg.dpt = 1.0008;
msg.payload = 1;
msg.delay = 3000;
```

The delay parameter is picked up by a delay node just in front of the knxUltimate node.

destination, payload and delay vary for each call to the sub flow and for each of the 3 knxUltimate nodes. One call to the sub flow produces 3 subsequent datagrams on the knx bus and thus 3 subsequent actions.

The connection to the knx bus is established through a MDT knx gateway over ethernet.

There has been an ***earlier variant*** of this setup merging the flow behind the 3 delay nodes into just 1 knxUltimate node with the exact same behavior.

**Expected behavior**
I would expect 3 subsequent datagrams on the knx bus once the sub flow is triggered.

**Actual behavior**
Everything works fine for a while. After one or a few days the behavior changes. The first (shortest delay) of the 3 nodes does not produce a datagram on the bus while the other remaining 2 nodes do.

Once there is a deploy action issued anywhere in node red, not related to the mentioned sub flow or any knxUltimate node, the behavior is back to normal for some time. Same of course for a restart of node red or a system reboot but a simple deploy is sufficient.

Seeing it work for some time and then going disfunctional for just one single knxUltimate node instance makes me believe it's something related to this node or its implementation respectively.

**Screenshots**
<img width="446" alt="node-red_sub_flow" src="https://user-images.githubusercontent.com/18400510/130244996-36d89148-eb80-4aaa-8a70-611eb322610b.png">

**Knx-Ultimate Version**
1.2.39

**Are you running node-red behind homematic, docker or anything similar?**
 Node-Red (installed via snap) on Ubuntu 20.04.2 LTS (x86_64)

**Additional context**
n/a

**Comment by Supergiovane** [comment]
Hi
is this `msg.dpt = 1.0008;`  an unwanted syntax error? The datapoint should have only 3 numbers after the point, and must be passed as string: `msg.dpt = "1.008";`

**Comment by Supergiovane** [comment]
Also... is there a reason by leaving the rbe filter active? If not, please remove the rbe filter.

**Comment by funkpunkt** [comment]
Hi
This was a quick one! I obviously misunderstood how the rbe filter is meant to be used.
As it is turned on by default and the description in the documentation made sense to me, I left it turned on. The way this sub flow is triggered by various other nodes in a certain sequence over time made it work for knxUltimate node 2 and 3 but started causing problems for node 1 at some point. Thus it wasn't obvious to me that the filter caused the problem.

Thanky you very much for clarification.

**Comment by Supergiovane** [comment]
Thank you to you!
