### ISSUE TITLE
i18n support zh-CN

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#136]
Hi @Supergiovane 
I translated the wiki into a Chinese document, how do I upload it？

**Comment by Supergiovane** [comment]
Hi Songzh.
Wow!
You cannot, because the wiki is hidden by gitHub. Please zip all and attach it here.
Thanks.

**Comment by songzh96** [comment]
[node-red-contrib-knx-ultimate.wiki.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7116291/node-red-contrib-knx-ultimate.wiki.zip)
I did not add a link to the Chinese document, can you help me add it

**Comment by Supergiovane** [comment]
Thanks
I’ll start to implement that. Are you able to translate the node config texts as well?

**Comment by songzh96** [comment]
Have been translated for a while and submit a pull request

**Comment by songzh96** [comment]
![Node-RED KNX Ultimate 交流群群二维码](https://user-images.githubusercontent.com/26770241/132228063-3b3b3124-b0fb-4fa2-8ecd-c97ebabcbce8.png)

Can you add a Chinese forum at the end of the README document，
`QQ group: 837579219 （加群需要备注 “来自github”）`

**Comment by Supergiovane** [comment]
Yes, sure!
Please be patient some days, because i’m on holiday and have no access to all the things!

**Comment by Supergiovane** [comment]
Hi Songzh
can you translate this as well? You need to add a row in your language, then i'll adapt the link to point to ypou cn wiki. Thanks.

[_Sidebar.md](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7117217/_Sidebar.md)

**Comment by Supergiovane** [comment]
..and i need your country flag as well, like this one
https://raw.githubusercontent.com/Supergiovane/node-red-contrib-knx-ultimate/master/img/wiki/flags/usa-today.png

**Comment by songzh96** [comment]
[_Sidebar.md](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7118503/_Sidebar.md)
Hi Supergiovane ，I have added it

**Comment by songzh96** [comment]
![image](https://user-images.githubusercontent.com/26770241/132275572-98951bbe-9fc0-4456-8336-7bb84f476c78.png)
It should be “单击此处查看中文文档”

**Comment by Supergiovane** [comment]
Fixed all. Thanks.
As soon as i've uploaded all the CN wiki with the right links, you can then edit it by yourself by clicking "edit" on github. Maybe.

**Comment by songzh96** [comment]
Hi, I found some error, the link is not direct to the Chinese doc.  
I can’t use the editing function on the wiki page, I can only do it on the code page。。。。

![image](https://user-images.githubusercontent.com/26770241/132316173-3c58b94e-0f9e-48ee-a353-602b92e0b775.png)

**Comment by Supergiovane** [comment]
Hi
I have no idea of what you’ve lined in red. 
Can you do the correction?

**Comment by songzh96** [comment]
[_Sidebar.md](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7120479/_Sidebar.md)
fixed it

**Comment by Supergiovane** [comment]
Ok, uploaded

**Comment by songzh96** [comment]
Hi @Supergiovane 
this is zh-CN samples，If you have time, can you help upload it

[cn-samples.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7143421/cn-samples.zip)

**Comment by Supergiovane** [comment]
Hi songzh
Can you translate this?

**Samples in Chinese**

**Comment by Supergiovane** [comment]
And this: **Please select a sample in the navigation bar**

**Comment by songzh96** [comment]
[-SamplesHome.md](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7143886/-SamplesHome.md)
ok，Already done

**Comment by Supergiovane** [comment]
Ok, uploaded. Many thanks.

**Comment by Supergiovane** [comment]
Hi Songz
can you please edit this page  https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/cn-9.-WathDog-Messages-to-the-node

and translate this part?

_All properties are optional. For example, to only change the IP:

```javascript
// IP: IP of your KNX/IP Router or Interface
msg.setGatewayConfig={IP:"224.0.23.12"};
return msg;
```_

Thanks!!

**Comment by songzh96** [comment]
```
// IP: IP of your KNX/IP Router or Interface
msg.setGatewayConfig={IP:"224.0.23.12"};
return msg;
```
Chinese:
```
// IP: 填写你的KNX路由器或者KNX接口的IP地址
msg.setGatewayConfig={IP:"224.0.23.12"};
return msg;
```

**Comment by Supergiovane** [comment]
Thank you!!

**Comment by Supergiovane** [comment]
And this? 

"All properties are optional. For example, to only change the IP:"

**Comment by songzh96** [comment]
All properties are optional. For example, to only change the IP:
所有属性都是可选的。比如，只改变IP:

**Comment by Supergiovane** [comment]
Hi Songzh
can you translate please this?

"Automatically connect to KNX BUS at start"
"Yes"
"No (To connect, pass msg.connectGateway = true to a Watchdog node)"

Thanks

**Comment by songzh96** [comment]
> Automatically connect to KNX BUS at start"
> "Yes"

在启动时自动链接到KNX总线
是
否（发送 msg.connectGateway = true 到看门狗节点以此来链接KNX总线）

**Comment by songzh96** [comment]
> And also this, please
> 
> * **Automatically connect to KNX BUS at start**
> 
> > Select wether to automatically connect to the KNX BUS at start, or not. Default is Yes. If you select "No", you must manually connect to the KNX BUS, by sending _**msg.connectGateway = true**_ to a Wachdog node. Please seee the Wiki (Watchdog node) for further instruction on how to manually connect/disconnect and change the configuration on the fly.
> 
> ## ADVANCED OPTIONS

> 在启动时自动链接到KNX总线

>>选择是否在启动时自动连接到 KNX BUS。 默认为是。 如果选择“否”，则必须手动连接到 KNX 总线，方法是将 msg.connectGateway = true 发送到 看门狗 节点。 有关如何手动连接/断开连接和动态更改配置的进一步说明，请参阅 Wiki（看门狗节点）。

## 高级选项

**Comment by Supergiovane** [comment]
Hello Songz
Can you please translate this page?
Thanks.
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/cn-LoadControl-Configuration

**Comment by songzh96** [comment]
ok
can you send me the source file

**Comment by Supergiovane** [comment]
You should be able to direct edit the page on gitHub. I gave you access.

**Comment by songzh96** [comment]
It's done

**Comment by Supergiovane** [comment]
Thank you! Your job is very appreciated!
For some reasons, the file was renamed. Please don't rename the files, because all links will be broken otherwise.
Thank you again!
