### ISSUE TITLE
KNXGlobalContext - dpt 5.001 issue sending to KNX bus

### ISSUE THREAD

**Issue by IllegalDuke** [Supergiovane/node-red-contrib-knx-ultimate#139]
Hello,

I am using the KNXGlobalContext node with importet GAs from ETS CSV-File.
The GA I am talking about was imported:
`"Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"J_E02_01_Absolute_Position(Arbeiten)"	"2/1/53"	""	""	"E05_Arbeitszimmer J_E05_01 Arbeiten"	"DPST-5-1"	"Auto"`

When I am writing a value to the KNX bus by a function node with the following code:
`let GroupAddressesSend = [];
GroupAddressesSend.push({address: "2/1/53", payload: 10 });
global.set("KNXGlobalContext_WRITE",GroupAddressesSend);`

Then the KNX bus receives a wrong value ($01 | 0 %), and the jalousie actuator does not accept the command:
<HTML>
<BODY>
<TABLE><TR><TD>#</TD><TD>Zeit</TD><TD>Dienst</TD><TD>Flags </TD><TD>Prio</TD><TD>Quelladresse</TD><TD>Quellname</TD><TD>Zieladresse</TD><TD>Zielname</TD><TD>Rout</TD><TD>Typ</TD><TD>DPT</TD><TD>Info</TD></TR><TR><TD>45</TD><TD>12.09.2021&#160;17:04:03,588</TD><TD>vom Bus</TD><TD></TD><TD>Niedrig</TD><TD>1.1.252</TD><TD>-</TD><TD>2/1/53</TD><TD>J_E02_01_Absolute_Position(Arbeiten)</TD><TD>6</TD><TD>GroupValueWrite</TD><TD> </TD><TD>$01 | 0 %</TD></TR></TABLE>

</BODY>
</HTML>

See the difference between payload: 10 and received value ($01 | 0 %) on the KNX bus.
Normaly with dpt 5.001 a value of 0% would be:  ($00 | 0 %) so the received value is not matching dpt 5.001.

When I adjust my code, to manually tell the node what dpt I have:
`let GroupAddressesSend = [];
GroupAddressesSend.push({address: "2/1/53", dpt:"5.001", payload: 10 });
global.set("KNXGlobalContext_WRITE",GroupAddressesSend);`

Then the KNX bus receives the right value:
<HTML>
<BODY>
<TABLE><TR><TD>#</TD><TD>Zeit</TD><TD>Dienst</TD><TD>Flags </TD><TD>Prio</TD><TD>Quelladresse</TD><TD>Quellname</TD><TD>Zieladresse</TD><TD>Zielname</TD><TD>Rout</TD><TD>Typ</TD><TD>DPT</TD><TD>Info</TD></TR><TR><TD>1</TD><TD>12.09.2021&#160;16:58:16,022</TD><TD>vom Bus</TD><TD></TD><TD>Niedrig</TD><TD>1.1.252</TD><TD>-</TD><TD>2/1/53</TD><TD>J_E02_01_Absolute_Position(Arbeiten)</TD><TD>6</TD><TD>GroupValueWrite</TD><TD> &nbsp;5.001 Prozent (0..100%)</TD><TD>$1A | 10 %</TD></TR></TABLE>

</BODY>
</HTML>

So the KNXGlobalContext node does not find the right dpt for the imported GA with dpt 5.001.

If I add a KNX Device node to my flow, it detects the dpt 5.001 automatically, what tells me, that the GA was importet and is known by KNX Ultimate.

**Knx-Ultimate Version**
 - 1.2.45

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-RED is running in IoBroker.

**Comment by Supergiovane** [comment]
Hi Duke
I’ll give a shot tomorrow at office!

**Comment by Supergiovane** [comment]
Hi
i can reproduce the issue. I'm working on that. I'll keep you updated.

**Comment by Supergiovane** [comment]
Hi,
the issue is fixed.
A new version will be out in about 1 hour.
If you enjoy my node, please star it on gitHub.
Thanks :-)

**Comment by IllegalDuke** [comment]
Thank you for the very fast support!
