### ISSUE TITLE
null payload to a Text DPT (16.001) 

### ISSUE THREAD

**Issue by Supergiovane** [Supergiovane/node-red-contrib-knx-ultimate#14]
I faced an annoyingly hard to find „bug“. If you send a null payload to a Text DPT (16.001) this leads to an error message only visible in the log of node-red and not in the debug pane, so it’s hard to find. Unfortunately this blocks the whole KNX communication. It cost me half a day to find out what was wrong.

**Comment by metaneutrons** [comment]
Dear Massimo, thank you for opening the issue.

I tried to reproduce the error and now it’s gone. I removed the RBE-nodes blocking null-values I inserted in my flow as a quick workaround and everything runs smooth. Weird!

The error raised when a function node eventually (!) returns null as payload and led to an error message in the log raised by https://bitbucket.org/ekarak/knx.js/src/master/src/dptlib/dpt16.js (line 13) stopping all KNX Ultimate nodes from getting traffic from the bus.

I really tracked down it to the problem described; but now it runs just fine. Sorry to bother you.

If I experience the behavior again I will let you know.

Kind regards,
Fabian

**Comment by Supergiovane** [comment]
Thanks Fabian.
Maybe something related to deploy button. Normally i use "Deploy modified nodes" in node-red, but when you touch the configuration nodes (this is valid for all node types), you should ever use "Deploy Full" button.
Or maybe is due to some variable not initialized when the node is newly created.
I tried to reproduce the issue, but i obtained only "Cannot read property 'toString' of null" in the debug window, but the system still works.
I've more than 600 group address and the node is up and running since ca. 1 year (in my oldest installation, because i have 3 in total).
