### ISSUE TITLE
Automatic States import from GA ind iobroker KNX 

### ISSUE THREAD

**Issue by d3frost** [Supergiovane/node-red-contrib-knx-ultimate#141]
Hello i´m new to Node Red and first i think i can imagine how usefull this cn be in case of KNX Ultimate ! 
But i have a small Problem with the understanding :( 

I want to create States for using in ioBroker VIS, so far im thinking i´m on the right way . But in the States ther is no Info what tis GA is about. Is it possible to get the States with descrition ? I only get the GA´like 0/0/7 for example .... without the Text :( 

Maybe ther is a small hint to get this working ? 

BR.

Jean - Paul 

![statesiobroker](https://user-images.githubusercontent.com/10303373/133703888-49df400f-5f2d-4793-bb94-65d2b89518e3.png)

**Comment by Supergiovane** [comment]
Hi Jean
I’m sorry, i’ve no knowledge on iobroker! You must ask on iobroker forum!
