### ISSUE TITLE
Node Disconnection from KNX Bus

### ISSUE THREAD

**Issue by Elektroarzt** [Supergiovane/node-red-contrib-knx-ultimate#142]
Dear Massimo,

I have a problem with your knx ultimate nodes, maybe you can give me a hint.
I run a big home automation project with more than 250 knx ultimate nodes. In certain cases of a mdt knx button calling a physical address with true (DP1.001) which is processed in node red and then outputs a scene number (DP18.001) back to knx results in a hung knx ultimate node. The node is not processing anymore for seconds to minutes in some cases and in this time throws connection errors on the watchdog node.

**Node Red Flow**
<img width="830" alt="image" src="https://user-images.githubusercontent.com/61664171/133745560-3d540c36-f858-4dc9-9d75-759e1c85f92f.png">

JSON file of example flow:
[flows json.txt](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7183970/flows.json.txt)

**To Reproduce**
1. send true to the input node on the left via knx button
2. watch debug window, all knx ultimate nodes throw connection errors

**Debug Output**
<img width="270" alt="image" src="https://user-images.githubusercontent.com/61664171/133746075-1b6166ea-2e12-4fa6-b06a-7cd8c1fad720.png">

**System**
- Node-Red-Contrib-KNX-Ultimate Nodes V1.2.46
- Node Red 2.0.6
- Debian 4.19.181-1 on
- Synology DS216+II Virtual Machine
- HP V1910-24G Switch 
- MDT KNX IP Interface (Application SW V3.0.3)

It seems not to be a general node red issue as other nodes are working while knx nodes seem to be hung up. I studied your FAQ WIKI and tried the hints but I am stuck in this issue. I would kindly appreciate your help.

Thank you in advance,
Thomas

**Comment by Supergiovane** [comment]
Hi
Ok, leave me some time to investgate...

**Comment by Supergiovane** [comment]
Hi Thomas
Can you put a debug node here and tell me what it outputs?
Thanks.
<img width="1379" alt="133745560-3d540c36-f858-4dc9-9d75-759e1c85f92f_png_1_660×322_pixel" src="https://user-images.githubusercontent.com/37666636/133752078-b2152201-84b9-4c6e-9fbb-c31d9721c0a9.png">

**Comment by Elektroarzt** [comment]
Thanks for your ultrafast response ... this is, what debug brings up in dependency of the prior state machine output:

State off:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/61664171/133755024-9954f8c7-1422-4e2a-ba07-f38b14f36815.png">

State on:
<img width="248" alt="image" src="https://user-images.githubusercontent.com/61664171/133755642-63cb522b-cfdc-41b8-bc0a-8ecf0b9bb91c.png">

**Comment by Supergiovane** [comment]
Hi
Ok, there is a lot of properties in the message.
Can you try this for me?
Import the code below and put the node you pasted, between the two nodes indicated by the red arrow.

`[
    {
        "id": "50cf9d47f7939ee5",
        "type": "function",
        "z": "5ed79f4a958a1f20",
        "name": "",
        "func": "return { topic:msg.topic, payload: { \"save_recall\": msg.payload.save_recall, \"scenenumber\": msg.payload.scenenumber } };\n",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1110,
        "y": 120,
        "wires": [
            []
        ]
    }
]`

Then try again and let me know.

**Comment by Elektroarzt** [comment]
The flow now looks like this:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/61664171/133759456-cfd7fcb2-6826-4dde-8e7d-8c07959c34ee.png">

Debug output:
<img width="196" alt="image" src="https://user-images.githubusercontent.com/61664171/133759376-a122bd2e-df89-4d41-afc8-532a964dbbe3.png">

Result is the same behavior as before.

**Comment by Supergiovane** [comment]
That is very odd. I'm unable to reproduce the issue.
Let me some more time...

**Comment by Elektroarzt** [comment]
Thank you Massimo

**Comment by Supergiovane** [comment]
I've tested with two KNX Routers in multicast and two in unicast (Enertex and an Eibmarkt interface).
All works without issues. No disconnections.
Are you able to temporary put in a different KNX Interface, or even better, a KNX Router to test?

**Comment by Elektroarzt** [comment]
I will try this and write back 😃

**Comment by Elektroarzt** [comment]
I made an interesting observation. If I disconnect the hue nodes in the flow like this:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/61664171/133769792-dbee3e93-e1a3-45fb-9381-c21b99ea8b3d.png">
I receive no errors on the watchdog node and all knx ultimate nodes keep alive.

Can you imagine any cross relation between your and the hue nodes?
(node-red-contrib-huemagic V3.0.0)

**Comment by Supergiovane** [comment]
Hmmmm
Maybe a retroaction between the two scene nodes? Is the hue linked anywhere in your flows, to a knx ultimate?
