### ISSUE TITLE
Issues with Zennio KIPI IP interface

### ISSUE THREAD

**Issue by bartdesign** [Supergiovane/node-red-contrib-knx-ultimate#143]
Hello Supergiovane,

Thanks for this great module. It seems exactly what it need to get some more data into my KNX bus :-) 

I'm having some issues with my IP interface. Link to the interface: https://www.zennio.com/products/system/kipi

Here is my flow: 
![Schermafbeelding 2021-09-18 204402](https://user-images.githubusercontent.com/404375/133905384-d31e34af-aba0-4c6c-8003-15a6102f5b8a.png)

I've tried multicast; but then i don't get any connection at all. When i try the direct IP adres it works with one time After that it does not update anymore, also when i restart the flow it still refused to work. And it reports no errors.

If i wait a while and restart the flow and it works once again. But this is only with the direct IP.

I've played around with the Ack settings but it does not resolve the issue. Debugging window reports no text.

I'm using the latest version of KNX Ultimate. I've tried it on my PC and on a raspberry pi; I did try to connect it to the IP interface with an small switch directly to sort out any mulitcast issues. Also a side note; i use the Easy KNX iphone app which connects to the multicast with no issues. So the multicast is confirmed working. Also i can use other apps with the tunneling with no issues. I wonder what is going wrong with the node red plugin.

I'm running node red on bare metal; so no virtual machines. I've exhausted my options, If i can do anything else to debug this issue i will gladly do so. Thanks!

**Comment by Supergiovane** [comment]
Hi
You have the rbe filter enabled, blocking you to send the same value multiple times.

**Comment by bartdesign** [comment]
Thank you for the quick reply! I disabled RBE and it solves my issues. Thanks!! I guess i should have read better.
