### ISSUE TITLE
Telegram seems to get dropped

### ISSUE THREAD

**Issue by danube** [Supergiovane/node-red-contrib-knx-ultimate#144]
Dear Max, thanks for your super work. I'm actually facing an interesting behavior and to be honest, I'm not a bit sure on what point it goes wrong. Let me describe what I see:

## Here's the issue
I have some motion detectors connected over KNX. They usually send payload:true when motion is detected and payload:false when no more motion is detected. But once a day I see in the protocol two times payload:true or payload:false.

### So that's the normal protocol (recorded with flogger)
`{"time":"2021/09/23 08:56:08","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"c57b1f6d7f5de06d"}}
{"time":"2021/09/23 08:56:10","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"057fbddb35bc4168"}}
{"time":"2021/09/23 08:56:17","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"c35fbde2affe74c2"}}
{"time":"2021/09/23 08:56:22","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"7c6ee433379b00d7"}}
{"time":"2021/09/23 08:56:37","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"5ebb45ddae24b841"}}
{"time":"2021/09/23 08:56:39","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"577cd21d38b133e7"}}`

### And here's what happens at some undefined point
`{"time":"2021/09/23 08:56:17","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"c35fbde2affe74c2"}}
{"time":"2021/09/23 08:56:22","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"7c6ee433379b00d7"}}
{"time":"2021/09/23 08:56:37","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"5ebb45ddae24b841"}}
{"time":"2021/09/23 08:56:39","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"577cd21d38b133e7"}}
{"time":"2021/09/23 08:57:47","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"d9421faa4479717b"}}
{"time":"2021/09/23 08:57:47","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":true,"_msgid":"34ab84a5a3a90755"}}
{"time":"2021/09/23 08:57:50","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"ef98af5722305110"}}
{"time":"2021/09/23 08:57:58","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"942e5d73a0f1b34c"}}
{"time":"2021/09/23 08:58:00","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"680ddbcd1b54fad3"}}`

### Conclusion
So usually, a message contains payload:true together with previouspayload:false or vice versa. But as you might see in the second snippet, two payload:true messages follow each other, where the first message contains previouspayload:false and the second previouspayload:true.

## Now one of these assumtions (hopefully) is true
1. The motion detector never sends a false telegram.
2. The KNX interface (details below) drops the telegram.
3. The knxUltimate node drops the telegram.

## Here's my setup
* Node-Red 2.0.5 runs directly on a Raspberry Pi 4. No Docker. Some other services are installed.
* knxUltimate 1.2.19 is installed.
* To connect to KNX, I use the IP interface from MDT, SCN-IP000.03, with firmware 3.03. v3.04 is available and I've opened a ticket asking for a changelog before I update.

## Bottomline
This is not a massive big thing, I simply connect a filter node after the in node. But it might be something woth to look at as at some point one telegram seems to be dropped. Hopefully you can help determining that point.

**Comment by Supergiovane** [comment]
Hi Danube
It should be a telegram retransmission from the MDT Interface.
Please enable the option **Suppress repeated (R-Flag) telegrams fom BUS** as stated here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/1.-Gateway-configuration
LEt me know if it fixed the issue.

**Comment by danube** [comment]
I needed to update knxUltimate first, as this flag came in a later version than I was running. It's now on latest 1.2.46. I'll not set that option but first monitor my environment if everything is just fine after the update. The described event happened before only once or twice a day. If it occurs again, I will then set the mentioned option to see if it resolves my issue. Let me report back to you.

**Comment by danube** [comment]
After updating and setting the option to suppress repeated telegrams, I still see the same behavior on three of three motion detectors I'm monitoring. One re-sends the telegram within the same second...
`{"time":"2021/09/25 07:36:15","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang EG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.9","destination":"1/2/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"ab543e15f9b6d54a"}}
{"time":"2021/09/25 07:36:15","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang EG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.9","destination":"1/2/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":true,"_msgid":"18e7fa6ca8ca4ee6"}}
`

... where the two others have some significant time between the telegrams:
`{"time":"2021/09/25 06:43:00","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Eingang Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.28","destination":"2/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"fd730329bab60cfd"}}
{"time":"2021/09/25 06:43:47","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Eingang Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.28","destination":"2/1/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":true,"_msgid":"114da9103f4beb22"}}
`
...
`{"time":"2021/09/25 06:42:29","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":true,"_msgid":"8160afd7d7c0079f"}}
{"time":"2021/09/25 06:43:22","level":"INFO","var":"msg","message":{"topic":"motion","payload":false,"devicename":"BM Gang OG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"Off","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.18","destination":"10/1/0","rawValue":{"type":"Buffer","data":[0]}},"previouspayload":false,"_msgid":"53e31c72ccb09740"}}
`

Need to say we have some pets triggering the detectors frequently... 😉

Again, need to say, the RBE filter on input is disabled, so there are ways of options to get rid of what I see. Just curious...

**Comment by Supergiovane** [comment]
This thing normally happens with resent telegrams. Very strange. You should put ETS in monitor mode, to get all telegrams and then analyse the matter

**Comment by danube** [comment]
Sorry for my delay, that was kinda tricky to catch. ETS seems to record all telegrams in a logic order. Every true is followed by a false and so on...

Here's the ETS recording:

`6979,"29.09.2021 21:30:57,657",vom Bus,,Niedrig,1.1.9,Bewegungsmelder,1/2/0,BM Gang EG Bewegung,6,GroupValueWrite,1.001 Schalten,$01 | Ein`

`6990,"29.09.2021 21:31:02,515",vom Bus,,Niedrig,1.1.9,Bewegungsmelder,1/2/0,BM Gang EG Bewegung,6,GroupValueWrite,1.001 Schalten,$00 | Aus`

`7016,"29.09.2021 21:31:35,519",vom Bus,,Niedrig,1.1.9,Bewegungsmelder,1/2/0,BM Gang EG Bewegung,6,GroupValueWrite,1.001 Schalten,$01 | Ein`

And here is the logged equivalent in Node-RED:

`{"time":"2021/09/29 21:30:56","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang EG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.9","destination":"1/2/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":false,"_msgid":"1418b5addbd2c68d"}}`

`{"time":"2021/09/29 21:31:34","level":"INFO","var":"msg","message":{"topic":"motion","payload":true,"devicename":"BM Gang EG Bewegung","payloadmeasureunit":"unknown","payloadsubtypevalue":"On","knx":{"event":"GroupValue_Write","dpt":"1.001","dptdesc":"Switch","source":"1.1.9","destination":"1/2/0","rawValue":{"type":"Buffer","data":[1]}},"previouspayload":true,"_msgid":"4059593e3becea18"}}`

Seems the false telegram has been recorded by ETS but somehow got lost on it's way into Node-RED... 🤔🤔🤔

**Comment by Supergiovane** [comment]
Hi
That's very strange bahaviour. Never had a single telegram lost in 3 years.
The loss of the "Off" telegram can be related to the "**Suppress repeated (R-Flag) telegrams fom BUS**". Maybe the MDT is resending a lost telegram and knx-ultimate avoid outputting such as message. Please re-enable it and enable "Suppress ACK requests" in the knx ultimate gateway configuration as well, then restart node-red.
Then i also recommend you to update your MDT firmware.

**Comment by Supergiovane** [comment]
PS: please also disable the WIFI in the rPI or manually select the ethernet interface on the KNX configuration node.

**Comment by danube** [comment]
MDT changelog seems minor, that is why I haven't updated yet. But yeah, to be sure, that might be worth a try. Regarding suppress options, those are enabled already. You meant me to disable one of them?

**Comment by Supergiovane** [comment]
No, sorry, i made a syntax error. I mean **DISABLE** the  "**Suppress repeated (R-Flag) telegrams fom BUS**"

**Comment by Supergiovane** [comment]
Also, you can try to direclty connect the MDT and Node-Red toghether to a dumb switch.
Sometime some UDP storm filtering protection kicks-in in some managed switches.

**Comment by danube** [comment]
Steps performed: R-flag disabled, MDT interface updated, knxUltimate Interface setting changed from auto to eth0. Now monitoring again.

**Comment by danube** [comment]
No luck, had that again this morning. Previously, ETS was running on a computer connected via Wi-Fi and recorded the missing telegram, so it was definitely out there.

Rpi and MDT are connected via a Netgear hub, there should not be any kind of protection mechanism. Pulling a cable between Rpi and MDT would result in not being able to connect to either of them anymore, as both have only one Ethernet port.

To do something, I'll set up an Ethernet sniffer in front of my Rpi. Guess Wireshark should be able to log that traffic, in my understanding it should not be encrypted. Maybe I find something on that layer. Getting back. Any suggestions from your side?

**Comment by Supergiovane** [comment]
Hi Danube
i had many users in the past, using MDT (or Zennio, that is visually identical to the MDT) interfaces, having issues. I don't really know if it's related to this particular interface, but i'm starting to think about that.
KNX-Ultimate has thousand of installations around the world and the only issues i'm still hearing (not related to wrong configurations by the users), are from these devices.
I'm running out of ideas. If you have connected node-red and the MDT to a dumb switch, you have disabled Wifi (or manually set the eth interface on the config gateway) and you still have telegrams dropped, i'm a bit confused.

Please check this:

- Do you have unused configuration gateway nodes lying arund? If yes, delete it and restart.
- Do you have KNX Nodes from other developers installed?  If yes, delete it and restart.

If none of the above: please try to install a KNX node from another developer (there are many, you can try knx-easy, knxjs, knx, and so on) and check if the issue appears.
Thanks

**Comment by danube** [comment]
There's no other KNX node installed, nor an unused configuration. I'll install the sniffer tonight and record TCP traffic over the weekend, we will see if something stinks there.

**Comment by danube** [comment]
I recorded two events that weekend, where at the same time "Destination unreachable" messages appear in the capture. 
![](https://i.imgur.com/PJ3N3BY.png)

These messages do not appear on any other positions in the recording. I'm no network crack, but there must be some correlation. Are you one, or do you have one at hand to introduce? Happy to exchange captures privately.

**Comment by danube** [comment]
Looks like some kind of reconnect starting with a disconnect telegram triggered by MDT on telegram 85645, together with some error code E_CONNECTION_ID. Let me get in touch with MDT, maybe they can help.

**Comment by Supergiovane** [comment]
Hi Danube
No, sorry, i haven't any wireshark capture avaiable.
Why would the MDT send a disconnect request?
In the meantime, can you please unzip this file into your **.node-red/node_modules/node-red-contrib-knx-ultimate/knxultimate-api2/src** and restart node-red?
[FSM.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7276005/FSM.js.zip)
Please keep the wireshark recording, i wanna try what happens with this file.

Thank you for keeping me informed.

**Comment by danube** [comment]
Done and recording. Meanwhile, I sent a request to MDT wth is going on.

**Comment by danube** [comment]
Depending on your expectation, it's good or bad for you to hear that after uploading modified FSM.js and restarting my rpi it happened again that morning.

In the meantime, MDT replied (and I have to say again, that I'm far away from being a KNX telegram crack). According to MDT, every tunneling telegram must be acknowledged within exactly one second by a tunneling-ACK. If this time exceeds, the interface re-sends the telegram, waiting another second for the tunneling-ACK. If this time exceeds again, the interface disconnects, as it happened here:
![](https://i.imgur.com/GVkoMfd.png)

Three seconds later, the rpi checks the connection and reconnects:
![](https://i.imgur.com/MbIyGJ9.png)

MDT raised the assumption, that my rpi is busy at that time and cannot process telegrams within the specified time. So shame on me, if that is true. Still, that has to be proven. So I'm going to check my CPU load now. Somehow.

**Comment by Supergiovane** [comment]
Hi
I'll inspect again the ACK, but as soon as the tunneling telegram arrives, i don't wait even a millisecond, i just reply immediately with the ACK.
If you wish to avoid further headache, i suggest you to buy a KNX Router. Eibmarkt has one that is not expensive.
To be honest, my main Node-Red installation has more than 300 knx-ultimate nodes and works rock solid in conjunction with my Enertex IP **Interface**. The second installation is running on an Eibmarkt router, rock solid as well.
I'm running all on a QNAP VM, that has two eth interfaces: 1 is directly connected to the Enertex Interface, the other one, is connected to my LAN. Even with this particular setup, never had any issue.

Rpi4 is powerful. I doubt that it's running out of resources.
The only thing that can cause problems, is if you have both WIFI and Ethernet enabled and active on your PI. In this case, the UDP routing can be difficult.

To make things ever worst, is the fact that the issue is non replicable in a simple way. You must wait until this happens.
As i already told you, i had other issues with users using MDT 003 interface.

**Comment by Supergiovane** [comment]
Hi again.
I've introduced a delay of 400ms from the arrive of a tunnel request, until i send the Acknowledge telegram.
I want to try this. Maybe i was responding too fast.

Please try this file and let me know (restart node-red after pasting the file).
[FSM.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7286818/FSM.js.zip)

**Comment by danube** [comment]
Occasionally my wife busts buttons as lights won't go on or off. My trigger only monitors three motion detectors, but a reestablishment of connection may explain her anger... 🥰

For now, I'm logging CPU load into a file. Maybe there's a peak hit. I also found an abandoned but still running docker container of homeassistant, which I wiped. Actually, no docker stuff is running at all anymore. This to make sure there's no CPU overload.

If this doesn't solve things, I'll upload your file and check the results.

Getting back to you. And, oh, I'm some kinda addicted in such headache deals... 🤫

**Comment by Supergiovane** [comment]
Hmmm... are you running Docker on rpi4? You said the node-red was running without docker.
Homeassistant does have a native implementation of KNX, so if the docker image was in NAT mode, there should be conflicts with the KNX port, used both from node-red and home assistant.
Dockerizing things on rPI gives only problems.

**Comment by danube** [comment]
Well, the CPU load is now somewhere around 0,4%, never thought that would be so super low. And I still am having those issues. So I guess the idea of MDT support having an overloaded board may be false. Now I'll load your latest FSM.js.

**Comment by Supergiovane** [comment]
Hi
Yes, i never had any issue even with the very first raspberry pi. 
Do you have other knx interfaces other than the mdt to test with?

**Comment by danube** [comment]
What you prefer to be tested first? The timeout delay fix above our your recent MDT subdue?

**Comment by danube** [comment]
Just loaded and started the recorder. It always takes about a day to see two or three events, so if we wait until Monday we should have speaking results.

**Comment by Supergiovane** [comment]
Hi
thank you for the update.
As told you before, an user with a Zennio have had a similar issue even with the interface connected to a Control4 gateway.
Anyway, i've spent some $$$ and bought an MDT for testing purposes. I hope this is the same model  as yours.

![IMG_5676](https://user-images.githubusercontent.com/37666636/136766699-2b923337-d27c-4f39-bfaf-040e9357212f.jpeg)

**Comment by danube** [comment]
You bought the IP Router where I have the IP Gateway, which was a bit cheaper. Dunno if there are major differences in telegram handling. Meanwhile, I found my old Loxone controller, which can also act as a KNX IP interface. So if you like, I can lend you the MDT IP interface for some testing and use the Loxone for that time. Let me know. I keep you posted regarding my questions to MDT. Or do you want to be CC'd?

**Comment by Supergiovane** [comment]
Thanks, this is helpful
I'll take a look

**Comment by danube** [comment]
Okay, gimme a bit. These are kind of modifications where I like to create a full backup first.

**Comment by danube** [comment]
I updated Node-RED vom 2.0.5 to 2.0.6, nodejs from 12.21.0 to 14.18.0, knxUltimate from 1.2.46 to 1.2.49 and tons of other stuff coming with the apt full-upgrade. Recording.

**Comment by danube** [comment]
The recent recording ran app. 48 hrs. Things seem more stable now, still I see two significant reconnects in that period:

## One
![grafik](https://user-images.githubusercontent.com/1183829/137207311-afb0e088-c836-4df1-833c-e148c4513070.png)

| Telegram no. | Timestamp (s) | Description |
|-|-|-|
| 2625508 | 0 | MDT sends request 10:186 |
| 2625510 | 0.933313530 | No Ack, MDT re-sends request 10:186 |
| 2625519 | 1.933134470 | No Ack, MDT disconnects |
| ... | ... | ... |
| 2625564 | 2.373812492 | Rpi ack's request 10:186 (probably req from 2625508) |
| 2625565 | 2.373876572 | Rpi ack's request 10:186 again (probably req from 2625510) |

## Two
![grafik](https://user-images.githubusercontent.com/1183829/137207822-b1b5df33-59f6-468d-8a9b-27d0b2d4d4e3.png)

| Telegram no. | Timestamp (s) | Description |
|-|-|-|
| 6118686 | 0 | MDT sends request 10:74 |
| 6118696 | 0.991119970 | No Ack, MDT re-sends request 10:74 |
| 6118700 | 1.991153450 | No Ack, MDT disconnects |
| ... | ... | ... |
| 6118725 | 2.251128022 | Rpi ack's request 10:74 (probably req from 6118686) |
| 6118726 | 2.251197942 | Rpi ack's request 10:74 again (probably req from 6118696) |

## Conclusion
I didn't look that close to the telegrams before, but with the time I get more familiar with the protocol, and we probably would have seen something similar: Ack's from Raspberry do not get lost, as it was assumed at the beginning. They are being sent back to the interface. Not in time, but more than two seconds after the first request from the interface.

So, what you suggest?

**Comment by danube** [comment]
Hi! I try to describe, what I see since I switched from MDT to Loxone interface.

First, I receive tons more telegrams (compared to using MDT) holding the same payload as a recent telegram from the same address. Here is one example:
![image](https://user-images.githubusercontent.com/1183829/137680242-0f62aa2a-5e19-4750-8203-0b5574b5f6eb.png)

The Loxone interface does no re-requesting, if a telegram is not received within one second. Hence, it does no disconnect, if a re-requested telegram is not acknowledged within another second. Not sure, if this behavior is reliable, and I doubt it acts as specified. For sure, it at least seem to work more stable, but as a fact it masks problems.

Still, there are telegrams not being acknowledged within one second, as shown below (where the ack time is 1.38 secs):
![image](https://user-images.githubusercontent.com/1183829/137682152-384f287b-d09c-4ff0-ba04-e842ff4fd3e1.png)

### Conclusion
The main problem reported at the very beginning still persists and even seem to be more present when using Loxone as interface than MDT. It so seems not to be related to the interface (if we call it representative testing with two interfaces). Reconnects haven't been an issue and even seem to be a specified behavior. It may make sense to add some log events in the ack part of your node (FSM?) to be able to compare this with the recordings.
