### ISSUE TITLE
how to add DPT 14.057 support?

### ISSUE THREAD

**Issue by MGKQB** [Supergiovane/node-red-contrib-knx-ultimate#146]
Hey! 

first i'd like to THANK you so much for your node!!! It is really awesome.

**Is your feature request related to a problem? Please describe.**
no problems here :)

**Describe the solution you'd like**
my new smart meter supports DPT 14.057 (power factor) but your node does not seem to support it. I tried to find the DPTs list in your code (i would have added it myself and created a pull request) but was unable to do so (e.G. the node does support 14.027 but i was unable to locate this anywhere in your code?)
Can you add it or point me to where in your code i can add it?

Thanks again and best regards,
Michael

**Comment by Supergiovane** [comment]
Hi
Thank you to you for using my node.
Where is the problem?
The new version with 14.057 will be out in about 1 hour.

**Comment by Supergiovane** [comment]
1.2.47 is out. Please let me know if it's working.
Thanks

**Comment by MGKQB** [comment]
it works fine. Thank you so much.
