### ISSUE TITLE
knx-node stuck in writing

### ISSUE THREAD

**Issue by stefan90403** [Supergiovane/node-red-contrib-knx-ultimate#147]
Hello!

first thanks, for this great node!!

i'm using the node with knxd on a raspberry pi.
Nodered is installed as module behind iobroker.

After some time I have the problem, that nodes are stuck writing to knx. 

<img width="260" alt="Bildschirmfoto 2021-09-30 um 08 28 39" src="https://user-images.githubusercontent.com/64328561/135404278-995f0f6a-506e-404d-81ae-38eeca6c7425.png">

I have read some other issues, where the problem was the connection to knxd. 
In my case I can still read from the bus. 

in the log file I found some, (in my opinion) successful writing of temperature to knxd:

2021-09-30 00:12:20.653  - debug: node-red.0 (6291) [trace] 9/30/2021, 00:12:20 KnxUltimate-API2: (sendDatagram): Sending TUNNELING_REQUEST_L_Data.req ==> {"header_length":6
,"protocol_version":16,"service_type":1056,"total_length":23,"hpai":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunn":{"protocol_type":1,"tunnel_endpoint":"0.0.0.0:0"},"tunnstate":
{"channel_id":2,"tunnel_endpoint":"127.0.0.1:3671","seqnum":180},"cemi":{"msgcode":17,"ctrl":{"frameType":1,"reserved":0,"repeat":1,"broadcast":1,"priority":3,"acknowledge":1,"confirm":0,
"destAddrType":1,"hopCount":6,"extendedFrame":0},"src_addr":"1.1.216","dest_addr":"2/0/0","apdu":{"apci":"GroupValue_Write","tpci":0,"data":{"type":"Buffer","data":[4,196]},"bitlength":16
}}}

2021-09-30 00:12:20.655  - debug: node-red.0 (6291) [debug] 9/30/2021, 00:12:20 KnxUltimate-API2: (sendDatagram): >>>>>>> localEchoInTunneling: echoing by emitting 180

2021-09-30 00:12:20.657  - debug: node-red.0 (6291) [trace] 9/30/2021, 00:12:20 KnxUltimate-API2: (sendDatagram): UDP sent OK: TUNNELING_REQUEST_L_Data.req

2021-09-30 00:12:20.660  - debug: node-red.0 (6291) [debug] 9/30/2021, 00:12:20 KnxUltimate-API2: >>>>>>> seqnum: 180

2021-09-30 00:12:20.662  - debug: node-red.0 (6291) [trace] 9/30/2021, 00:12:20 KnxUltimate-API2: (sendTunnReq_waitACK): Received TUNNELING_ACK message: {"header_length":6,"
protocol_version":16,"service_type":1057,"total_length":10,"tunnstate":{"header_length":4,"channel_id":2,"seqnum":180,"rsvd":0}}
[debug] 9/30/2021, 00:12:20 KnxUltimate-API2: ===== datagram 180 acknowledged by IP router
[debug] 9/30/2021, 00:12:20 KnxUltimate-API2: (idle):    zzzz...

After some time I can only see these entries:

2021-09-30 00:23:13.331  - debug: node-red.0 (6291) [debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle

2021-09-30 00:23:13.331  - debug: node-red.0 (6291) [debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle

2021-09-30 00:23:13.333  - debug: node-red.0 (6291) [debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle
[debug] 9/30/2021, 00:23:13 KnxUltimate-API2: *** deferring outbound_TUNNELING_REQUEST until transition to idle

Can you give me some hint how to debug this problem?

Regards,
Stefan

**Comment by Supergiovane** [comment]
Hi
have you folloqed the troubleshoots here? https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/5.-FAQ-Troubleshoot
There is a "KNXD CONFIGURATION" troubleshoot.
Unfortunately, you're running node-red behind 2 layers: knxd and iobroker. 
With konnex, you should stay as cleaner as possible.

**Comment by stefan90403** [comment]
Hi, 
yes I have tried that. Sorry for not writing this. 

knxd is on tunnel_endpoint":"127.0.0.1:3671",
Echo sent message to all node with same Group Address is activated 
and there are no filters configured.

**Comment by Supergiovane** [comment]
HI
why are you unsing knxd? Do you have an RPI KNX hat?
Does knxd still communicate to the knx bus?
Can you tell me node-red, knx-ultimate and node version? For node version, just type "node -v" in a prompt command.
Thanks.

**Comment by stefan90403** [comment]
yes I can still write to knxd with knxtool groupwrite

Versions i use:
node-red-contrib-knx-ultimate: 1.2.47
node-red 1.3.6
node: v12.22.6

**Comment by Supergiovane** [comment]
Hi
can you please enable the "Suppress ACK request" in the config window and restart node-red?
Does the issue only occurs on temperature datapoint?

**Comment by stefan90403** [comment]
Hi, 
ok i configured "Suppress ACK request". 
It will need some time to test, because the Problem starts after some hours. 
The issue occurs regardless of the datapoint. 

Regards, Stefan

**Comment by Supergiovane** [comment]
PS: please also disable the WIFI in the rPI or manually select the ethernet interface on the KNX configuration node.

**Comment by stefan90403** [comment]
ok, i will try that.

**Comment by stefan90403** [comment]
hi, i have still this problem. I use knxd, because of the usb-knx stick. Will no try to install node-red stand alone and maybe buy a knx-ip interface.

**Comment by Supergiovane** [comment]
Hi
thanks for the feedback. I know that knxd does work, but it's a bit tricky to set it up correctly.
If you can spend a little more money, buy a KNX Router instead of an interface. It's more robust and accepts infinite connections (The KNX IP Interface has a limited amount of avaiable connections, normally 3 or 4).

But prior of buying anything, try with a KNX node from other developers, maybe these works better with knxd. (Remember to delete knx-ultimate before that, because you cannot install more than one KNX node at the same time).

**Comment by Supergiovane** [comment]
Hi Stefan,
any news about that?

**Comment by stefan90403** [comment]
Hi! no unfortunately not. I use the knx adapter in iobroker now, which is working for me. 
But I have still some nodes in node red were I would love to use your node. 
Next step is to install a new node-red standalone installation and test with that. 
Just need some time for that.

**Comment by Supergiovane** [comment]
Ok, i'll close this issue. Very sad you had so many problems with knx-ultimate :-(
