### ISSUE TITLE
dpt: "10.001" decoding issue (sunday +7)

### ISSUE THREAD

**Issue by tx73github** [Supergiovane/node-red-contrib-knx-ultimate#148]
Dear Max,
Congrats to your great job, and effort you put into this node.

I do get wrong time/date on a SUNDAY from my Jung 2225 WS U GPS time (weatherstation).
The station is coding the (optional) day of week as per spec 3 octets: N3U5r2U6r2U6
It seems to only hit on sundays and adds 7 days to the date. (DPT 10.001 code for sunday is DEC "7")
So it looks like the first 3 bits aren't completely nulled when converting, and the "7" slips through to date conversion.

Here is the decode including the RAW bytes from the station (1.3.31):
17.10.2021, 22:47:59node: 40a1a3ec3543de4a
5/0/0 : msg : Object
object
topic: "5/0/0"
payload: "2021-10-24T20:48:03.567Z"
devicename: "(System->Zeit) Uhrzeit"
payloadmeasureunit: "unknown"
payloadsubtypevalue: "unknown"
knx: object
event: "GroupValue_Write"
dpt: "10.001"
dptdesc: "Time of day"
source: "1.3.31"
destination: "5/0/0"
rawValue: buffer[3]
0: 0xf6
1: 0x30
2: 0x3

Monday looks fine:
18.10.2021, 00:48:59node: 40a1a3ec3543de4a
5/0/0 : msg : Object
object
topic: "5/0/0"
payload: "2021-10-17T22:49:02.987Z"
devicename: "(System->Zeit) Uhrzeit"
payloadmeasureunit: "unknown"
payloadsubtypevalue: "unknown"
knx: object
event: "GroupValue_Write"
dpt: "10.001"
dptdesc: "Time of day"
source: "1.3.31"
destination: "5/0/0"
rawValue: buffer[3]
0: 0x20
1: 0x31
2: 0x2

Knx-Ultimate Version 1.2.49
node-red 2.0.6
rapi 3b standalone

Many thanks
//t

**Comment by Supergiovane** [comment]
Hi
I’ll look at it…

**Comment by tx73github** [comment]
Hi Max,
I use the GPS to set the time to the BUS, node-red for now is passiv in my installation.
I think you did exactly the right thing to convert the 10.001 into the JS datestring.

The "missing" information are coming from the node-red's host time which most probably will be in sync anyway. 
To change the interpretation would probably break stuff that others have build on the data. 

So if you ask for my opinion, leave the conversion of the 10.001 as it is, because it provides the correct data 6 of 7 days of the week, just use the right date for the sunday (as its currently simply using nexts weeks sunday) and if DPT and JS value are conflicting, just override the KNX dow since its optional anyway. (and since you transport the raw bytes one could look into that if really needed).

Again, many thanks for the work and effort.
Regards,
//t

**Comment by tx73github** [comment]
I'm travelling 'til saturday, lets see what sunday brings, are you checking the patch on your system or should I apply anyway ?
as always, many thanks to put so much effort into this node
