### ISSUE TITLE
Import ETS file

### ISSUE THREAD

**Issue by VivereSmart** [Supergiovane/node-red-contrib-knx-ultimate#15]
Hi,
i can't import the ets database. In the debug window, i've no items but under the node there is the red square with this (3,current hour) wrong group address format.
If you want i give you the csv file.
Best regards

![knxnodered](https://user-images.githubusercontent.com/51285577/68083608-f12f4800-fe2a-11e9-809f-108e026b1006.PNG)
[Prova.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/3801431/Prova.zip)

**Comment by Supergiovane** [comment]
Grazie
Lunedì ci do un’occhiata. Hai seguito le istruzioni nelle wiki ?

**Comment by VivereSmart** [comment]
Si, ho allegato tutto, l'errore che vedi è quello di connessione al server di Alexa e non c'entra nulla. Grazie per la risposta e buona domenica. Saluti
Ottieni Outlook per Android



On Sun, Nov 3, 2019 at 1:12 PM +0100, "Supergiovane" <notifications@github.com> wrote:












Grazie


Lunedì ci do un’occhiata. Hai seguito le istruzioni nelle wiki ?

**Comment by Supergiovane** [comment]
Ciao
ho provato ora il tuo file csv e non ho alcun errore.
Sei sicuro di aver impostato il group address del nodo o di aver selezionato " Universal mode (listen to all Group Addresses)"?

**Comment by VivereSmart** [comment]
Grazie, Provo il prima possibile. Molto gentile. Saluti
Ottieni Outlook per Android



On Sun, Nov 3, 2019 at 1:46 PM +0100, "Supergiovane" <notifications@github.com> wrote:












Ciao

ho provato ora il tuo file csv e non ho alcun errore.

Sei sicuro di aver impostato il group address del nodo o di aver selezionato " Universal mode (listen to all Group Addresses)"?

**Comment by VivereSmart** [comment]
Buona serata Supergiovane, Effettivamente funziona, ho inserito manualmente l'oggetto di gruppo 3/0/0 e diventa verde. Unica cosa che mi ha tratto in inganno che su una versione più datata, una volta inserito il csv in topic, suggeriva gli indirizzi di gruppo. Questo sinceramente mi ha bloccato. Grazie ancora per l'aiuto e scusa il disturbo..... Saluti
Ottieni Outlook per Android



On Sun, Nov 3, 2019 at 1:46 PM +0100, "Supergiovane" <notifications@github.com> wrote:












Ciao

ho provato ora il tuo file csv e non ho alcun errore.

Sei sicuro di aver impostato il group address del nodo o di aver selezionato " Universal mode (listen to all Group Addresses)"?
