### ISSUE TITLE
receive raw data from bus

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-knx-ultimate#151]
Hi,

i'm using this node to implement my home knx system, from more than one year and is very stable.

Now i like to read from my energy meter some measure like voltage.

If i read the group 1/4/21 from ETS it give me a response like that :

# | Ora | Servizio | Flag | Prio | Indirizzo fonte | Nome fonte | Indirizzo   destinazione | Nome destinazione | Indirizzo | Tipo | DPT | Info
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
776 | 26/10/2021 17:41:55,026 | da bus |   | Alto | 1.0.14 |   | 1/4/21 |   | 6 | GroupValueResponse |   | 09 0D 00 23 00 39 C5 1E 01 0E AC 6B

Yes, i know, i need to decode the response 09 0D 00 23 00 39 C5 1E 01 0E AC 6B, it is an aggregate from voltage, current, frequencie, cosfi, but later... :-)

The problem is that i can't receive this group on nodered, it doesn't appear on debug window.

How can i do?

Tnx

**Comment by Supergiovane** [comment]
Ciao
Di che datapoint si tratta?

**Comment by bolfox** [comment]
Ciao,

non è un datapoint standard, mi dicono sia un concatenato di voltaggio corrente frequenza e cosfi

Hi

is not a standard datapoint, it is an aggregate from voltage, current, frequencie, cosfi

**Comment by Supergiovane** [comment]
Sul nodo di debug, hai impostato la visualizzazione del messaggio completo (quindi non solo il payload)? In ogni caso un messaggio deve emetterlo.

**Comment by bolfox** [comment]
![image](https://user-images.githubusercontent.com/35669017/139531205-8a5371c7-46a7-4341-a59d-4071a002497a.png)

**Comment by bolfox** [comment]
![image](https://user-images.githubusercontent.com/35669017/139531223-3b4bc0e0-6471-442f-a613-827e48ee7b90.png)

**Comment by Supergiovane** [comment]
Ciao
Ti consiglio di dare un’occhiata alla Wiki e magari di fare un salto qui https://www.facebook.com/groups/viveresmart/?ref=share

Esporra il json dei noi ed incollalo qui. Te oo sistemo io.

**Comment by bolfox** [comment]
Ok, forget to enable "react to read"

![image](https://user-images.githubusercontent.com/35669017/139531743-3b87b5b0-fe98-4b5b-87bc-0b2bbffec83b.png)

**Comment by bolfox** [comment]
`[{"id":"878a3bdc.b6d918","type":"knxUltimate","z":"feb91cdd.8f0b8","server":"129d7115.337b3f","topic":"1/4/21","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":true,"notifyresponse":false,"notifywrite":false,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"","listenallga":false,"name":"Volt","outputtype":"write","outputRBE":false,"inputRBE":false,"x":430,"y":260,"wires":[["e75b5e58.93b6b"]]},{"id":"4dccb2dc.680e1c","type":"function","z":"feb91cdd.8f0b8","name":"Read","func":"return {readstatus:true};","outputs":1,"noerr":0,"x":310,"y":260,"wires":[["878a3bdc.b6d918"]]},{"id":"6cc32b4d.9ecbc4","type":"inject","z":"feb91cdd.8f0b8","name":"Read","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":260,"wires":[["4dccb2dc.680e1c"]]},{"id":"e75b5e58.93b6b","type":"debug","z":"feb91cdd.8f0b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":720,"y":260,"wires":[]},{"id":"8aa0e862.a17408","type":"knxUltimate","z":"feb91cdd.8f0b8","server":"129d7115.337b3f","topic":"1/4/21","outputtopic":"","dpt":"","initialread":0,"notifyreadrequest":true,"notifyresponse":true,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"V","outputtype":"response","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":400,"y":440,"wires":[["e75b5e58.93b6b"]]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"14.14.200","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"838","localEchoInTunneling":true}]`

**Comment by Supergiovane** [comment]
E voilà.
Are you sure that your KNX gateways does work? They points to 127.0.0.1. Are you using knxd?
Other than that, you're passing using a datapoint 1.001. That will never works! You need to know the datapoint type. If the device doesn't use a standard datapoint, i suggest you to find another way to do that.

Here the updated flow.
Please READ the WIKI carefully, because KNX-Ultimate is powerful and complex.

`[
    {
        "id": "878a3bdc.b6d918",
        "type": "knxUltimate",
        "z": "7395b5c7aa32af34",
        "server": "129d7115.337b3f",
        "topic": "1/4/21",
        "outputtopic": "",
        "dpt": "6.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "",
        "listenallga": false,
        "name": "Volt",
        "outputtype": "read",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": "1",
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": "999",
        "passthrough": "no",
        "x": 290,
        "y": 120,
        "wires": [
            []
        ]
    },
    {
        "id": "6cc32b4d.9ecbc4",
        "type": "inject",
        "z": "7395b5c7aa32af34",
        "name": "Read",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 150,
        "y": 120,
        "wires": [
            [
                "878a3bdc.b6d918"
            ]
        ]
    },
    {
        "id": "e75b5e58.93b6b",
        "type": "debug",
        "z": "7395b5c7aa32af34",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 450,
        "y": 160,
        "wires": []
    },
    {
        "id": "8aa0e862.a17408",
        "type": "knxUltimate",
        "z": "7395b5c7aa32af34",
        "server": "129d7115.337b3f",
        "topic": "1/4/21",
        "outputtopic": "",
        "dpt": "6.001",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Volt",
        "outputtype": "response",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 290,
        "y": 160,
        "wires": [
            [
                "e75b5e58.93b6b"
            ]
        ]
    },
    {
        "id": "129d7115.337b3f",
        "type": "knxUltimate-config",
        "host": "127.0.0.1",
        "port": "3671",
        "physAddr": "14.14.200",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error",
        "name": "838",
        "localEchoInTunneling": true
    }
]`

**Comment by bolfox** [comment]
Tnx, it works setting the DPT 6.001, i'have triend other without success...

Yes is correct 127.0.0.1, it is a kberry 838 directly on rpi
