### ISSUE TITLE
DPT12 subtypes

### ISSUE THREAD

**Issue by OSwimmer** [Supergiovane/node-red-contrib-knx-ultimate#154]
Hi Supergiovane,

Can you add extra subtypes in the DPT12 (4-byte unsigned value), some are missing:
- 12.001 counter pulses (unsigned)
- 12.100 counter timesec (s)
- 12.101 counter timemin (min)
- 12.102 counter timehrs (h)
- 12.1200 volume liquid (l)
- 12.1201 volume (m³)

Only the pulses and volume (in m³) currently exists.

I'm using knxultimate to send log messages to influxdb2, and use the 'dptdesc' as measurement. Current the volume reported by my water meter gives 'unknown' as dptdesc.

Thanks in advance,
Wim

**Comment by Supergiovane** [comment]
Hi Wim
Tomorrow i’ll take a look.

**Comment by Supergiovane** [comment]
Hi
V.1.2.57 is out.
Please STAR my node ;-)

**Comment by OSwimmer** [comment]
Hi Supergiovane,
That's working great:
<img width="281" alt="Screenshot 2021-11-21 at 19 32 27" src="https://user-images.githubusercontent.com/2663269/142774591-1c61a616-749e-4a10-b856-37b733362188.png">

Thanks for the fast response!
Wim
