### ISSUE TITLE
KNX Virtual does not work with Node-RED

### ISSUE THREAD

**Issue by mleister97** [Supergiovane/node-red-contrib-knx-ultimate#155]
We sucessfully installed and used KNX Virtual with ETS6.

When trying to use KNX Virtual with Node-RED (KNX Device node) we get an inifinite loop saying "Connecting......", even tough everything seems to be configured correctly. 

Any ideas?

**Comment by mleister97** [comment]
Please see KNX virtual here: https://www.knx.org/knx-en/for-professionals/get-started/knx-virtual/index.php

**Comment by Supergiovane** [comment]
Hi
Yes, this is a known issue.
Currently, i'm focused on KNX-Secure and i cannot give it a look, sorry!
The problem arises when the tunnel_endpoint is 0.0.0.0 in the tun section of the datagram; KNXVirtual doesn't like that and either closes itself or refuse the connection.
Currently, changing the tunnel_endpoint with the actual node-red IP causes issues on some KNX/IP interface, so i prefer to leave that as is for now.

**Comment by mleister97** [comment]
Wow, anyways thanks for your fast response!
