### ISSUE TITLE
 Node-red-contrib-sia-ultimate

### ISSUE THREAD

**Issue by EmilionDK** [Supergiovane/node-red-contrib-knx-ultimate#158]
Sorry for opening an issue here! But it is not possible on your other repository. (Node-red-contrib-sia-ultimate)

I need help as something is not working with the Ajax alarm, with "Acknowledge for SIA"
I will not go into detail as it belongs to the other repository.

I hope you will make it possible to open issue's in the other repository.

And thank you for your good work :)

**Comment by Supergiovane** [comment]
Sorry Emilion,
yet you can open an issue on SIA Ultimate.
