### ISSUE TITLE
Group address check

### ISSUE THREAD

**Issue by dartial** [Supergiovane/node-red-contrib-knx-ultimate#159]
Hi Massimo,

thanks to your faboulous KNX connection. It really works great and I use it for longer time.

**Problem**
When I want to set a boolean value to group address 25/0/50, I receive "Send write Error: Invalid digit at pos 0 inside address 25/0/51"

**To Reproduce**
Try to send a boolean value to "25/0/51"

**Expected behavior**
The address validation is not clear to me.

function validateKNXAddress (KNXUtils.js:15)

In KNXUtils.js:25: (count > 1 && digit > 15) is for the given address ''true'' (count = 2; digit = 25 [for address **25**/0/50]) and the exception is thrown.

Range for group addresses: [0..31]/[0..7]/[0..255] (excluding 0/0/0) or [0..31]/[0..2047] (excluding 0/0) (see https://support.knx.org/hc/en-us/articles/115003188109-Group-Addresses)

**Knx-Ultimate Version**
1.3.10 (2021/12/21)

**Are you running node-red behind homematic, docker or anything similar?**
direct connection

Unfortunatly I'm new to GitHub und must get into NodeRed contribution programming, then I would try to fix it directly and push it ;)

**Comment by Supergiovane** [comment]
Hi
node-red-contrib-knx-ultimate@1.3.11 is out with address validation fix.

**Comment by dartial** [comment]
Thank you for the super fast fix!
