### ISSUE TITLE
Problem with KNX-Header since updates

### ISSUE THREAD

**Issue by Maell0** [Supergiovane/node-red-contrib-knx-ultimate#160]
**Good morning Massimo**

**Describe the bug**
yesterday's well-known problem - "sending a malformed KNX Header"

**To Reproduce**
always - "with my hardware"

**Expected behavior**
here the discussed log

[debug] 22.12.2021, 09:39:25.122 KNXUltimate-KNXEngine: Received KNX packet: CONNECTIONSTATE_RESPONSE, ChannelID:30 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:25.936 KNXUltimate-KNXEngine: isSixBits:true Includes (should be = isSixBits):true ADPU BitLenght:1
[debug] 22.12.2021, 09:39:25.937 KNXUltimate-KNXEngine: Sending KNX packet: KNXTunnelingRequest Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 Host:192.168.178.15:3671 channelID:30 seqCounter:204 Dest:11/2/165  Data:01 TPCI:Write
[trace] 22.12.2021, 09:39:25.940 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 06100421000a041ecc00 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":10} ChannelID:30
[debug] 22.12.2021, 09:39:25.940 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: TUNNELING_ACK, ChannelID:30 seqCounter:204 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:25.976 KNXUltimate-KNXEngine: isSixBits:true Includes (should be = isSixBits):true ADPU BitLenght:1
[debug] 22.12.2021, 09:39:25.977 KNXUltimate-KNXEngine: Sending KNX packet: KNXTunnelingRequest Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 0/1/52 Host:192.168.178.15:3671 channelID:30 seqCounter:205 Dest:0/1/52  Data:01 TPCI:Write
[trace] 22.12.2021, 09:39:25.983 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041eb7002900bce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:25.983 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:183 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:26.54 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 06100421000a041ecd00 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":10} ChannelID:30
[debug] 22.12.2021, 09:39:26.54 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: TUNNELING_ACK, ChannelID:30 seqCounter:205 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:26.64 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041eb80029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:26.64 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:184 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:39:26.65 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:39:26.136 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041eb90029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:26.137 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:185 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:39:26.137 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:39:26.230 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041eba0029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:26.230 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:186 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:39:26.231 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:39:26.302 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ebb002900bce011fa0134010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:26.303 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 0/1/52 ChannelID:30 seqCounter:187 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:26.375 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ebc002e00bce011640134010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:26.375 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_CON, ChannelID:30 seqCounter:188 Host:192.168.178.15:3671
[info] 22.12.2021, 09:39:26.693 knxUltimate-config: No nodes linked to this gateway ControlTouch
[info] 22.12.2021, 09:39:36.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[info] 22.12.2021, 09:39:46.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[trace] 22.12.2021, 09:39:55.963 KNXUltimate-KNXEngine: isSixBits:true Includes (should be = isSixBits):true ADPU BitLenght:1
[debug] 22.12.2021, 09:39:55.964 KNXUltimate-KNXEngine: Sending KNX packet: KNXTunnelingRequest Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 Host:192.168.178.15:3671 channelID:30 seqCounter:206 Dest:11/2/165  Data:01 TPCI:Write
[trace] 22.12.2021, 09:39:55.973 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 06100421000a041ece00 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":10} ChannelID:30
[debug] 22.12.2021, 09:39:55.973 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: TUNNELING_ACK, ChannelID:30 seqCounter:206 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:56.4 KNXUltimate-KNXEngine: isSixBits:true Includes (should be = isSixBits):true ADPU BitLenght:1
[debug] 22.12.2021, 09:39:56.4 KNXUltimate-KNXEngine: Sending KNX packet: KNXTunnelingRequest Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 0/1/52 Host:192.168.178.15:3671 channelID:30 seqCounter:207 Dest:0/1/52  Data:01 TPCI:Write
[trace] 22.12.2021, 09:39:56.15 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ebd002900bce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:56.16 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:189 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:56.97 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 06100421000a041ecf00 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":10} ChannelID:30
[debug] 22.12.2021, 09:39:56.97 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: TUNNELING_ACK, ChannelID:30 seqCounter:207 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:56.108 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ebe0029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:56.109 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:190 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:39:56.109 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:39:56.200 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ebf0029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:56.201 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:191 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:39:56.201 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:39:56.273 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ec00029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:56.274 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:192 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:39:56.274 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:39:56.345 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ec1002900bce011fa0134010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:56.346 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 0/1/52 ChannelID:30 seqCounter:193 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:39:56.428 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ec2002e00bce011640134010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:39:56.429 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_CON, ChannelID:30 seqCounter:194 Host:192.168.178.15:3671
[info] 22.12.2021, 09:39:56.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[trace] 22.12.2021, 09:40:01.188 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200017041ec3002900bce01110204003008007a0 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":23} ChannelID:30
[debug] 22.12.2021, 09:40:01.189 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":{"_data":{"type":"Buffer","data":[7,160]}}} srcAddress: 1.1.16 dstAddress: 4/0/64 ChannelID:30 seqCounter:195 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:01.280 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200017041ec4002900bce0111020420300800c1a srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":23} ChannelID:30
[debug] 22.12.2021, 09:40:01.281 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":{"_data":{"type":"Buffer","data":[12,26]}}} srcAddress: 1.1.16 dstAddress: 4/0/66 ChannelID:30 seqCounter:196 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:01.593 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200017041ec5002900bce0111b202203008007fa srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":23} ChannelID:30
[debug] 22.12.2021, 09:40:01.593 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":{"_data":{"type":"Buffer","data":[7,250]}}} srcAddress: 1.1.27 dstAddress: 4/0/34 ChannelID:30 seqCounter:197 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:01.664 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200017041ec6002900bce0111b20240300800c1a srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":23} ChannelID:30
[debug] 22.12.2021, 09:40:01.664 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":{"_data":{"type":"Buffer","data":[12,26]}}} srcAddress: 1.1.27 dstAddress: 4/0/36 ChannelID:30 seqCounter:198 Host:192.168.178.15:3671
[info] 22.12.2021, 09:40:06.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[info] 22.12.2021, 09:40:16.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[trace] 22.12.2021, 09:40:24.805 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200017041ec7002900bce01133204a0300800c38 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":23} ChannelID:30
[debug] 22.12.2021, 09:40:24.805 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":{"_data":{"type":"Buffer","data":[12,56]}}} srcAddress: 1.1.51 dstAddress: 4/0/74 ChannelID:30 seqCounter:199 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:25.114 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 0610020800081e000801000000000000 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":16} ChannelID:30
[error] 22.12.2021, 09:40:25.115 KNXUltimate-KNXEngine: Received KNX packet: KNXHeader: createFromBuffer: Message length mismatch 8/16 Data processed: 0610020800081e000801000000000000
[debug] 22.12.2021, 09:40:25.115 KNXUltimate-KNXEngine: Received KNX packet: CONNECTIONSTATE_RESPONSE, ChannelID:30 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:25.958 KNXUltimate-KNXEngine: isSixBits:true Includes (should be = isSixBits):true ADPU BitLenght:1
[debug] 22.12.2021, 09:40:25.961 KNXUltimate-KNXEngine: Sending KNX packet: KNXTunnelingRequest Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 Host:192.168.178.15:3671 channelID:30 seqCounter:208 Dest:11/2/165  Data:01 TPCI:Write
[trace] 22.12.2021, 09:40:25.965 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 06100421000a041ed000 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":10} ChannelID:30
[debug] 22.12.2021, 09:40:25.965 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: TUNNELING_ACK, ChannelID:30 seqCounter:208 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:25.998 KNXUltimate-KNXEngine: isSixBits:true Includes (should be = isSixBits):true ADPU BitLenght:1
[debug] 22.12.2021, 09:40:25.999 KNXUltimate-KNXEngine: Sending KNX packet: KNXTunnelingRequest Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 0/1/52 Host:192.168.178.15:3671 channelID:30 seqCounter:209 Dest:0/1/52  Data:01 TPCI:Write
[trace] 22.12.2021, 09:40:26.8 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ec8002900bce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:40:26.8 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:200 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:26.110 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 06100421000a041ed100 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":10} ChannelID:30
[debug] 22.12.2021, 09:40:26.110 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: TUNNELING_ACK, ChannelID:30 seqCounter:209 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:26.120 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ec90029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:40:26.120 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:201 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:40:26.121 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:40:26.193 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041eca0029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:40:26.193 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:202 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:40:26.194 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:40:26.265 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ecb0029009ce011fa5aa5010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:40:26.266 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 11/2/165 ChannelID:30 seqCounter:203 Host:192.168.178.15:3671
[warn] 22.12.2021, 09:40:26.267 KNXUltimate-config: Ignored telegram with Repeated Flag GroupValue_Write Src:1.1.250 Dest:11/2/165
[trace] 22.12.2021, 09:40:26.358 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ecc002900bce011fa0134010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:40:26.359 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 1.1.250 dstAddress: 0/1/52 ChannelID:30 seqCounter:204 Host:192.168.178.15:3671
[trace] 22.12.2021, 09:40:26.431 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 061004200015041ecd002e00bce011640134010081 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":21} ChannelID:30
[debug] 22.12.2021, 09:40:26.432 KNXUltimate-KNXEngine: Received KNX packet: TUNNELING: L_DATA_CON, ChannelID:30 seqCounter:205 Host:192.168.178.15:3671
[info] 22.12.2021, 09:40:26.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[info] 22.12.2021, 09:40:36.694 knxUltimate-config: No nodes linked to this gateway ControlTouch
[info] 22.12.2021, 09:40:46.693 knxUltimate-config: No nodes linked to this gateway ControlTouch

**Knx-Ultimate Version**
 - after 1.3.5 - 1.3.10

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red running alone in RaspberryPi

**Additional context**
I use Busch Jaeger Controltouch (6136 / APP) as IP-Gateway. 
Could it be due to the peculiarities of this device?

**Comment by Supergiovane** [comment]
Hi!
Thank you very much for the log and welcome to gitHub!
Generally speaking, these multi purpose devices should be KNX certified but in some cases, they go out of the KNX boundary specs.
In particular, i clearly see this:

```
[trace] 22.12.2021, 09:40:25.114 KNXUltimate-KNXEngine: Received KNX packet: _processInboundMessage, Data received: 0610020800081e000801000000000000 srcAddress: {"address":"192.168.178.15","family":"IPv4","port":3671,"size":16} ChannelID:30
[error] 22.12.2021, 09:40:25.115 KNXUltimate-KNXEngine: Received KNX packet: KNXHeader: createFromBuffer: Message length mismatch 8/16 Data processed: 0610020800081e000801000000000000
[debug] 22.12.2021, 09:40:25.115 KNXUltimate-KNXEngine: Received KNX packet: CONNECTIONSTATE_RESPONSE, ChannelID:30 Host:192.168.178.15:3671 
```

The culprit is the connectionstate response sent by the Busch-Laeger.
Every xx seconds, KNX-Ultimate sends an "heartbeat" packet to the IP Gateway, as per KNX Specs, and the Gateway must respond with that CONNECTIONSTATE_RESPONSE packet.
The Header of that packed seems to be malformed. It's seems to be longer as advertised in the Header itself.
By strictly adhering to the KNX Specs, KNX-Ultimate was initially aborting the communication.
Then, i re-programmed KNX-Ultimate to be more relaxed and to accept such things, but bear in mind, that if you encounter other Devices less "relaxed" as KNX-Ultimate, you may have problem.
For now, you can live with that.
Please also upgrade to v1.3.12. No hurry there, just added some more logs and Group Address validation.
