### ISSUE TITLE
Import of GA list from ETS fails

### ISSUE THREAD

**Issue by peterbuchheim** [Supergiovane/node-red-contrib-knx-ultimate#161]
The list of GAs which were exported from the ETS generates an error "Invalid address format: Only 3 level addresses are allowed".

However, the list contains only 3 level GAs.
[20211229 GA_export.csv](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/7790781/20211229.GA_export.csv)

**Comment by Supergiovane** [comment]
Hi.  Please follow the guideline on how to open a bug issue, as i need more infos. Thanks.

**Comment by peterbuchheim** [comment]
closed

**Comment by peterbuchheim** [comment]
after complete new installation the problem does no longer exist

**Comment by Supergiovane** [comment]
Good to know and please, if you enjoy my node, STAR it! (click the star on the upper right of this page).
Thanks!
