### ISSUE TITLE
Hikvision ISAPI issue doorbell

### ISSUE THREAD

**Issue by pergolafabio** [Supergiovane/node-red-contrib-knx-ultimate#165]
Hey @Supergiovane , i have a question for you, i see you created a nice rep for hikvision ISAPI commands
But creating the issue ticket here, seems its not possible on that repository

I had  a look on the hangup call, i wasnt aware that you first need to send the delete ring command

I have a DS-KD8003, when i send this command first : 

`curl -i --digest -u admin:xxxx -X DELETE http://192.168.0.70/ISAPI/VideoIntercom/ring`
Gives me a 200 response,, so looks good, allthough i still hear the indoor / app device ringing

if i then do : , it always gives me a bad request/invalid operation...

any idea?

`curl -i --digest -u admin:xxx -d "{"CallSignal":{"cmdType":"hangUp"}}" -H "Content-Type: application/json" -X PUT http://192.168.0.70/ISAPI/VideoIntercom/callSignal?format=json`

![image](https://user-images.githubusercontent.com/43251136/150768611-d902a54d-7dfb-467d-bb05-25c04d2404f5.png)

PS: i see you are also using Home Assistant, i created this thread a while ago with some usefull commands:

https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535

Are you also going to add twowayaudio ? thats also possible with ISAPI

**Comment by Supergiovane** [comment]
Ciao Fabio.
Ho disattivato temporaneamente l'assistenza su tutti i miei nodi tranne questo, perchè sono molto impegnato sul nodo KNX (prima spendevo mezza giornata ogni giorno per rispondere alle richieste di aiuto).
Ho integrato i doorbell diverso tempo fa ed ora non mi ricordo, comunque il tuo problema piò dipendere dal firmware. Ci sono 2 versioni delle API: 1.0 e 2.0. Dipende quale delle due il tuo citofono utilizza.
Non ho citofoni hik da provare (mi ero collegato con un citofono di un utente) per cui non posso aiutarti!

**Comment by pergolafabio** [comment]
Hey, sorry, dont speak italian :-)
did a google translate, devices are running latest firmwares
i have tested 2 devices 8113 and 8003 , both give same issues :-(

the 2 commands are actually needed?

**Comment by Supergiovane** [comment]
Hi
sorry, but Pergola Fabio looks as an Italian name!
One command is to stop the app ringing. The other is to hangup. 
If you hangup and it stops ringing automatically, you need only one command.

**Comment by pergolafabio** [comment]
It is italian, my father was, but i'm born in Belgium :-)

I always get below response with this command:

`curl -i --digest -u admin:XXXX -d "{"CallSignal":{"cmdType":"hangUp"}}" -H "Content-Type: application/json" -X PUT http://192.168.0.70/ISAPI/VideoIntercom/callSignal?format=json`

On what device did test?
```

HTTP/1.1 400 Bad Request
Date: Mon, 24 Jan 2022 11:57:44 GMT
Server: webs
Content-Length: 206
Connection: close
X-Frame-Options: SAMEORIGIN
Cache-Control: no-store
Pragma: no-cache
Content-Type: application/json

{
        "requestURL":   "/ISAPI/VideoIntercom/callSignal",
        "statusCode":   4,
        "statusString": "Invalid Operation",
        "subStatusCode":        "invalidOperation",
        "errorCode":    1073741830,
        "errorMsg":     "invalid operation"
}
```

**Comment by Supergiovane** [comment]
Search and download an ISAPI Hikvision PDF on the internet, as i cannot help you on that, sorry!
I cannot remember the device i tested!

**Comment by pergolafabio** [comment]
yeah; i already have the pdf's :-)

np;, maybe its just not supported
