### ISSUE TITLE
Problem with KNX Logger

### ISSUE THREAD

**Issue by gerribaldi** [Supergiovane/node-red-contrib-knx-ultimate#166]
Hi,

on my nodered i wrote all KNX Telegramm to a file using KNX Logger. The file is roted every 3 days. I use this flow [1] to write the file
 
**Describe the bug**
If i open a log-file in the ETS i only see the message which are sent form Node-Red to the bus. All messages between the other bus-members are not showing up in the ETS. When i open the file with a editor, i get a line count from 803xx lines. In ETS i get a line count from 2697. I wonder a bit, why the other messages are not showing up in the ETS.

**Expected behavior**
A while ago it was working without a problem and i could reopen the files in ETS to check the logs. At the moment i don´t know when the problem started..... So i can´t tell you which was the last working version....

**Screenshots**
![image](https://user-images.githubusercontent.com/4014772/151047303-07d9983b-afd9-4313-a8d8-274108eacb7b.png)

**Knx-Ultimate Version**
1.3.20

**Are you running node-red behind homematic, docker or anything similar?**
Stand-Alone in a Virtualbox on Centos 7.9

[1] Flow:
`[
    {
        "id": "6d09329993d5490f",
        "type": "file",
        "z": "3c28634794e16119",
        "name": "",
        "filename": "/home/jochen/nodered-log/knx1.xml",
        "appendNewline": false,
        "createDir": false,
        "overwriteFile": "false",
        "encoding": "none",
        "x": 660,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "60a32a66af30a6af",
        "type": "knxUltimateLogger",
        "z": "3c28634794e16119",
        "server": "c61ecb10.f99958",
        "topic": "KNX.BUS.Logger",
        "intervalCreateETSXML": "15",
        "name": "Bus Logger",
        "autoStartTimerCreateETSXML": true,
        "maxRowsInETSXML": 0,
        "autoStartTimerTelegramCounter": false,
        "intervalTelegramCount": "180",
        "x": 310,
        "y": 80,
        "wires": [
            [
                "6d09329993d5490f"
            ],
            []
        ]
    },
    {
        "id": "c61ecb10.f99958",
        "type": "knxUltimate-config",
        "host": "10.100.10.245",
        "port": "3671",
        "physAddr": "15.15.22",
        "hostProtocol": "TunnelUDP",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "enp0s3",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "error",
        "name": "KNX IP Gateway",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "40",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "keyringFileXML": "",
        "credentials": {
            "keyringFilePassword": ""
        }
    }
]`

**Comment by Supergiovane** [comment]
Hi.
i'm able to reproduce the issue.
The node logger correctly gets the traffic, but there is an error in the ETS telegram's encoding.
I'm looking at that.

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate@1.3.21 is out with the fix.
Please star my node. 
Thanks.
