### ISSUE TITLE
Raw value is ignored

### ISSUE THREAD

**Issue by Sven0507** [Supergiovane/node-red-contrib-knx-ultimate#167]
Hello, when sending a raw value, this is not always accepted by a KNX device

**Describe the bug**
If I send a 1-byte telegram as a raw value, for example the value 0, this telegram is displayed in busmonitor but the target device does not react to it. 
With larger values ​​from 70 - 255 it always works.

**Expected behavior**
With version 1.2.57 it always worked without problems.

**Screenshots**
Version 1.2.57
![V_1 2 57](https://user-images.githubusercontent.com/75073886/151682759-05a3eef3-d51f-4d4c-9385-f71a258683c4.PNG)
Version 1.3.21
![V_1 3 21](https://user-images.githubusercontent.com/75073886/151682769-06be17e5-edb4-4bc2-bb38-1bf0a1fe2df5.PNG)
**Knx-Ultimate Version**
1.3.21

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running on ioBroker

`[{"id":"b67fb59a.23ad08","type":"knxUltimate","z":"649a43d9.1af134","server":"6e7dcd37.e95fa4","topic":"","outputtopic":"","dpt":"","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":true,"name":"","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":2030,"y":940,"wires":[["587031ee.8dc5a"]]},{"id":"587031ee.8dc5a","type":"debug","z":"649a43d9.1af134","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":2210,"y":940,"wires":[]},{"id":"802f6477.2bd188","type":"inject","z":"649a43d9.1af134","name":"","props":[{"p":"destination","v":"1/0/1","vt":"str"},{"p":"writeraw","v":"[70]","vt":"bin"},{"p":"bitlenght","v":"8","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1870,"y":960,"wires":[["b67fb59a.23ad08"]]},{"id":"a711da6c.37ac48","type":"inject","z":"649a43d9.1af134","name":"","props":[{"p":"destination","v":"1/0/1","vt":"str"},{"p":"writeraw","v":"[0]","vt":"bin"},{"p":"bitlenght","v":"8","vt":"num"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":1870,"y":920,"wires":[["b67fb59a.23ad08"]]},{"id":"6e7dcd37.e95fa4","type":"knxUltimate-config","host":"192.168.0.35","port":"3671","physAddr":"1.1.23","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"KNX Gateway","localEchoInTunneling":true,"delaybetweentelegrams":"50","delaybetweentelegramsfurtherdelayREAD":"1","ignoreTelegramsWithRepeatedFlag":false,"keyringFileXML":"","autoReconnect":"yes"}]`

**Comment by Supergiovane** [comment]
Hi Sven. Monday i’ll take a look immediately. 
In the meantime, you can downgrade to the latest 1.2.x version.

**Comment by Supergiovane** [comment]
PS: or, instead of downgrade, you can avoid using raw value and, instead, specify the datapoint, like this:

```
msg.destination = "5/0/1"; 
msg.dpt = "5.001"; 
msg.payload = 20; 
return msg;
```

**Comment by Supergiovane** [comment]
Please update to the latest version to fix that.

PS: you know, you have to pass an hex value, not a decimal one, right?

For example, if you wish to send some text:
```
msg.destination = "2/2/10";
msg.writeraw = Buffer.from('4F747420362C3320B043', 'hex'); // "Ott 6.3 °C"
msg.bitlenght = 112;
return msg;
```

Or some brightness value:

```
msg.destination = "5/0/1";
msg.writeraw = Buffer.from("FF", 'hex'); // Max Brightness
node.status({ fill: "red", shape: "ring", text: msg.writeraw});
msg.bitlenght = 8;
return msg;
```

**Comment by Sven0507** [comment]
Hello, with the new version it works again as it should.
Thanks very much :)
