### ISSUE TITLE
KNX IP secure and KKNX data secure implementation

### ISSUE THREAD

**Issue by nanosonde** [Supergiovane/node-red-contrib-knx-ultimate#168]
Hi @Supergiovane ,

just in case you are searching for existing implementation of those two secure layers, I would like to point you to my implementation of the KNX data secure layer in this Arduino KNX stack:
https://github.com/thelsing/knx/blob/master/src/knx/secure_application_layer.cpp

Here are some learnings from my journey while implementing it: 
https://github.com/thelsing/knx/issues/57

The data secure implementation was inspired by this one: https://github.com/calimero-project/calimero-core/blob/master/src/tuwien/auto/calimero/secure/SecureApplicationLayer.java

The KNX IP secure layer has not been implemented yet in the above KNX stack.
But maybe this helps? https://github.com/calimero-project/calimero-core/blob/master/src/tuwien/auto/calimero/knxnetip/SecureSessionUdp.java

You will definitely want to read the KNX specs. AN158 (Data secure) and AN159 (IP secure).

**Comment by Supergiovane** [comment]
Hi Nanosonde! Thanks!
Yes, i also saw the Calimero implementation and i bought the ISO for KNX Secure.
Thank you for pointing me out your Arduino KNX stack, i'll take a look!!
I'm working on KNX Secure and i hope to release the first secure implementation before the summer arrives.

Nanosonde seems an italian name.

**Comment by farmio** [comment]
Hey there!
In case you are looking for an additional IP-Secure implementation, I just got this working with Python in xknx - it's still a draft though. https://github.com/XKNX/xknx/pull/875

**Comment by Supergiovane** [comment]
Thank you!

**Comment by Flow86** [comment]
If you need help to test a secure implementation, please feel free to ping me. I tried to connect to my secure KNX router but failed currently (`signature verification failed for keyring`)

**Comment by nikosvai** [comment]
Hello there, is the secure implementation tested now?

**Comment by Supergiovane** [comment]
Hi
We are working on that, but we need time. We work on that in our free time.

**Comment by nikosvai** [comment]
Hi
Thank you a lot for the update.

**Comment by Flow86** [comment]
since you're silently closing it, does it work now?

**Comment by Supergiovane** [comment]
Hi
It’s still under development https://github.com/lapo-luchini/KNXUltimate/commit/220c67bc39d4180fc34b3125c7046dd856458f77

I’ve closed this issue because i was annoyed to see it always open.
