### ISSUE TITLE
KNX User Forum - Translation 

### ISSUE THREAD

**Issue by Amokd0c** [Supergiovane/node-red-contrib-knx-ultimate#169]
hey massimo, 

i´ve tried to edit the text to translate it into german. But, I already told you, I only see a "create new page" site.
[That also happens, if I choose ](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-LoadControl-Configuration)

I am sorry, but this is my first contact with github

**Comment by Supergiovane** [comment]
Hi Amok
Wellcome. 
The link for the wiki is here. https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-Overview

On the left, you see the menu to navigate to the pages.
Find one not already translated, then click “edit” button somewhere in the page :-)
