### ISSUE TITLE
Starting translation - first question

### ISSUE THREAD

**Issue by Amokd0c** [Supergiovane/node-red-contrib-knx-ultimate#170]
Hey Massimo, 

relates the paragraph "KNX gateway".
Is that correct, that you can configure "one gateway" or " any gateway" ? 
I guess you ment, that "it is also possible that "no gateway" is selected? 
Am I right? What do mean with any? I think you either have one or you don't

Thanks ... Joe

**Comment by Supergiovane** [comment]
Hi Joe
Kan you please link the related page? Thanks

**Comment by Amokd0c** [comment]
Gateway
    KNX gateway selected. It is also possible not to select **any** gateway; in this case, only incoming messages to the node will be considered.

You mean .. you can also select that "no" gateway is present, right?

**Comment by Supergiovane** [comment]
Hi
I think you’re referring to the Scene controller, right? 
If yes, the phrase is correct, bacause you can choose not select any gateway. (Leave the gateway field unselected) :-)

**Comment by Amokd0c** [comment]
Scene Controller? No I mean the Load Controller.. but ok I understand, it is also possible to leave it unselected, if no gateway is present...

**Comment by Amokd0c** [comment]
what is the meaning of "Limit Wh" ... do you mean the maximum power of the supplier, which is shown in the display of the electric meter? or do you mean the max used power of one device?

**Comment by Supergiovane** [comment]
Hi
The maximum power of the supplier

**Comment by Amokd0c** [comment]
Ok I am ready so far.. but I will let check the translation by a friend also :) .. maybe tomorrow I will be finished...
