### ISSUE TITLE
[Question] knxUltimateViewer : Format of "Date, time" coloumn

### ISSUE THREAD

**Issue by Noschvie** [Supergiovane/node-red-contrib-knx-ultimate#171]
Hello Massimo

How is the format of the "Date, time" coloumn taken ?
Prefer to have it dependnig of the locale settings like "12.02. 22:23:04"

![grafik](https://user-images.githubusercontent.com/48217146/153749123-4e7a645f-e709-41f7-9a2d-733330147b5f.png)

**KNX-Ultimate Version**
1.3.28

Thanks for your nodes !

**Comment by Supergiovane** [comment]
Hi
Is the same as the date shown in the node status. Day, hour:minites:seconds
If you prefer, i can add an option to select the preferred date format. 
let me know. Thanks.

**Comment by Noschvie** [comment]
Suggest to have the preferred date/time format as property of the KNX Gateway settings. This property shall be used for the node status as well as for coloumn "Day, time" and DPT type DPT_TimeOfDay.
Find below a screenshot of the viewer:

![grafik](https://user-images.githubusercontent.com/48217146/153814090-088dec50-1a98-4a64-b077-e4832c1ed36e.png)

Thanks!

**Comment by Supergiovane** [comment]
Hi
node-red-contrib-knx-ultimate@1.3.30 is out with the KNXViewer node datetime change.
I cannot yet touch the other nodes, because many users are using such format, but in future i'll eventually add an option to select the datetime format in the datapoint and status as well.
Please star my node if you find it useful.
Ciao!

**Comment by Noschvie** [comment]
Output with v1.3.30

![grafik](https://user-images.githubusercontent.com/48217146/153949987-5f7187fc-d37e-4d33-a890-16c3d810f362.png)

**Comment by Supergiovane** [comment]
Hi
yes, exactly what expected.
As i wrote: I cannot yet touch the other nodes, because many users are using such format, but in future i'll eventually add an option to select the datetime format in the datapoint and status as well.
**Datapoint value format cannot yet be changed.**

**Comment by Noschvie** [comment]
To get the 24-hour format I added the standard Linux environment variables LANG and LANGUAGE to the Docker compose file and restarted the container.

![grafik](https://user-images.githubusercontent.com/48217146/154016707-7b1930ca-edb4-47dd-9500-63f83d5e829d.png)


How is this list sorted ? Seems to be sorted by group address as string, isn't ?
Maybe it can be changed to use the three-part integers ?

**Comment by Supergiovane** [comment]
Hi
with the next version, you'll have the choice to order by many properties...
Stay tuned. This is only the very first version.
