### ISSUE TITLE
Load Control - German language

### ISSUE THREAD

**Issue by Amokd0c** [Supergiovane/node-red-contrib-knx-ultimate#173]
Hey Massimo, i can´t find the edit button anymore .. I don´t know why? But here is the translation, maybe you can insert it for yourself.
**### English Version:**

LOAD CONTROL SETTINGS

With the Load Control node you can automatically manage the disconnection of loads (washing machine, oven, etc.) when the current consumption exceeds a certain threshold.
The devices are turned off intelligently, checking the possible consumption of the device to determine whether to turn it off together with others.
The node can automatically reactivate the loads.
The node turns off one device (or multiple devices) at a time, based on the order you have selected.

    Gateway

    KNX gateway selected. It is also possible not to select any gateway; in this case, only incoming messages to the node will be considered.

    Monitor Wh

    Here you have to enter the group address which represents the total consumption of your building.

    Limit Wh

    Here you have to enter the maximum threshold that your electricity meter can withstand. When this threshold is exceeded, the node starts to turn off the devices.

    Delay switch off (s)

    This value (expressed in seconds) indicates how often the node will evaluate consumption and switch off each device.

    Delay switch on (s)

    This value (expressed in seconds) indicates how often the node will evaluate consumption and turn on each device that was turned off.

LOAD CONTROL

Here you can add devices to turn off in case of overload.

    First row

    Choose the device to turn off. Enter the device name or its group address.

    Second row

    Here you must enter any group address that indicates the consumption of the device chosen in the first line. ** This is an optional parameter **. If the device is consuming more than a certain number of Watts, it means that it is in use. If it consumes less, the device will be considered "not in use" and both this and the next will be turned off at once.

    Automatic recovery

    If enabled, the device is automatically reactivated when the "reset delay" expires.

**### German Version:**

LOAD CONTROL Einstellungen

Mit der Node „Load Control“ kann man automatisch die Abschaltung von Verbrauchern (Waschmaschine, Backofen, etc.) verwalten, wenn die aktuelle benötigte Leistung einen definierten Schwellenwert überschritten hat.
Die Verbraucher werden erst abgeschaltet, nachdem die mögliche Leistung des Verbrauchers geprüft wurde, um ggf. mehrere Verbraucher gemeinsam abzuschalten.
Der Node kann u.a. die Verbraucher wieder aktivieren bzw. zuschalten.
Der Node schaltet ein Gerät (oder mehrere) zu einem definierten Zeitpunkt aus, welche man in einer Abfolge festgelegt hat. (siehe unten)

Gateway:
Hier wir das bestehende KNX Gateway angewählt. Es ist aber auch möglich den Node ohne ein Gateway zu konfigurieren bzw. zu betreiben. In diesem Fall werden nur eingehende Nachrichten / Informationen in der Node berücksichtigt und weiterverarbeitet.

Monitor Wh / Anzeige des aktuellen Verbrauchs:
Hier wird die Gruppenadresse eingetragen, welche den aktuellen Verbrauch der Anlage (z.B. des Gebäudes) an den KNX Bus sendet.

Limit Wh / Leistungsgrenze:
Hier wird die maximale Leistung angegeben, welche zur Verfügung steht. Sollte diese Grenze überschritten werden, beginnt der Node damit unten angelegte Verbraucher abzuschalten.

Ausschaltverzögerung:
Hier wird der Zyklus (s) eingetragen, wie oft der Verbrauch der Anlage überprüft wird, und ggf. unten aufgeführte Geräte ausschaltet werden.

Einschaltverzögerung:
Hier wird der Zyklus (s) eingetragen, wie oft die aktuelle Gesamtleistung geprüft wird. Bei Bedarf werden Verbraucher wieder zugeschaltet.

Verwaltung der Verbraucher:
Hier werden Geräte bzw. Verbraucher angelegt, die im Fall von Überlast abgeschaltet werden.

In der ersten Zeile (Control GA) wird die Gruppenadresse und der Name des Verbrauchers welcher ausgeschaltet werden soll eingetragen.
In der zweiten Zeile kann optional die benötigte Leistung des Gerätes eingetragen werden.
Wenn das Gerät mehr als die angegebene Leistung benötigt, gilt es als eingeschaltet. Würde es weniger Leistung benötigen, gilt es als ausgeschaltet.

**Comment by Supergiovane** [comment]
Hi,
Sorry!! 
You should see the EDIT button now. Please try it.
Thanks!!

**Comment by Amokd0c** [comment]
hehe.. yes I do!!! now it is visible!

**Comment by Amokd0c** [comment]
done... pls have look, and tell me if its ok ... or not ! :)

**Comment by Supergiovane** [comment]
Hi,
Wow, it's almost perfect.
The "Ausschaltverzögerung" is still in english tough.  https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-LoadControl-Configuration
