### ISSUE TITLE
DTP 16 String output

### ISSUE THREAD

**Issue by torebrigaglia** [Supergiovane/node-red-contrib-knx-ultimate#174]
Hi Max!

We are trying to get a clear text out of KNX DTP 16 to use it with sonos-plus node. We try to send the name of the playlist we want to play directly from a KNX Ultimate device node. Text flows in corectly but it brings with him also residuals ascii "00"s that confuses the sonos node. 
This is what exits the node if i send the text "prova" sent from ETS to the group address: prova

Do you think that has something to do with your node or we just need a function in between to clear the text?

Thank you for your work on this awesome project!

**Comment by Supergiovane** [comment]
PS: honpensato che probabilmente vedi i caratteri di trailing. Da specifiche del dpt16: If the string to be transmitted is smaller than 14 octets, unused trailing octets in the character string shall be set to NULL (00H).
Prova con una stringa esattamente lunga 14 caratteri.

**Comment by torebrigaglia** [comment]
Ciao, grazie per la pronta risposta

Sicuro che non ci sia altro. Da ets mando dalla diagnostica solo il testo.
La playlist sonos si chiama Lab,  scrivo lab sulla diagnostica, la scrivo
sull'indirizzo di gruppo e arrivano anche tutti gli altri trailing come
dici. Scrivendo tuttie  14 i caratteri ovviamentr non c'è problema. Non c'è
modo di trimmare il testo utile?

Il Mar 15 Feb 2022, 19:01 Max Supergiovane ***@***.***> ha
scritto:

**Comment by Supergiovane** [comment]
Ciao
Il nodo emette il datapoint come da specifiche. In ogni caso posso vedere di pensare a come trimmarlo, però domani. Stasera non faccio in tempo. 
Intanto metti un nodo funzione dopo knxultimate ed incollaci questo:

msg.payload = msg.payload.toString().replace(/\0/g, '');
return mag;

**Comment by Supergiovane** [comment]
`msg.payload=msg.payload.toString().replace(/\0/g, '');
return msg; `

**Comment by Supergiovane** [comment]
PS: vienici a trovare su facebook:
https://www.facebook.com/groups/viveresmart/?ref=share

**Comment by torebrigaglia** [comment]
Regex to the rescue! L'aveva detto Vannuzzi che eri un grande! Grazie!

**Comment by Supergiovane** [comment]
Ciao
KNX-Ultimate v1.3.32 è fuori.
C'era un problema di encoding/decoding dei caratteri ISO8859-1
Prova adesso e fammi sapere.
