### ISSUE TITLE
TTS-Ultimate - make filename controllable

### ISSUE THREAD

**Issue by bs-eng** [Supergiovane/node-red-contrib-knx-ultimate#175]
Hi Supergiovane!

Since the issues are turned off at TTS-Ultimate and according to your post on node-red you seldom check node-red forum, I am posting this here - hoping you will move it to the correct repo.

**Is your feature request related to a problem? Please describe.**
Currently the TTS-Ultimate node seems to set the filename using the complete input text. When the input text is getting long, the node returns a file name too long error - which is expected as the file system has a limit there. However in our case we need the audio to be in one output file.

**Describe the solution you'd like**
From our perspective it would be highly appriciated if the file name could be set by a control parameter like *msg.filename*. If this parameter is set the node uses that as filename. In case it is not set the current standard behaviour is used.

**Describe alternatives you've considered**
Concatenating audios does not work properly because the pauses at the end of the audio (e.g. from google TTS) are different when text is passed in one block instead of in mutliple blocks and then concatenated.

Thanks a lot for considering!
Sorry for crossposting!
JR

**Comment by Supergiovane** [comment]
Hi
What version are you using?
The last version overcones all these issues by giving to the filenane, an md5 hash.

**Comment by bs-eng** [comment]
Hi!
the version I use is 1.0.36
The error I get is:
ttsultimate: node id: 3d9635bc.53c14a Error Downloading TTS: ENAMETOOLONG: name too long, open '/home/nodered/.node-red/sonospollyttsstorage/ttsfiles/AudioBox är en talutgångsenhet med en högtalare_stop_ Inuti finns en liten dator_stop_ För att du ska kunna höra meddelanden från AudioBox på ett säkert och tillförlitligt sätt_bd30734d3e9c811572aefa085348ab19_sv-SE-Standard-A_sv-SE_FEMALE01_ssml.mp3'. THE TTS SERVICE MAY BE DOWN.

I will try the newest version and come back to you!
Thx!
JR

**Comment by bs-eng** [comment]
Just upgraded to version 1.0.40 and getting still the same error.

**Comment by Supergiovane** [comment]
Please restart nodered

**Comment by bs-eng** [comment]
Thank you so much!
That did it for me!
JR
