### ISSUE TITLE
no response to read requests

### ISSUE THREAD

**Issue by Anka001** [Supergiovane/node-red-contrib-knx-ultimate#176]
Hi supergiovane,

new to knx, so please be kind..

When I send "msg.payload = true" to a device node representing a switch, the switch will turn on, and the node will issue a status msg
When I try to read from a device node by sending "return ({readstatus: true});", I do not get any response.

The node's status changes to
![grafik](https://user-images.githubusercontent.com/95497334/156447719-d8890954-ca57-47ea-a1da-37d07eca74d7.png)
but still no response

I tried your samples ("Sample Read value from Device") - no response from the bus.

knx-ultimate version is 1.3.32

My brand new knx installation works perfectly - I can issue commands to every actor, the action is what I expect, and I get a response from the knx bus.
I am just completly unable to actively request any status information from any device.

Any help appreciated,
Andreas

**Comment by Supergiovane** [comment]
Hi
Is the 1/1/1 set to respond to read requests on the actuator?
You should see on the actuator itself… You must use the proper object on the actuator.

**Comment by pkess** [comment]
Hello @Anka001
The response on read depends on the setup in your knx system. The actor has to be configured to reply to read commands.
Did you check this in your ets?

**Comment by Anka001** [comment]
> Is the 1/1/1 set to respond to read requests on the actuator?
It is.
>You should see on the actuator itself… You must use the proper object on the actuator.
Not sure I understand what you mean. 

I tried your samples ("Sample Read value from Device"), adjusted Gateway configuration and GAs, leaving everything else untouched. When I try to read, status of the device node changes from 
![grafik](https://user-images.githubusercontent.com/95497334/156638794-6fd4dd52-ff78-494e-ad5f-e41e7ee7b4af.png)
to the status shown above. But no response.

Gateway configuration seems to be OK, as I am able to write to the Bus, and receive response. 

Thank you for your help,
Andreas

**Comment by Supergiovane** [comment]
Hi Andreas
You should ask on some knx forums, how does the KNX objects works. This will help you understand, why you doesn’t receive any response from that group.

**Comment by Anka001** [comment]
> The response on read depends on the setup in your knx system. The actor has to be configured to reply to read commands.
> Did you check this in your ets?

As line voltage is involved, and critical systems in my house are concerned, I had the system installed by a professional. Basic critical functions like closing roof windows on rain alarm have been implemented by him, because I do not want to rely on my node red running on a raspi for that.
Right now, I do not even own an ets license. I hoped the interface exposed to node red would be enough to suit my needs. And spending the money for the license just for debugging purposes.. Not sure.

**Comment by pkess** [comment]
> > The response on read depends on the setup in your knx system. The actor has to be configured to reply to read commands.
> > Did you check this in your ets?
> 
> As line voltage is involved, and critical systems in my house are concerned, I had the system installed by a professional. Basic critical functions like closing roof windows on rain alarm have been implemented by him, because I do not want to rely on my node red running on a raspi for that. Right now, I do not even own an ets license. I hoped the interface exposed to node red would be enough to suit my needs. And spending the money for the license just for debugging purposes.. Not sure.

Hello Andreas,

if you have the ets project available i can offer you to open this and check your configuration. I would need
- the ets project file (typically *.knxproj )
- your node red flow
- some info what type of value you want to read

I don't know your location, so if you are located in germany we can even phone / talk in german.

**Comment by Anka001** [comment]
> Ask you installer about what group addresses you can use. Explain him what you wanna do. They will help! Cheers.

I received a proper documentation regarding group adresses and datapoints, and a csv file to import into knx-ultimate. So far I cannot complain on this side.

On the other hand, I agree this is a knx issue, and not a node-red-contrib-knx-ultimate issue. I tried knx-easy nodes, and results are basically the same.

**Comment by Anka001** [comment]
> I don't know your location, so if you are located in germany we can even phone / talk in german.

Gerne per pm über ak09@pflanzenphotos.de

Danke für das Angebot!

**Comment by Anka001** [comment]
jtfr
I was not aware the response to a read to ga 1/1/1 would arrive at 1/4/1
