### ISSUE TITLE
KNX Secure Tunneling

### ISSUE THREAD

**Issue by primpler** [Supergiovane/node-red-contrib-knx-ultimate#177]
Hi supergiovane,

I am a happy user of your knx ultimate node, but are not able to hook up Secure Tunneling. When I am trying to setup a new Gateway IP I do not have the field described in your manual.

1) Keyring file
2) Password
3) Login

Therefore I cannot connect to my Ip Gateway. 

Where is the mistake in my setup or your code?

Thanks for your help.

Best regards
Patrick

**Comment by Supergiovane** [comment]
Hi Patrick
In the config window, there is a warning. The knx secure is currently under development. It’s not ready yet.
