### ISSUE TITLE
KNX Ultimate with MDT IP Router

### ISSUE THREAD

**Issue by primpler** [Supergiovane/node-red-contrib-knx-ultimate#178]
Hi Supergioanve,

I still have problems establishing a stable connection between nde-red / KNX Ultimate and my IP Interface. I often get the state "connected. On duty" but I am not able to send or receive telegrams from / onto the knx bus.

In my test setup almost a year ago everything worked, but now after moving into our new home I am facing these problems.

Do you have an idea for my issue?

Best regards and thank you very much
Patrick

**Comment by Supergiovane** [comment]
Hi primpler.
How are you skills in KNX? This will help me to adapt my suggestions to your skill

**Comment by Supergiovane** [comment]
PS: please follow this guide: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/5.-FAQ-Troubleshoot
and, if you've Unifi stuffs or L2/L3 switches, be sure to disable any UDP storming protection.
