### ISSUE TITLE
Ciruclar reference protection is faulty

### ISSUE THREAD

**Issue by andreasmuellerka** [Supergiovane/node-red-contrib-knx-ultimate#179]
In the flow the same group address (input and output) is used with a delay in between but the circular reference protection kicks in. It does not matter if RBE is activated or not, the protection kicks in.
To test the behavior, just reduce the delay to 5s. After clicking two times (with a delay of 5s in between) on the "Party (8h)" button the circular dependency protection kicks in.

The flow should activate ventilation for 8h after clicking the button and disable it automatically after 8h. The flow is designed in a way that the ventilation is deactivated definitely after 8h after activation (either via Party button or via another external event).

The circular protection is obviously unnecessary here, but I do not know how to avoid it.
I see no possibility to change the flow in a way that it works. A solution would be to disable the circular dependency protection manually in such a case.

`[
    {
        "id": "dd6b35b7e0a5fc21",
        "type": "delay",
        "z": "2a3733e.9a4cd4c",
        "name": "",
        "pauseType": "delay",
        "timeout": "8",
        "timeoutUnits": "hours",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 580,
        "y": 220,
        "wires": [
            [
                "ada7811221464f20"
            ]
        ]
    },
    {
        "id": "651c5090bbd4932a",
        "type": "knxUltimate",
        "z": "2a3733e.9a4cd4c",
        "server": "92fa2c65.b7036",
        "topic": "3/1/105",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": "0",
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HLK Lüftung intensiv Kanal",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": "1",
        "passthrough": "no",
        "x": 940,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "4926b6b2c5e6956a",
        "type": "ui_button",
        "z": "2a3733e.9a4cd4c",
        "name": "",
        "group": "e8e342d6.93bd48",
        "order": 3,
        "width": 2,
        "height": 1,
        "passthru": false,
        "label": "Party (8h)",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "payload": "true",
        "payloadType": "bool",
        "topic": "",
        "topicType": "str",
        "x": 140,
        "y": 180,
        "wires": [
            [
                "651c5090bbd4932a"
            ]
        ]
    },
    {
        "id": "ada7811221464f20",
        "type": "change",
        "z": "2a3733e.9a4cd4c",
        "name": "Aus",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "false",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 730,
        "y": 220,
        "wires": [
            [
                "651c5090bbd4932a"
            ]
        ]
    },
    {
        "id": "35bc4e88a98ec536",
        "type": "switch",
        "z": "2a3733e.9a4cd4c",
        "name": "1/0?",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 290,
        "y": 220,
        "wires": [
            [
                "dd6b35b7e0a5fc21"
            ],
            [
                "0f5fc155a204e2c5"
            ]
        ]
    },
    {
        "id": "0f5fc155a204e2c5",
        "type": "change",
        "z": "2a3733e.9a4cd4c",
        "name": "Reset",
        "rules": [
            {
                "t": "set",
                "p": "reset",
                "pt": "msg",
                "to": "true",
                "tot": "bool"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 410,
        "y": 240,
        "wires": [
            [
                "dd6b35b7e0a5fc21"
            ]
        ]
    },
    {
        "id": "f6e24624.cddd88",
        "type": "knxUltimate",
        "z": "2a3733e.9a4cd4c",
        "server": "92fa2c65.b7036",
        "topic": "3/1/105",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": "1",
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "HLK Lüftung intensiv Kanal",
        "outputtype": "update",
        "outputRBE": false,
        "inputRBE": true,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": "1",
        "passthrough": "no",
        "x": 210,
        "y": 300,
        "wires": [
            [
                "3fb59a13.b1900e",
                "a1e01dd4.6c43c",
                "35bc4e88a98ec536"
            ]
        ]
    },
    {
        "id": "92fa2c65.b7036",
        "type": "knxUltimate-config",
        "host": "192.168.1.7",
        "port": "3671",
        "physAddr": "1.2.5",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "error",
        "name": "Multicast KNX Gateway",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "40",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "keyringFileXML": "",
        "autoReconnect": "yes",
        "credentials": {}
    },
    {
        "id": "e8e342d6.93bd48",
        "type": "ui_group",
        "name": "Lüftung",
        "tab": "79fe6824.787928",
        "order": 2,
        "disp": true,
        "width": "7",
        "collapse": false
    },
    {
        "id": "79fe6824.787928",
        "type": "ui_tab",
        "name": "Klima und Lüftung",
        "icon": "dashboard",
        "order": 12,
        "disabled": false,
        "hidden": false
    }
]`

**Comment by Supergiovane** [comment]
Hi Andreas
Have you read this when you opened the issue?
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

I'm an italian and we italians do love kindly introductions like "Hello", "Hi there!", "Guten Tag" and so on. 

As for your question: The WIKI is your friend, you can find any useful info. Please see here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-Protections at the page's bottom.

**Comment by andreasmuellerka** [comment]
Ciao Supergiovane,

thank you very much for your hint, I like kindly introductions, too. ;-) I think it was list during editing the text. Sorry for that.

Indeed I found the FAQ but not the solution with this special node. This would help in my case.

Maybe there is still a possibility to fix the behavior of circular dependency detection (especially if there is a delay involved).
What do you think?

**Comment by Supergiovane** [comment]
Hi Andreas
That's really not an issue, it's so by design. To better undestand: in the very first releases of the node, there was no circular protection.
About 30 out of the first 100 users have broken Node-Red (no access to the UI anymore) and flooded the KNX Bus because of that.
This is too important to be disabled, even by an option in the config ui.
The only way to disable the circular protection, is to delete the **msg.topic** from the outcoming KNX node's message.
That's by design, otherwise i'll spend again the whole week to fix the mistakes made by some users.
In the FAQ https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-5.-FAQ-Troubleshoot there is a link that explains all the KNX-Device protections and how to overcome it.

In your flow, just add a "change" node and set it to delete the msg.topic.

<img width="1397" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/161051420-52d6ae2e-77d0-4562-acb2-5a1605f2676b.png">

**Comment by Supergiovane** [comment]
Sorry, made a mistake.
Delete the msg.knx.destination property, not the msg.topic.

<img width="508" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/161057217-2da69012-5d7a-4623-b0b6-38e1effa1cb2.png">

**Comment by andreasmuellerka** [comment]
Thank you very much, @Supergiovane.
This helps me a lot.

**Comment by Supergiovane** [comment]
Hi Andreas
Node red doesn’t allow a node to “see” other linked nodes, so knx ultimate is not aware of a delay node.
