### ISSUE TITLE
 KNXEngine documentation

### ISSUE THREAD

**Issue by boellner** [Supergiovane/node-red-contrib-knx-ultimate#181]
Hi,

-is there a documentation of the api? Did not find it in the examples and have to go through the code.
-Concrete: Im looking for a callback that indicates me that a write to knx on bus is done. The original library supports this, but implementation is poor, it does not check for confirmance on the bus but just calls the callback.
Seem this has been thrown out, although the functionality is quite important for certain use cases.
Code is in KNXClient.js
// sendWriteRequest(dstAddress, data) {
    write(dstAddress, data, dptid) {

**Comment by Supergiovane** [comment]
Hi Boellner
Have you seen the readme?
The API has been extracted and it’s here https://github.com/Supergiovane/KNXUltimate

**Comment by Supergiovane** [comment]
For any questions about the api, please open an issue in that page.

**Comment by Supergiovane** [comment]
PS: if you need such function, please ask it in the issue page of the API. 
It’s quite simple to implement, because the api already has the telegrams ACK handling. I just need to add an event for that.

**Comment by boellner** [comment]
Hi @Supergiovane thank you, im opening an issue there
