### ISSUE TITLE
Disconnection issue

### ISSUE THREAD

**Issue by KevinSzr** [Supergiovane/node-red-contrib-knx-ultimate#182]
Hi,
KNXUltimate worked fine on my Docker-Node-RED for quite some time and the flows are growing bigger.
Recently it gets stuck in a constant connect / disconnect cycle. It still establishes the connection and is still able to read or write to the BUS, but it gets disconnected every 30-60seconds.
As node-RED does not alert anything I do not think taht it is a general issue.
Probably I have mess up something anywhere in the setting, but I am not sure how to proceed with the analysis.

First I had 1.3.35, now updated to 1.3.37 - no change

Best regards,
Kevin

**Comment by Supergiovane** [comment]
Hi Kevin
Do you use a knx interface or a knx router?

**Comment by Supergiovane** [comment]
Anyway... if you're using a KNX interface, be sure not to have reached the maximum connection limit.

I need you to push this button (you find it in the gateway config window) and to paste here the result
<img width="503" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/161377643-8f8292f1-72a4-4930-adc0-d3e1142db417.png">

Then, in advanced option, se the loglevel to "debug" and RESTART nodered.
<img width="548" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/161377688-48a1a381-8ab7-45b4-a4b0-5d945a7a80c0.png">

You should see something like this in the log terminal:
<img width="1016" alt="Schermata 2022-04-02 alle 11 49 30" src="https://user-images.githubusercontent.com/37666636/161377716-27e26d24-5e11-44f9-b300-040afa6ce91b.png">

I need you to paste here that log as well. It will tell us the cause of the disconnection.

**Comment by KevinSzr** [comment]
I am using a X1 as an interface
maximum connection limit may be the case. I have A LOT of nodes reading. How do I manage this?
I have set the log to debug, but did not restart yet.... now I did. 
How do I access the log terminal? 
If it is this, than its empty:
![grafik](https://user-images.githubusercontent.com/79407376/161380621-b3d0c8f7-2e42-42dd-9bc7-25e98040cc40.png)


`-> id: fd51a54b.851e58
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 192.168.179.11
-> port: 3671
-> physAddr: 1.0.1
-> hostProtocol: TunnelUDP
-> suppressACKRequest: true
-> csv: "Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Haus [HA]"	"0/-/-"	""	""	""	""	"Auto"
"Zentral"	"0/0/-"	""	""	""	""	"Auto"
"Beleuchtung"	"0/1/-"	""	""	""	""	"Auto"
"[HA] Zentral / Beleuchtung / Deckenleuchte - Schalten"	"0/1/0"	""	""	""	"DPST-1-1"	"Auto"
"[HA] Zentral / Beleuchtung / Deckenleuchte - Dimmen relativ"	"0/1/1"	""	""	""	""	"Auto"
"[HA] Zentral / Beleuchtung / Deckenleuchte - Dimmen absolut"	"0/1/2"	""	""	""	"DPST-3-7"	"Auto"
"[HA] Zentral / Beleuchtung / Deckenleuchte - Status EIN/AUS"	"0/1/3"	""	""	""	"DPST-1-1"	"Auto"


<< DELETED A COUPLE OF LINES TO MAKE IT SHORTER >>


"."	"30/-/-"	""	""	""	""	"Auto"
"Logik"	"31/-/-"	""	""	""	""	"Auto"
"Sensoren"	"31/5/-"	""	""	""	""	"Auto"
"Logik / Sensoren - Wetter : Temperatur"	"31/5/0"	""	""	""	""	"Auto"
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> statusDisplayLastUpdate: true
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: skip
-> loglevel: debug
-> name: Gira X1
-> localEchoInTunneling: true
-> delaybetweentelegrams: 40
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: 
-> knxSecureSelected: false
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=n+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> credentials: [object Object]
-> infoEditor: [object Object]
`

**Comment by Supergiovane** [comment]
Hi
No limits on knx node number. All nodes refera to a single connection. 
The Gira X1 is an interface. I don’t the max connections limit, you should ask on any knx forum. Normally, such interfaces does have from 1 to 5 maximum simultaneous connections. If you have other devices connecting to the X1 ( for example a visualization panel) you may reached the limit. 

About the log: you should ask somewhere, where the dockerized nodered saves the log. I don’t know that, because every docker image can have different log folder.

**Comment by KevinSzr** [comment]
Hi,
currently I am just using Node-RED with KNX Ultimate to connect to my X1 / no other devices. I am planning to do the visualization via Node RED.

Haven't found the log file yet, but found a log screen:
![grafik](https://user-images.githubusercontent.com/79407376/161381495-29ec6366-7ddc-428c-9135-3d1da64ef8ce.png)

**Comment by Supergiovane** [comment]
Good
The X1 seems not to respond to connection status request, thus after 60 second, KNX-ultimate disconnects the connection. 
Since when do you have discovered this issue?

**Comment by Supergiovane** [comment]
PS: the X1 should be a router as well. Please set the IP to 224.0.23.12 and restart nodered.

**Comment by KevinSzr** [comment]
Hi,
I discovered the issue just recently, but as it still does what it should this issue may be there a little longer.

Just to understand the differnce between interface and router:
In case of an interface node-red gives the orders and X1 passes them through. In case of a router Node RED tells X1 what to do and it gives the orders to the BUS - is that correct?

Why the IP 224.0.23.12? There is no such IP in my network....
... it seems as if this was the solution. Could you please explain?

**Comment by Supergiovane** [comment]
Hi
Both does work the same way. 
The difference is that the router is “connection-unaware” because the traffic is multicast and it has no concurrent connections limit. The interface uses unicast and does mimic a tcp connection, thus each connection consumes resources. 
That strange IP is the official KNX multicast IP, used with knx routers. 
Remember to restart nodered after changing the IP in the gateway config window.

**Comment by KevinSzr** [comment]
thanks. it works.

**Comment by Supergiovane** [comment]
Good. Please remember to click the star icon, up right in this page, to leave your appreciatoon.

**Comment by KevinSzr** [comment]
Hi,
I would like to reopen this issue.
Now the nodes are showing me "Connected. On duty." all the time, but the messages seem not to go through. Neither sending nor receiving works. I am a bit lost. I even tried going back to interface settings - no success.

I had updated the firmware of my X1 / not sure if this had something to do with this.

the settings are still unchanged:
`-> id: fd51a54b.851e58
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 224.0.23.12
-> port: 3671
-> physAddr: 1.0.1
-> hostProtocol: Multicast
-> suppressACKRequest: true
-> csv: "Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Haus [HA]"	"0/-/-"	""	""	""	""	"Auto"
"Zentral"	"0/0/-"	""	""	""	""	"Auto"
"Beleuchtung"	"0/1/-"	""	""	""	""	"Auto"
"[HA] Zentral / Beleuchtung / Deckenleuchte - Schalten"	"0/1/0"	""	""	""	"DPST-1-1"	"Auto"

[.....]

"Sensoren"	"31/5/-"	""	""	""	""	"Auto"
"Logik / Sensoren - Wetter : Temperatur"	"31/5/0"	""	""	""	""	"Auto"
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> statusDisplayLastUpdate: true
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: skip
-> loglevel: debug
-> name: Gira X1
-> localEchoInTunneling: true
-> delaybetweentelegrams: 40
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: 
-> knxSecureSelected: false
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=n+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> changed: false
-> highlighted: false
-> credentials: [object Object]
-> infoEditor: [object Object]
-> z: 
`

As KNXultimate thinks that everything is fin I do not get any error...

**Comment by Supergiovane** [comment]
In routing mode, the disconnection event is triggered very late, because of udp multicast. 
Do you have Unifi gears? 
Do you have udp storming protection on your switches?
Do you have more than one eth enabled on your pc? Maybe eth and wifi? If yes, just select the desired interface in the gateway config window and restart nodered.

**Comment by KevinSzr** [comment]
> In routing mode, the disconnection event is triggered very late, because of udp multicast.
I even tried setting it back to interface mode.... same here

> Do you have Unifi gears?
Yes I do. but noob here as well...

> Do you have udp storming protection on your switches?
I did not turn it on intentionally and do not find the settings on my switch.

> Do you have more than one eth enabled on your pc?
The NodeRED is running on my NAS (connected via LAN). And my PC is LAN-only as well.

**Comment by Supergiovane** [comment]
Unifi has many options enabled by default, related to multicast grouping and so on. You should look at the unifi forum but prior of that, pick a very dumb little switch and connect your nas, your Gira X1 and your PC to that dumb switch. Check wether all is working. If it works, look at unifi forum, otherwise i think the culprit is your X1. I have read other users complains about that but i don’t know which firmware version they have. 
If you have another KNX gateway lying around, try using that.

**Comment by KevinSzr** [comment]
Now I connected my NAS directly to the X1 (my PC is still connected via the UniFi Switch) - still the same
I agree that the culprit is probably the X1, unfortunately I do not have an alternative gateway.
The thing is, that I do not even understand the error.

If the KNXUltimate has a connection shouldn't it at least receive messages from it?

**Comment by Supergiovane** [comment]
Can you post the log again?

**Comment by KevinSzr** [comment]
Hi, I checked the X1 as good as I can. Should work...

-> id: fd51a54b.851e58
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 224.0.23.12
-> port: 3671
-> physAddr: 1.0.1
-> hostProtocol: Multicast
-> suppressACKRequest: true
-> csv: "Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Haus [HA]"	"0/-/-"	""	""	""	""	"Auto"
"Zentral"	"0/0/-"	""	""	""	""	"Auto"

[DELETED]

"Logik"	"31/-/-"	""	""	""	""	"Auto"
"Sensoren"	"31/5/-"	""	""	""	""	"Auto"
"Logik / Sensoren - Wetter : Temperatur"	"31/5/0"	""	""	""	""	"Auto"
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> statusDisplayLastUpdate: true
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: skip
-> loglevel: debug
-> name: Gira X1
-> localEchoInTunneling: true
-> delaybetweentelegrams: 40
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: 
-> knxSecureSelected: false
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=n+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> infoEditor: [object Object]
-> z: 
-> changed: false
-> highlighted: false
-> credentials: [object Object]

**Comment by Supergiovane** [comment]
Hi i need a log, not the debug info.

**Comment by KevinSzr** [comment]
![grafik](https://user-images.githubusercontent.com/79407376/161626086-015f5a62-9959-4959-bbb3-a9ac1f308405.png)

**Comment by Supergiovane** [comment]
Hi
You have no nodes linked to that gateway. Have you created another gateway? Simply delete the unused gateway.

**Comment by KevinSzr** [comment]
... no there is just this one gateway...

![grafik](https://user-images.githubusercontent.com/79407376/161681780-426dafd6-cf84-4ab9-8030-baa3dbce946a.png)

**Comment by Supergiovane** [comment]
Hmmm maybe you need to restart NodeRed, because i see in the log that there is a gateway without linked nodes.

**Comment by KevinSzr** [comment]
I already restarted NodeRED a couple of times already. As I do it everytime I change the gateway-settings...

**Comment by Supergiovane** [comment]
This means, you have an unused gateway node, named Gira X1, because no KNX devices uses that node. That's strange.
<img width="806" alt="Disconnection_issue_·_Issue__182_·_Supergiovane_node-red-contrib-knx-ultimate" src="https://user-images.githubusercontent.com/37666636/161698110-e1f2dc39-b4f1-488f-bd1c-abe6654d084a.png">

**Comment by KevinSzr** [comment]
I tried to set up new gateways. I now have three: The original / a copy with 224:0:23:12 / one with 192.168.178.41.
I did connect all three of them to a Viewer Node (+Debug) Going through the house and hitting switches just the third one (.41) responsed. 
Unfortunately - even if I change all the nodes to this gateway it will not switch the lights.
Aditionally I get the "no nodes linked" message for all three gateways.

I do not understand the situation.
How can the node say "connected" and the terminal says "no nodes linked"?
How could the KNX Viewer receive some information, but is not able to send commands.

It seems like the X1 blocks incoming commands. Is this reasonable?
And: where is the change? It did work some time ago.... Is it related to the firmware update?

**Comment by Supergiovane** [comment]
Hi
The X1 can block telegrams. You should disable all filters and allow forwarding. See the x1 user manual. 
Please paste here your complete flow, so i can see what is going on.

**Comment by KevinSzr** [comment]
[quote]The X1 can block telegrams.[/quote]
I did not find it. Neither in the parameters, nor in the gira project assistant. I will search the web if there is anything I do not see yet...
Here are my two flows. first one (in combination with dashboard) should have been my test environment
The second one should collect all data and store it in SQL.

https://we.tl/t-O2jDMT54PD

Currently all gateways are mixed in several nodes, but as I started everything was clean there....

**Comment by Supergiovane** [comment]
Hi Kevin
I’ll take a look tomorrow.

**Comment by KevinSzr** [comment]
thx.
additional quetion: Why does KNXultimate think that there is no node connected - even if there is?
Is there something messed up with internatio IDs?

**Comment by Supergiovane** [comment]
I need to check your flow. For sure, one of the gateway nodes, is not used by any node.

**Comment by Supergiovane** [comment]
Hi Kevin
i saw your flows.
Here you have the 3 gateways, each one with some linked nodes.
Bear in mind, that each tunnel consumes a connection, so you should delete the tunnel gateway, and leave only one multicast gateway node. Here you can also considering to use a single KNX Device note, set in "universal mode", to catch all telegrams and save it to the database. You should also consider using the ETS logger node, that outputs an ETS XML payload, suitable for ETS, if you intend to only save the traffic. You should just save that payload in a file. There is an example on the WIKI page about that.

<img width="1200" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/162675269-1991fd64-9de8-4c1d-a560-c8ad97eef3a2.png">



In the Dasboard flow, you also have many gateway nodes.
Here also, delete all but the multicast one.

<img width="1080" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/162675905-02d4ffaf-9bb1-4e9b-aa7f-556ee2339421.png">

After you've linked all nodes to the unique multicast gateway, you shouldn't have any issue. If you still have issues, you must inspect the X1 and understand why it seems to filter telegrams. 
Bear in mind that you're using RBE filters on the KNX nodes. With RBE filter, subsequents equals commands are not sent (for example if you send **true**, and again **true**, the second **true** will not be sent).
You should also consider asking on some forums, because i've read that the X1 had some issue when used as KNX gateway. I don't know if it has been fixed with some firmware updates.

About your flows, i don't see any issue preventing it to work as expected, apart maybe from the physical address of your gateways (15.15.22). If there is a filter in the X1, you should consider to set the physical address on the same line belonging to the X1.

**Comment by Supergiovane** [comment]
Hi Kevin
15.15.22 is in the advanced options, in the gateway node config.

**Comment by KevinSzr** [comment]
Hi,
in my options there is the correct adress:
![grafik](https://user-images.githubusercontent.com/79407376/162794769-a79af439-3ee4-407e-a2fb-97d8cd77d630.png)

**Comment by KevinSzr** [comment]
No solution yet.
And I still do not understand how can KNXultimate state that there are no connected nodes - even if there are....

**Comment by Supergiovane** [comment]
Hi Kevin
have you tried to install a fresh installation of node-red somewhere (VM, Docker, Raspberey etc) and try it?
I suggest, also, to use another KNX node from other devs. You may have look with the X1.

**Comment by KevinSzr** [comment]
read a bit and experimented a bit.
It seems as if Gira X1 does not suppurt multicast. So I set it to "Tunnel TCP". Now it works. 
But I still have a bad feeling about this, because it is where I started from...

Could you briefly descripe whats the difference between Tunnel UDP, Multicast and Tunnel TCP

**Comment by Supergiovane** [comment]
Hi Kevin
are you registered on knx-user-forum.de? If yes, search for the X1, as some users experienced issues.
For KNX Routers use Multicast, for KNX Interfaces, use Tunnel UDP.
Tunnel TCP is for KNX Secure,  you have not to use that.

**Comment by KevinSzr** [comment]
thx. seems to work right now.
