### ISSUE TITLE
Issues with importing the GA from ETS

### ISSUE THREAD

**Issue by deblasioluca** [Supergiovane/node-red-contrib-knx-ultimate#183]
Ciao Supergiovane

**Describe the bug**
I'm trying to import the Group Addresses exported from ETS into the KNX/IP Gateway Configuration. I've exported the GAs as per guideline. I've attached both, the exported GA and the error report from the Gateway Node.

**To Reproduce**
1. Open config of your KNX Global Context Node
2. Edit your Gateway
4. Open section "ETS Group Address list import"
5. Import attached GAs

**Expected behavior**
a) There should be no errors in the error section of the import GA
b) I've setup a KNXViewer Node, which still states that I should import the ETS file to view the group address name
******************************
address: "1/3/2"
addressRAW: 2818
dpt: "9.001"
payload: 376.32
devicename: "Import ETS file to view the group address name"
lastupdate: "2022-04-20T05:50:45.314Z"
******************************

**Screenshots**
N/A

**Knx-Ultimate Version**
 - 1.3.38

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red running alone in RaspberryPi

**Additional context**
[Group_Addresses_Reworked.txt](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/8518630/Group_Addresses_Reworked.txt)
[Node_Red_GA_Import_Error.txt](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/8518631/Node_Red_GA_Import_Error.txt)

**Comment by Supergiovane** [comment]
Hi Luca
The fielnds should be surrounded by "
Here an example

```
"Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Attuatori luci"	"0/-/-"	""	""	""	""	"Auto"

```

**Comment by deblasioluca** [comment]
Many thanks, Supergiovane! This worked!!

**Comment by Supergiovane** [comment]
PS: remember to STAR my node! :-)
