### ISSUE TITLE
ERROR dptlib.fromBuffer:Error converting date buffer to Date object.

### ISSUE THREAD

**Issue by tx73github** [Supergiovane/node-red-contrib-knx-ultimate#184]
Dear Max,

I am getting a decoding issue for the time of day object which changes per minute.
Here are a few examples. 

The 1.3.31 source is a GPS weatherstation that send the value once a minute.

Regards,
//t

22.4.2022, 00:55:59 node: 40a1a3ec3543de4a
{"topic":"5/0/0","payload":"UNKNOWN: ERROR dptlib.fromBuffer:Error converting date buffer to Date object.","devicename":"KNX-Knoten","payloadmeasureunit":"","payloadsubtypevalue":"","knx":{"event":"GroupValue_Write","dpt":"unknown","dptdesc":"","source":"1.3.31","destination":"5/0/0","rawValue":[160,56,58]},"_msgid":"990a6f1266102e97"}

22.4.2022, 01:00:59node: 40a1a3ec3543de4a
{"topic":"5/0/0","payload":"UNKNOWN: ERROR dptlib.fromBuffer:Error converting date buffer to Date object.","devicename":"KNX-Knoten","payloadmeasureunit":"","payloadsubtypevalue":"","knx":{"event":"GroupValue_Write","dpt":"unknown","dptdesc":"","source":"1.3.31","destination":"5/0/0","rawValue":[161,0,58]},"_msgid":"9fd35739926bb95f"}

22.4.2022, 01:01:59node: 40a1a3ec3543de4a
{"topic":"5/0/0","devicename":"KNX-Knoten","payload":"2057-12-31T23:00:00.000Z","payloadmeasureunit":"unknown","payloadsubtypevalue":"unknown","knx":{"event":"GroupValue_Write","dpt":"11.001","dptdesc":"Date","source":"1.3.31","destination":"5/0/0","rawValue":[161,1,58]},"_msgid":"9f1653c81c40439d"}

22.4.2022, 19:47:54node: 40a1a3ec3543de4a
{"topic":"5/0/0","payload":"UNKNOWN: ERROR dptlib.fromBuffer:Error converting date buffer to Date object.","devicename":"KNX-Knoten","payloadmeasureunit":"","payloadsubtypevalue":"","knx":{"event":"GroupValue_Write","dpt":"unknown","dptdesc":"","source":"1.3.31","destination":"5/0/0","rawValue":[179,47,52]},"_msgid":"6d687f391d4f022c"}

**Comment by tx73github** [comment]
Sure, 
ETS:
1.3.31 is a JUNG 2225 WS U GPS weather station sending 3 byte DPT 10.001
GA 5/0/0 is also DPT 10.001

I have not importet the ETS CSV into knx-ultimate, but it used to work here:
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/148

As always many thanks and great job !
Regards //t

**Comment by Supergiovane** [comment]
Hi //t
Can you check please, not to have two nodes  5/0/0 in your flows, having different DPT? For example, a node set to 10.001 and another set to 11.001?

**Comment by tx73github** [comment]
Checked 5/0/0 has 46 devices, all are set to 10.001.
Importing the ETS csv solves the issue, since it doesn't try to guess the DPT and either throws an exception or converts wrong.
csv line: "Uhrzeit"	"5/0/0"	""	""	""	"DPST-10-1"	"Auto"

 
> Hi //t Can you check please, not to have two nodes 5/0/0 in your flows, having different DPT? For example, a node set to 10.001 and another set to 11.001?

**Comment by Supergiovane** [comment]
Hi
If you have a knx node set with dpt 10.001, you don’t need the csv.
Only if you have a knx node set in Universal Mode, you need the csv. Do you maybe have a knx node set as universal?

**Comment by tx73github** [comment]
Yes its an universal node that does monitor a few other things as well and also runs a knxviewer node for a quick overview. 
I never imported the CSV before yesterday. The 5/0/0 (10.001) did never throw errors and did convert correctly before,

**Comment by Supergiovane** [comment]
Hi
If no csv, it tries the most common datapoints. It can happen, that it fails. You should ever import a csv file, if you work with the universal node, to obtain real values. It’s too dangerous not to import the csv and rely only in the “i think it is this datapoint” routine. ;-)

**Comment by tx73github** [comment]
clear, when guessing, garbage can happen, and also crap data. but the error ?
BTW: I needed to "clean" the ETS so it propperly imports the fully set DPTs for the CSV import. Wouldn't it be sufficient to know the main group when representing the data as the main holds the datatype ? 
As ETS in auto mode only sets the full DPT when all elements are the exact same type. (Which seems to cause a lot of import issues).

**Comment by Supergiovane** [comment]
Hi
Simply select to import with a fake dpt.
But… Setting the right dpt in ETS is mandatory for a good setup. Just put your headphones, listen “O’ sole mio” at full volume and do the changes!

**Comment by Supergiovane** [comment]
Ps: better the Maneskin. 
Try disabling the knx node in universal mode. The error should gone away.

**Comment by tx73github** [comment]
It went away after CSV import, and yes it took a few hours cleaning 1000 GA's on ETS...
