### ISSUE TITLE
Issue with knxUltimateGlobalContext without a .csv file

### ISSUE THREAD

**Issue by Sebastien-Posca** [Supergiovane/node-red-contrib-knx-ultimate#185]
Hello @Supergiovane ,

First off congrats and thank you for this great module !

I noticed an issue when using, the knxUltimateGlobalContext node without any csv imported.
Indeed, I get the error "knxUltimateGlobalContext: Datapoint not found in CSV for address 0/0/10 in node 59d2815c980ac7f4"

But what I send does contain the dpt: [{address: "0/0/10", dpt:"1.001", payload:msg.payload}]

So I went and look up the code of module, and noticed that there might be a mistake here:

` if (!element.hasOwnProperty("dpt") || element.dpt !== undefined) {`
while I guess it should be: `if (!element.hasOwnProperty("dpt") || element.dpt == undefined) {`

So I changed it locally and it now works great.

Have a nice day !

**Comment by Supergiovane** [comment]
Hi Sebastien,
node-red-contrib-knx-ultimate@1.3.40 is out. 
Thank you again ;-)
