### ISSUE TITLE
KNX Viewer: Sequence of output

### ISSUE THREAD

**Issue by deblasioluca** [Supergiovane/node-red-contrib-knx-ultimate#187]
Dear Supergiovane

I'm trying to log the bus telegrams into a DB. Currently I'm trying to use the simple output of the KNX Viewer for this in Node Red. The issue that I've detected is, that you sort the output before sending the message. This gives me the difficulty to identify the last message. I've done some small changes to the knxUltimateViewer.js, which i thought shold solve the problem:

a) commented out the sorting 
            const aSorted = node.exposedGAs;

            //const aSorted = node.exposedGAs.sort((a, b) => {
            //    if (a.addressRAW !== undefined && b.addressRAW !== undefined) {
            //        return a.addressRAW > b.addressRAW ? 1 : -1;
            //    } else {
            //        return a.addressRAW !== undefined ? 1 : -1
            //    }
            //});

b)  only send the last entry of the node.exposedGAs-Array:

            var last_entry = node.exposedGAs.slice(-1);
            node.send([{ topic: node.name, payload: sHead + sPayload + sFooter }, { topic: node.name, payload: last_entry[0] }]);

It seems to work for a certain while, but then i get the effect, that always the same message is coming through. I was not able to determine where in the knxUltimate-config.js this change is happening, that the last entry in the array is no longer the last telegram received from the bus.

Do you have an ideas how I can get from the KNX viewer node always ONLY the LAST telegram received?

Regards,
Luca

**Comment by Supergiovane** [comment]
Hi
The KNX Viewer node is not intended to be used to do such tings.
Why not simply use a KNX node set as universal node? 
Many users are doing this with success.

**Comment by deblasioluca** [comment]
Hi Supergiovane

Perfect! Solved the issue. Many thanks, that was super!

Have a great weekend!

Luca
