### ISSUE TITLE
After Update: Problem connecting to KNX Bus

### ISSUE THREAD

**Issue by hias-grandl** [Supergiovane/node-red-contrib-knx-ultimate#188]
Hello Supergiovane,

I'm using knx ultimate in my node-red (running in iobroker on a Raspberry Pi 4) and so far it worked great for me - thank you very much for your work!

Today however I updated to v 1.3.41 and now I can't connect to KNX, getting this Error instead:
21:31:42.820 KNXUltimate-KNXEngine:  ipAddressHelper.getLocalAddress:Cannot read property 'toString' of  undefined
21:31:42.820 KNXUltimate-config: Error in  instantiating knxConnection Cannot read property 'toString' of  undefined. Node AppModule

![Screenshot1](https://user-images.githubusercontent.com/106112413/169894950-78f885d3-cb5f-49d0-b04a-c5e083e79963.jpg)

![Screenshot2](https://user-images.githubusercontent.com/106112413/169895192-42af023c-87a2-4d50-bb3b-44b2967545dd.jpg)
Restart of Node red and rebooting the Raspi did not solve the problem.
The IP interface I use is a BABTec AppModule 
https://bab-technologie.com/appmodule/

![Screenshot3](https://user-images.githubusercontent.com/106112413/169895230-9ca78f93-5fc3-49d8-9b63-06f3994000f9.jpg)

Could you please help me to get it working again?

**Comment by Supergiovane** [comment]
Hi
There is an issue in the local ethernet config retrieval. What version of node do you have? Issue a **node -v** command please. 
You can, in the meantime, revert to a previous older version by issuing:
**npm install node-red-contrib-knx-ultimate@1.2.20** (for example, but uou can choose any previous version)

Tomorrow morning i’ll take a look immediately, but for maybe you’re running an old version of nodejs.

**Comment by Supergiovane** [comment]
https://nodejs.dev/learn/install-an-older-version-of-an-npm-package

**Comment by Supergiovane** [comment]
Hi
V. 1.3.42 is out with a possible fix, but unless you tell me what node version you have, i cannot ditch into your issue.
Please try this version.

**Comment by Supergiovane** [comment]
Hi hias
Can you give me a feedback please?

**Comment by hias-grandl** [comment]
Hi, 
and thank you for your quick answers!
(Un-)Fortunately my whole system crashed yesterday after my initial post and I had to restore everything from a earlier backup. 
This "solved" my problem - or more exactly I cannot reproduce it anymore. 
Node version was/is v14.19.0.
Anyway, thanks a lot for your help!
