### ISSUE TITLE
About Scene Node Delay Function

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#189]
Hi

Scene node pause function the unit must be "milliseconds".
Can i set it to minutes or seconds?

Thanks

**Comment by Supergiovane** [comment]
Hi Songh, noce to hear you again. 
let me check it….

**Comment by Supergiovane** [comment]
Hi Songhz
node-red-contrib-knx-ultimate@1.3.43 is out.
Wiki has been updated as well: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/cn-SceneController-Configuration

**Comment by songzh96** [comment]
Get it .
Thanks Again
