### ISSUE TITLE
RBE reset

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-knx-ultimate#191]
Hi supergiovane,

is possible to reset the RBE filter every X hour/day or with some inject payload?

Can be useful in some case like a reboot supervisor or webserver with virtual knx group that need to be re-writed again…

Tnx

**Comment by Supergiovane** [comment]
Hi bolfox
I’ll take a look

**Comment by Supergiovane** [comment]
Hi.
msg.resetRBE = true is your friend here.
Please upgrade to 1.3.44 as soon as you see it in the palette. 
msg.resetRBE works only on the node you send it to.

**Comment by bolfox** [comment]
Wow, super fast and super thanks…

**Comment by bolfox** [comment]
I’have tried, but on reset it send a zero on the bus…

**Comment by Supergiovane** [comment]
You should only send resetRBE, without any payload. 
For example: 

`
return {resetRBE:true};

`

**Comment by bolfox** [comment]
`[
    {
        "id": "f8514536d9359de3",
        "type": "knxUltimate",
        "z": "a8d17054b4db59d8",
        "server": "b5eb0e2f506a67e8",
        "topic": "1/4/246",
        "outputtopic": "",
        "dpt": "",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Studio",
        "outputtype": "write",
        "outputRBE": true,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 1430,
        "y": 200,
        "wires": [
            []
        ]
    },
    {
        "id": "b879c40c1cd02928",
        "type": "inject",
        "z": "a8d17054b4db59d8",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 1230,
        "y": 180,
        "wires": [
            [
                "f8514536d9359de3"
            ]
        ]
    },
    {
        "id": "99863f5199a6520e",
        "type": "inject",
        "z": "a8d17054b4db59d8",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "false",
        "payloadType": "bool",
        "x": 1230,
        "y": 220,
        "wires": [
            [
                "f8514536d9359de3"
            ]
        ]
    },
    {
        "id": "d5aefee80d79b510",
        "type": "inject",
        "z": "a8d17054b4db59d8",
        "name": "",
        "props": [
            {
                "p": "resetRBE",
                "v": "true",
                "vt": "bool"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "x": 1430,
        "y": 100,
        "wires": [
            [
                "f8514536d9359de3",
                "c353a786cf89be1f"
            ]
        ]
    },
    {
        "id": "c353a786cf89be1f",
        "type": "debug",
        "z": "a8d17054b4db59d8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1580,
        "y": 80,
        "wires": []
    },
    {
        "id": "ff0847d1275533a4",
        "type": "inject",
        "z": "a8d17054b4db59d8",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1140,
        "y": 280,
        "wires": [
            [
                "7fe4cde10356f282"
            ]
        ]
    },
    {
        "id": "7fe4cde10356f282",
        "type": "function",
        "z": "a8d17054b4db59d8",
        "name": "",
        "func": "return {resetRBE:true};",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1320,
        "y": 280,
        "wires": [
            [
                "f8514536d9359de3",
                "0b109dbdddfb58ec"
            ]
        ]
    },
    {
        "id": "0b109dbdddfb58ec",
        "type": "debug",
        "z": "a8d17054b4db59d8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1510,
        "y": 280,
        "wires": []
    },
    {
        "id": "b5eb0e2f506a67e8",
        "type": "knxUltimate-config",
        "host": "192.168.0.99",
        "port": "3671",
        "physAddr": "15.15.0",
        "hostProtocol": "TunnelUDP",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error",
        "name": "KNX Gateway",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "50",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "keyringFileXML": "",
        "autoReconnect": "yes"
    }
]`

**Comment by Supergiovane** [comment]
Hi
got it.
Please update to 1.3.45 and try again.

**Comment by bolfox** [comment]
Yes, now it works as expected.

I can contact you on PM for some thanks?

**Comment by Supergiovane** [comment]
<.maxsupergiovane@icloud.com.>

**Comment by bolfox** [comment]
Mail sent, you can remove it
