### ISSUE TITLE
KNXDebugText

### ISSUE THREAD

**Issue by wgumaa** [Supergiovane/node-red-contrib-knx-ultimate#192]
-> id: ee97895d32aa3eca
-> type: knxUltimate-config
-> info: undefined
-> users: 
-> _config: [object Object]
-> host: 192.168.88.XXX
-> port: 3671
-> physAddr: 15.15.22
-> hostProtocol: Multicast
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> statusDisplayLastUpdate: true
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: stop
-> loglevel: error
-> name: KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 50
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: 
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=n+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> credentials: [object Object]
-> infoEditor: [object Object]
-> z:

**Comment by wgumaa** [comment]
Not sure if i am connected to my KNX IP interface or not! Can you check the debug and let me know? 

I am completely new to this. Was able to get knx into HA and now trying to use node red to automate and create scenes and functions.  After some reading all roads pointed to KNX ultimate. But I am also new to Node Red. 

Want to avoid using YAML in HA to create automations etc.

**Comment by Supergiovane** [comment]
Hi
Thank you for using my node. 
Sorry, but i usually don’t help people not having real issues, because my time is very limited and i cannot help everyone on evetything. 
I suggest you to first study knx-ultimate via the wiki page and to ask for help in the HA forum.

**Comment by Supergiovane** [comment]
PS: what you’ve posted is not a log, but the full  configuration, from where isn’t possible to know if you’re connected or not.
