### ISSUE TITLE
DNS Name as Gateway address

### ISSUE THREAD

**Issue by ForumSchlampe** [Supergiovane/node-red-contrib-knx-ultimate#194]
Hey there,

**Is your feature request related to a problem? Please describe.**
My KNX IP Interface has an internal Network Name (DNS), but if i use this DNS name which is usable for Webinterface and other things....it just dont work. So i think DNS Names are not usable in the Extension so my feature request would be. Make it fit for DNS Names

**Describe the solution you'd like**
Support DNS Names as Gateway address instead of only IP addresses

**Describe alternatives you've considered**
Using ip adresses and make fixed ip reservations in DHCP

**Additional context**
![image](https://user-images.githubusercontent.com/5485277/178162020-913ad49f-f52c-4eb4-a3f8-0b1a0cb51b53.png)

Hope it is clear what i mean

**Comment by Supergiovane** [comment]
Hi Schlampe.
Thank you for using my node.
I think to be able to implement the DNS resolver today.
I'll keep you posted. From which Forum do you come from?

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate@1.3.46 is out.
Please star my node if you find it useful.
