### ISSUE TITLE
Send all values to DB (e.g. InfluxDB), without having to define them one by one

### ISSUE THREAD

**Issue by frankvandenhurk** [Supergiovane/node-red-contrib-knx-ultimate#196]
Hi,

Thank you for your hard work, I really like the functionality

**Is your feature request related to a problem? Please describe.**
I would like to send all sensor data (including binary switches) to InfluxDB, without having to define them one by one. (I have around 2000 group adresses)

**Describe the solution you'd like**
Have an output that contains a json for each KNX message on the bus with all the knxUltimateViewer fields

**Describe alternatives you've considered**
I'n now using KNX2MQTT and read from MQTT, but that's an extra service that need to be maintained, I would like it contained in node-red

**Additional context**
-

**Comment by superkalt** [comment]
hi,

some problem ...

first steps to a solution

![image](https://user-images.githubusercontent.com/44277174/184532604-141c18f8-7f2e-4fd6-a214-d8680c6c4cd6.png)

![image](https://user-images.githubusercontent.com/44277174/184532632-b284382c-f8ad-4214-b9c6-ae92db0d904b.png)

**Comment by superkalt** [comment]
i don't want to import ets files. a sql database query should allow a quick adjustment of the data points. Also, all necessary information should be drawn from it, such as visualization or sureveillance. A connection to influxdb is then child's play

**Comment by Supergiovane** [comment]
Hi
Why are you using the viewer node?
Try the device node set i  “universal mode”. 
Please see the wiki about that. 
Importing the ETS file is mandatory to have corrected decoded values.

**Comment by Supergiovane** [comment]
…or you can use the Global Context node and make your own json. Pkease see the wiki also about that.

**Comment by frankvandenhurk** [comment]
Thank you for your quick reply. Already tried using a device node set to “universal mode”, but the output i got from the node in msg.payload contains only the value, not the rest of the fields. 

![image](https://user-images.githubusercontent.com/11859067/184546561-5e7af317-b316-478a-9960-853906432a37.png)

Is there another way to get the data in JSON and use it in another node?

**Comment by Supergiovane** [comment]
Hi
Pick the complete msg object, not only the payload; you can also build your own json using that data.

**Comment by frankvandenhurk** [comment]
How do I do that? Everything that i have used before uses msg.payload as a starting point. I tried logging to file (only logs msg.payload) and debug (doesn't accept msg without addition).

Should I write a function? Can you give me an hint?

**Comment by Supergiovane** [comment]
Hi
First of all, you should learn node-red, all the nodes and uow to write a function. 
You lack some knowledge; as soon as you’re more familiar with nodered, you’ll enjoy all the things much more. 
Unfortunately, i cannot teach all users, otherwise i’ll have no more time for myself :-). 
Please start with some forums, for example knx-user-forum.de
Enjoy Node Red !!

**Comment by frankvandenhurk** [comment]
Tnx, I will dive into writing functions. For anyone who is ready this issue and is wondering how to put the complete message in the payload so you can use it in other nodes, this function works for me

```
var newMsg = { payload: msg };
return newMsg;
```

**Comment by superkalt** [comment]
> Hi Why are you using the viewer node? Try the device node set i “universal mode”. Please see the wiki about that. Importing the ETS file is mandatory to have corrected decoded values.

the constant attempt to use a 3-group address distracts from the actual topic. I create all my KNX projects with free group addresses. only the "VIEWER" node currently brings the "RAW Address"

![image](https://user-images.githubusercontent.com/44277174/184552622-03b79979-fdc0-48b3-bc1f-fc001221478a.png)

**Comment by Supergiovane** [comment]
Understood. KNX-Ultimate supports only the 3-level group address, sorry!
