### ISSUE TITLE
Invalid input pattern in Node Name

### ISSUE THREAD

**Issue by superkalt** [Supergiovane/node-red-contrib-knx-ultimate#197]
Hi

Invalid input pattern in Node Name

![image](https://user-images.githubusercontent.com/44277174/184647367-0e01d476-b28b-4802-98de-21fbdfdb6614.png)

If you use "numbers" you get "Invalid input pattern"

**To Reproduce**

**Expected behavior**
to use Letters and numbers

![image](https://user-images.githubusercontent.com/44277174/184648702-6d672d6f-701f-471f-be79-383e9fbb193c.png)

**Knx-Ultimate Version**
 - 1.3.48

**NodeRed Version**
 - 3.0.2

**Are you running node-red behind homematic, docker or anything similar?**
 - Docker

**Comment by Supergiovane** [comment]
Thank you. I’ll take a look.

**Comment by Supergiovane** [comment]
Hi
knx-ultimate@1.3.49 is out with the fix.
