### ISSUE TITLE
Implement a proprietary data point Griesser Object

### ISSUE THREAD

**Issue by croghostrider** [Supergiovane/node-red-contrib-knx-ultimate#200]
Hii Supergiovane,

are you willing to implement a proprietary data point? Or would you accept a pull request?
It's about the Griesser Object (SunControl Object), used by Griesser and BMS-Solutions.
Here the details from the Object: [Griesser Object.pdf](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/9545625/238-10755_10757-13_Griesser.Object__d.1.pdf)

What is used in Italy for automatic shading with horizon limitation?
Do you know an easy way to make the horizon measurement Yourself?

Thanks.
Regards
Vinko

**Comment by Supergiovane** [comment]
Hi Vinko
If you’re able, i accept pull requests. 
About Horizont: sorry, i’m not an installer so i’ve never used such a function, but you can search on the repositories, if there is a node for that. It should be a pretty standard calculation.

**Comment by croghostrider** [comment]
ok, I will try to create a pull request.

With the Horizon, I don't mean the calculation in which position the blind must be.
I mean consideration of shadows from other houses.
Currently, I am dependent on the company Griesser to create the calculation for each window's individual.
Here is a sample of what I mean:
![image](https://user-images.githubusercontent.com/8603272/189606275-db32739c-d3e2-4ec5-a996-d727d080927d.png)

Griesser creates the calculation with two pictures from each window.
But I could never find any software where I can do the same calculation, I hope you understand want I mean.

**Comment by croghostrider** [comment]
if I emulate the Gateway how I can simulate the receive on a KNX telegram from the bus?

**Comment by Supergiovane** [comment]
Just put a knx node on the flow and send a value to it, using an inject node.
