### ISSUE TITLE
DPT 13.002 wrong

### ISSUE THREAD

**Issue by max-stockhausen** [Supergiovane/node-red-contrib-knx-ultimate#203]
Hello Massimo, thank you for this great node! It´s really well done :)
But I think I found a problem.

**Describe the bug**
DPT 13.002 is shown as "Activation energy"; I think it should be Flow Rate in m³/h.

**To Reproduce**
1. Go to any device node
2. Click on datapoint type
3. Scroll down to 13.002
4. Look at the text

**Expected behavior**
I expect the DPT to be named "Flow Rate in m³/h". I use it for my gas meter, this puts out m³/h in DPT13.002

It is also described on page 43 in this document: https://www.knx.org/wAssets/docs/downloads/Certification/Interworking-Datapoint-types/03_07_02-Datapoint-Types-v02.02.01-AS.pdf

**Screenshots**
![Screenshot 2022-09-24 134137](https://user-images.githubusercontent.com/44135545/192096612-07a46f1f-5aed-4588-8f39-fce69025f322.png)

**Knx-Ultimate Version**
1.3.49

**Are you running node-red behind homematic, docker or anything similar?**
node-red on CCU3

**Comment by Supergiovane** [comment]
Yup! Thank you. I’ll fix it Monday.

**Comment by Supergiovane** [comment]
Fixed in 1.4.0.
