### ISSUE TITLE
DPT 22.101 RHCC_Status

### ISSUE THREAD

**Issue by tx73github** [Supergiovane/node-red-contrib-knx-ultimate#207]
Dear Supergiovane,

I'm use a MDT AKH-0800.02 (heating actor) with DPT 22.101 (RHCC Status, 2 byte).
When the KNX viewer node sees it flying by, it creates the below in the KNX viewer template window as one line, scrambling the entire page.

{"Fault":true,"StatusEcoH":false,"TempFlowLimit":false,"TempReturnLimit":false,"StatusMorningBoostH":false,"StatusStartOptim":false,"StatusStopOptim":false,"HeatingDisabled":false,"HeatCoolMode":true,"StatusEcoC":false,"StatusPreCool":false,"CoolingDisabled":false,"DewPointStatus":false,"FrostAlarm":false,"OverheatAlarm":false,"reserved":false}

I guess for the Viewer just displaying the two bytes would be totall fine.

node-red-contrib-knx-ultimate 1.4.2
Node-RED v2.2.3
RPI 4B 

Many thanks,
//t

**Comment by Supergiovane** [comment]
Hi //t
Noted for v. 1.4.3.
Cheers.

**Comment by Supergiovane** [comment]
V 1.4.3 is out.
If you enjoy it, please STAR my node. Thanks.

**Comment by Supergiovane** [comment]
Thank you Thorsten! I really appreciate your donation.

**Comment by tx73github** [comment]
Works perfect, than you very much !
