### ISSUE TITLE
"KNXUltimate-KNXEngine: Multicast: cannot add membership" - can't tx or rx to/from KNX bus

### ISSUE THREAD

**Issue by greiginsydney** [Supergiovane/node-red-contrib-knx-ultimate#208]
Hi Massimo!

Sorry to trouble you. I'm new to node-red and knx-ultimate, and I can't seem to get it working. I'm hoping I've missed something basic?

**Describe the bug**
I can't send to or receive from the KNX bus.

I've stripped back my initial attempt (to send a 'response' to a 'read') to simply injecting true/false to a light's SW GA, but still no good.

**To Reproduce**
1. I can restart Node-Red and it restarts ok/cleanly.
2. Create a basic flow:

![image](https://user-images.githubusercontent.com/11004787/194227134-ce8b52e1-12f0-4ff0-ab1b-5196068ac94a.png)

(Is this flapping to be expected? The KNX objects cycle between "Connected. On duty" to "Next cycle will reconnect").

3. I'm clicking the Injects for `true` or `false` but the light does not respond, and I don't see it logged in ETS.

**Expected behavior**
The light should light/extinguish and ETS should log it. (Yes, my Group address is otherwise working and KNX logs other interactions).

**Screenshots**

```
[error] 10/6/2022, 5:05:36 PM.643 knxUltimate-config: received KNXClientEvents.error: addMembership EINVAL
[error] 10/6/2022, 5:05:36 PM.646 knxUltimate-config: Disconnected by: addMembership EINVAL
[error] 10/6/2022, 5:05:56 PM.645 KNXUltimate-KNXEngine: Multicast: cannot add membership (Error: addMembership EINVAL
    at Socket.addMembership (node:dgram:841:11)
    at Socket.<anonymous> (/config/node-red/node_modules/node-red-contrib-knx-ultimate/KNXEngine/KNXClient.js:170:30)
    at Socket.onListening (node:dgram:244:7)
    at Socket.emit (node:events:539:35)
    at startListening (node:dgram:173:10)
    at node:dgram:358:7
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'addMembership'
})
[error] 10/6/2022, 5:05:56 PM.648 knxUltimate-config: received KNXClientEvents.error: addMembership EINVAL
[error] 10/6/2022, 5:05:56 PM.650 knxUltimate-config: Disconnected by: addMembership EINVAL
```

**Knx-Ultimate Version**
1.4.3

Node-red version: 13.4.0
Home Assistant:
```
Home Assistant 2022.10.0
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221005.0 - latest
```

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running natively on a Raspberry Pi 4, co-residing with HA.

**Additional context**
I found knx-easy before knx-ultimate, and it worked well for less than an hour (I told you I was new to this), up until it stopped responding, presumably [this bug](https://github.com/atlewee/node-red-contrib-knx-easy/issues/28).

I uninstalled it, installed knx-ultimate, rebuilt my flow, but have not been able to get any response from the KNX bus. Changing the "bind to local gateway" from Auto to eth0 didn't help.

I've power cycled the Pi running HA/Node-Red & my Weinzierl 752 IP Gateway in case ports were still locked up, all to no avail.

Existing (legacy) automations in HA that use KNX are still working fine. In case there was a clash/conflict I disabled that Integration and restarted HA but that wasn't the fix.

I've seen you ask for debug text, so here's that too:

```
-> id: 6e363d0f7e6698c5
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 10.10.16.111
-> port: 3671
-> physAddr: 15.15.22
-> hostProtocol: Multicast
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterface: eth0
-> KNXEthInterfaceManuallyInput: 
-> statusDisplayLastUpdate: true
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: stop
-> loglevel: error
-> name: KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 50
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: undefined
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> changed: false
-> credentials: [object Object]
-> infoEditor: [object Object]
```

Thanks,

&nbsp;<br>
\- Greig.

**Comment by Supergiovane** [comment]
Hi Greig
i need the <redacted by Greig> Host!
`host: <redacted by Greig>`
As this is an internal IP, there's no issues to publish it.

Other than that, please be sure that the Interface Bind option in the gateway node, ist set to "Auto"
<img width="477" alt="Istantanea_06_10_22__08_44" src="https://user-images.githubusercontent.com/37666636/194232825-71ba3ca1-16f7-420b-9000-6ce42565455b.png">

**Comment by greiginsydney** [comment]
Host IP reinstated above under protest. :p

Here's a fresh debug log after changing back to Auto:

```
-> id: 6e363d0f7e6698c5
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 10.10.16.111
-> port: 3671
-> physAddr: 15.15.22
-> hostProtocol: Multicast
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> statusDisplayLastUpdate: true
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: stop
-> loglevel: error
-> name: KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 50
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: undefined
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> credentials: [object Object]
-> infoEditor: [object Object]
-> z: 
```

**Comment by Supergiovane** [comment]
Hi
The host is 10.10.16.111 so you must use "Tunnel UDP" as protocol in the Gateway Node configuration, instead of "Multicast".

**Comment by greiginsydney** [comment]
Aha! OK, changed that but still no good.

**Comment by greiginsydney** [comment]
Actually, I tell a lie: the input/read from the bus looks to be working now. YAY! Halfway there.

**Comment by Supergiovane** [comment]
Hi
Can you export these nodes and paste the code here, so i can see how you configured the settings?
![194227134-ce8b52e1-12f0-4ff0-ab1b-5196068ac94a](https://user-images.githubusercontent.com/37666636/194245797-2baded08-ea14-4896-b404-102b849fc5bf.png)

**Comment by greiginsydney** [comment]
```
[{"id":"520d1670ed8d54cc","type":"knxUltimate","z":"d0fe523914a4373f","server":"6e363d0f7e6698c5","topic":"1/0/1","outputtopic":"","dpt":"1.001","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":660,"y":680,"wires":[[]]},{"id":"4d897d4a93e37297","type":"inject","z":"d0fe523914a4373f","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"true","payload":"","payloadType":"str","x":470,"y":640,"wires":[["520d1670ed8d54cc"]]},{"id":"3f605dc0d38d3565","type":"inject","z":"d0fe523914a4373f","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"false","payload":"","payloadType":"str","x":470,"y":720,"wires":[["520d1670ed8d54cc"]]},{"id":"72a147aad77577e0","type":"knxUltimate","z":"d0fe523914a4373f","server":"6e363d0f7e6698c5","topic":"1/0/1","outputtopic":"","dpt":"1.001","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":480,"y":820,"wires":[["225291948da41c17"]]},{"id":"225291948da41c17","type":"debug","z":"d0fe523914a4373f","name":"debug 6","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":660,"y":820,"wires":[]},{"id":"6e363d0f7e6698c5","type":"knxUltimate-config","host":"10.10.16.111","port":"3671","physAddr":"15.15.22","hostProtocol":"TunnelUDP","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"KNX Gateway","localEchoInTunneling":true,"delaybetweentelegrams":"50","delaybetweentelegramsfurtherdelayREAD":"1","ignoreTelegramsWithRepeatedFlag":false,"autoReconnect":"yes","credentials":{}}]

ooh that's ugly. Is there a way of prettifying it?
```

**Comment by Supergiovane** [comment]
Hi
The inject nodes are wrongly configured.
Do this in the inject nodes 
![Uploading Istantanea_06_10_22__09_58.png…]()

**Comment by greiginsydney** [comment]
Well spotted, thanks.

That's stange. I'd had them sending a `payload` of true before, but they've somehow changed themselves after I previously deleted the Topic. It's come back from the grave and swapped the values.

Alas, still no good though, and the Debug is still not showing inputs.

Do I burn it all to the ground and start again?

**Comment by greiginsydney** [comment]
I also still have that "Next cycle will reconnect" and "Connected. On duty" flapping. Is that expected?

**Comment by Supergiovane** [comment]
> I also still have that "Next cycle will reconnect" and "Connected. On duty" flapping. Is that expected?

The node loose the connection to your KNX gateway. I don't know why, i had you to enable the debug log and to send me that log, but i suspect your KNX Gateway has reached the maximum connection limit allowed. Do you have other devices connecting to it, for example a visualization server, or Home Assistant KNX plugin installed? Home Assistant KNX plugin and KNX nodes for Node-Red, doesn't play well toghether.

**Comment by greiginsydney** [comment]
The only connections are a Gira X1 and ETS on my PC, and the router supports up to 5 connections. The HA KNX Plugin is disabled.

BTW, I found what I think is another error in my Inject nodes: I was sending the string true/false and not the Boolean type. Not that changing it has fixed it.

I'll bounce the KNX network again (which will reset the Router). Back soon.

**Comment by greiginsydney** [comment]
Still no good sorry Massimo.

Rather than keep wasting your time on this one, let me uninstall everything, restart, re-install and see how I go. Back soon.

**Comment by greiginsydney** [comment]
Ok, we're making progress. It doesn't seem to be flapping any more, and I'm seeing incoming Telegrams on the inbound GA monitor. Still unable to tx though.

Here's an export of my reconstituted nodes:

```
[{"id":"2d6a98497d0a66a7","type":"inject","z":"d0fe523914a4373f","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":390,"y":320,"wires":[["8234b10da3146d67"]]},{"id":"1721ca9d5ab5c935","type":"inject","z":"d0fe523914a4373f","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":390,"y":400,"wires":[["8234b10da3146d67"]]},{"id":"8234b10da3146d67","type":"knxUltimate","z":"d0fe523914a4373f","server":"917f788354b5c2ad","topic":"1/0/1","outputtopic":"","dpt":"1.001","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":540,"y":360,"wires":[[]]},{"id":"2cbbf9e10aee9a38","type":"knxUltimate","z":"d0fe523914a4373f","server":"917f788354b5c2ad","topic":"1/0/1","outputtopic":"","dpt":"1.001","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":340,"y":500,"wires":[["187df3d5f20951d6"]]},{"id":"187df3d5f20951d6","type":"debug","z":"d0fe523914a4373f","name":"debug 1","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":580,"y":500,"wires":[]},{"id":"917f788354b5c2ad","type":"knxUltimate-config","host":"10.10.16.111","port":"3671","physAddr":"15.15.22","hostProtocol":"TunnelUDP","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"KNX Gateway","localEchoInTunneling":true,"delaybetweentelegrams":"50","delaybetweentelegramsfurtherdelayREAD":"1","ignoreTelegramsWithRepeatedFlag":false,"autoReconnect":true}]
```

(Thanks for this).

**Comment by greiginsydney** [comment]
OK, this is nuts. The inject buttons have just started working!!!

**Comment by Supergiovane** [comment]
Good.
Is your problem solved?
The next step is to take a look at the wiki, because KNX-Ultimate is very powerful https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki

**Comment by greiginsydney** [comment]
Thanks Massimo, it looks to be working now. I'll let it sit overnight (approaching 8pm here) then play some more tomorrow.

I had a look at the Wiki and that's a hell of a lot of documentation. Huge kudos for putting all that effort into it!

Thanks for your help today too.
