### ISSUE TITLE
node-red-contrib-knx-ultimate causes node-red to crash after KNX IP router change

### ISSUE THREAD

**Issue by peterphilipp** [Supergiovane/node-red-contrib-knx-ultimate#209]
Hi,

i changed my KNX IP Router and now node-red-contrib-knx-ultimate causes node-red to crash.

This ist the log entry that I am getting:

6 Oct 12:59:57 - [info] Flows sind gestartet
[error] 6.10.2022, 13:00:12.24 KNXUltimate-KNXEngine: signature verification failed for keyring xxxx
6 Oct 13:00:12 - [red] Uncaught Exception:
6 Oct 13:00:12 - [error] Error: The password is wrong
    at Object.load (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/KNXEngine/KNXsecureKeyring.js:428:16)
    at /home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:212:36

It would be great if node-red-contrib-knx-ultimate could handle the problem more gracefully e.g. printing out debug message and not crashing node-red.

As a workaroung: How can I change the password? I cannot find a way to do that.

Thank you for that great piece of software!

Best regards,

Peter

**Comment by Supergiovane** [comment]
Hi
Knx secure is not yet implemented. Can i see a screenshot of your gateway configuration node?

**Comment by Supergiovane** [comment]
Hi
Please set the host to use Tunnel UDP instead of TCP

**Comment by peterphilipp** [comment]
Hi, replacing the config node helped, thank you!
