### ISSUE TITLE
UDP socket not freed upon connection failure

### ISSUE THREAD

**Issue by tarag** [Supergiovane/node-red-contrib-knx-ultimate#210]
Hi, I'm using knx-ultimate to log all messages in some knx installations, and it works great!

Still I encountered a strange behaviour on a system where I did not have my flow properly configured. I put a wrong IP for the KNX interface and left node-red to run for almost a month. After some time, the system hosting node-red (Intel NUC with ubuntu 20 LTS, connected to a regular KNX interface) exhibited a strange behaviour, like failing DNS resolutions (`$ nslookup www.google.com`results in `nslookup: isc_socket_bind: address in use`). I found out that the system was starved of UPD connections because node-red was holding onto all the failed connection attempts.

Running the command below showed that 28224 UDP socket remained open by node-red:
```
$ netstat -nvuap | grep node-red | wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
28224
```

**To Reproduce**
1. Create a flow with wrong IP for KNX interface and let it run
2. Run command to show open UDP sockets by node-red: `netstat -nvuap | grep node-red` (Linux)
3. Observe that each new connection attempt results in an increase of the number of sockets

**Expected behavior**
In case of connection failure to the KNX interface, the socket should be freed after a reasonable time.

**Screenshots**
https://user-images.githubusercontent.com/11686092/194582428-c422cb9c-b285-4b06-911d-37eec6fb7b46.mov

**Knx-Ultimate Version**
 - 1.3.49

**Are you running node-red behind homematic, docker or anything similar?**
No, runs directly (handled by supervisor)

**Comment by Supergiovane** [comment]
Hi tarag. 
Thank you. I’ll check that.

**Comment by tarag** [comment]
Thanks for the quick update.

I did test and no longer see the count of open sockets increasing so I'm confident the fix is good.
