### ISSUE TITLE
no send via knxd

### ISSUE THREAD

**Issue by ozett** [Supergiovane/node-red-contrib-knx-ultimate#211]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Hello great developer, i like your node-module.
i would like it more, if i could send to the bus with it.
hope you can help me debugging the problem

**Describe the bug**
i can receive all knx-dtatgrams from the bus,
with the same configuration i can not send from node-red

**To Reproduce**
click true/false on the flow

**Expected behavior**
switch light on, send "True" to knx-bus from node-red

Flow example screenshot
![image](https://user-images.githubusercontent.com/5937811/195987667-ca135889-0278-4738-886d-ba509b4bd7de.png)`

<details>
  <summary>Flow example code</summary>
  <p><code>[
    {
        "id": "c262317e8a297d1c",
        "type": "debug",
        "z": "b4e1524eca956f8f",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 710,
        "y": 1100,
        "wires": []
    },
    {
        "id": "5cf9661752473ae9",
        "type": "knxUltimate",
        "z": "b4e1524eca956f8f",
        "server": "a01c5d80.1bbb78",
        "topic": "1/6/111",
        "outputtopic": "",
        "dpt": "1.002",
        "initialread": "1",
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Essen Erco Esstisch - ein",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "yes",
        "x": 390,
        "y": 1100,
        "wires": [
            [
                "c262317e8a297d1c"
            ]
        ]
    },
    {
        "id": "18c897ebb2420a23",
        "type": "inject",
        "z": "b4e1524eca956f8f",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 150,
        "y": 1100,
        "wires": [
            [
                "5cf9661752473ae9"
            ]
        ]
    },
    {
        "id": "6920c957b15d36eb",
        "type": "inject",
        "z": "b4e1524eca956f8f",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "false",
        "payloadType": "bool",
        "x": 190,
        "y": 1140,
        "wires": [
            [
                "5cf9661752473ae9"
            ]
        ]
    },
    {
        "id": "a01c5d80.1bbb78",
        "type": "knxUltimate-config",
        "host": "224.0.23.12",
        "port": "3671",
        "physAddr": "15.15.16",
        "hostProtocol": "Multicast",
        "suppressACKRequest": true,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": true,
        "stopETSImportIfNoDatapoint": "fake",
        "loglevel": "warn",
        "name": "fo46",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "50",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": true,
        "keyringFileXML": "",
        "autoReconnect": "yes"
    }
]
</code></p>
</details>

**Screenshots**
not much installed in node-red

![image](https://user-images.githubusercontent.com/5937811/195987717-3e10d5f1-105e-4d81-9c6a-c43410823f62.png)

**Knx-Ultimate Version**
knx ultimate v1.4.4
15 Oct 13:43:32 - [info] Node-RED version: v3.0.2
15 Oct 13:43:32 - [info] Node.js  version: v16.17.1
15 Oct 13:43:32 - [info] Linux 5.15.61-v7+ arm LE
15 Oct 13:43:34 - [info] Loading palette nodes

knxd running:
/usr/bin/knxd -e 15.0.0 -E 15.0.100:254 -D -T -R -S -i -b tpuarts:/dev/ttyKNX1

knxd has no version flag.
root@raspberrypi:/home/olaf# knxd --help
Usage: knxd [OPTION...] URL
knxd -- a stack for EIB/KNX
installed via apt

root@raspberrypi:/home/olaf# apt list knxd
Listing... Done
knxd/stable,now 0.14.46-1 armhf [installed]
root@raspberrypi:/home/olaf#

**Are you running node-red behind homematic, docker or anything similar?**

Node-Red running on RaspberryPi
knxd running on the same raspberry pi

many knx devices working well in multicast with knxd
like this other install
![image](https://user-images.githubusercontent.com/5937811/195987977-24b741e4-0e67-4daa-b804-042a7e23dc6c.png)

**Additional context**
i tried different kombinations of IP-Adresses, localhost etc.
but had no luck. the busmonitor doesnt show any sign from this node-red 
```knxtool vbusmonitor1 ip:localhost```

![image](https://user-images.githubusercontent.com/5937811/195988080-1240dc7f-63d4-42d9-870a-6cf99a5ad913.png)

how to trace more?
what additional information do you need ?

**Comment by Supergiovane** [comment]
Hi
I’m not a knxd expert, but i know many users runs it without issue. 
You can try to change the binding from “Auto”, to a specitif eth card, in the gateway config node. 
You should also set the Physical Address of the gateway node, according to the KNXd physical address. 
Other than that, can you take a screenshot of the Inject node? I wish to see how you send the payload. Thanks.

**Comment by Supergiovane** [comment]
..also, please take a look at the troubleshoot here. 
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/5.-FAQ-Troubleshoot

**Comment by ozett** [comment]
i will test you suggestion one by one, even if i did something of that.
now installed "knx-easy" on the same raspberry/node-red and have same behavior of not sending.
maybe seems related to knxd
https://github.com/knxd/knxd/issues/539

**Comment by ozett** [comment]
not working. is the port-number correct?
![image](https://user-images.githubusercontent.com/5937811/195989294-c62231c8-e065-4587-8dad-f0de1225b9f0.png)
injection:
![image](https://user-images.githubusercontent.com/5937811/195989318-ed493cc3-024b-4fc7-9d31-f187586ec000.png)

**Comment by Supergiovane** [comment]
If you receive the telegrams via knxd and you see it on nodered, then the port is correct. 
For the host, use 127.0.0.1

**Comment by ozett** [comment]
no success. weired ...
knxd- option -T is for Tunnel (but UDP stated the readme),
tried this also without success..
(all other devices running fine with multicast on this knxd. but not on this rasperry itself...

![image](https://user-images.githubusercontent.com/5937811/195991682-064e6ea2-0845-461b-840e-2d3d3b1a3883.png)

**Comment by ozett** [comment]
maybe the user running node-red is not allowed to use multicast-join ?
or limited rights to access hardware?

have no clue why node-red modules cannot send to knxd via multicat on the same device.... 🤔

**Comment by Supergiovane** [comment]
I cannot help you in that, sorry!

**Comment by ozett** [comment]
thanks so long.. only for the records:
change log-level of your module to debug, and looked a the node-red-log.
now i see some errors coming up sending with knx-module/flow

```channelID:undefined seqCounter:undefined```

have no clue what that means, will try to google. 
coming from nodered-knx driver? or knxd?


```
bug] 15/10/2022, 17:08:35.288 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:35.294 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:35.538 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:35.542 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:35.988 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:35.992 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:36.191 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:36.194 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:36.540 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:36.544 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:36.741 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:36.744 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:36.892 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:36.895 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:37.93 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:37.96 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:08:37.293 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:00 TPCI:Write
[debug] 15/10/2022, 17:08:37.296 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":128,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/1```

**Comment by ozett** [comment]
i stopped knxd and on my old ubuntu device used for testing my old eibd alone again.
everything works as expected.
knx-sending and multicast works that way, but in the node-red logs the same error. strange

```
ebug] 15/10/2022, 17:21:34.796 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 4.4.23 dstAddress: 1/6/114 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:21:34.922 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:01 TPCI:Write
[debug] 15/10/2022, 17:21:34.923 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:21:35.11 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 4.4.23 dstAddress: 1/6/114 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:21:35.178 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:01 TPCI:Write
[debug] 15/10/2022, 17:21:35.180 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:21:35.263 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 4.4.23 dstAddress: 1/6/114 Host:224.0.23.12:3671
[debug] 15/10/2022, 17:21:35.482 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 15.15.16 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:01 TPCI:Write

```

**Comment by Supergiovane** [comment]
Hi
Seqcounter and channelid are “undefined” in multicast mode, because multicast wont’t use them. 
The log is coming from knx ultimate. 
You have knx devices on line 4 and others on line 15?
Are you sure that’s correct? If knxd does filtering, you may be filtered out if you send from other phyisical addresses.

**Comment by ozett** [comment]
> You have knx devices on line 4 and others on line 15?

yes. runs now for 10 years with the old eibd. maybe knxd is sensible for that?
can fiddle with pys-adresses on knxd... 
maybe... thanks for hinting...

**Comment by ozett** [comment]
strange error: "no nodes connect to the gateway..."
receiving works, but not sending...


![image](https://user-images.githubusercontent.com/5937811/195997752-bc7b001c-a728-4989-aaef-b9b6a6260075.png)

**Comment by ozett** [comment]
very strange.

KNXUltimate-KNXEngine states that it is sending 
AND
receiving, but the lamp does not switch on or off..

```
debug] 15/10/2022, 17:45:08.859 KNXUltimate-KNXEngine: Sending KNX packet: KNXRoutingIndication Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 4.4.222 dstAddress: 1/6/111 Host:224.0.23.12:3671 channelID:undefined seqCounter:undefined Dest:1/6/111  Data:01 TPCI:Write
[debug] 15/10/2022, 17:45:08.864 KNXUltimate-KNXEngine: Received KNX packet: ROUTING: L_DATA_IND, Data: {"_tpci":0,"_apci":129,"_data":null} srcAddress: 4.4.222 dstAddress: 1/6/111 Host:224.0.23.12:3671

```

**Comment by ozett** [comment]
some answer from the knxd developer:
https://github.com/knxd/knxd/issues/539#issuecomment-1279777816

"set a sending flag"... 

what to do? in the module?

**Comment by Supergiovane** [comment]
I never used knxd, sorry! Please ask here: knx-user-forum.de

**Comment by ozett** [comment]
looks like it must be done on the coding-level of the underlying framework for configuration of multicast-looping
https://stackoverflow.com/questions/43109552/how-to-set-ip-multicast-loop-on-multicast-udpconn-in-golang

**Comment by ozett** [comment]
last notes for this, as i am no developer and this is the end of my google-wisdom:

looks to me, that an socket-option at this place could help with multicast on the same host

https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/241bf0f4a250ca190c09b3b80ce972bf452558b7/KNXEngine/KNXClient.js#L164

looks like an nodejs example for this option:

```
// establish connection
        socket.bind({ 'port' : multicastPort, 'exclusive' : false }, function() {
        	socket.setMulticastLoopback(true);
        	socket.setMulticastTTL(128);
```

found here: https://github.com/nodejs/help/issues/1207#issue-313083775

**Comment by Supergiovane** [comment]
Thank for the hint
