### ISSUE TITLE
Node keeps open old connections

### ISSUE THREAD

**Issue by S10VG** [Supergiovane/node-red-contrib-knx-ultimate#212]
Hi dear developers

I use the KNX Ultimate nodes a lot, I think they are amazing.

I noticed, If I have an installation running for some months, and I try to connect to a KNX/IP interface, ETS tells me the device can't accept more connections, all tunnels are used.

Screenhot:
https://user-images.githubusercontent.com/116189110/196737505-83182e21-0dfd-446a-9d19-29dcd1e1a143.png

I use the Zennio ALLinBOX1612 v2 and KNX Ultimate v1.4.3.
The ALLinBOX1612 v2 has 5 tunnels, and the only devices connecting are Node-RED and my laptop with ETS.
It looks like Node-RED doesn't properly close unused connections.

Anyone else has this problem?
Anyone has a solution other than rebooting the KNX/IP Interface?

Kind regards

**Comment by Supergiovane** [comment]
Hi
Please upgrade to 1.4.4
See here: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/master/CHANGELOG.md

Cheers!

**Comment by Supergiovane** [comment]
PS: as for the connection issue you have, i haven’t had any compliant before. Can you ssh to the zennio and see, which IP are currently using the tunnels?
