### ISSUE TITLE
watchdog node

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#213]
Hello Massimo

It's been a long time since I heard from you! 
How are you? 

I use over 10,000 KNX nodes in one project. It works pretty well so far.

Only the watchdog node worries me. It gives out hundreds/thousands of messages when the connection cannot be established. This causes poor performance in the Node-RED. After a while, I also experience an out-of-memory.

Tested with version 1.4.4

Thanks for your support.

Greetings Reto

**Comment by Supergiovane** [comment]
Hi Reto
Thank you. Nice to hear that.
I'll look at the watchdog and see what i can do to avoid connection error repetitions.

The low memory footstep is always my primary concern and i've had no out-of-memory issues so far.
Anyway, the v.1.4.4 fixed an issue related to a problem appearing when you've too many disconnections and the UDP Socket was unable do free the UDP connection, leading (in about 1 month of persistent disconnection) to an "out of UDP port" problem.

About the KNX Secure, we are proceeding, with the help of a skilled cryptographer guy.

**Comment by Supergiovane** [comment]
Hi Reto
fixed in 1.4.5, out in minutes.
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/master/CHANGELOG.md

If you still have issues, let me know.

**Comment by heleon19** [comment]
Hi Massimo
Thank you seems to work
Regards Reto
