### ISSUE TITLE
Unable to debug the power consumption (Load Control node)

### ISSUE THREAD

**Issue by pridi** [Supergiovane/node-red-contrib-knx-ultimate#214]
Hello Max, really great job! I'm trying to see in the debugger the Power consumption, but I cannot, even if in the node I see the values changing (it's for sure reading correctly!). 
I've tried to load also your example (https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/SampleLoadControl), but I still cannot see any value on the debug.
How could it be? Thank you!

**Comment by Supergiovane** [comment]
Hi pridi
If you mean the total power consumption, you should have it written in the output message:

```
msg = {
  "topic": "Home Total Consumption", // Node Name
  "operation": "Increase Shedding" or "Decrease Shedding" or operation reflecting the input message (disable, enable, reset), // Operation
  "device": "Washing machine", // Device shedded
  "ga": "", // Group address of the shedded device
  "totalPowerConsumption": 3100, // Current power consumption
  "wattLimit": 3000, // Limit you set in the config window
  "payload": 1, // Current shedding stage
}
```

Can you please copy your flow and paste it here?

**Comment by pridi** [comment]
Hi Max!I’m very sorry for the late reply but I’ve been out for work. Yes, it’s working! I was completely misunderstanding the functioning of the node.Thanks!Il giorno 22 ott 2022, alle ore 07:36, Massimo Saccani ***@***.***> ha scritto:﻿
Hi pridi
If you mean the total power consumption, you should have it written in the output message:
msg = {
  "topic": "Home Total Consumption", // Node Name
  "operation": "Increase Shedding" or "Decrease Shedding" or operation reflecting the input message (disable, enable, reset), // Operation
  "device": "Washing machine", // Device shedded
  "ga": "", // Group address of the shedded device
  "totalPowerConsumption": 3100, // Current power consumption
  "wattLimit": 3000, // Limit you set in the config window
  "payload": 1, // Current shedding stage
}

Can you please copy your flow and paste it here?
