### ISSUE TITLE
Relative dimming steps fail, logged by ETS as 3.007 $00 - Break

### ISSUE THREAD

**Issue by greiginsydney** [Supergiovane/node-red-contrib-knx-ultimate#216]
Hi Massimo, greetings again from sunny Newcastle, AU.
&nbsp;<br>
**Describe the bug**
I'm trying to implement relative dimming (following your [sample dimming](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Dimming)) guide, but when I send the commands for up or down, the light doesn't respond, and ETS logs 3.007 $00 - Break.

Yes, I'm sending to a relative dimming GA.

Switch on/off commands work fine.

**To Reproduce**
Here's my logic. I've created a Function that determines if the incoming webhook trigger is an on or an off, or if it's a dim message. If it's a dim I convert the literal "up" and "down" to the structure from the dimming sample:

```
[{"id":"dd4e272ad434158c","type":"ha-webhook","z":"8ecb2bb641722c76","name":"Stream Deck webhook","server":"13657eb61b497f93","version":1,"outputs":1,"webhookId":"StreamDeck","outputProperties":[{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"},{"property":"payload","propertyType":"msg","value":"","valueType":"data"}],"payloadLocation":false,"payloadLocationType":false,"headersLocation":false,"headersLocationType":false,"x":420,"y":360,"wires":[["d60653cd4eafadad"]]},{"id":"f73bac010baf3077","type":"debug","z":"8ecb2bb641722c76","name":"debug 14","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":900,"y":540,"wires":[]},{"id":"d60653cd4eafadad","type":"function","z":"8ecb2bb641722c76","name":"function 1","func":"var newMsg = {\n    destination: msg.payload.group\n    };\n\nif (msg.payload.value == 'up')\n{\n    newMsg.payload = { decr_incr: 1, data: 5 }\n}\nelse if (msg.payload.value == 'down')\n{\n    newMsg.payload = { decr_incr: 0, data: 5 }\n}\nelse\n{\n    newMsg.payload = msg.payload.value\n}\n\nreturn newMsg;\n\n\nreturn ({\n    payload: msg.payload.value,\n    destination: msg.payload.group\n    //dpt: \"1.001\",\n    //event: \"GroupValue_Write\"\n});","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":700,"y":500,"wires":[["f73bac010baf3077","68c726a8ac489267"]]},{"id":"68c726a8ac489267","type":"knxUltimate","z":"8ecb2bb641722c76","server":"917f788354b5c2ad","topic":"4/0/1","outputtopic":"","dpt":"","initialread":0,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"WRITE","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":900,"y":440,"wires":[[]]},{"id":"13657eb61b497f93","type":"server","name":"Home Assistant","version":4,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":": ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"default","statusTimeFormat":"h:m"},{"id":"917f788354b5c2ad","type":"knxUltimate-config","host":"10.10.16.111","port":"3671","physAddr":"15.15.22","hostProtocol":"TunnelUDP","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"KNX Gateway","localEchoInTunneling":true,"delaybetweentelegrams":"50","delaybetweentelegramsfurtherdelayREAD":"1","ignoreTelegramsWithRepeatedFlag":false,"autoReconnect":true}]
```

**Expected behavior**
Each time I fire this logic I expect the chosen light to dim up or down a step.

**Screenshots**

![image](https://user-images.githubusercontent.com/11004787/198952838-bc6531fe-9e5d-4387-882a-c514679f5f4f.png)

This is what I see in ETS after I trigger it multiple times:

![image](https://user-images.githubusercontent.com/11004787/198951514-70db1551-6b29-4eff-a680-b2f1d83ee241.png)

**Knx-Ultimate Version**
 - Eg. 1.4.5

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running natively on a Raspberry Pi 4, co-residing with HA.

**Additional context**
I think we're a pretty vanilla config here. Just new and still trying to find my feet.

Thanks,
&nbsp;<br>

\- Greig.

**Comment by Supergiovane** [comment]
Hi Greig
You're passing a "destination" property to the message, but you're using a simple KNX device node.
Please remove the "destination" property in the function window, as you've already set the group address into the KNX Node:

```
var newMsg = {};

if (msg.payload.value == 'up')
{
    newMsg.payload = { decr_incr: 1, data: 5 }
}
else if (msg.payload.value == 'down')
{
    newMsg.payload = { decr_incr: 0, data: 5 }
}
else
{
    newMsg.payload = msg.payload.value
}

return newMsg;

```

In the KNX "WRITE" node, be sure to set the right datapoint

<img width="481" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/198957192-c71f9374-e23a-4d6a-8599-e1eb3f073b3f.png">

Also, be sure to use the right Group Address. In the KNX actuator, you should have a set the 4/0/1 as a "relative dim" group address.

I've setup a simple sample. Copy the code below and attach the function node to your "WRITE" knx node. This allows you to test the things more easily:

<img width="590" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/198957551-a94bb19a-d93e-4839-95cc-52958cbb96f7.png">

`[{"id":"d60653cd4eafadad","type":"function","z":"33206bfafc46cdb4","name":"function 1","func":"var newMsg = {};\n\nif (msg.payload.value == 'up')\n{\n    newMsg.payload = { decr_incr: 1, data: 5 }\n}\nelse if (msg.payload.value == 'down')\n{\n    newMsg.payload = { decr_incr: 0, data: 5 }\n}\nelse\n{\n    newMsg.payload = msg.payload.value\n}\n\nreturn newMsg;\n\n\nreturn ({\n    payload: msg.payload.value,\n    destination: msg.payload.group\n    //dpt: \"1.001\",\n    //event: \"GroupValue_Write\"\n});","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":420,"y":400,"wires":[["f73bac010baf3077","68c726a8ac489267"]]},{"id":"acaad3ac6f8fdaa0","type":"inject","z":"33206bfafc46cdb4","name":"up","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"value\":\"up\"}","payloadType":"json","x":270,"y":380,"wires":[["d60653cd4eafadad"]]},{"id":"0c9f5a38229fe4b8","type":"inject","z":"33206bfafc46cdb4","name":"down","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"value\":\"down\"}","payloadType":"json","x":270,"y":440,"wires":[["d60653cd4eafadad"]]}]`

**Comment by Supergiovane** [comment]
UPDATE: If you wish to pass the destination group address, you need to set the KNX node as Universal mode. Please see the wiki on gitHub, on how to handle the Universal Mode node messages.

<img width="482" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/198958370-16418171-bda4-493d-b044-62869ecddd59.png">

**Comment by greiginsydney** [comment]
Thanks for getting back to me so quickly.

> You're passing a "destination" property to the message, but you're using a simple KNX device node.

I mistakenly thought that was how the device node worked! 

From [Node Configuration](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/2.-Node-Configuration):

> Group Address. Example 0/0/1, KNX Group address to read/write to. It can be overridden by passing an input msg with msg.destination

My goal here was to make a generic flow that interpreted the incoming data/payload and sent the relevant parameters, but it wouldn't follow the override if the GA field was blank, so I populated it with the 'dummy' value 4/0/1. From that point I was able to dynamically inject a msg.destination and THAT was the GA that was sent to KNX.

I've just been able to resolve my issue by hard-coding the dpt type in the function:

```
if (msg.payload.value == 'up')
{
    newMsg.payload = { decr_incr: 1, data: 5 }
    newMsg.dpt = "3.007"
}
else if (msg.payload.value == 'down')
{
    newMsg.payload = { decr_incr: 0, data: 5 }
    newMsg.dpt = "3.007"
}
```

I had mistakenly though that importing the ETS csv file (which I've only just done today) would automatically apply the correct dpt type, but it seems not - or at least not in the way I've been using it.

So am I using a Simple node in a way it's not designed for, because it's working?

\- Greig.

**Comment by Supergiovane** [comment]
Hi, ok understood what you wish to do.
In **Universal Mode,** having the ETS file imported, you don't need to pass the Datapoint, as the node automatically reads it from the ETS file.
Your function is correct and it should work fine. I've tested yet on my system, and it works:

```
let newMsg = {destination: msg.payload.group};

if (msg.payload.value == 'up')
{
    newMsg.payload = { decr_incr: 1, data: 5 }
}
else if (msg.payload.value == 'down')
{
    newMsg.payload = { decr_incr: 0, data: 5 }
}
else
{
    newMsg.payload = msg.payload.value
}

return newMsg;

```
