### ISSUE TITLE
Need DPT 13.1200

### ISSUE THREAD

**Issue by Deeds87** [Supergiovane/node-red-contrib-knx-ultimate#221]
Hi @Supergiovane ,
can you please add the DPT 13.1200 to your Device Node?

For example Lingg&janke meters need it to return 15min or 60min interval values.

Thanks a lot

**Comment by Supergiovane** [comment]
Hi
Are you sure about the datapoint number? Does your actuator handle liquid volumes?

<img width="676" alt="https___www_knx_org_wAssets_docs_downloads_Certification_Interworking-Datapoint-types_03_07_02-Datapoint-Types-v02_02_01-AS_pdf" src="https://user-images.githubusercontent.com/37666636/201525701-69955cb2-36f4-41af-9807-7f2e439fbc14.png">

**Comment by Deeds87** [comment]
Hi,
yes, that's it exactly what i need. It gives me the DELTA of the 15min or 60min water consumption on a communication object from the smart meter.

Sorry but i dont't know if i should open another issue. I see there is missing another DPT (DPT 13.016 - Active Energy MWh) which is important for me. In my case it's for returnig the meter reading of the heat meter.

Thanks for the fast response

**Comment by Supergiovane** [comment]
Hi
node-red-contrib-knx-ultimate@1.4.8 is out with your new datapoints.
