### ISSUE TITLE
Provide a way to retrieve the metadata of all imported GAs

### ISSUE THREAD

**Issue by Alloc86** [Supergiovane/node-red-contrib-knx-ultimate#222]
Hi Massimo,

as we just discussed over on the KNXUF I'd love to be able to get a list of the full metadata imported from the ETS GA export. Currently it seems the only thing we can do is use the Global Context node to get the GAs that were used during the current Node-Red session, but those might not cover rarely used GAs.

E.g. currently I want to automatically compile a list of all GAs which names match certain patterns to do automated operations (like monthly energy measurement polling).

**Describe the solution you'd like**
Maybe a simple new node that outputs that list when it receives a message (or a specific topic).

Cheers,
Chris

**Comment by Supergiovane** [comment]
Hi Chris
done. You now have the full list and the devicename as well.
See here: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-GlobalVariable

**Comment by Alloc86** [comment]
Wow, lightning fast again, thanks 👍 

Just curious, the devicename (which, if it is a new field that has not been there before and therefore would not break backwards compatibility, might be better "gaName" or something, as it's not related to devices :) ) is currently a combination of main group name, middle group name and GA name. Is that how KNXU stores those internally or would it be possible to have individual fields for those three (possibly in addition to the combined one)?

**Comment by Supergiovane** [comment]
Hi
i must leave "devicename" for standardizing pourposes (other nodes uses "devicename" also).
You can simply split the devicename using standard JS string.split() function to separate the group address name from the building structure.

**Comment by Alloc86** [comment]
Already assumed that was the case, but wanted to bring it up just to make sure :)

**Comment by Supergiovane** [comment]
Thank you for your donation!
