### ISSUE TITLE
RBE filter not working for data point 9.008 Parts/million (ppm)

### ISSUE THREAD

**Issue by jimwest256** [Supergiovane/node-red-contrib-knx-ultimate#223]
Hello,

First I want to say thank you for the very useful addon.

But I faced a bug using the KNX device node to send data to KNX bus with the datapoint  "9.008 Parts/million (ppm)" selected.
The rbe filter is not blocking. Even if I round the value before sending. It will still not be blocked. Also wrong value is sent.

1. Create inject node of type number with value 1000.55 
2. Create KNX Device node with RBE-filter selected
3. Connect both nodes
4. Deploy and run
5. RBE filter is not blocking and KNX Device is sending wrong value (1000.32 in my case)

**Expected behavior**
rbe filter should block dublicates and not sending wrong values.

**Knx-Ultimate Version**
1.4.10

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running alone in RaspberryPi

Thanks for your help.

**Comment by Supergiovane** [comment]
Hi Jim
I’m very sorry, but i cannot take a look yet because of Christmas time and i need to handle all the things with my family. 
I’ll take a look at it on 27 Decemver!

**Comment by Supergiovane** [comment]
Hi Jim
This is strange. Look at this. I've done a test **without involving KNX-Ultimate nor Node-Red at all**, only using ETS.
Whenever i write 1000.55, on the BUS appears 1000.32.
I cannot understand. Do you have any clue, why it behaves like this?

https://user-images.githubusercontent.com/37666636/209567525-cd7e6832-6d47-4c4e-9fd6-90a6676ce9d4.mov

**Comment by jimwest256** [comment]
Hi Supergiovane,

Thank you for the feedback. 
This is an interesting find. 

Does the problem only occur with this KNX data type or with floating point types in general? 
I'm not at home at the moment so I can't test it myself.

**Comment by Supergiovane** [comment]
Cannot test it yet. I’ll try tomorrow

**Comment by Supergiovane** [comment]
Hi Ji,
Thi occurs even with 9.004 Lux

https://user-images.githubusercontent.com/37666636/209633376-69a0b3c7-248f-4078-94ec-24ff6df91abd.mov

**Comment by twod-davydemaegt** [comment]
Dear Supergiovane

This is correct, there is no real 0.01 resolution in the KNX standard, they work with encoding: FloatValue = (0,01*M)*2(E).

999.68 corresponds with 36 1A in HEX
1000.32 corresponds with 36 1B in HEX
1000.96 corresponds with 36 1C in HEX
Every value between wil be rounded to the value that is the closest fitting.

page 39:
https://www.knx.org/wAssets/docs/downloads/Certification/Interworking-Datapoint-types/03_07_02-Datapoint-Types-v02.02.01-AS.pdf

With kind regards

Davy

**Comment by jimwest256** [comment]
Thanks Davy for pointing this out.

@Supergiovane Is it possible to get the RBE filter working for Float values?

**Comment by Supergiovane** [comment]
Hi Jim
since the values received from KNX ultimate, is never equal to the value sent to the BUS, it's impossible for now. I could think about a solution, by applying the "round" option not only to the telegrams transmitted to the bus, but also to the telegram received, so the RBE will function.
I've a pair of issue from @twod-davydemaegt  to check, then i'll take it a look.

**Comment by jimwest256** [comment]
Hi Supergiovane,
Thank you very much!
