### ISSUE TITLE
ESF file wrong DPT in 

### ISSUE THREAD

**Issue by twod-davydemaegt** [Supergiovane/node-red-contrib-knx-ultimate#224]
Hi @Supergiovane 

First of all thanks for the wonderfull node! It helps me a lot in my projects!

**Describe the bug**
When I import the DPT trough ESF file there a wrong recognition of the DPT 16.001. When I use it the node recognizes it as 1.001. And it gives then 'null' as output when there is a new value.

**To Reproduce**

1. Make a group address with DPT 16.001
2. Make export with the DPT 16.001 in it
3. import this in the ETS Group Address list import
4. send a value from ETS tot this group address
5. the output of the Universal node will be 'null'

1. do the same with a KNX DEVICE node with the Datapoint type manual filled in
2. send a value from ETS tot this group address
3. Everything works like expected

**Expected behavior**
Recognize the 16.001 type trough the ESF import.

**Screenshots**

**Knx-Ultimate Version**
1.4.10
Node-red version: v3.0.2

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running as deamon on a ubuntu server

**Additional context**
Maybe you can help me with the info what u use in the ESF file, is it the DPT in brackets () or is it the EIS info you use?

**ESF file data:**
<PRESENCE / HOSPITALITY>.<Sold-Unsold>.1/7/129	[01] <PMS> - Firstname (16.001)	EIS 15 'Character String' (14 Byte)	Low	
<PRESENCE / HOSPITALITY>.<Sold-Unsold>.1/7/193	[01] <PMS> - Lastname (16.001)	EIS 15 'Character String' (14 Byte)	Low

**Screenshots:**
ETS send:
![image](https://user-images.githubusercontent.com/64135780/212869539-799134a0-8352-44d1-9196-59a88957c7ca.png)

Nod-red recognition:
![image](https://user-images.githubusercontent.com/64135780/212869929-60262dc0-d16e-40b6-a66b-6f9afa267ae8.png)

**Comment by Supergiovane** [comment]
Hi
ok, let me check that.

**Comment by Supergiovane** [comment]
Hi
i use the "EIS 15" and i checked now, that it works.
Can you please paste here your ESF, so i can test if there's some invalid chars, that produces some isssue?

**Comment by twod-davydemaegt** [comment]
Hi

Can I send you the file in private? I don't like to post it here in public.

Thanks

Davy

**Comment by Supergiovane** [comment]
maxsupergiovane@icloud.com

**Comment by Supergiovane** [comment]
Fixed. Update should appear in the palette soon.
