### ISSUE TITLE
Array to Global

### ISSUE THREAD

**Issue by EIKSEU** [Supergiovane/node-red-contrib-knx-ultimate#225]
Hello thanks for the KNXNode use it and am very satisfied. However, I have now come to a problem, I hope you have a solution for me. I created a list in which you can select several group addresses, these are sent to the global node in a loop of a function node with a variable. The problem is that only the first group address is switched. What can I do against it? thanks

**Comment by Supergiovane** [comment]
Too fast?
Add a delay node and limit the sendout to max 5 msg per second. Then try to increase.

**Comment by EIKSEU** [comment]
Ja danke ich habe schon versucht innerhalb der Schleife 1 Sekunde zu Warten aber ohne erfolg kann das funktionieren?

**Comment by EIKSEU** [comment]
Yes thanks I have already tried to wait 1 second for the loop but without success can this work?

**Comment by Supergiovane** [comment]
I need to see your flow.
Can you paste it here?

**Comment by EIKSEU** [comment]
In the evening

**Comment by EIKSEU** [comment]
Hallo,

`var BWM = flow.get('dataArrayBWM');

for (let i = 0; i < BWM.length; i++) {
var GA = BWM[i].Addr; 

//setTimeout(500)
let GroupAddressesSend = [];
GroupAddressesSend.push({address:GA, payload:true});
global.set("PushToKNX_WRITE",GroupAddressesSend);
msg.payload = BWM;   
}
return msg`

this is my code and only one light is switched on at a time how can I add a waiting time to switch on all selected lights?
In another function, I make a query about switched-on lights that works fine without a timeout.

mfg

**Comment by Supergiovane** [comment]
Why not to use KNX-Ultimate node set in universal mode?
Anyway, do this:

```
var BWM = flow.get('dataArrayBWM');

for (let i = 0; i < BWM.length; i++) {
var GA = BWM[i].Addr;

//setTimeout(500)
let GroupAddressesSend = [];
GroupAddressesSend.push({address:GA, payload:true});
msg.payload = BWM;
}
global.set("PushToKNX_WRITE",GroupAddressesSend);
return msg

```

**Comment by Supergiovane** [comment]
For other things, like delay etc, please ask on the knx-user-forum.de, because i can only strictly handle issues related to my nodes, because my time is limited.
Thanks :-)

**Comment by EIKSEU** [comment]
Hi, Thank You,
for your help was actually too fast I now have the output on one msg. reduced and it works now!
But now I have the problem from #163 again, I can't save any scenes again
Apparently no data point is recognized. Only the name is saved, but with most data points zero and without status. Saving is only possible after a restart as soon as the lights change, the scene node says "null update dev in scene" and it is no longer possible to save. Can this be related to the global node? Can I continue writing on #163?
`-> id: 63a6d23a922229b4
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 10.0.0.41
-> port: 3671
-> physAddr: 15.15.150
-> hostProtocol: TunnelUDP
-> suppressACKRequest: false
-> csv: "Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Licht 4 Essbereich Schalten Ein/Aus"	"0/0/4"	""	""	""	"DPST-1-1"	"Auto"
"Licht 5 Gang Terrasse  Schalten Ein/Aus"	"0/0/5"	""	""	""	"DPST-1-1"	"Auto"
"Licht 6 Wohnbereich Schalten Ein/Aus"	"0/0/6"	""	""	""	"DPST-1-1"	"Auto"
"Licht 7 Indirekte Beleuchtung Schalten Ein/Aus"	"0/0/7"	""	""	""	"DPST-1-1"	"Auto"
"Licht 4 Essbereich Status"	"0/1/4"	""	""	""	"DPST-1-1"	"Auto"
"Licht 5 Gang Terrasse Status"	"0/1/5"	""	""	""	"DPST-1-1"	"Auto"
"Licht 6 Wohnzimmer Status"	"0/1/6"	""	""	""	"DPST-1-1"	"Auto"
"Licht 7 Indirekte Beleuchtung Status"	"0/1/7"	""	""	""	"DPST-1-1"	"Auto"
"Licht 7 Indirekte Beleuchtung Dimmwert Absolut"	"0/2/0"	""	""	""	"DPST-5-1"	"Auto"
"Licht 7 Indirekte Beleuchtung Schrittdimmen"	"0/2/7"	""	""	""	"DPST-3-7"	"Auto"
"Licht 7 Indirekte Beleuchtung Dimmwert Prozent"	"0/2/77"	""	""	""	"DPST-5-1"	"Auto"
"Licht Schalten Ein/Aus"	"2/0/-"	""	""	""	""	"Auto"
"Licht 20 Büro Schalten Ein/Aus"	"2/0/20"	""	""	""	"DPST-1-1"	"Auto"
"Licht 20 Büro Status"	"2/1/20"	""	""	""	"DPST-1-1"	"Auto"
"Zeitserver Störung"	"4/0/0"	""	""	""	"DPST-1-5"	"Auto"
"Alarm/Panik"	"4/0/2"	""	""	""	"DPST-1-1"	"Auto"
"Windgeschwindigkeit"	"4/1/3"	""	""	""	"DPT-9-5"	"Auto"
"Dämmerung"	"4/1/4"	""	""	""	"DPT-9-4"	"Auto"
"Außentemperatur"	"4/1/7"	""	""	""	"DPST-9-1"	"Auto"
"Szene Abwesend Eingang 2"	"4/2/33"	""	""	""	"DPST-1-1"	"Auto"
"Regensensor Status"	"4/3/0"	""	""	""	"DPST-1-1"	"Auto"
"Wetterstation Status"	"4/3/1"	""	""	""	"DPST-1-1"	"Auto"
"Windalarm 1"	"4/4/3"	""	""	""	"DPST-1-1"	"Auto"
"Tag/Nacht Wetterstation"	"4/4/4"	""	""	""	"DPST-1-8"	"Auto"
"Regenalarm"	"4/4/5"	""	""	""	"DPST-1-1"	"Auto"
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 127.0.0.1
-> statusDisplayLastUpdate: false
-> statusDisplayDeviceNameWhenALL: true
-> statusDisplayDataPoint: false
-> stopETSImportIfNoDatapoint: fake
-> loglevel: silent
-> name: Multicast KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 10
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: 
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> changed: false
-> infoEditor: [object Object]
-> z: 
-> credentials: [object Object]`


Kind regards

**Comment by Supergiovane** [comment]
Hi
What version of knx ultimate are you using?
I need please also your flow to be able to test it.

**Comment by EIKSEU** [comment]
Version 1.4.11

`[
    {
        "id": "7378c49edabdf7ec",
        "type": "knxUltimateSceneController",
        "z": "20f8a0057794b681",
        "server": "63a6d23a922229b4",
        "name": "Recal/Save: Szene2",
        "outputtopic": "",
        "topic": "4/2/37",
        "dpt": "1.001",
        "topicTrigger": "true",
        "topicSave": "4/2/36",
        "dptSave": "1.001",
        "topicSaveTrigger": "false",
        "property": "payload",
        "propertyType": {},
        "rules": [
            {
                "topic": "0/0/6",
                "devicename": "Licht 6 Wohnbereich Schalten Ein/Aus",
                "dpt": "1.001",
                "send": ""
            },
            {
                "topic": "0/0/5",
                "devicename": "Licht 5 Gang Terrasse  Schalten Ein/Aus",
                "dpt": "1.001",
                "send": ""
            },
            {
                "topic": "0/0/6",
                "devicename": "Licht 6 Wohnbereich Schalten Ein/Aus",
                "dpt": "1.001",
                "send": ""
            },
            {
                "topic": "0/0/7",
                "devicename": "Licht 7 Indirekte Beleuchtung Schalten Ein/Aus",
                "dpt": "1.001",
                "send": ""
            }
        ],
        "x": 970.0000076293945,
        "y": 302.99999046325684,
        "wires": [
            []
        ]
    },
    {
        "id": "d4ed89d92b46364c",
        "type": "function",
        "z": "20f8a0057794b681",
        "name": "Recall",
        "func": "msg.recallscene=true;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 780,
        "y": 284.99998569488525,
        "wires": [
            [
                "7378c49edabdf7ec"
            ]
        ]
    },
    {
        "id": "faef992cd3555fab",
        "type": "function",
        "z": "20f8a0057794b681",
        "name": "Save",
        "func": "msg.savescene=true;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 783.0000038146973,
        "y": 319.99999141693115,
        "wires": [
            [
                "7378c49edabdf7ec"
            ]
        ]
    },
    {
        "id": "10fc3210e4bd636d",
        "type": "ui_button",
        "z": "20f8a0057794b681",
        "name": "",
        "group": "65e95fe4b66a62f6",
        "order": 2,
        "width": 3,
        "height": 1,
        "passthru": false,
        "label": "{{ msg.label }}",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "payload": "true",
        "payloadType": "bool",
        "topic": "topic",
        "topicType": "msg",
        "x": 660,
        "y": 284.99998569488525,
        "wires": [
            [
                "d4ed89d92b46364c"
            ]
        ]
    },
    {
        "id": "9fd0edc5564a7d4f",
        "type": "ui_button",
        "z": "20f8a0057794b681",
        "name": "",
        "group": "f2aefa84.a9a108",
        "order": 5,
        "width": 0,
        "height": 0,
        "passthru": false,
        "label": "LichtSzene_2 Speichern",
        "tooltip": "",
        "color": "",
        "bgcolor": "",
        "className": "",
        "icon": "",
        "payload": "true",
        "payloadType": "bool",
        "topic": "topic",
        "topicType": "msg",
        "x": 606,
        "y": 317.99999046325684,
        "wires": [
            [
                "faef992cd3555fab"
            ]
        ]
    },
    {
        "id": "4a55d9d2558c0a37",
        "type": "ui_text_input",
        "z": "20f8a0057794b681",
        "name": "",
        "label": "LichtSzene_2",
        "tooltip": "",
        "group": "f2aefa84.a9a108",
        "order": 4,
        "width": "0",
        "height": "0",
        "passthru": true,
        "mode": "text",
        "delay": "0",
        "topic": "topic",
        "sendOnBlur": true,
        "className": "",
        "topicType": "msg",
        "x": 523.9999923706055,
        "y": 252.99997234344482,
        "wires": [
            [
                "5099ea491800795d",
                "5956913efd1240e7"
            ]
        ]
    },
    {
        "id": "5099ea491800795d",
        "type": "file",
        "z": "20f8a0057794b681",
        "name": "",
        "filename": "Szenenname_2",
        "appendNewline": true,
        "createDir": true,
        "overwriteFile": "true",
        "encoding": "none",
        "x": 525.9999961853027,
        "y": 219.9999876022339,
        "wires": [
            []
        ]
    },
    {
        "id": "b5c4cc23dee6fcfb",
        "type": "file in",
        "z": "20f8a0057794b681",
        "name": "",
        "filename": "Szenenname_2",
        "format": "utf8",
        "chunk": false,
        "sendError": false,
        "encoding": "none",
        "allProps": false,
        "x": 370,
        "y": 284.99998569488525,
        "wires": [
            [
                "5956913efd1240e7"
            ]
        ]
    },
    {
        "id": "4899b5dc43430800",
        "type": "inject",
        "z": "20f8a0057794b681",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": "5",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "x": 220,
        "y": 284.99998569488525,
        "wires": [
            [
                "b5c4cc23dee6fcfb"
            ]
        ]
    },
    {
        "id": "5956913efd1240e7",
        "type": "function",
        "z": "20f8a0057794b681",
        "name": "",
        "func": "msg.label =msg.payload;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 530,
        "y": 284.99998569488525,
        "wires": [
            [
                "10fc3210e4bd636d",
                "4a55d9d2558c0a37"
            ]
        ]
    },
    {
        "id": "63a6d23a922229b4",
        "type": "knxUltimate-config",
        "host": "10.0.0.41",
        "port": "3671",
        "physAddr": "15.15.150",
        "hostProtocol": "TunnelUDP",
        "suppressACKRequest": false,
        "csv": "\"Group name\"\t\"Address\"\t\"Central\"\t\"Unfiltered\"\t\"Description\"\t\"DatapointType\"\t\"Security\"\n\"Licht 4 Essbereich Schalten Ein/Aus\"\t\"0/0/4\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 5 Gang Terrasse  Schalten Ein/Aus\"\t\"0/0/5\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 6 Wohnbereich Schalten Ein/Aus\"\t\"0/0/6\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 7 Indirekte Beleuchtung Schalten Ein/Aus\"\t\"0/0/7\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 4 Essbereich Status\"\t\"0/1/4\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 5 Gang Terrasse Status\"\t\"0/1/5\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 6 Wohnzimmer Status\"\t\"0/1/6\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 7 Indirekte Beleuchtung Status\"\t\"0/1/7\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 7 Indirekte Beleuchtung Dimmwert Absolut\"\t\"0/2/0\"\t\"\"\t\"\"\t\"\"\t\"DPST-5-1\"\t\"Auto\"\n\"Licht 7 Indirekte Beleuchtung Schrittdimmen\"\t\"0/2/7\"\t\"\"\t\"\"\t\"\"\t\"DPST-3-7\"\t\"Auto\"\n\"Licht 7 Indirekte Beleuchtung Dimmwert Prozent\"\t\"0/2/77\"\t\"\"\t\"\"\t\"\"\t\"DPST-5-1\"\t\"Auto\"\n\"Licht Schalten Ein/Aus\"\t\"2/0/-\"\t\"\"\t\"\"\t\"\"\t\"\"\t\"Auto\"\n\"Licht 20 Büro Schalten Ein/Aus\"\t\"2/0/20\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Licht 20 Büro Status\"\t\"2/1/20\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Zeitserver Störung\"\t\"4/0/0\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-5\"\t\"Auto\"\n\"Alarm/Panik\"\t\"4/0/2\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Windgeschwindigkeit\"\t\"4/1/3\"\t\"\"\t\"\"\t\"\"\t\"DPT-9-5\"\t\"Auto\"\n\"Dämmerung\"\t\"4/1/4\"\t\"\"\t\"\"\t\"\"\t\"DPT-9-4\"\t\"Auto\"\n\"Außentemperatur\"\t\"4/1/7\"\t\"\"\t\"\"\t\"\"\t\"DPST-9-1\"\t\"Auto\"\n\"Szene Abwesend Eingang 2\"\t\"4/2/33\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Regensensor Status\"\t\"4/3/0\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Wetterstation Status\"\t\"4/3/1\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Windalarm 1\"\t\"4/4/3\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"Tag/Nacht Wetterstation\"\t\"4/4/4\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-8\"\t\"Auto\"\n\"Regenalarm\"\t\"4/4/5\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "127.0.0.1",
        "statusDisplayLastUpdate": false,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "fake",
        "loglevel": "silent",
        "name": "Multicast KNX Gateway",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "10",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "keyringFileXML": "",
        "autoReconnect": "yes"
    },
    {
        "id": "65e95fe4b66a62f6",
        "type": "ui_group",
        "name": "Szenen_Licht",
        "tab": "2f9a533e1eb6a4ec",
        "order": 3,
        "disp": true,
        "width": "6",
        "collapse": false,
        "className": ""
    },
    {
        "id": "f2aefa84.a9a108",
        "type": "ui_group",
        "name": "Szenen",
        "tab": "12c7c5a9.cc3c3a",
        "order": 9,
        "disp": true,
        "width": "6",
        "collapse": false,
        "className": ""
    },
    {
        "id": "2f9a533e1eb6a4ec",
        "type": "ui_tab",
        "name": "Home",
        "icon": "dashboard",
        "order": 1,
        "disabled": false,
        "hidden": false
    },
    {
        "id": "12c7c5a9.cc3c3a",
        "type": "ui_tab",
        "name": "Info",
        "icon": "mi-settings",
        "disabled": false,
        "hidden": false
    }
]`

**Comment by Supergiovane** [comment]
Thanks
Please upgrade to 1.4.12. It will be out in some minutes.
Cheers.

**Comment by EIKSEU** [comment]
Ok Danke.

**Comment by EIKSEU** [comment]
thanks it works again :)
