### ISSUE TITLE
new DPT28.001

### ISSUE THREAD

**Issue by twod-davydemaegt** [Supergiovane/node-red-contrib-knx-ultimate#226]
Hi @Supergiovane

First of all thanks for the wonderfull node! It helps me a lot in my projects!

**Is your feature request related to a problem? Please describe.**
I'm in a project where there is a String send trough the DPT28.001, this DPT uses the utf-8 decoding. Now there is only the 16.000 and the 16.001 wich uses the ascii and latin1 decoding. Now everything works except for the special characters like éèàëê ...

**Describe the solution you'd like**
When I look into you code I see that the DPT's are defined in the dptlib folder, I think the only difference with the 16.xxx datapoint type is the utf-8 decoding and also no fixed length of the buffer, this is dynamicly.

**Describe alternatives you've considered**
1. Now I have made my own translation trough your 999.001 and did the encoding myself.
2. I also made my own dpt28.js file but this is no stable solution for the future.

**Additional context**
![2023-01-17_16-41-00](https://user-images.githubusercontent.com/64135780/212942995-4bcf5795-fe92-43da-a88f-829b67db2bb1.png)

**Comment by Supergiovane** [comment]
Hi
can you post here the code you used for the dpt28.js? This will help me saving time.

**Comment by twod-davydemaegt** [comment]
Hi

I have no experience with a PR, I will check this when I have time so I can do this in the future.

```
/**
* KNXEngine - a KNX protocol stack in Javascript
* (C) 2020-2023 Supergiovane
*/

const knxLog = require('./../KnxLog')

//
// DPT28: ASCII string (variable length)
//

// Write to BUS
exports.formatAPDU = function (value) {
  if (typeof value !== 'string') {
    knxLog.get().error('Must supply a string value. Autoconversion to string')
    try {
      value = value.toString()
    } catch (error) {
      value = 'DPT Err'
    }
  }

  const buf = Buffer.alloc(14)
  if (this.subtypeid === '001') buf.write(value, 'utf-8')
  return buf
}

// Read from BUS
exports.fromBuffer = function (buf) {
  //nog length check because this is variable
  //if (buf.length != 14) {
  //  knxLog.get().error('DPT28: Buffer should be 14 byte long, got', buf.length)
  //  return null
  //}
  if (this.subtypeid === '001') return buf.toString('utf-8')
}

// DPT28 basetype info
exports.basetype = {
  bitlength: 14 * 8,
  valuetype: 'basic',
  desc: '14-character string',
  help:
    `// Send a text to a display
msg.payload = "Hello!"
return msg;`,
  helplink: ''
}

// DPT28 subtypes
exports.subtypes = {
  // 28.001 UTF-8 string
  '001': {
    use: 'G',
    desc: 'DPT_String_UTF-8',
    name: 'UTF-8 string',
    force_encoding: 'UTF-8'
  }
}

**Comment by Supergiovane** [comment]
Added in the upcoming version. Thanks.
