### ISSUE TITLE
too much decimals

### ISSUE THREAD

**Issue by Tobi266** [Supergiovane/node-red-contrib-knx-ultimate#227]
Hi Supergiovane,

i'm using KNX-Ultimate 1.4.12, Node-Red 3.0.2 direct on current RaspberryOS.

After last update KNX-Ultimate an Node-Red im recieving values from KNX with many Decimals, see attached pictures from ETS diagnosis and Node-Red.
Is there anything I can do to prevent this?

Regards
![Node-Red](https://user-images.githubusercontent.com/84711635/215461506-83c3b9b2-0b46-4081-a449-4e4ec2e56b45.png)
![ETS](https://user-images.githubusercontent.com/84711635/215461514-b082be43-4a70-4af0-9d65-fdd6def0a2bd.png)

**Comment by Supergiovane** [comment]
Hi
In the node setting, you can select how many decimals to keep.
<img width="594" alt="Node-RED___192_168_1_16" src="https://user-images.githubusercontent.com/37666636/215476907-c017301e-41d7-4478-b4f3-ade29030cfa0.png">

**Comment by Tobi266** [comment]
Thank you for replying.
My question only, where is the error?
Is the KNX bus giving the wrong output, which I do not see according to the diagnosis or is a bug in KNX Ultimate?

**Comment by Supergiovane** [comment]
Hi
What datapoint are you using?

**Comment by Tobi266** [comment]
Actually i can see this behavior only with Temperatures.
Datapoint ist 9.001

**Comment by Supergiovane** [comment]
Ok, let me check that...
