### ISSUE TITLE
1 level group address

### ISSUE THREAD

**Issue by DominikBaer** [Supergiovane/node-red-contrib-knx-ultimate#228]
**Hi everybody**

**I have an issue with my knx project using 1 level group addresses

**Would you be so kind and add a feature to support 1 level group addresses?
See e.g. "Easy KNX" - a nice App for IoS and Mac, which allows to configure the levels of your group addresses

**Describe alternatives you've considered**
I think there is only one alternative to change the knx project which is a pain in the but and a lot of work.

**Comment by superkalt** [comment]
I already asked that.
the answer was no. But i write some Code that will Change from 3 Level to 1 Level and back

**Comment by DominikBaer** [comment]
Okay understood – I figured it out. Such a function would be great.

I have used Excel to calculate and it worked. Instead of 1026  I passed 0/4/2.

So if you could just add a node which will do the trick, that would be awesome.

 

From: Stefan Obermaier ***@***.***>
Reply to: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Date: Monday, 6 February 2023 at 22:32
To: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Dominik Baer ***@***.***>, Author ***@***.***>
Subject: Re: [Supergiovane/node-red-contrib-knx-ultimate] 1 level group address (Issue #228)

 

I already asked that.
the answer was no. But i write some Code that will Change from 3 Level to 1 Level and back

**Comment by Supergiovane** [comment]
Hi Dominik
As superkalt wrote, knx ultimate is tied with 3 level group address and it’s difficult to touch all the code to adapt to 1 and 2 level.

**Comment by superkalt** [comment]
[node-red-knx-groupchange](https://github.com/superkalt/node-red-knx-groupchange)

**Comment by Supergiovane** [comment]
Thank you superkalt!

**Comment by DominikBaer** [comment]
Herzlichen Dank Stefan

 

Das hat prima funktioniert. Denke die KNX Association könnte problemlos in ETS so ein Feature einbauen, dass es ermöglicht die 1 stufigen in 3 stufige Gas zu konvertieren.

Ich versuchs jetzt mal noch mit der Projektdatei. Vielleicht gelingt es mir.

 

Gruss

Dominik

 

From: Stefan Obermaier ***@***.***>
Reply to: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Date: Tuesday, 7 February 2023 at 07:20
To: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Dominik Baer ***@***.***>, Author ***@***.***>
Subject: Re: [Supergiovane/node-red-contrib-knx-ultimate] 1 level group address (Issue #228)

 

node-red-knx-groupchange

**Comment by superkalt** [comment]
das kannst du dir sparen! ich habe eine Funktion mit einer KNX Datenbank. 1 Gruppig => Datenbank suche => dort sind alle Dinge gespeichert die du brauchst => und schon gehts weiter. Das ganze läuft automatisch in einen MQTT Broker dann gehts mit Telegraf automatisch in Influx.
