### ISSUE TITLE
Telegram lost when writing multiple telegrams simulations

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#23]
Hi Supergiovane

I’m using Node-RED V1 with the new asynchronous flow processing, where the node messages are passed by “setImmediate”. When I try to send multiple KNX write telegrams simulations often one of them is not written to the KNX-Bus. When I add an additional delay of 50ms for each telegram, then the behaviour is better. 
Do you have an Idea to ensure all telegrams are written, even I pass them simulations to your KNX node?

Many thanks for your support!
Heleon19

**Comment by Supergiovane** [comment]
Hello Heleon19,
How do you assume, that the telegrams are not written? Do you monitor the KNX Bus using ETS? That's important to know. Thanks.

**Comment by heleon19** [comment]
Yes I'm using ETS for monitoring the Bus. I had the problem yesterday with an RGB LED, one of the colors was not written. I do not have access to that system right now, therefor I did an other test with the system at my home.

Actualy here I'm using an Node-RED version below V1, therefor I prepared a function node for simulating the pehavior.

When I trigger the flow below, sometimes telegrams are missing, as you can see at the print screen of the GroupMonitor.

`[
    {
        "id": "c81a089b.504928",
        "type": "inject",
        "z": "ea717d77.07fe",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 95,
        "y": 105,
        "wires": [
            [
                "69ee379c.bce698"
            ]
        ]
    },
    {
        "id": "69ee379c.bce698",
        "type": "function",
        "z": "ea717d77.07fe",
        "name": "setTimeout 0ms and send 5 messages",
        "func": "\nsetTimeout(() => {\n    node.send(msg);\n}, 0);\nsetTimeout(() => {\n    node.send(msg);\n}, 0);\nsetTimeout(() => {\n    node.send(msg);\n}, 0);\nsetTimeout(() => {\n    node.send(msg);\n}, 0);\nsetTimeout(() => {\n    node.send(msg);\n}, 0);",
        "outputs": 1,
        "noerr": 0,
        "x": 330,
        "y": 105,
        "wires": [
            [
                "3e9a8b3f.9f2f24"
            ]
        ]
    },
    {
        "id": "3e9a8b3f.9f2f24",
        "type": "knxUltimate",
        "z": "ea717d77.07fe",
        "server": "39ebf231.b0aebe",
        "topic": "1/0/0",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "x": 560,
        "y": 105,
        "wires": [
            []
        ]
    },
    {
        "id": "39ebf231.b0aebe",
        "type": "knxUltimate-config",
        "z": "",
        "host": "192.168.2.250",
        "port": "3671",
        "physAddr": "1.1.250",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false
    }
]`

Example flow, sends 5 messages in parallel:
![image](https://user-images.githubusercontent.com/10326318/70982635-9b032500-20b7-11ea-9e5a-39578dd6155f.png)

Missing telegrams:
![image](https://user-images.githubusercontent.com/10326318/70982555-7dce5680-20b7-11ea-8fee-fc26d213418b.png)


Would the connection option minimumDelay help? Is the knxjs library able to process a queue of write telegrams?

```
// wait at least 10 millisec between each datagram
  minimumDelay: 10,
```

**Comment by heleon19** [comment]
And the same test without setTimeout:

`[
    {
        "id": "2e9996ca.cac28a",
        "type": "function",
        "z": "ea717d77.07fe",
        "name": "send 5 messages",
        "func": "node.send([msg, msg, msg, msg, msg]);",
        "outputs": 5,
        "noerr": 0,
        "x": 270,
        "y": 180,
        "wires": [
            [
                "3e9a8b3f.9f2f24"
            ],
            [
                "3e9a8b3f.9f2f24"
            ],
            [
                "3e9a8b3f.9f2f24"
            ],
            [
                "3e9a8b3f.9f2f24"
            ],
            [
                "3e9a8b3f.9f2f24"
            ]
        ]
    }
]`

![image](https://user-images.githubusercontent.com/10326318/70985632-b3c20980-20bc-11ea-8c88-30ce92558933.png)
![image](https://user-images.githubusercontent.com/10326318/70985705-d6ecb900-20bc-11ea-88c7-c5aa4c20a204.png)

**Comment by heleon19** [comment]
And here with `return [msg, msg, msg, msg]`

All variants show the same behavior.

![image](https://user-images.githubusercontent.com/10326318/70986044-727e2980-20bd-11ea-8e29-f0749e4d7162.png)

**Comment by Supergiovane** [comment]
Hello
Version below 1 should not cause any issue, as well as V1.02 (i'm using this version without issues.
Your settimeout code are all set to zero, so the messages are sent all at the same time.
As i can see, you're using an IP Interface. If the IP Interface is capable of multicast routing, please use the multicast KNX address 224.0.23.12 instead of the interface's IP 192.168.2.250.
Multicast routing is way better.
If your IP Interface is not capable of Multicast routing, please try to activate the "Suppress the ACK request", as per the image below:

![Node-RED](https://user-images.githubusercontent.com/37666636/70986135-9e011400-20bd-11ea-8342-46342c8679d2.png)


Be aware, that KNX uses UDP in any cases. If your ethernet switch has some other works to do (other traffic), it can be possible that it loses some UDP packets. 
Be sure to have also disabled any multicast flood protection on the ethernet switches (if any), because you are really "flooding" the LAN with UDP packet.

The right procedure to "flood" a KNX node with telegram, is to add a delay in front of it:
![Node-RED](https://user-images.githubusercontent.com/37666636/70986753-cccbba00-20be-11ea-9b96-cfc756ef3da6.png)

Please import this code below, and put it in front of the knx node, as you can see in the image above. Then try again and let me know.

`[{"id":"f8948492.880cd8","type":"delay","z":"eb97b356.202078","name":"","pauseType":"delay","timeout":"150","timeoutUnits":"milliseconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":290,"y":360,"wires":[[]]}]`

**Comment by heleon19** [comment]
Unfortunately, my interface can't multicast. I have activated the "Suppress the ACK request", no change here either. 

The delay of 150ms for each message will certainly help to reduce the number of errors. For a single RGB logic this would certainly help a bit. So what is whom do several RGB logics want to send at the same time? Shouldn't the limitation already be implemented in the KNX Lib? From the knxjs API description I saw that there is a corresponding option, what if you could set this limitation in the config node?

The proposed delay didn't work, so I changed it to one below:
`[
    {
        "id": "bd7e9553.41f628",
        "type": "delay",
        "z": "ea717d77.07fe",
        "name": "",
        "pauseType": "rate",
        "timeout": "150",
        "timeoutUnits": "milliseconds",
        "rate": "1",
        "nbRateUnits": "0.15",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "x": 625,
        "y": 105,
        "wires": [
            [
                "3e9a8b3f.9f2f24"
            ]
        ]
    }
]`

**Comment by Supergiovane** [comment]
Yes, sorry, you're right. The code i pasted was wrong.
Be aware that the KNX specs, suggests up to max 50 messages per seconds, that means that the min delay is 20millisecs, not 15milliseconds.
V 1.1.16 has a delay of 60millisecs added and will be out, i think, in about 30 minutes.
It handles all delay by his own, so you don't need the delay node anymore.
Please let me know if you'll have other issues.
Cheers and thank you to use my node!

**Comment by heleon19** [comment]
Thank you, for this simple test it works. I'll test it on the other system tomorrow, and report to you.

**Comment by waldbaer** [comment]
I am facing the same issue.
Therefore I created this test flow using the new knx-ultimate version 1.1.16.

`[{"id":"7d459a68.9a213c","type":"function","z":"8e164a6.71881b8","name":"gen outputs","func":"let outputs = []\n\nfor(let i = 0; i<0x80; i++) {\n    outputs.push({payload: i});\n}\nreturn [ outputs ];","outputs":1,"noerr":0,"x":370,"y":200,"wires":[["13f35500.61af9b","df0cc0cf.ebe25"]]},{"id":"5a20ca24.cfe83c","type":"inject","z":"8e164a6.71881b8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":200,"wires":[["7d459a68.9a213c"]]},{"id":"df0cc0cf.ebe25","type":"knxUltimate","z":"8e164a6.71881b8","server":"e307417e.b4e0c","topic":"2/2/2","dpt":"5.004","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":false,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":false,"inputRBE":false,"x":550,"y":200,"wires":[[]]},{"id":"e307417e.b4e0c","type":"knxUltimate-config","z":"","host":"192.168.0.40","port":"3671","physAddr":"15.15.22","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false}]`

When I trigger the flow the first time I see all messages in the KNX trace with the payloads 0x00..0x80.
But with every next trigger of the flow no more message are transmitted on the KNX bus. Only a re-deploy currently helps.
As interface I am using knxd with a TUL stick running on a rpi.

**Comment by Supergiovane** [comment]
Why you are trying to flood your poor knx bus?
The loop protection prevents exactly this. 
You maybe have other 2/2/2 nodes somewhere, linked to another 2/2/2?
Then please use a real knx/eth ip router, not a knxd.

**Comment by waldbaer** [comment]
The provided flow is just a test scenario.

The real use case was implementation of lighting scenes like 'all lights off' on node-red. In this case I need around 50 messages on the bus. I know that this could also be done by programming the knx devices and use a single knx message. But for prototyping and flexibility reasons it should be possible to do. 


What's the big difference between knxd and 'real' hardware routers?

**Comment by Supergiovane** [comment]
Hello
with knxd have had some issue in the long run with hangs and stability issues.
The connection between Ethernet and KNX BUS is the most important things and should be done by a dedicated IP Router.
Please split your sequence of 50 messages in two or three steps, separated with at least 1 second each step, or put, just behind your function, a delay node and set, for example, max 1 telegram each 150 msecs.
This avoids flooding the bus. If you don't do so, the auto flood protection of the knx-ultimate kicks in, to avoid flooding your KNX Bus, loosing KNX datagrams and to make datagrams of your real KNX devices not timing out.

Let me know.

**Comment by waldbaer** [comment]
I agree that nobody should flood the 9.6kBaud KNX bus with hundreds of messages.
But for me the error message "loop prevention" is a little bit misleading. Better would be a error message like "overload situation detected".

**Comment by Supergiovane** [comment]
.. but... wait a moment. 
You’re incurring in a loop protection, not in a flood protection. 
If you need to switch all lights off, you need to use  knx-ultimate as a universal node and to pass the group addres you want to switch off, along with the payload. 
In your sample, you set only one node with 2/2/2. 
If a loop protection kicks in, it means that you have two node with the same group address, link together, even if there are other nodes between. 
When it kicks in, if you go through you flows, you’ll see exactly where it happens, because the affected node will have a status indicating that the node has been disabled. 
Please verify that again.
