### ISSUE TITLE
Node-RED SubFlow Environment variables

### ISSUE THREAD

**Issue by mw-nfi** [Supergiovane/node-red-contrib-knx-ultimate#231]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**
Hi,
i will control my devices with subflows. I've created a subflow with adresses of my devices. How can i set the ${evirontment_Variable} to GroupAddress without setting a dynamic device with polling all other values?

Thanks!

**To Reproduce**
1. Create a Subflow
2. Paste KNX Device for readings
3. Define an Envrionment variable
4. inject Node. 
5. Nothing happend.

**Expected behavior**

**Screenshots**

**Knx-Ultimate Version**
 - latest

**Are you running node-red behind homematic, docker or anything similar?**
 - docker running on a standalone server

**Additional context**

**Comment by Supergiovane** [comment]
Hello
Please see here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/GlobalVariable

**Comment by mw-nfi** [comment]
Thanks for your quick reply!
In the example I see that I have to set the groups anyway. Is there also a way to write all addresses from the esf file automatically?

Kind regards

**Comment by mw-nfi** [comment]
I have found my error. Multicast could not find any addresses.
Thank you very much!
Kind regards
