### ISSUE TITLE
KNX-Ultimate Scene Controller

### ISSUE THREAD

**Issue by gtnscebba** [Supergiovane/node-red-contrib-knx-ultimate#234]
Hi Supergiovane,
in my house I have a KNX system with which I also manage some scenarios.

Running them directly from KNX, they work perfectly. I integrated them into my NodeRed project using KNX-Ultimate Scene Controller node (see attached JSON).

When I call them from the NR dashboard, "Recall Scene" appears on the debug, but no command arrives on the KNX bus and therefore the scenarios are not executed.

Surely I'm doing somet

Thanks for support

[NR_Scenari_flows.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/10958139/NR_Scenari_flows.zip)

**Comment by Supergiovane** [comment]
Hi!
You're are mistaking scene controller node with scene caller node.
<img width="686" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/224731717-05e2b8ee-6b2e-4eeb-bd3e-86f71a990927.png">

The scene controller node act as stand alone scene controller and you need to put all the device you want to control, in the listbox, while the other, simply call a scene from a KNX scene device.
Please see here and use the proper scene caller node: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Control-a-scene-actuator
