### ISSUE TITLE
German "Umlaute" - special signs are not supported in KO list

### ISSUE THREAD

**Issue by NilsRo** [Supergiovane/node-red-contrib-knx-ultimate#235]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Hi, its a small issue but there seems a codepage issue as german umlaute are ignored if imported from esf file. As it is a description special signs should be supported in my opinion.

**Describe the bug**
special signs are ignored in ETS KO (esf) upload

**To Reproduce**
Add a special sign in the ETS upload

**Expected behavior**
Special signs should be visible and searchable

**Screenshots**
![image](https://user-images.githubusercontent.com/51311453/226168631-8555cc3c-cc70-4fbb-ab89-fbc2a109fa08.png)
![image](https://user-images.githubusercontent.com/51311453/226168634-0abf22e7-e039-4948-91c6-16b770949620.png)

**Knx-Ultimate Version**
 - 1.4.14

**Are you running node-red behind homematic, docker or anything similar?**
 - docker in debian

**Additional context**
nothing to add

**Comment by Supergiovane** [comment]
Hi
I’ll take a look tomorrow! Thanks for the hint

**Comment by Supergiovane** [comment]
Hi
can you please paste here your ESF ? Thanks,

**Comment by Supergiovane** [comment]
I mean.... **the ESF coming from ETS**, not the ESF pasted in knx-ultimate. Thanks.

**Comment by Supergiovane** [comment]
Hi
Should be fixed now. Please update to node-red-contrib-knx-ultimate@1.4.15

**Comment by NilsRo** [comment]
Yes, fixed. Thanks a lot!
