### ISSUE TITLE
Node-RED crashes when IP Router is not connected

### ISSUE THREAD

**Issue by 0per8or** [Supergiovane/node-red-contrib-knx-ultimate#236]
Hello,

first of all, thanks for this great plugin! I used it for a while without any problems but since my IP Router broke (sent in for repair), my Node-RED instance crashes regularly.

**Describe the bug**
Node-Red crashes after 10 - 20 minutes when no IP Router is not connected. Logfile excerpt:

Mar 26 13:38:40 nared1 Node-RED[465038]: [error] 3/26/2023, 1:38:40 PM.421 knxUltimate-config: received KNXClientEvents.error: Connection timeout to 192.168.11.11:3671
Mar 26 13:38:40 nared1 Node-RED[465038]: [error] 3/26/2023, 1:38:40 PM.424 knxUltimate-config: Disconnected by: Connection timeout to 192.168.11.11:3671
Mar 26 13:38:56 nared1 Node-RED[465038]: 26 Mar 13:38:56 - [red] Uncaught Exception:
Mar 26 13:38:56 nared1 Node-RED[465038]: 26 Mar 13:38:56 - [error] UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "{"jsonrpc":"2.0","error":{"code":-32500,"message":"Application error.","data":"SQL statement execution has failed \"DELETE FROM sessions WHERE status='1' AND userid='3'\""},"id":"0.42880816426913815"}".

**To Reproduce**
1. Disconnect KNX IP Router / IP Interface
2. Wait for Node-RED crash

**Knx-Ultimate Version**
 - 3.0.2

**Are you running node-red behind homematic, docker or anything similar?**
- Ubuntu 22.04 LXC container running on Proxmox host

**Additional context**
Can you catch this exception? Or is it possible to check if the IP Router is up before trying to establish a connection to it?

**Comment by Supergiovane** [comment]
Hi
This exception cones from another node (node id: 0.42880816426913815) and refers to a SQL query. It’s unrelated to knx-ultimate. 
You should check your flow and look at that node id.

**Comment by Supergiovane** [comment]
PS: the latest version of knx ultimate is Version 1.4.15. 
You wrote 3.0.2. Where have you read that number? Thanks.

**Comment by 0per8or** [comment]
Sorry, 3.0.2 is the Node-RED version. I am using 1.4.15 of KNX Ultimate.
I will check the Node ID now.

**Comment by 0per8or** [comment]
I did not find the id in Node-RED. Interestingly the id in the exception changes every time.

But it looks you are right and the issue is caused by another plugin. I disabled some other nodes of the node-red-contrib-zabbix plugin yesterday and it did not crash so far.

Thanks anyway for your support.
