### ISSUE TITLE
Roller Shutter engine stop event

### ISSUE THREAD

**Issue by gtnscebba** [Supergiovane/node-red-contrib-knx-ultimate#239]
I am trying to manage from Nodered, through KNX Ultimate, the absolute position of the shutters with actuators that do not provide the absolute position.
Everything works perfectly both in the event that the movement of the roller shutter is generated by Nodeded and when it is generated by physical KNX buttons.
There is an event, however, that KNX Ultimate does not return me and therefore in these case the routine calculates badly the percentage of opening of the roller shutter.
The event is the stop of the roller shutter when to moto reach the end of the race (upper and lower). In this case I don't know when the engine stopped and therefore I cannot calculate the correct percentage.
The only way I would have in these cases is the management of the maximum time of movement, but before writing a lot of code I wanted to try to understand if there was a more "cunning" way to do it.
Do you have any advice, without changing the actuators?  :-)

**Comment by Supergiovane** [comment]
Hi
I doubt that the actuator does send “stop” when it reaches the limits. 
I have also had such issue and, after many struggeling, i ended up by replacing the actuators with a simple Gira one, that have the absolute position. 
Why, the hell, a KNX producer does not implement the absolute status, is beyond my judgment. 
Do you a favor… buy a good actuator and forgot about these problems. 
I know, there should be some new motor, with integrated KNX command and precise position. 
Insteadnof an actuator, you could take a look at these.

**Comment by gtnscebba** [comment]
Thanks a lot.
Ciao

**Comment by Supergiovane** [comment]
Ciao Gaetano 💪🏻
