### ISSUE TITLE
error during installing node-red-contrib-marantz-http

### ISSUE THREAD

**Issue by StassyWi** [Supergiovane/node-red-contrib-knx-ultimate#24]
Hello,

During installing node-red-contrib-marantz-http I result in the following error;

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'node-red-contrib-marantz-http'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose npm-session e7dec09cc1e4bbdd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-marantz-http 207ms (from cache)
8 silly pacote tag manifest for node-red-contrib-marantz-http@latest fetched in 235ms
9 timing stage:loadCurrentTree Completed in 255ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule node-red-contrib-marantz-http@0.1.1 checking installable status
17 silly fetchPackageMetaData error for marantz-avr@git+https://github.com/estbeetoo/marantz-avr.git Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/estbeetoo/marantz-avr.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/machina 52ms (from cache)
19 silly pacote range manifest for machina@^1.1.2 fetched in 56ms
20 silly resolveWithNewModule machina@1.1.2 checking installable status
21 timing stage:rollbackFailedOptional Completed in 1ms
22 timing stage:runTopLevelLifecycles Completed in 357ms
23 verbose stack Error: spawn git ENOENT
23 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
23 verbose stack     at onErrorNT (internal/child_process.js:456:16)
23 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
24 verbose cwd C:\Users\wimtechniek\AppData\Roaming\npm
25 verbose Windows_NT 10.0.18362
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-red-contrib-marantz-http"
27 verbose node v12.14.0
28 verbose npm  v6.13.4
29 error code ENOENT
30 error syscall spawn git
31 error path git
32 error errno ENOENT
33 error enoent Error while executing:
33 error enoent undefined ls-remote -h -t https://github.com/estbeetoo/marantz-avr.git
33 error enoent
33 error enoent
33 error enoent spawn git ENOENT
34 error enoent This is related to npm not being able to find a file.
35 verbose exit [ 1, true ]

cmd is started as Administrator

Any idea what the reason can be?

Tnx in advace Wim Stassyns

**Comment by Supergiovane** [comment]
Hello
Please ask to the node-red-contrib-marantz-http developer.
