### ISSUE TITLE
Write command not working

### ISSUE THREAD

**Issue by simonegaffuri** [Supergiovane/node-red-contrib-knx-ultimate#240]
Hi

i've a system running on RPi connected to 2 separated KNX network with independent IP interfaces (siemens). both are same type.
i've implemented two independent flow where i've added a KNX global context node each, connected to the respective gateway.

the configuration is exactly the same but i cannot write values on KNX bus from the first one while it's working perfectly on the second one.

I've tried to send a write command on the first network using an object KNXDevice and it's working fine. only with the Global context node doesn't.

KNXZero node (which doesn't work)
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/40138826/76a9bf64-b2f0-4702-9cbb-81954ce5363b)

KNXuno node that works
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/40138826/e3466bdb-4735-4c36-b109-21741c0b0f4c)

i've a function recalled every 100ms with the following lines
GroupAddressesSend_P0.push({ address: "3/2/35", dpt: "5.001", payload: LEDIntensity }); 
global.set("KNXzero_WRITE", GroupAddressesSend_P0);
with this output
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/40138826/4afb9f5d-4c2f-4cdb-a9f2-9a06eee66c53)
but there are no messages on the KNX bus.

i've tried the KNX device node with the same output is working 
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/40138826/31fe9cf0-cc73-400b-aff6-2ed02f72631a)

btw all the READ functions are working very good on both!

do you have any idea? 
can i have two object using the write functions (independent)?

thanks for your help!
regards,
Simone

**Comment by Supergiovane** [comment]
Hi
Can i see the config window screenshot of KNX_Gateway_P0 and KNX_Gateway_P1?

**Comment by Supergiovane** [comment]
Hi
Nevermind.
It should be fixed in V. 1.4.16 out now!
Cheers.
PS: please STAR my node. Thank you.
Let me know.

**Comment by simonegaffuri** [comment]
it works!
thank you!
*starred
