### ISSUE TITLE
Feature - Allow updating the group export list from script or local file

### ISSUE THREAD

**Issue by jackie-t** [Supergiovane/node-red-contrib-knx-ultimate#242]
Hey,

First of all, KNX Ultimate works extremely well. There's just one thing that'll make things a little bit easier, and more convenient - currently, whenever any group address on my KNX installation changes, I have to export the file, open the file I just exported, copy everything, log into nodered, go to the configuration node page, locate KNX Ultimate, double click, scroll down, uncollapse the group address field, select all, paste the content I copied earlier, click Update, click Deploy.

That's a lot of steps to be performed every time something changes, so a lot of the time, I just don't bother. Which means, of course, I don't get the updated group addresses in nodered, nor on mqtt (I use KNX Ultimate to forward everything KNX to mqtt), until I update KNX Ultimate once again.

It would make it way easier, if KNX Ultimate could read a local file (containing the exported group addresses), or if I could somehow pass it the updated group addresses over a script. I know I could probably just patch the JSON in its configuration, but that's incredibly hack-ish and probably also quite prone to breakage. An official way would be very helpful :)

**Comment by Supergiovane** [comment]
Hi Jackie
one note on that: where do you store your exported ETS file? On a remote PC, or on the machine where you run node-red?

**Comment by Supergiovane** [comment]
Starting from version 1.4.18, you can also simply enter the path to the file in this field (e.g.: /home/pi/mycsv.csv).

Please STAR my node and have a good weekend.

**Comment by jackie-t** [comment]
Works great, maybe remark somewhere that the file has to end in .csv.

I use incron, so with `incrontab -e` I simply put:

`/nas/.../knx-group-addresses.csv IN_MODIFY /srv/scripts/on-ets-group-address-change`

there, and in said script, I copy the csv file whereever its needed, as long as its size is >0 bytes (since the ETS truncates it first):

```
SIZE=`stat /nas/.../knx-group-addresses.csv --printf='%s'`

if [[ "$SIZE" -gt 0 ]]; then
        # copy file
fi
```
Now I just have to export the file and that's it!

Thanks, I did star, and I did rate. :D
