### ISSUE TITLE
Can't use IP tunneling communicate

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#25]
First, wish you a happy new year

I found a problem while testing today，When I use Tunneling to send information in the ETS software, the plugin does not execute, but I filled in the KNX Tunneling IP in the plugin IP, when I changed to multicast in ETS and node-red-knx-UItimate The address (224.0.23.12) is ready to use.

Question:
How can I send information in the tunnel so that node-red-knx-Uitimateye can respond accordingly?

**Comment by Supergiovane** [comment]
Hello, happy new year. 
What make/model of IP router are you using?

**Comment by songzh96** [comment]
KANONTEC KTS1

**Comment by Supergiovane** [comment]
Hello
If your device is this
http://kanontec.com/files/datasheet/KTS1.pdf
As far as i can tell, it’s an IP Router, it cannot act as a tunnel device. It can maybe act as ETS programming device, but i think it's only a router. 
If it works as ip interface, maybe it has only 1 tunnel, that is occupied by ETS.

**Comment by songzh96** [comment]
Yeh, It's a programming device, very useful, Can implement a lot of logic.

Found the reason, it should be a Tunneling client is not enough. I have used knxd to add a few additional clients and are ready to use them.

Thank you for your help

**Comment by songzh96** [comment]
Hi @Supergiovane ,

I have a problem. Can you help me?


Problem Description

1. Unable to program KNX device

I can't download the device (partial download, full download, download application) through the serial download tool and KNX IP gateway. It can be downloaded at first, but the device shows no response (T_Disconect) when the download is halfway through.

2. KNX messages sent through the KNX panel and network, sometimes it takes many times for the device to respond.

Case: When I send a KNX message through APP (or use ETS software), the device is not executed (but the message can be seen in the "group monitoring software"), it will be executed many times before it is executed. It's like the message is blocked.

I think both problems have the same cause


Best Regards
songzh

**Comment by Supergiovane** [comment]
Hello Songzh

You need to proceed by steps.
First, i'll replace the ethernet cable
Second, i'll try to connect the PC running ETS and the KANONTEC KTS1, together to a separate switch.
Third, do you have another KNX/IP Router around to test with? If yes, i'll test with a different KNX/IP Router.

Then you can try to reboot the KANONTEC each time you program a device. If, after each reboot, ETS can program the device, that means that the KANONTEC does have some problem.
