### ISSUE TITLE
Supporting Hue-Group 

### ISSUE THREAD

**Issue by RobertHerter** [Supergiovane/node-red-contrib-knx-ultimate#252]
Hello,

i am using knx-ultimate for a long time now to control my hue (and more) over knx.
Supporting hue directly in knx-ultimat is great, but because i have more than one hue in a room, 
it would be great not if we could not only control single lights but complete groups.

Great Job

Robert

**Comment by Supergiovane** [comment]
Hi Robert
Is already under development.

**Comment by Supergiovane** [comment]
duplicate
#251
