### ISSUE TITLE
Value 0 telegrams sent to server

### ISSUE THREAD

**Issue by platini76** [Supergiovane/node-red-contrib-knx-ultimate#253]
hello thanks very much for your work! 
I have a problem but did not know how to solve.. don't know if this is a bug...

this is my node:

<img width="727" alt="Screenshot 2023-07-16 alle 03 21 01" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/10352902/b77f5863-c0f9-440c-b8ce-86f932905bae">
<img width="569" alt="Screenshot 2023-07-16 alle 03 21 10" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/10352902/1ec8e05b-f944-4468-94d1-ecb9e492fb2b">

all telegrams go to server with value 0

**Comment by Supergiovane** [comment]
Hi
First of all, update Knx-ultimate, your version is quite old. 
Then, put a debug node behind that blu node. I need to see, what and how that node sends its msg.

**Comment by platini76** [comment]
updated....

![Uploading Screenshot 2023-07-16 alle 05.25.09.png…]()

**Comment by Supergiovane** [comment]
Put a function node between the blue node and knx-ultimate. 
Write this into the function node:

msg.payload = Number(msg.payload)
return msg

**Comment by platini76** [comment]
I think I solved at same mode... thank you!!!!!
<img width="561" alt="Screenshot 2023-07-16 alle 05 36 17" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/10352902/3f8b2a26-89c1-4e5f-9176-1ba17c2977d4">
