### ISSUE TITLE
Group address overrules set topic name

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-knx-ultimate#257]
Hi,

A KNX Ultimate (2.1.35) node with a set topic name is overruled by its group address. See attached screen shot with the node's configuration and its debug output, which shows the group address instead of the topic name.

<img width="827" alt="Bildschirmfoto 2023-08-02 um 19 57 18" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26072184/7ccbbc46-c6fb-453c-827b-8331937d8508">

Regards,
Graefe

**Comment by Supergiovane** [comment]
Hi
Hmm… very strange. I’ll take a look tomorrow

**Comment by Supergiovane** [comment]
Hi
Fixed in the upcoming version. Out today 2.1.39

**Comment by Graefer** [comment]
Great! Thanks.
