### ISSUE TITLE
Switch all HUE Lamps off with one group address

### ISSUE THREAD

**Issue by Poeschie** [Supergiovane/node-red-contrib-knx-ultimate#258]
Hi!

i successfully integrated your HUE node into my nodeRED flows to control them via KNX.
I have a group address to switch all my lamps (KNX actuators and DALI) off for example when i leave my flat.

Is there a way to connect this group address with your HUE node to switch all lamps off? Or is there a workaround to switch all HUE lamps off with this "all-off group address"?

Best regards.
Perold

**Comment by Supergiovane** [comment]
Hi
Yes, you can group your lamps in the Philips HUE app, then the group will appear on the HUE light node.
Or, you can add a HUE node for each of your lamp, all pointing to the same KNX group address for switching.
