### ISSUE TITLE
Turn on/off a lamp on Hue does not update KNX state

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-knx-ultimate#262]
Hi,
when I turn on or off a lamp via Hue app (or Apple Home app), the KNX status does not update. (KNX ultimate v. 2.1.39)
Thank you
Graefe

**Comment by Supergiovane** [comment]
Hi!
You’re old. Please update to the latest knx ultimate version and try again.

**Comment by Supergiovane** [comment]
Hi Graefe
Have you solved the problem?

**Comment by Graefer** [comment]
No. To specify the problem: it is the dim status which does not get an update. I think this is as Hue handles lamps different to KNX: in Hue a lamp can have a dim status >0% although it is actually turned off. This is different in KNX.

**Comment by Supergiovane** [comment]
Hi Graefe
Yes. This behavior is simulated in the knx hue node. If you wish to unlink the dim status from the on/off switch, there is an option to do that (in the last tab of the config window, I don’t remember yet the name, but there is an explanation in the help panel of nodered). 

If you’re not satisfied by my answer, please tell me simply what do you want. I’ll do it! :-)

PS: i’ll soon do a youtube live video to explain all the new features of the latest knx-ultimate version.

**Comment by Graefer** [comment]
Hm, if I turn off a light via Hue, the KNX dim status does not change to 0% as it should - no matter if the ‚link brightness to on/off‘ switch checked or not
To my understanding, this switch only adapts Hue behavior to KNX - but not Vice versa.

**Comment by Supergiovane** [comment]
Hi
Have you updated to the latest knx-ultimate version?
Can you please post your json flow here?
Thanks

**Comment by Graefer** [comment]
Yes, I updated.
How can I poist the json flow without having to post the complete relating configuration file with all ETS GA?

**Comment by Supergiovane** [comment]
You can’t. You could make some screenshots of the flow and of the node config window

**Comment by Graefer** [comment]
<img width="692" alt="Bildschirmfoto 2023-08-27 um 19 53 02" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26072184/5a8eafce-5a8e-415c-96f2-2c72bfdfe5ba">
<img width="692" alt="Bildschirmfoto 2023-08-27 um 19 53 31" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26072184/789ee24d-5ed5-4963-96d6-59193e8811f9">
<img width="692" alt="Bildschirmfoto 2023-08-27 um 19 53 55" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26072184/fa4bcb9d-6320-4eb7-a1b1-980628da927d">

**Comment by Supergiovane** [comment]
By turning off the light via the hue app, do you expect the 1/5/63 to be zero, right?

**Comment by Graefer** [comment]
Exactly! But it remains unchanged, for now.

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate@2.1.44 is out. It should be fixed.
Thanks.

**Comment by Graefer** [comment]
It is perfectly fixed. Thank you!
