### ISSUE TITLE
kNX ultimate crashes NodeRed

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-knx-ultimate#263]
Hi,
KNX uktimate suddenly exceeds Node Red‘s CPU time end eventually crashes Node Red which restarts and the mess starts again. I think I observed this with 2.1.43 for the first time. Now, it occurs daily. 
The log says, that 192.168.3.21, which is the Hue bridge, was unreachable. However, the bridge is working fine and there is no problem with the network. 
![IMG_1470](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26072184/154e693c-f2d0-49e1-909f-8a3f368eaa23)
![IMG_1471](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26072184/51bdb622-9d1c-44bd-8002-7b1513af039b)

**Comment by Supergiovane** [comment]
Oh crap. 
I’ll take a look asap. You can revert to 2.1.43 in the meantime

**Comment by Supergiovane** [comment]
Hi
Should be fixed in node-red-contrib-knx-ultimate@2.1.45, out right now.
