### ISSUE TITLE
Hue Bridge Config problem

### ISSUE THREAD

**Issue by Critit** [Supergiovane/node-red-contrib-knx-ultimate#264]
Hello,

I updated your node today and thank you in advance that you have now integrated hue (I wished for it very much), my problem is when I want to configure my hue bridge and enter the IP address, it reports the following:

" "Error KNXUltimateRegisterToHueBridge non gestito request to https://192.168.1.35/api/config failed, reason: self-signed certificate" "

I think it is because it wants to connect via https and not via http can that be?

I run node red via the IoBroker

Best regards

Marcel

**Comment by Critit** [comment]
sure :)

![huebug](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/107431893/24736024-71f2-4f7f-b2d3-2514dfd308f4)

**Comment by Supergiovane** [comment]
What happens when you open this url from your browser?
https://192.168.1.35/api/config

**Comment by Supergiovane** [comment]
Anyway, tomorrow i’ll find a way to duplicate your issue, but as i can see, it’s a matter of self signed certs

**Comment by Critit** [comment]
thank you :) I still have the 2 screenshots here, have a nice evening
![http](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/107431893/9a144b36-a4e4-46ac-865c-0de9d74a021b)
![sdfsdf](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/107431893/8f4eac6d-2216-410b-9599-f95de9d0dc05)

**Comment by Supergiovane** [comment]
The Hub seems to have an expired certificate. Have you update the firmware's HUB?

**Comment by Supergiovane** [comment]
Please, replace the existing file in your **.node-red/node-red-contrib-knx-ultimate/nodes** folder (the folder location can change if you're using iobroker), with this one (decompress it first). Then restart node-red and try again.
[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/12496152/knxUltimate-config.js.zip)

**Comment by Critit** [comment]
Hello

Many thanks for the effort, the certificate error has disappeared but now it spits out a new error message (see picture), if I don't press the button then the error message appears that I didn't press the button

Best regards

Marcel
![gasdfasdf](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/107431893/a0a9e8a3-90e5-4116-a3d4-ec3bb396b57e)

**Comment by Supergiovane** [comment]
Can you tell me your node.js version?
To do so, type `node -v` in a command line prompt.
Also, please, tell me your node-red version.
Thanks.

**Comment by Critit** [comment]
my node red version is 18.17.1, this is currently the recommended node version of IoBroker

**Comment by Supergiovane** [comment]
Please try with this file. I need to know the exact error.

[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/12497676/knxUltimate-config.js.zip)

**Comment by Critit** [comment]
![sdfdsagsadg](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/107431893/a05b14e5-34c2-406a-8779-7e3857248ed3)

**Comment by Supergiovane** [comment]
Please try this file

[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/12497802/knxUltimate-config.js.zip)

**Comment by Critit** [comment]
My Windows Defender deletes the zip folder

**Comment by Supergiovane** [comment]
Hi Critic,
yes, because it contains a javascript code. Disable it temporarily.

**Comment by Critit** [comment]
Thakn you Giovane

it works!

Thank you for maintaining your project so well and helping with problems

best regards

Marcel

**Comment by Supergiovane** [comment]
Hi
Thank  you to you! Appreciate that!
In the upcoming version, there will be the option to select the https or http protocol to connect to the bridge, to avoid such problems.
Bye.
