### ISSUE TITLE
KNXDebugText

### ISSUE THREAD

**Issue by Saranger85** [Supergiovane/node-red-contrib-knx-ultimate#265]
Hello,

the problem is that knx ultimate lost somtimes the connection to knx. I can send a payload to knx group adress but on knx group monitor can't see the new message. Than i restart nodered an then the connection is ok. Nodered runing behind iobroker in a proxmox CT and in the log of iobroker i saw this entry
`<html>
<body>

node-red.0 | 2023-09-05 16:37:42.524 | error | [error] 9/5/2023, 4:37:42 PM.523 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 3
-- | -- | -- | --

</body>
</html>`

In the knx ultimate config node -> maintenance i coppy this info

`-> id: 6fc013af.98132c
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 192.168.2.89
-> port: 3671
-> physAddr: 1.0.3
-> hostProtocol: TunnelUDP
-> suppressACKRequest: true
-> csv: 
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> stopETSImportIfNoDatapoint: stop
-> loglevel: error
-> name: Martins KNX
-> localEchoInTunneling: true
-> delaybetweentelegrams: 40
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: 
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> infoEditor: [object Object]
-> z: 
-> changed: false
-> credentials: [object Object]
`

The knx Ultimate Version is 2.1.43

I hope you can help me.

thank you and best regards

**Comment by Supergiovane** [comment]
Hi
You gave me little clues. 
Anyway, your knx/ip interface does not respond to connection status requests. 
Maybe you have reached the maximum allowed connection?
Maybe you have some kind of udp storm filtering on uour ip switch/router?

**Comment by Supergiovane** [comment]
Hi
are you using node-red behind something, like iobroker or homeassistant? If yes, please be sure not to share IP ports.
If you're running node-red in a docker container, please be sure that either you allow port forwarding or, better, set the interface to "bridge".
What model of MDT do you use?
Please also be sure to give the MDT, a fixed IP address.
If you have multiple ethernet interface, try to specify the ethernet interface in the `Bind to local interface` options, in the node gateway config window.
You can also try to connect the PC running node red, with a LAN cable, directly to the MDT interface, to exclude any issue with your network devices.

**Comment by Supergiovane** [comment]
Hi
Any news on that?

**Comment by Saranger85** [comment]
Hi,

 

sorry for the late answer.

 

I use Nodered behind IO Broker the IP Port of IObroker is 8081 and from Nodered 1885.

 

IoBroker run on a Proxmox CT with a static IP. The MDT IP Interface has a static IP and the model is IP SCN-IP000.03 IP. I can’t a directly connection to the MDT Interface because I need the Nodered Dashboard on my Iphone and I use Homeassistant in a Virtual machine in Proxmox what I need.

 

Thank you.

 

br

 

Von: Massimo Saccani ***@***.***> 
Gesendet: Donnerstag, 7. September 2023 11:28
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Saranger85 ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] KNXDebugText (Issue #265)

 

Hi
Any news on that?

**Comment by Supergiovane** [comment]
Hi
Try asking on iobroker forum. Your setup may need some tweaks!
