### ISSUE TITLE
DPT declared both via config and via msg is IGNORED

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#266]
Hi there!
Thank you for the wonderful life-changing piece of software!
I've searched something similar for a lot and now I've found it... I'll never buy a phisical KNX/HUE interface! ;-)

I've set the DPT for a couple of AG, they are 5.004 (percent) and 12.001 (4-byte unsigned).
Telegrams are always  sent to the bus as 1.001.
GA file is well imported and generates 0 errors  against those 2 AG.
I tried to force the DPT with `msg.dpt="5.004"` and `msg.dpt="5.001"` but nothing changed.

To reproduce it you can create a virtual AG and listen to the KNX bus.

Here the setting: watch at the _6/4/2_
![KNX Setting](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/fa268a48-b90c-40f4-9000-55e870151c01)

Here the flow and the debug log:

![KNX Out](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/26eb67d8-8254-4f04-ab9b-d7f5fefde6c0)

Here the log on ETS:

![KNX In Log](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/1674e749-65a2-480a-a5be-c1fbdaa65ec4)

KNX-Ultimate Version is _2.1.46_
NodeRed is running on a _Strato Pi_ with the dedicated Raspberry Pi Installation

I hope I made some mistake somewhere, but it seems a bug...
King regards!
Enrico.

**Comment by Supergiovane** [comment]
Hi Enrico
Are you using a KNX Device node, or what?
The msg output you see in the right window (payload:50), is the real value read from the KNX bus.
Can you paste here your flow? I'm interested only in the KNX part, connected to output 1.
Thanks

**Comment by Supergiovane** [comment]
PS: se hai facebook, iscriviti qui: https://www.facebook.com/groups/viveresmart 
E' una community molto attiva di system integrator KNX.

**Comment by evazzoler** [comment]
Unfortunately my flow was routed in a bad way by a switchc node inside a subflow I never opened (it was taken from an example on the net). That subflow was forcing dpt to "1.001" in certain cases, leaving the original in others. I don't know the reason and the (bad) choice for doing that.
I restarted from zero with a subflow of mine and thrashed that subflow. All is working well now.
Sorry for having found this stupid trap after posting this issue. I have to pay some beers for this!

(subscribed to the FB group, thanks!)
