### ISSUE TITLE
datapoint missing?

### ISSUE THREAD

**Issue by jkoopmann** [Supergiovane/node-red-contrib-knx-ultimate#267]
Hi,

not sure if this is a bug or am I just being too stupid. I asked my dealer for the ETS export and got the GAs in this format:

"Profil Unterwegs Regelung Ventilatorleistung Status"	"8/1/24"	""	""	""	"DPT-5"	"Auto"

Which looks pretty much like what I see in the video. Yet during import I get the Warning:

KNXUltimate-config: WARNING: Datapoint not fully set (there is only the main type). I applied a default .001, but please check if i'ts ok ->Profil Unterwegs Regelung Ventilatorleistung Status 8/1/24 Datapoint: DPT-5

I am unsure what to change in ETS or the export to heal this and my dealer also is at a loss as he claims that all values in ETS are set correctly.

Regards

JP

**Comment by Supergiovane** [comment]
Hi, 
this is just a warning. The datapoint in question, lacks some things, but just don't care about it.
;-)

**Comment by Supergiovane** [comment]
Hi,
you could either fix the missing datapoint part or just ignore it. If you don't want to see the warnings every time you deploy, just deploy only the modified nodes. 

<img width="512" alt="Node-RED___192_168_1_16" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/8ef6113a-c052-4191-ab02-f38b51ce808b">

**Comment by jkoopmann** [comment]
Hence my question what I have to tell my ETS specialist what he needs to fix. What does he have to set in ETS so that everything is "complete" in the sense of the plugin? If you could provide a small screenshot of that this would be incredible helpful. Your help is greatly appreciated. I love your plugin!

**Comment by Supergiovane** [comment]
Hi
`"Luci viale (switch) Stato"	"0/1/32"	""	""	""	"DPST-1-1"	"Auto"`

This is a sample of a complete datapoint of mine. You can see that the DPT string is complete of subcode and that the name has changed to **DPST**.
In your case, the ventilator status should be a scaling value, so you can manually modify your DPT5, into **DPST-5-1**  
Here, a subtype list of the datapoint 5.xxx

<img width="518" alt="https___www_knx_org_wAssets_docs_downloads_Certification_Interworking-Datapoint-types_03_07_02-Datapoint-Types-v02_02_01-AS_pdf" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/7c5e2d9c-a75a-47c4-9353-51aca808dfd2">



Or... you can ask your installer to set the missing subtype in ETS, like this (your current datapoint is the red row and your installer should select one of the subtypes, for example "percentage", the green row):

<img width="1164" alt="Windows_11" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/48dc2c00-c966-4b1d-a682-bcdf92b77093">


Hope this is clear now.
:-)
