### ISSUE TITLE
knxUltimateViewer Group Address Name font-size

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#268]
This is not properly a bug report, but a little enhancement request.
In the _knxUltimateViewer_ 1 pin output the _Group Address Name_ font-size is inline styled (_size="2pt"_). The inline style cannot be overwritten.
This unfortunately prevent the user to customize the view without creating a new one from scratch (time expensive).
I.E., when I use the template with
`<div style="font-size: xx-small;" ng-bind-html="msg.payload"></div>`
for a better view in a mobile phone, the result is a greater font for Group Address Name values.
This could be fixed using a relative size css property like _smaller_ or a percent value (quick fix!) or declaring the size in the html head o at a higher level (elegant fix).

**Comment by Supergiovane** [comment]
Hi Enrico
the knxUltimateViewer node is a bare group address viewer.
Anyway, i'll take a look!

**Comment by Supergiovane** [comment]
Hi Enrico
node-red-contrib-knx-ultimate@2.1.48 is out with the fix ("smaller" instead of "2pt")

**Comment by evazzoler** [comment]
You are great! I've never seen a fix and release faster than this!
Thank you so much!
(It seems that with some browsers "smaller" is ignored but if ignored it permits to overwrite the font size. In this case all small is better than one column bigger)

**Comment by evazzoler** [comment]
Ops...
You should use:
 <font style="font-size: smaller;">
instead
 <font size="smaller">

**Comment by Supergiovane** [comment]
Ops... Sorry, you're right...

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate-2.1.50 is out with the fix.

**Comment by evazzoler** [comment]
All is working good now!
