### ISSUE TITLE
nodered 14.6.1 start not possible

### ISSUE THREAD

**Issue by platini76** [Supergiovane/node-red-contrib-knx-ultimate#270]
Hello

on nodered for homeassistant 

11 Oct 16:03:53 - [error] Error: Error response for https://192.168.0.29/clip/v2/resource with status 404
    at /config/node-red/node_modules/node-red-contrib-knx-ultimate/nodes/utils/http.js:39:32
    at /config/node-red/node_modules/simple-get/index.js:98:7
    at IncomingMessage.<anonymous> (/config/node-red/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:628:28)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

it stops nodered and cannot start it

after last update to 14.6.1
last homeassistant version.
thanks for help

**Comment by Supergiovane** [comment]
Hi,
i'm looking at it now...

**Comment by Supergiovane** [comment]
Please install the new version node-red-contrib-knx-ultimate@2.1.53
If you can't access the palette menu within node-red, just cd into your .node-red folder and do **npm i node-red-contrib-knx-ultimate**

**Comment by platini76** [comment]
[npm](zsh:) command not find: npm

**Comment by Supergiovane** [comment]
Hi
you should search for help in the homeassistant community forum. I've never installed node-red as homeassistant plugin.
