### ISSUE TITLE
Hue Light timeout

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#272]
When you use a light for stair light, you'd need to set a timeout for turning the light off after a certain time.
This is implemented in almost every KNX actuator. What to do if that light is a HUE light?
It would be useful if the light configuration has a timeout (maybe different for day and night).

In the meantime I implemented a "KNX TimeOuter" that works with every KNX object.
Feel free to adapt the code in a better javascript way and integrate into your suite.

`[{"id":"cca0b73622b1d111","type":"subflow","name":"TimeOuter","info":"","category":"","in":[{"x":300,"y":100,"wires":[{"id":"8c8f134d9f35b230"}]}],"out":[{"x":660,"y":100,"wires":[{"id":"8c8f134d9f35b230","port":0}]}],"env":[{"name":"TimeOut","type":"num","value":"","ui":{"icon":"font-awesome/fa-hourglass","label":{"en-US":"TimeOut (m)"},"type":"input","opts":{"types":["num"]}}},{"name":"SwitchGA","type":"str","value":"","ui":{"icon":"font-awesome/fa-cloud-upload","label":{"en-US":"Switch GA"},"type":"input","opts":{"types":["str"]}}},{"name":"StatusGA","type":"str","value":"","ui":{"icon":"font-awesome/fa-cloud-download","label":{"en-US":"Status GA"},"type":"input","opts":{"types":["str"]}}}],"meta":{},"color":"#87A980","inputLabels":["KNX flow IN"],"outputLabels":["KNX flow OUT"],"icon":"node-red-contrib-knx-ultimate/node-knx-icon.svg"},{"id":"11ae0a8f200e0a24","type":"inject","z":"cca0b73622b1d111","name":"1m Clock","props":[{"p":"topic","vt":"str"}],"repeat":"60","crontab":"","once":true,"onceDelay":"10","topic":"check","x":250,"y":140,"wires":[["8c8f134d9f35b230"]]},{"id":"8c8f134d9f35b230","type":"function","z":"cca0b73622b1d111","name":"TimeOuter","func":"const gaSwitch = env.get('SwitchGA');\nconst gaStatus = env.get('StatusGA');\nconst timeOut = env.get('TimeOut') * 60 * 1000; //entro in minuti, esco in millisecondi\nvar storage = []\n\nif (flow.get(\"$parent.KNXTimeOuter\") !== undefined) {\n    storage = flow.get(\"$parent.KNXTimeOuter\");\n}\n\n// verifico se il messaggio è destinato al nodo o meno\nif (msg.topic == gaStatus){\n    // verifico se presente ed estraggo eventuale indice\n    const ga_index = storage.findIndex((list) => list.ga==msg.topic);\n    // node.warn(ga_index)\n    // se il comando è di accensione\n    if (msg.payload) {\n        // se restituisce -1, il GA non è presente, quindi inserisco nuovo valore\n        if (ga_index < 0) {\n            //node.warn(\"Salvo \" + gaStatus)\n            storage.push({ ga: msg.topic, value: new Date() })\n        }\n        // se restituisce l'indice e sto mandando ancora ON, aggiorno il valore\n        else {\n        //node.warn(\"Aggiorno \" + gaStatus)\n        storage[ga_index].value = new Date()\n        }\n    // se restituisce l'indice e sto mandando OFF, cancello l'oggetto\n    } else {\n        if (ga_index > -1)\n        //node.warn(\"Cancello \" + gaStatus)\n        storage =storage.slice[ga_index]\n    }\n    // salvo l'array aggiornato\n    flow.set(\"$parent.KNXTimeOuter\", storage)\n}\n// se arriva un clock di verifica con topic=\"check\"\nelse if (msg.topic == \"check\"){\n    const ga_index = storage.findIndex((list) => list.ga==gaStatus);\n    if (ga_index > -1) {\n        const nowCheck = new Date();\n        const onCheck = new Date(storage[ga_index].value)\n        const diffCheck = (nowCheck.getTime() - onCheck.getTime())\n        //node.warn(\"Adesso: \" + nowCheck);\n        //node.warn(\"Ultimo On: \" + onCheck);\n        //node.warn(\"Diff: \" + (diffCheck));\n        // se scaduto\n        if ( diffCheck > timeOut ) {\n            //node.warn(gaStatus + \"scaduto\")\n            var newmsg_off = {}\n            newmsg_off.destination = gaSwitch\n            newmsg_off.payload = false\n            newmsg_off.event = \"GroupValue_Write\"\n            node.send([newmsg_off])\n        }\n    }\n    // Cancello la variabile se è vuota\n    if ((flow.get(\"$parent.KNXTimeOuter\") !== undefined) && (storage.length == 0)) {\n        //node.warn(\"Storage vuoto, rimuovo...\");\n    flow.set(\"$parent.KNXTimeOuter\", undefined);\n    }\n}\nelse {\n    //node.warn(\"Messaggio da ignorare\");\n    return;\n}\nreturn;","outputs":1,"timeout":0,"noerr":0,"initialize":"","finalize":"","libs":[],"x":450,"y":100,"wires":[[]]},{"id":"995a8e636df35f58","type":"subflow:cca0b73622b1d111","z":"9035f77216a8a87e","name":"","x":640,"y":440,"wires":[[]]}]`

**Comment by Supergiovane** [comment]
Hi Enrico
I'm unable now to see your flow, but what if you use a simple KNX device node to control the HUE light? You are certain able to control the KNX device node staircase function with, for example, a trigger node:

<img width="508" alt="Node-RED___192_168_1_16" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/f0267ec3-bd0a-41ee-b77c-385948fb56d2">

I don't want to implement all possibile options, otherwise i must work on the KNX node H24 ;-)

**Comment by evazzoler** [comment]
Maybe, but status GA and switch GA are different, so is not so fast to manage it with a trigger.
Anyway I'll use my subflow. It was a suggestion for a simple way dedicated to simple users... ;-)
