### ISSUE TITLE
After updating home assistant node-red knx ultimate can't make connection to ip interface.

### ISSUE THREAD

**Issue by limwakra** [Supergiovane/node-red-contrib-knx-ultimate#273]
Hi Giovane,

Today I've updated the Home Assistant Operating System 11.0, and now I got the watch dog alarm that it can't connect to the ip interface. I've tried to restart the interface in ETS 6 but doesn't make a difference. Switched to the back-up interface, but the same problem.

Looks like there is something changed in how to connect to the interface.

I'm running the node-red as an add-on in Home Assistant.

The change log of HA states:
>Breaking Change: On Arm based boards network names are enumerated based on device tree. This means that the first Ethernet devices will no longer be named eth0 but end0. The network configuration is automatically applied to the new network interface.

**The solution is to change eth0 to end0.**

Solution was found while typing this message. Screenshot for other people with the same problem, so they know what to change.
<img width="587" alt="Schermafbeelding 2023-10-14 om 12 32 58" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/97366516/8e464d38-dff5-4080-aefb-63656963aacc">

**Comment by Supergiovane** [comment]
Thank you for the tip.
