### ISSUE TITLE
Knx Ultimate Hue state dpt 1.011?

### ISSUE THREAD

**Issue by DonKanaille667** [Supergiovane/node-red-contrib-knx-ultimate#277]
Hello, I have a question about KNX ultimate.  When I use Hue and select - Node Hue Light -switching - Status - dpt 1.011 it doesn't play it.  It keeps jumping to 1,001 (switch).  Did you want this that way?

**Comment by DonKanaille667** [comment]
![Screenshot_20231026_144610_Firefox](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/149076120/d4d0e560-da4e-4438-b0a0-5ad3ecfdfddf)

**Comment by Supergiovane** [comment]
Hi,
no. If you have imported the CSV from ETS, KNX-Ultimate uses the Datapoint specified in the CSV.
If you wish to override the DPT, you must first type in the GA address (that is 1.001), then change the datapoint to 1.011.

**Comment by Supergiovane** [comment]
Hi,
You have right. It's a bug.
I'll fix that in the upcoming version. In the meantime, you can leave 1.001, because it's a BIT datapoint anyway.

**Comment by DonKanaille667** [comment]
Thx for Support

**Comment by Supergiovane** [comment]
Fixed in 2.2.0 out now.
