### ISSUE TITLE
> Multiple scene in one node

### ISSUE THREAD

**Issue by Supergiovane** [Supergiovane/node-red-contrib-knx-ultimate#278]
@evazzoler

![274672082-d58a5b63-372e-4d08-b445-7ff195cc4aff](https://user-images.githubusercontent.com/37666636/279043016-0546d389-a460-4234-97eb-c78980e8bcf7.JPG)

**Comment by Supergiovane** [comment]
@evazzoler

Next week i'll start to working on that.

**Comment by Supergiovane** [comment]
Hi 
for info, how many scenes do you have to handle? I need such info for thinking about the scene node UI.

**Comment by evazzoler** [comment]
Hi, I think I will use a lot of the philips scene (not all, they are too much) plus some of mine. I own some inputs modules (MDT) that manage 8 different telegram at every touch (4 for short and 4 for long, 4 or in sequence), using a double half-button i can manage 16 scenes in one slot of my 503.
So, at least 16 in the living room. Other inputs (ABB or Siemens) can cycle values from 1 to 255...
I think that the "+add" button at the footer and a scroller would be the best solution.
Thank you!

**Comment by Supergiovane** [comment]
Hi
sorry for the delay, but my "real" work overwhelmed me too much during the last days.
I'll start working on that very soon.

**Comment by evazzoler** [comment]
Hey Max...
No need to justify! We all have to say "thanks" for the good job you are doing with this.
I hope some day to offer you some beers in person!


Il 28 novembre 2023 08:09:46 CET, Massimo Saccani ***@***.***> ha scritto:

**Comment by evazzoler** [comment]
Supermax, Supergiovane! I can't wait for giving it a try, but I must delay it because I'm busy with a lot of electric modifications for optimizing the HVAC that had the first start 2 days ago...
I'll back to you in a few days! ;-)
Take care!


Il 2 dicembre 2023 21:00:46 CET, Massimo Saccani ***@***.***> ha scritto:

**Comment by evazzoler** [comment]
Good! All seems to work perfectly!
Thank you so much!
I'll start tomorrow trying it "in the field" and keep you informed!
