### ISSUE TITLE
Problem with state

### ISSUE THREAD

**Issue by DonKanaille667** [Supergiovane/node-red-contrib-knx-ultimate#279]
Hello, I have another problem.  It would be nice if you could help me with this.  The status of the hie is not set correctly in the node.  To be precise.  You turn off the lamp, the status goes to zero, but a short time later it goes to some value.  The lamp is off in the Hue app and it is also displayed correctly in the iobroker with the Hue adapter.  This means that the status in knx is of course not correct.  Thanks

**Comment by DonKanaille667** [comment]
![Screenshot_20231030_102147_Firefox](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/149076120/3bf46db8-a445-4c54-a947-1cd4a845d1cc)
![Screenshot_20231030_102024_Firefox](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/149076120/4c0736ed-2126-4df6-9c0d-4ed05854145a)

**Comment by Supergiovane** [comment]
Hello,
the whole DIM/Brightness function is under re-write, so please be patient. A new version that fix the issues is upcoming...

**Comment by DonKanaille667** [comment]
Thx

**Comment by Supergiovane** [comment]
Hi
please check it again with version 2.2.3 and let me know if it solved your issue.
Thanks

**Comment by DonKanaille667** [comment]
OK, I'll do it as soon as the version is available. Thanks.

**Comment by Supergiovane** [comment]
Hi 2.2.4 is out, with some other fixes.

**Comment by DonKanaille667** [comment]
state on version 2.2.3 works fine. I will still check version 2.2.4

**Comment by DonKanaille667** [comment]
Version 2.2.4 seems to work fine. I'll keep an eye on it throughout the day tomorrow. If I notice anything else, I'll let you know. Many thanks for the support.

**Comment by Supergiovane** [comment]
Thanks for the feedback.
