### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by tobi-coder** [Supergiovane/node-red-contrib-knx-ultimate#28]
Hi
First of all thank you very much for your great work. 
I have one question: is there a way to enable a detailed log for debuging purposes? I have some troubles with not receiving telegrams and with loosing the connection totaly after some telegrams.
I already read through the troubleshooting guide but didn't find the Problem so I'm looking for more information.

**Comment by Supergiovane** [comment]
Hello Tobi, thank you for using my node!
This hapens if you have two ethernet devices, for example an eth and a wifi. 
Can you explain me your setup?

**Comment by tobi-coder** [comment]
Hi

Thank you very much for the fast answer. Here some information about my environment.

- MDT IP Router (SCN-IP100.02)
- node-red raspi and the IP Router are in the same subnet.
-  currently using the IP address of the device not the multicast address in the node config. This because I do not get any connection at all with the multicast address.
- when using the ip address I can send a few telegrams before it stops (no telegrams visible in ETS Monitor)
- receiving telegrams seems not to work at all
- I bound the KNX node to the eth0 (not using auto)
- I have 145 KNXUltimate device nodes (too much?)

**Comment by Supergiovane** [comment]
Hello
I have about 300 group addresses. No problems at all. 
If the node doesn’t work with multicast routing, it means that somewhere, the udp traffic is dumped. 
Do you have switch/router with udp flood protection active? Try to directly connect the knx/ip router with the PI, or at least using a little separated switch. 
But first, try to select “disable ACK request” in the node configuration. 
If no success, try to phisically disable the wifi on the PI. 
Please let me know. 
Thanks!

**Comment by tobi-coder** [comment]
Thank you for the feedback and the help.

- I switched back to multicast
- storm control is disabled on all switch ports
- even with only a dump mini switch between node-red and KNX Router no chance to get multicast working
- if I "Connected waiting for telegram" is shown under a send or receive node does it mean the connection has been established? 

For today I give up. ;-(

**Comment by Supergiovane** [comment]
Ok let’s continue tomorrow!
Your system will be up and running. No fear. 
Bye.

**Comment by tobi-coder** [comment]
Thx again for your help.

I don't think it works with ETS. But at the moment I'm very confused. ;-) I'll check again tomorrow.

**Comment by Supergiovane** [comment]
Hello Tobi,
i downloaded the user manual of your MDT. This is a dual personality device, with 4 IP Tunnels and an IP Router. The latter is what you should use.
Have you selctet this option, to enable IP Routing?

![https___www_mdt_de_download_Archiv_MDT_TM_IP_Router_02_20_pdf](https://user-images.githubusercontent.com/37666636/72879324-f058d480-3cfc-11ea-9d98-c7288d358988.png)

If you're more comfortable and if you have an account on knx-user-forum.de, we can enter in a chat.
Let me know what do you prefer.

**Comment by tobi-coder** [comment]
Hi thank you for the efforts and your time. I'll check later in the evening. I have an account in the knx forum and we can switch to a chat there.

**Comment by Supergiovane** [comment]
No problem.
First of all, we need to assure us, that the IP Router is working with ETS in router mode.
Then we'll ditch further.
My Nickname is on knx-user-forum.de is TheMax74.
