### ISSUE TITLE
Error at 2.2.8

### ISSUE THREAD

**Issue by DonKanaille667** [Supergiovane/node-red-contrib-knx-ultimate#280]
Hello, nothing works anymore with the update to 2.2.8. Is it just me? I've already tried a reboot and reinstalled the lights. Without success. Thanks.
Mistake:
TypeError: Cannot read properties of undefined (reading 'filter') at node.addClient (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-knx-ultimate/nodes/hue-config.js:279:51) at new knxUltimateHueLight (/opt/iobroker/iobroker-data/node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimateHueLight.js:638:22) at Object.createNode (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/util.js:90:27) at Flow.start (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/Flow.js:206:48) at start (/opt/iobroker/node_modules/@node-red/runtime/lib/flows/index.js:394:33)

**Comment by Supergiovane** [comment]
Hi
Mine works flawlessy. 
I saw you are using iobroker. 
Does iobroker crash? The error in the log is only a warning.

**Comment by DonKanaille667** [comment]
Exactly, runs under iobroker. I've already tried restarting iobroker. No improvement. Restarting the Hue bridge and a new contact didn't help either.

**Comment by Supergiovane** [comment]
You can revert to a previous version. You need to use a terminal window, login (for example via ssh) and issue a npm command:  npm install node-red-contrib-knx-ultimate@[version-number]

**Comment by Supergiovane** [comment]
I'm fixing that warning for you. Maybe iobroker raises a critical error.
The new version will be out in about 30 minutes.

**Comment by DonKanaille667** [comment]
Great, thank you very much. I think the 5€ donation I made isn't enough anymore :)

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate@2.2.9 is out. Please try it.

**Comment by DonKanaille667** [comment]
Works perfectly again. Thanks again. Will repeat a small donation.

**Comment by Supergiovane** [comment]
Good to know. 
Thank you for the feedback!
