### ISSUE TITLE
Turn external dependencies for fontawesome and iro, into local.

### ISSUE THREAD

**Issue by Supergiovane** [Supergiovane/node-red-contrib-knx-ultimate#285]
You are my personal super hero for today, thanks a lot for fixing it so quickly. Confirm that the issue is gone with 2.2.20!

Saw that the issue is with https://kit.fontawesome.com/11f26b4500.js... Is there a way to avoid this external dependency on a production system?

_Originally posted by @KomtGoed in https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/282#issuecomment-1794358713_

**Comment by Supergiovane** [comment]
Done in the upcoming version, out shortly.

**Comment by KomtGoed** [comment]
Great, thanks a lot!
