### ISSUE TITLE
Exceptions in 2.2.25 

### ISSUE THREAD

**Issue by RobertHerter** [Supergiovane/node-red-contrib-knx-ultimate#287]
Hello an good Morning,

updated to 2.2.25 and got exeptions after deployment:

"knxUltimateHueLight: node.handleSendHUE = (_event): Cannot read properties of undefined (reading 'x')"

**Comment by Supergiovane** [comment]
Hi Robert
Thank you for the report.
It'a already fixed in the upcoming v. 2.2.16

**Comment by Supergiovane** [comment]
Sorry, upcoming 2.2.26
