### ISSUE TITLE
Getting error on the node states

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#289]
After the last upgrade, I get those statuses.
All seems to work good except the status.
I updated  the config of every lamp for setting those fields that were blank after the upgrade, nothing changed.

![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/9479876/6e255a37-2c77-48a5-bcc4-c736a386a1dc)

**Comment by Supergiovane** [comment]
Hi
Fixed in upcoming version. Nothing to worry about

**Comment by evazzoler** [comment]
Hi Supergiovane! Today fix did not fix the message.

**Comment by Supergiovane** [comment]
Ciao
Are you on version 2.2.28?

**Comment by evazzoler** [comment]
> Ciao Are you on version 2.2.28?

Sure!

**Comment by Supergiovane** [comment]
Are the light affected, capable of color, or they are simple light with only brightness?

**Comment by evazzoler** [comment]
All the light are affected, color and white.

**Comment by Supergiovane** [comment]
Are you able to get the log of the error and paste it here? I need to see more details about this error.

**Comment by Supergiovane** [comment]
I've probably managed to reproduce the issue. For now, no log is required.

**Comment by Supergiovane** [comment]
Fixed in node-red-contrib-knx-ultimate@2.2.29

**Comment by evazzoler** [comment]
Confirm fixed! Thank you so much!
