### ISSUE TITLE
Error ERR_SOCKET_DGRAM_NOT_RUNNING

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#29]
Hi Supergiovane

From time to time I get the following error, but I still can't figure out why. Node-RED crashes after this error.

Do you have an idea why this happens?

Node-RED: v0.20.8
knx ultimate: v1.1.25

> 2 Feb 23:38:41 - Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at healthCheck (dgram.js:663:11)
    at Socket.close (dgram.js:545:3)
    at fsm.<anonymous> (/hbvisu-data/node_modules/knx/src/FSM.js:178:23)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
>

**Comment by Supergiovane** [comment]
Hello
Never saw this error before.
Do you have other nodes using KNX?
Let me some time to ditch into.

**Comment by Supergiovane** [comment]
For me, this is a socket error in some components of node-red.
Please update your node-red. Your version is very old, yet there is V. 1.0.xx

**Comment by heleon19** [comment]
There is an other Docker container running with an other KNX lib running. You think this could cause this error? Is there a way to prevent Node-RED crashing?

**Comment by Supergiovane** [comment]
Yes, change your KNX/IP router port directly in ETS and on the knx-ultimate config node.

**Comment by heleon19** [comment]
> at fsm. (/hbvisu-data/node_modules/knx/src/FSM.js:178:23)

I think line 178 in FSM.js should be handled by an try and catch, to prevent application stop? Because it's called in a cb function of setTimeout. The lines after are never executed.

`try { 
   sm.socket.close();
} catch(err) {
}`

**Comment by Supergiovane** [comment]
Hello
yes, i'll open an issue for that, but i've more than 1400 users and no one has connection problems.
You have for sure some issue in your chain. Please see my question on the other issue thread. Thanks.
