### ISSUE TITLE
Feedback on 2.26

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-knx-ultimate#290]
Hi,
as you asked for user back feedback I can report that 2.26 (and many version before) have a few problems concerning the handling of Hue lamps. The problems change from version to version. With 2.26  if a lamp is turned off and I try to turn the lamp on by dimming (long press), the dim level on the KNX side always jumps to 100% (rather than slowly dimming) – but the lamp remains dark. 
Graefe

**Comment by Supergiovane** [comment]
Hi
Nice to meet you again. 
The upcoming version should solve all the issues. 
The problem you reported, shouldn’t happen, even in the previous versions. 
Anyway, the whole handling of hue lighting has been rewrote. In the upcoming version, the hue light node take care of the lamp type, to adapt the ui and to issue more correct lighting commands.

**Comment by Supergiovane** [comment]
Hi
the issue appears when the dim direction is "down" and the light is already off.
It has been fixed in the upcoming version.
Thank you for the feedback. I appreciate that.

**Comment by Graefer** [comment]
Yes, .29 is one of the best versions since some time.
