### ISSUE TITLE
Add dynamic scenes and the status of a scene 

### ISSUE THREAD

**Issue by BoBeRzE** [Supergiovane/node-red-contrib-knx-ultimate#292]
Hi Supergiovane,

first of all, thank you for your fantastic work on the KNX and HUE nodes. It is currently not possible to select dynamic scenes in the HUE Scene node. I would like to use the "dynamic light" scene for my hallway so that the right light is switched on depending on the time of day and especially at night.

![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/49961176/ae6b1118-716a-4fa8-9a6f-9024483e1f30)

Would it be possible to implement this?

It would also be nice if there was a possibility in the node for each scene to have the status whether it is active or not in order to be able to use this information as input for the switches. You could use the "Active" property from the feedback of the activated scene for this. Currently I have to use additional logic blocks to map this.

Like this.

![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/49961176/b2fb74a4-1714-4583-8885-a78fabc4003a)

But maybe I'm just using the node incorrectly :D

Thank you very much

BoBeRzE

**Comment by Supergiovane** [comment]
Hi
The scene node needs some adjustment. 
In particular, i need to learn in deep, how they work. 
I’ll take a look at what you need. :-)

**Comment by BoBeRzE** [comment]
Thank you very much for your prompt feedback. I am waiting patiently :)

**Comment by BoBeRzE** [comment]
Hi, no Problem. Take your time :)
