### ISSUE TITLE
Filter telegrams based on the source

### ISSUE THREAD

**Issue by chrfin** [Supergiovane/node-red-contrib-knx-ultimate#293]
Hi,

First thanks for your great work!

I would like to expand my manual switches with a motion sensor without introducing new group-addresses.
Therefore, I connected the motion sensor events to turn on/off the lights by writing to the same group-address as my manual switch, which works fine. But if I now for example turn the light off via the manual switch the motion sensor turns it back on right away.

What I would like is to detect a write to the group address from the manual switch and then disable the motion-sensor flow for e.g. 10 minutes. This could be done by examining the source of the telegram and trigger if the source is the manual switch.

I can also solve this by introducing a separate group address for the motion sensor, but that would make my whole KNX-system more complicated, as I would need two switching group addresses for every light.

Thanks and regards,
Christoph

**Comment by Supergiovane** [comment]
Hi
the msg.topic contains the source Group address.
Is that what you're asking for?

**Comment by chrfin** [comment]
Hi,

Thanks for your reply, but no, I'm not searching the source group address, but the source device address.

But I also found that one: `msg.knx.source` BUT only when using a `KNX DEVICE`\-node. It's not visible in the `KNX Viewer`\-node, where I searched first. But that's exactly what I need, so it should work 🤓.

Thanks, and regards,  
Christoph
