### ISSUE TITLE
Connection Issue to KNX

### ISSUE THREAD

**Issue by 1erturbo** [Supergiovane/node-red-contrib-knx-ultimate#296]
Hello,
I hope someone here can help me. 

I am not able to connect to KNX from my NodeRed installations and KNX-Ultimate V2.2.29. NodeRed is running on a Victron Cerbo GX.

Maintenance Log Gateway Configuration NodeRed:
-> id: b9ce687c7d9c3ba0
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object]
-> _config: [object Object]
-> host: 192.168.1.3
-> port: 3700
-> physAddr: 1.0.242
-> hostProtocol: TunnelUDP
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> stopETSImportIfNoDatapoint: stop
-> loglevel: error
-> name: KNX/IP Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 50
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: undefined
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> infoEditor: [object Object]
-> z: 
-> changed: false
-> credentials: [object Object]

**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Knx-Ultimate Version**
 - Eg. 1.1.95

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Additional context**

**Comment by Supergiovane** [comment]
Hi
Are you sure about the IP port of your KNX Interface "3700" ?

**Comment by 1erturbo** [comment]
Hi,
yes this specific Interface uses port 3700. I've also tested it with other KNX interfaces that use port 3671. But it doesn't work no matter which interface.

**Comment by 1erturbo** [comment]
it is always in a reconnect loop
<img width="631" alt="image" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/152384507/75069c6a-3d66-45cc-bc80-212abee6459f">

**Comment by Supergiovane** [comment]
Hi
the node cannot connect and goes in timeout.
Are you sure, you can ping the KNX Interface from the PC running node-red?
Do you have some firewall that blocks the port 3700?

**Comment by 1erturbo** [comment]
Hello,
ping is working. also all my KNX interface do work with ETS6. firewall should not

**Comment by 1erturbo** [comment]
Hi again,

I have installed nodeRed on another PC (in a Docker Container). In this installation KNX Ultimate works fine with all my KNX-Interfaces (with all the same settings for the interface, ports...).

One last question for the interface settings. The "physAddr:", is this the real PA of the KNX-Interface or a tunnel-PA? I've tried both and it makes no difference.

**Comment by Supergiovane** [comment]
Hi
The physycal address(physAddr) is the real physical address of KNX Ultimate. Think KNX-Ultimate as a stand alone device with its own physAddr. You can leave the default, or you can set your preferred physical address according to your installation.
If you have any other question, please ask. Thank you for using KNX-Ultimate!!!

**Comment by 1erturbo** [comment]
Thank you for your help!
