### ISSUE TITLE
Hue Tunable White Control Issue with KNX-Ultimate

### ISSUE THREAD

**Issue by enguar80** [Supergiovane/node-red-contrib-knx-ultimate#297]
Hello Massimo,

First of all, I'd like to extend my sincere gratitude for your remarkable contribution to the community. KNX-Ultimate has truly been a game-changer.

I've recently begun integrating it with Philips Hue, and I'd like to report a potential bug I've encountered.

### Bug Description
There appears to be an issue with controlling the Tunable White setting for a Philips Hue Light White and Color via KNX DPT 7.600. The Hue Light Node seems to receive the telegram, as evidenced in the flow, but the light's color temperature remains unchanged.

### Test Scenario
- **Device:** Philips Hue White and Color Light
- **Bridge:** Philips Hue Bridge 2.0
- **Environment:** Node-Red v3.1.0 running in a container as a Home Assistant Plugin
- **Software:** node-red-contrib-knx-ultimate v2.2.31

### KNX GA Configuration in the Hue Light Node
- **Switching**
  - Control
  - Status

- **Dim/Brightness**
  - Control %
  - Status %

- **Tunable White**
  - Control Kelvin (DPT 7.600)
  - Status Kelvin (DPT 7.600)

### KNX Light Configuration in Home Assistant
```yaml
- name: "Living Hue Faretti Ingresso"
  address: 2/5/1
  state_address: 2/5/2
  brightness_address: "2/5/24"
  brightness_state_address: "2/5/26"
  color_temperature_address: "2/5/19"
  color_temperature_state_address: "2/5/20"
  color_temperature_mode: absolute
  min_kelvin: 2200
```

I appreciate your extensive contributions to the community and look forward to any guidance you can provide on this issue.

Best regards,
Enrico

![Screenshot 2023-12-03 at 21 17 22](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/18d556ec-0c6c-4e7a-831b-08fcb775f5b2)
![Screenshot 2023-12-03 at 21 17 48](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/11a02b76-e1ee-4b9c-8def-da80ac7b043f)
![Screenshot 2023-12-03 at 21 20 13](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/2ca71e21-9e9c-48e5-8c6c-02c98ea9c963)
![Screenshot 2023-12-03 at 21 20 16](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/b779f8b1-cc21-4f48-b95b-4e835de9d8c8)
![Screenshot 2023-12-03 at 21 20 19](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/fd014581-2bfd-42a6-acd1-b6c47164f03f)
![Screenshot 2023-12-03 at 21 20 21](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/ae2d153a-d004-42f8-8179-fe9e063671e0)
![Screenshot 2023-12-03 at 21 20 23](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/2b69923c-38cd-46e4-afdd-4d8125a77c7d)
![Screenshot 2023-12-03 at 21 20 25](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/43eef7cc-dd40-4866-9677-e783e2ab459a)
![Screenshot 2023-12-03 at 21 21 06](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/130a45a8-c0c9-4bf9-95d7-2f8b0cfe2ad6)
[flows.json](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/13540158/flows.json)

**Comment by enguar80** [comment]
[flows.json](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/13540152/flows.json)

**Comment by Supergiovane** [comment]
Hi Enrico.
As i have also Homeassistant as front-end, i'll tray what you showed me in the VIDEO 1.
About Video 2, you raised an interesting issue. Maybe having an user-selectable kelvin range could solve the issue. You set the min and max kelvin, to be scaled to 0-100%.

**Comment by Supergiovane** [comment]
Hi Enrico,
please set the light in Homeassistant to
`color_temperature_mode: absolute_float`
Then try again. It should work with Datapoint 9.002

**Comment by enguar80** [comment]
Hi Massimo,

Thanks for the 'color_temperature_mode: absolute_float' tip for Home Assistant. It works well for adjusting the TW color temperature.

But, I've noticed a mismatch in Kelvin values, like in the video. It seems the conversion from mirek to Kelvin to RGB is causing this. For example, setting the Hue light to 5000 Kelvin in the Hue Essentials app shows almost 6000 Kelvin in Home Assistant (integration via KNX Hue node as you suggested).

![Screenshot 2023-12-05 at 01 07 05](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/96979185-523e-4f02-bab5-c16aa8669cf7)
![IMG_0084](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/2fa8812e-426c-44e0-a149-918e72f35309)


Thanks again,
Enrico

**Comment by Supergiovane** [comment]
hi Enrico
a difference of 1000° kelvin is too much.
Not knowing how HA hadles the conversions, neither knowing how Hue Essentials does it either, i think that the min/max range is taken into consideration, when scaling values.
```
min_color_temp_kelvin: 2700
max_color_temp_kelvin: 6000
```
min color temp is well above the minimum temp that the HUE light can reach.
Also the max color temp is below HUE light range.
Can you try changing it to these values?
```
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
```
Then please try again.
If succesfull, i can send you a modified file with user adjustable min/max kelvin.

**Comment by enguar80** [comment]
Good morning Massimo,

I made the changes, but unfortunately, the problem persists, as you can see in the screenshot below. However, I don't think the issue is within Home Assistant because, in my tests, I'm changing the color temperature in the Hue Essential app, and I'm using Home Assistant just to monitor the color temperature state. I can see the same value in ETS. Moreover, as shown in the video, the Hue Node can set the light to the exact Kelvin color temperature by configuring the startup behavior. The value I configure in the Hue Node reflects at startup in the Hue Sync app. However, as I explained, the Kelvin color temperature states are not consistent in the middle of the range.

Thanks again for your prompt support

Enrico
<img width="1091" alt="Screenshot 2023-12-05 at 08 59 37" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/c2d872e7-a8ba-4ec8-a441-97df39de5785">
![IMG_0085](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/63158464/2ace1529-e266-4d4d-a62c-334e8a18bd25)

**Comment by Supergiovane** [comment]
I'm downloading the HUE Essential app.
I'll let you know as soon as i've done some tests...

**Comment by Supergiovane** [comment]
Got it!
A fix will be out later today.

**Comment by enguar80** [comment]
Woow! Thank you!

**Comment by Supergiovane** [comment]
Quinck fix done.
V.2.2.32 is out.

As info, there are other correction and Homeassistant import section to be done in the upcoming 2.2.33.

**Comment by enguar80** [comment]
Hello Massimo,

Great news - the fix worked!

Thanks a ton!

Cheers,
Enrico
