### ISSUE TITLE
Hue night mode restore at day

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#298]
Hi there!
I don't know if I did something wrong or if the feature is not expected.
I have a GA where an object declare night and day at certain hours.
The light behaviour is and should remain "last state" because I have a lot of scenes in that rooms. When night comes, the light turns on as configured in night mode, but when day comes back, lights remains at night configuration instead to restore the previous state. This makes night mode unusable for me because the user must everyday push the scene button to restore bright light and not all the switches of the room has scene control (topically only the main switch near the door).
Is it possible to store the state somewhere on the persistences and restore it at morning?
I could do it by myself with a couple of nodes if I had i.e. the node saying when switched to night "night mode on, previous state was: bright, colour, etc." and "night mode off, restore the previous state", but the state should be configurable without turning the light on.
Thank you for reading me!

**Comment by Supergiovane** [comment]
Hi Enrico
As i can understood, you want the HUE Light node to automatically restore the "day" lighting as soon as the day comes, right?
What if the night comes while the HUE Light is on? Do you need the HUE Light node to automatically set the light to night mode?

**Comment by evazzoler** [comment]
Hi Max,
the behavioir when the day/night comes while the light is on is secondary, maybe selectable by a checkbox or a drop-down...
Maybe useful in the bedroom as signal when your childrens have to go bed, not good if you are in bathroom taking a shower...

For me the important is to recover the last state at morning, where the last state is the last the user leaves before going to bed. If it was red light, the light will be back red, if was blue, will be back blue.
Actually the only way to have the day light at morning seems to force an initial colour/brightness.

I well know you've started hating me for my perversive requests! 😜
I'll make it up to you by drinking a few beers together... Do you like beer?

**Comment by Supergiovane** [comment]
Hi Enrico
yes, i'm starting hating you, but your ideas are useful.
I like better a Chinotto San Pellegrino.

**Comment by Supergiovane** [comment]
Enrico,
can you confirm you've currently set this as "Last status"?

<img width="676" alt="Node-RED___Flow_2" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/227f4e7a-72d3-4970-986b-496b37998c86">

**Comment by evazzoler** [comment]
Sure, this is the reason why I opened this issue... I only use "last status" because of my tech-intolerant wife...

`There are a series of chinotti better than the "san pellegrino" one... I know where to find them and I'm already getting them. As soon as a box from my move gets free, I think we'll have to talk in PVT...`

**Comment by Supergiovane** [comment]
Hi Enrico
Sorry for the delay. I had "squaraus" due to some sort of fake salmon i eated.
The upcoming version will be out later today in the evening.

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate@2.2.34 is out.

**Comment by evazzoler** [comment]
Good Job! Only one thing needs to be fixed: group and zones.
In my "lampadario studio", the (in)famous zone with 3 lamp, when night comes with a scene of 3 different colors during the day (violet, pink, fucsia), it works as expected (2000k 10%), but when day comes back, lamps light on with a light cyan.

**Comment by evazzoler** [comment]
Hi @Supergiovane!
Do you think is better if I group the 3 lights in knx and leave separate on the philips side? What abaout status? I could take it from one of the 3 and ignore the others.

**Comment by Supergiovane** [comment]
Hi
I haven’t forgotten you. 
The group can have a status, in AND with all the lamps belonging to the group. 
I’m planning to fix your lampadario.

**Comment by evazzoler** [comment]
Supergood, Supergiovane!
Thank you! 🙏🏻
(my whole family says thanks, too 😉)
