### ISSUE TITLE
Bind to local interface lists only "Auto" in Windows

### ISSUE THREAD

**Issue by rotorman** [Supergiovane/node-red-contrib-knx-ultimate#3]
When Node-Red is installed in Windows, the Properties dialog field "Bind to local interface" lists only "Auto". Tested in a system with two LAN's, both with functioning static IPv4 on different subnets.

node-red-contrib-knx-ultimate does not bind to second NIC if first is enabled.

node-red-contrib-knx-ultimate in Version 1.1.6
Windows Server 2019 64-Bit (on Intel Xeon Hardware)
Node-RED v.0.20.7
Node.js v10.16.3 64-Bit
Node-RED running as a service in the context of a "Network Service" user.
Node-RED log has no errors (just warnings about rpi-gpio and disabled projects).

**Comment by Supergiovane** [comment]
Will investigate on that.

**Comment by Supergiovane** [comment]
Hello,
on windows 10 i see the devices.
Yet i'm unable to installa a VM with Win 2019 to test it. 
I'll solve by adding an option to manually write the interface name. (The dropdown simply lists all interfaces simply and passes the name to the underliyng KNX api).
This will be ready in Version 1.1.7 as soon as possible.

![Casa](https://user-images.githubusercontent.com/37666636/63600336-aa6bd900-c5c3-11e9-8c6c-3f697b382e5c.png)

**Comment by Supergiovane** [comment]
Fixed in 1.1.7
