### ISSUE TITLE
Node status in 24h format

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-knx-ultimate#302]
Hi,
would it be possible, to optionally change the status text of a KNX Ultimate node to 24h format?
Gracie
Graefe

**Comment by Supergiovane** [comment]
Hi Graefe
it depends on your system settings.
Mine, for example, is already 24h

<img width="592" alt="Node-RED___192_168_1_16" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/ca9e780e-ea00-442b-a310-0f3b531640ca">

**Comment by Graefer** [comment]
Ah, I see, this has nothing to do with your nodes. Sorry and thank you

**Comment by Graefer** [comment]
We‘re discussing this problem elsewhere [https://discourse.nodered.org/t/solved-issue-display-am-pm-time-instead-of-24hours/11947/27](url). Can you tell me, which local time zone and which node.js you are using?

**Comment by Supergiovane** [comment]
<img width="496" alt="massimosaccani_—_pi_NodeRed2022____—_ssh_pi_192_168_1_16_—_80×24_e_Posta_in_arrivo_•_massimosaccani_icloud_com" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/1aa4f23e-6453-4d9f-945a-729a070dbd61">

**Comment by Supergiovane** [comment]
<img width="490" alt="massimosaccani_—_pi_NodeRed2022____—_ssh_pi_192_168_1_16_—_80×24_e_Posta_in_arrivo_•_massimosaccani_icloud_com" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/3f6f597e-f2e7-46b4-8d72-970a042d86ab">

**Comment by Supergiovane** [comment]
<img width="437" alt="massimosaccani_—_pi_NodeRed2022____—_ssh_pi_192_168_1_16_—_80×24_e_Posta_in_arrivo_•_massimosaccani_icloud_com" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/2024a78f-e096-4074-8c56-f0b6b4b79d7b">

**Comment by Graefer** [comment]
Thanks!
