### ISSUE TITLE
Scale values

### ISSUE THREAD

**Issue by pkess** [Supergiovane/node-red-contrib-knx-ultimate#31]
When working with real datatypes on bus a scale value within the dialog for the group adress may be usefull
E.g. i would use this to scale the Wh values of my energy counter to kWh

**Comment by Supergiovane** [comment]
Hello
You can use a simple function node to multiply the number. 1kWh = 1000Wh
You idea seems good. I’ll think on that for a next version.

**Comment by Supergiovane** [comment]
Hello pkes
What ‘s your name?
Are you still interested in value scaling?

**Comment by pkess** [comment]
Hi,
Call me Peter. I would use this feature. So I am still interested

**Comment by Supergiovane** [comment]
Hello Peter
[formatting the payload](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/2.-Node-Configuration) will be available starting from V. 1.1.32.
Cheers.
Massimo
