### ISSUE TITLE
hue too many request?

### ISSUE THREAD

**Issue by ColdFireIce** [Supergiovane/node-red-contrib-knx-ultimate#313]
Hi,

thank you for your hard work!

I noticed a problem with the hue integration:
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5567159/f53cde95-c526-41cf-b526-f1f6d498c701)

Is there a way to reduce the calls made to the bridge?

Greetings and keep up the good work!

**Comment by Supergiovane** [comment]
Hi
The hue node makes only one call at node-red start and some minimum short random calls. 
I’ve carefully avoided such issues. 
What is the version of knx-ultimate ?

**Comment by Supergiovane** [comment]
Hi,
has the HUE node connection been resumed?

**Comment by ColdFireIce** [comment]
Hi,
thank you for your fast response.
I think this has solved it self. Today I can't reproduce it. (Yesterday I worked on many locations (HA, NodeRed, ...))
I'll keep an eye on it, but I think this should be solved.

Greetings
