### ISSUE TITLE
Feature: Hue Light: Support for HSV color control

### ISSUE THREAD

**Issue by ColdFireIce** [Supergiovane/node-red-contrib-knx-ultimate#314]
Hi,

I really love the integration of the hue <-> KNX link. But one thing is missing to make it completly replace my custom flows.
The MDT "[Glass Push-button II Smart](https://www.mdt.de/en/products/product-detail/glastaster-ii-smart-serie-02.html)" support Color-Change only via a HSV color control. See
4.4.12 in the [manual](https://www.mdt.de/fileadmin/user_upload/user_upload/download/MDT_TM_BE_02_Glass_Push_Button_II_Smart_Push_Button_Smart_86_V10.pdf).
It works with a 3.007 Dimmer to change either Hue, Saturation oder Value (Brightness) and as response:
5.003 Winkel (Grad) for Hue
5.001 Prozent (0..100%) for Saturation
5.001 Prozent (0..100%) for Value (Helligkeit)

In my current implementation I use the last received value and add the dimmer value until the stop command is received. (color is of course %360).

It would be really cool to have this function to use the link with these controllers.

Best regards!

**Comment by Supergiovane** [comment]
Hi, i'm taking a look at the user manual...

**Comment by ColdFireIce** [comment]
Excellent. If I can support you, let me know!

**Comment by Supergiovane** [comment]
Hi Cold, what's your name? I'm Max.
Basically, it works like the "tunable white" controls, but with HUE, Saturation and brightness and with slight changes to the statuses GA.

<img width="772" alt="Node-RED___192_168_1_16" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/295a3842-d9b4-4796-91f5-3daf21e3e200">

I'll work on that.
The main issue is to retrieve and read the HUE color wheel.
Can  you share here some code you used, to let me save some time?

**Comment by ColdFireIce** [comment]
Hi Max,

yes I think this is basically the case for saturation and brightness.
For Hue its the degree on an color wheel.
My current implementation is far from perfect, but basically it works like this:
- Use hue lamp current color (in my case, saved in an subflow)
- Change the values
- Convert HSV -> RGB
- Set RGB to hue lamp

My code looks like this:
- I only change hue, as i don't need saturation and brightness (both at 100%).
- I use [node-red-contrib-looptimer2](https://flows.nodered.org/node/node-red-contrib-looptimer2) to repeat the command until the stop command is received.
- I use [node-red-contrib-color-convert](https://flows.nodered.org/node/node-red-contrib-color-convert) to convert from HSV to RGB.

```
[{"id":"0f254daf2271a72b","type":"looptimer2","z":"cc2d22b7145c4de5","duration":"0.5","units":"Second","maxloops":"100","maxtimeout":"1","maxtimeoutunits":"Minute","name":"","x":370,"y":220,"wires":[["3957120ceaf4e1e7","c647e9e28f005820"],["be82a6b2865fca59"]]},{"id":"939b714536929f5d","type":"function","z":"cc2d22b7145c4de5","name":"","func":"if (msg.payload.data === 0) {\n    return {payload:\"STOP\"}\n} else {\n    let sign = (msg.payload.decr_incr === 0) ? -1 : 1;\n    return {payload: sign * msg.payload.data * 10}\n}\n","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":180,"y":220,"wires":[["0f254daf2271a72b"]]},{"id":"3957120ceaf4e1e7","type":"function","z":"cc2d22b7145c4de5","name":"hue -> HSV","func":"let flowHue = flow.get(\"colorHue\")\n\nlet hue = flowHue ? ((flow.get(\"colorHue\") + msg.payload) % 360) : 0\nhue = (hue < 0) ? hue +360 : hue; \nflow.set(\"colorHue\", hue)\n\nreturn {payload: [hue, 100, 100]};","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":830,"y":220,"wires":[["bf38073094f528a7"]]},{"id":"bf38073094f528a7","type":"color-convert","z":"cc2d22b7145c4de5","input":"hsv","output":"rgb","outputType":"array","scaleInput":true,"x":1010,"y":220,"wires":[["cd866f929ab6820b"]]},{"id":"cd866f929ab6820b","type":"function","z":"cc2d22b7145c4de5","name":"-> payload.rgb","func":"\nreturn {payload: {rgb: msg.payload}};","outputs":1,"timeout":"","noerr":0,"initialize":"","finalize":"","libs":[],"x":1200,"y":220,"wires":[[]]},{"id":"c647e9e28f005820","type":"change","z":"cc2d22b7145c4de5","name":"","rules":[{"t":"set","p":"running","pt":"flow","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":590,"y":200,"wires":[[]]},{"id":"be82a6b2865fca59","type":"change","z":"cc2d22b7145c4de5","name":"","rules":[{"t":"set","p":"running","pt":"flow","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":590,"y":260,"wires":[[]]}]
```

I hope this helps a little bit.

Best regards
Daniel

**Comment by ColdFireIce** [comment]
A thing on the side:
I played around with the HA template and noticed, that it is currently not possible to have *color* and *tuneable white*:
https://community.home-assistant.io/t/solved-flapping-states-knx-light-card/667139/12
There are versions for https://www.home-assistant.io/integrations/knx/#rgbw_address
but I don't have any KNX lights that support that.

I thought I share my findings as soon as possible for you.

**Comment by Supergiovane** [comment]
Hi
Do you have your MDT set like this? 
https://youtu.be/cx85Y5eTSHQ?t=528

**Comment by Supergiovane** [comment]
Out in 2.4.5-beta.1  https://github.com/Supergiovane/node-red-contrib-knx-ultimate/milestone/24
