### ISSUE TITLE
Bug: Hue Light: Color Temperature absolute values wrong 

### ISSUE THREAD

**Issue by ColdFireIce** [Supergiovane/node-red-contrib-knx-ultimate#316]
Hi,

is it possible, that the Kelvin values for Color Temperature are a bit off?
Everything works and you can change them reliably, (What goes in comes out). But I think they are off by a factor 10:
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5567159/c25a422b-925e-4294-b249-cd7b89ce385e)
I change the color temperature from very cold (~6500K) to very warm (~2000K)

Was as shown in KNX the values are off by a faktor of 10 and I'm not sure about the low end? Shouldn't it be at about 2000?
currently it comes back as 0. Looks more like an 0..100% streched to 0..65535 (0x0000..0xFFFF). Is this intended for the color temperature absolute DPT?
Looking at https://www.home-assistant.io/integrations/knx/#color_temperature_mode and some other sources (including my own previous implementation) I think the values should be "real" Kelvin numbers e.g. 2200K..6500K
I think this text ist also a bit off regarding the range:
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5567159/417b4bbd-d38f-4774-bab4-b79e888550e0)
https://www.home-assistant.io/integrations/knx/#value-types (see. 7.600 and 9.002)
Additionally here: https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PmDrivers/KNXDTypes.htm 9.002 is mentioned as 2byte *double*

When implementing the light with HA this shows as not beeing able to select cold colors, but the light will only show warm colors

Best regards
Daniel

**Comment by Supergiovane** [comment]
Hi Daniel
I've developed all in a hurry, so it may be prone to optimization/fixing.
You're the only one pointing this me out. I've spent many time in developing the HUE integration and i need some time for my "real" work.
I'm fixing the bugs with the maximum priority, but i'm forced to leave other issues behind. At least for a while...
I'm not really using any HSV and Tunable White function and i'm developing this for free for other users than me. ;-)
I'll watch your other issues, then i'll proceed as soon as possible.
If you're comfortable with javascript, you could join the developing by forking the code and, then, making a PR. Currently, i'm alone :-/
If not, please give me some time, as i'm currently a little busy.

**Comment by ColdFireIce** [comment]
Sure thing and no worries. I thought I just open some issues it's more for a backlog than an must.

Thanks again for your work. I know how unrewarding the opensource projects sometimes are.

**Comment by Supergiovane** [comment]
Hi Daniel
Please put the unzipped files into the **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder, by replacing the existing files and restart nodered.
Then, please, verify if this issue is resolved. 
Thanks.
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/13901014/Archivio.zip)
