### ISSUE TITLE
Feature?: KNX Scene Controller: Scene number for 17.001 and 18.001 instead of trigger

### ISSUE THREAD

**Issue by ColdFireIce** [Supergiovane/node-red-contrib-knx-ultimate#319]
Hi,

Currently when selection and DPT of 17.001 or 18.001 for the recall or save group address you have to set the trigger to match the payload (like for all other DPTs). I know that this creates a big flexibility for other DPTs like triggering a scene by reaching a specific dimming value or such.
But for Scene DPTs it would by nice to just set the scene number. instead of: `{save_recall:1, scenenumber:1}` you would just have an input for the number `1`.

I know that this is not breaking anything or making anything not usable, but it might be an idea for some convenience?
If you don't like the idea, that's fine with me as well ;)

best regards
Daniel

**Comment by Supergiovane** [comment]
Good catch, but it's too late.
Too many users around the world are using the {save_recall:1, scenenumber:1} format and i must assure no breaking changes from previous versions. I know i could make some stuffs in the code to adapt the changes from previous versions, but i prefer spend my time for other issues.
Anyway, yes, good idea.

**Comment by ColdFireIce** [comment]
Wood it be an idea to have a scene number field wich is only visible for 17.001 and 18.001 and automatically populates the trigger field accordingly?
Somewhat like the group address field that populates the name?
