### ISSUE TITLE
Startup with dimming from zero 

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-knx-ultimate#321]
Hi,
two issues/enhancements:
1) if a lamp is off and I turn it on with a short press, it jumps to the previous brightness level (as it should). 
If a lamp is off and I turn it on by dimming (with a long press), I would expect the lamp to start with 0. Instead of this, the lamp jumps to the previous brightness level which is in memory and continues to dim on from that level. 

2) If a lamp ist turned on with a short press, a following long press results that the lamp dims off instead of dimming it on, as I would expect it to do. 

Running v.2.3.4 here (with which I am really happy!). 

Thank you!

**Comment by Supergiovane** [comment]
Hi Graefe
Please update at least to 2.3.5, as there are some changes in the dimming feature.
Then, do you have set these options like this?

<img width="788" alt="Node-RED___Flow_2" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/676fe15e-bf97-44cf-a117-645aee03a105">

**Comment by Graefer** [comment]
With KNX Brightness Status on "Leave as is" the lamps still jump to the previous level (and it messes up the brightness status on my KNX device). No change with 2.3.5.
BTW: This is only a minor request. I am happy as it is, right now.

**Comment by Supergiovane** [comment]
Hi Graefe
You're right. There was a stupid error in the brightness computation.
This has now been fixed.
As the upcoming version contains many changes, i wish to test it consistently. There is no hurry, because the 2.3.5 is already pretty stable.

**Comment by Supergiovane** [comment]
PS: if you with to install a beta, you can do it by issuing npm install node-red-contrib-knx-ultimate@2.4.0-beta.0 in the .node-red folder.
