### ISSUE TITLE
Add DataType 275.100

### ISSUE THREAD

**Issue by Chris909090** [Supergiovane/node-red-contrib-knx-ultimate#323]
Hello together :)

Thanks for that great integration.
I just have a problem that a DataPoint I-ve needed is still not availaible.

My actor MDT AKH-0800.03 needs the DataPoint 275.100 to send the heating and cooling values.

Is it possible to add this DataPoint to the solution?

It would be really great!

Thanks for your help! :)

Greetings 
Chris

**Comment by Supergiovane** [comment]
Hi Chris,
noted for the next milestone 2.4.0

**Comment by Chris909090** [comment]
> Hi Chris, noted for the next milestone 2.4.0

Oh wow thats really fast! Thanks for it! :)

**Comment by Supergiovane** [comment]
v 2.4.0 is out in minutes.

**Comment by Chris909090** [comment]
I'm sry for aksing here but should I see the update here?
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/57b85878-6d3b-4249-9b05-59189cf1dee9)

And please allow me the question why you are using deployment and not releases?

**Comment by Supergiovane** [comment]
No, this is a beta.
The stable is 2.4.0 without any "beta" in the text.
It should be out in minutes.

**Comment by Chris909090** [comment]
Now its there thanks a lot!

**Comment by Supergiovane** [comment]
Please, if you haven't yet starred my node, please click the "star" button above right. Thank you to you , for using KNX Ultimate.

**Comment by Supergiovane** [comment]
Please update to 2.4.1 because 2.4.0 contains an error.

**Comment by Chris909090** [comment]
I click the "Star" :)

Sry for asking gain but after the update I have the problem that I see this window.
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/c751ed4c-4018-4cbf-a451-a0984eac6913)
If I delete it it appear again.

I want to add my configuration new but there is no button to do this?
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/b32bc56d-9a96-4a0a-8c81-d2ac35bb7c54)

**Comment by Supergiovane** [comment]
Yes, please update to **2.4.1**

**Comment by Chris909090** [comment]
Thanks for your help.

The Problem with the configuration is now fixed.

But I can't select a DataPoint?
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/c094af44-9df3-4bb5-9cd0-5c50fad3767f)

**Comment by Supergiovane** [comment]
Hi, mine works
Have you restarted node-red?

<img width="939" alt="Screenshot 2024-01-23 alle 12 20 34" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/95b39fab-aa0d-4963-bfe2-d4289bbaf588">

**Comment by Chris909090** [comment]
Yes I've restarded Node_Red and thw whole HomeAssistant but it is still not working.
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/1c1ef34e-d650-4fb4-b2b8-1bb58512d975)

**Comment by Chris909090** [comment]
I'm using the MIcrosoft Edge or the GoogleChrome.

My OperatingSystem is Windows 11 on a NUC and there I'm using a VM.

**Comment by Supergiovane** [comment]
I've tested with chrome and firefox on Win 11 and with safari on a Macbook.
I think it's an issue with the cookies. 
Can you try from annother PC?

**Comment by Chris909090** [comment]
I'm sry but I try different Browser, different Devices and reboot the NUC but I still have the same problem.

**Comment by Supergiovane** [comment]
I cannot really reproduce the issue.

https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/fb86a335-16c1-40b5-a498-8f8a7cb70f8b

Are you able to enter the **developer mode in chrome browser?**
If yes, the console should tell you if there are some errors and where.

**Comment by Supergiovane** [comment]
Yes, this helps:

<img width="1053" alt="298945053-c39ed955-8d14-425c-a3ab-a5ce04a9ae4a_png_3_579×1_998_pixel" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/45950d5c-49de-44ad-a982-a0f125b4f6f5">

Let me work on that...
In the meantime, please try to change the default language of your browser, to English and try again.

**Comment by Chris909090** [comment]
My firefox is in english and there it also doesn't work. Maybe it's the problem of the language of the HomeAssistant?

**Comment by Supergiovane** [comment]
Hi again
in the previous version of KNX Ultimate, were you able to see the DPTs in the dropdown list?

**Comment by Chris909090** [comment]
Hi :)
I have installed 2.4.1 and didn't see the Datapoint.
In the 2.4.0 beta before I saw them.

**Comment by Chris909090** [comment]
Thanks for your great/fast help but it is still not working... :/
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/ac8b8063-5559-4912-8e14-a15f8c5584d1)

Maybe it could be an error here?
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/b72fbe79-289f-4d13-b6fc-d0627b64b48b)

Here again the developer-tools
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/6d0beee0-9429-4eb6-a38c-2537b585dc32)
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/73207a3d-5a98-4ff6-9b8e-f5fd56779eba)

**Comment by Supergiovane** [comment]
Hi
the issue is the same as previous. Error 404 not found.
I'm start thinking, that node-red doesn't have the requested permissions to read from the web server.
Can you try, please, copying this row and paste it into the browser? You should get some JSON strings. 

<img width="1090" alt="Istantanea_23_01_24__16_41" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/f679dfeb-c2ef-4c2f-939f-6fc54d4b40c3">

**Comment by Chris909090** [comment]
I get this 
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/86b3240a-34c4-4513-b925-42bac20d3d04)

**Comment by Chris909090** [comment]
I#m sry but there are still the same errors.
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/ffa2c78b-fb0c-4363-826d-5f1f7073888c)

**Comment by Supergiovane** [comment]
Ok, let's move on.
I'm tweaking some things...
In the meantime, could you please insert another node type, for example, the **KNX Scene Controller**, and tell me, if you see the datapoint list?
Thanks

**Comment by Supergiovane** [comment]
Can you tell me more about your setup?
I know you've a login password to access Homeassistant, but do you have a password to access Node-Red as well?
What is the Node-Red version? You'll find in here:

<img width="859" alt="Node-RED_–_Home_Assistant" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/091dbe31-4bd2-41b2-a5d1-2d9f71a332dd">

**Comment by Chris909090** [comment]
Here is a version
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/fc31c9b0-b05d-4a40-b1ac-72bc2e2f1329)

I don't have a password to log in to Node-Red. I only entered something here because it was required by the setup.
Do you need something special or is that enough?
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/9b20fab1-3710-4167-8368-a6ce3764ece3)

If it helps you, you can also write me a private message and we can look at it together in TeamViewer?

**Comment by Supergiovane** [comment]
Where can in find in Homeassistant, this option window?
![299057290-9b20fab1-3710-4167-8368-a6ce3764ece3](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/a5a0f750-8239-4e01-892c-1140c8b975a6)

**Comment by Chris909090** [comment]
Here
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/00fc93a5-a145-4d3c-a6c4-ec192e53efa1)
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/39734863/9a3b111b-5271-471b-a1c4-09f296d21546)

**Comment by Supergiovane** [comment]
I'm setting up all the things...
It will take some time....

**Comment by Supergiovane** [comment]
<img width="495" alt="Home_Assistant" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/926ba522-de5c-46e0-81e3-ce862e103dfc">


<img width="823" alt="Screenshot 2024-01-23 alle 19 47 20" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/330fb5ae-cf59-46ce-8c17-3fe3a2de3c29">

It works. There must be something else...

**Comment by Chris909090** [comment]
Hmm ok I don't know what I could do?
In the 2.4.0 beta all works

Is there a instruction how to completely uninstall node-red because if I uninstall and install again there are also some old settings

**Comment by Supergiovane** [comment]
Hi
Yes, you can install an older version, by entering in the **.node-red/node_modules** folder of your Homeassistant, via a Terminal window.
Then issue a command **npm install node-red-contrib-knx-ultimate@2.4.0-beta.0**

But before, please update to 2.4.4.

**Comment by Supergiovane** [comment]
Are you now on version 2.4.4 ?

**Comment by Chris909090** [comment]
Yes I'm using 2.4.4

**Comment by Supergiovane** [comment]
Thank you for your patience and sorry for the problems.
You are very patient and tolerant.
A new public beta is out: **2.4.5-beta.0** that should solve these issues.
Cheers from Italy.
