### ISSUE TITLE
Node Error npm WARN config production Use --omit=dev instead.

### ISSUE THREAD

**Issue by CyberChris79** [Supergiovane/node-red-contrib-knx-ultimate#324]
Hi, i just wanted to update the Node. My Node Red instace running under ioBroker.

After i tried to update i got the error message in my log file and the Node does not start.
`
2024-01-28T07:15:29.140Z Installieren : node-red-contrib-knx-ultimate 2.4.5-beta.0

2024-01-28T07:15:29.164Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-knx-ultimate@2.4.5-beta.0
2024-01-28T07:15:29.302Z [err] npm WARN config production Use `--omit=dev` instead.
2024-01-28T07:15:30.080Z [out] 
2024-01-28T07:15:30.080Z [out] up to date in 797ms
2024-01-28T07:15:30.093Z rc=0
`

I could backup my system before the update, but everytime i try it, i get the same error.

Cheers
CyberChris

**Comment by Supergiovane** [comment]
Hi
This is only a warning. It could be, because you either have an old npm, an old node version or because this version of knx ultimate is flagged as beta. 
You should wait for the official 2.4.0 release, or read here, found on google: https://stackoverflow.com/questions/72776325/npm-warning-config-production-use-omit-dev-instead

**Comment by CyberChris79** [comment]
Hello @Supergiovane 

thank you for your answer, but after this error, your node is not installed properly again. So i can't use is.
My NPM and node version are the latest release.

**Comment by Supergiovane** [comment]
I suggest you to revert to any previous version of knx-ultimate and wait for the official new release, out of the beta shortly. https://www.npmjs.com/package/node-red-contrib-knx-ultimate?activeTab=versions

**Comment by CyberChris79** [comment]
Do you know how i can install the latest non Beta Version on an iobroker Node Red System?

**Comment by Supergiovane** [comment]
Hi
just ask at iobroker forum, where node-red is installed. The folder should be .node-red/node_modules and you need to just type **npm i node-red-contrib-knx-ultimate@2.4.4** in a prompt window,
