### ISSUE TITLE
Install Error WARN config production Use `--omit=dev` instead.

### ISSUE THREAD

**Issue by 19dexter86** [Supergiovane/node-red-contrib-knx-ultimate#328]
Hello,
I have node red running on a Pi 4. When updating to the beta I get the error message: WARN config production Use `--omit=dev` instead.

I am using npm 10.2.4
After the failed update knx ultimate was uninstalled. i am not able to install it again.

**Comment by Supergiovane** [comment]
Please be sure to have at least node v16 (issue a node -v command).
Your system may not allow to install betas.
Please revert to a previous version. https://www.mend.io/free-developer-tools/blog/npm-how-to-install-a-specific-version-of-node-js-package/#:~:text=an%20installed%20package.-,Use%20npm%20install%20%5Bpackage%2Dname%5D%40%5Bversion%2Dnumber%5D,minor%20or%20patch%20version%2C%20respectively.

You can revert to any non "beta" version.

**Comment by 19dexter86** [comment]
I am using nodejs v20.11.0

I have done the following:

```
pi@raspberrypi:~ $ npm i node-red-contrib-knx-ultimate@2.4.4
added 52 packages in 9s
10 packages are looking for funding
run `npm fund` for details
```

but KNX Ultimate cannot be found in node red. Not even after a restart. How does the installed package get into node red? 
Where can I download the tgz file alternatively?

**Comment by Supergiovane** [comment]
Hi David
you must issue the **npm i node-red-contrib-knx-ultimate@2.4.4** command, into your **.node-red/node_modules** folder.

**Comment by Supergiovane** [comment]
Hi David
solved the issue?

**Comment by 19dexter86** [comment]
Hi and thank you very much. Yes, I got it working thanks to your hint. The 2.4.4 is running stable. How can you be sure that a future update to 2.4.5 will work? Will this bug be fixed in the beta?

**Comment by Supergiovane** [comment]
Hi David
there are no bugs. The "beta" version is marked internally as "beta", so you can install it only either your node-red allows it, or you manually install the beta with the npm option `--omit=dev`
There will be another beta (2.4.5-beta.1) out shortly, then the official 2.4.5 release should be out the next week.

**Comment by 19dexter86** [comment]
ok but why was I able to install 2.4.4 without errors and not 2.4.5?
