### ISSUE TITLE
KNX needs redeployment and stops communicating with bus for unknown reason 

### ISSUE THREAD

**Issue by airspacetech** [Supergiovane/node-red-contrib-knx-ultimate#330]
Hello ! been loving the knx ultimate node not sure why but i need to randomly redeploy my node red after sometimes days sometimes weeks 

stops getting values from knx bus randomly 

not sure how to reproduce

 Node-Red running alone in RaspberryPi

-> id: 5f489a2ba521ec2b
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 192.168.20.106
-> port: 3671
-> physAddr: 1.1.244
-> hostProtocol: TunnelUDP
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> stopETSImportIfNoDatapoint: stop
-> loglevel: debug
-> name: KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 50
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: undefined
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> changed: false
-> credentials: [object Object]
-> infoEditor: [object Object]
-> id: 5f489a2ba521ec2b
-> type: knxUltimate-config
-> info: undefined
-> users: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
-> _config: [object Object]
-> host: 192.168.20.106
-> port: 3671
-> physAddr: 1.1.244
-> hostProtocol: TunnelUDP
-> suppressACKRequest: false
-> csv: 
-> KNXEthInterface: Auto
-> KNXEthInterfaceManuallyInput: 
-> stopETSImportIfNoDatapoint: stop
-> loglevel: debug
-> name: KNX Gateway
-> localEchoInTunneling: true
-> delaybetweentelegrams: 50
-> delaybetweentelegramsfurtherdelayREAD: 1
-> ignoreTelegramsWithRepeatedFlag: false
-> keyringFileXML: undefined
-> knxSecureSelected: undefined
-> autoReconnect: yes
-> label: function () {
            return typeof this.name === undefined ? (this.host + ":" + this.port) : this.name + " " + (this.host + ":" + this.port);
        }
-> _def: [object Object]
-> _: function(){var e=Array.prototype.slice.call(arguments,0),t=e[0],o=(-1===e[0].indexOf(":")&&(e[0]=i+":"+e[0]),RED._.apply(null,e));return o=o===e[0]?t:o}
-> valid: true
-> validationErrors: 
-> dirty: true
-> changed: false
-> credentials: [object Object]
-> infoEditor: [object Object]

**Comment by Supergiovane** [comment]
Hi
I need to know your node-red version, node version, knx-ultimate version and the make/model of your knx/ip interface. 
This behavior is not normal.

**Comment by airspacetech** [comment]
Node red V 3.1.3  knx ultimate 2.4.5 beta-1 knx interface is a WEINZIERL 752

Thank you,
Jamie

Jamie Thorp
Director
Airspace Technical Solutions Pty Ltd




[Icon  Description automatically ***@***.***>

***@***.******@***.***>



[Icon  Description automatically generated]<https://goo.gl/maps/ctgNHcWEZiHhwwEs8>

Factory 7
490 Frankston-Dandenong Road
Carrum Downs VIC 3201



[Logo, icon  Description automatically generated]

0424 913 848



[Icon  Description automatically generated]

1300 560 221



[Icon  Description automatically generated]<https://www.instagram.com/createautomation/>

[Logo, icon  Description automatically generated]<https://www.facebook.com/people/Airspace-Technical-Solutions/100066987246382/>

[Icon  Description automatically generated]<https://www.linkedin.com/company/airspace-technical-solutions/>









[Logo  Description automatically generated]<https://www.airspacesolutions.com.au/>

www.airspacesolutions.com.au<http://www.airspacesolutions.com.au>

[Logo  Description automatically generated][Icon  Description automatically generated][Logo  Description automatically generated]

**Comment by Supergiovane** [comment]
Hi
please look at this thread
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/78#issuecomment-641957072

You need to either update the firmware of your KNX/IP interface, or enable the "suppress ack". You can find this option here:
<img width="567" alt="Node-RED___Avvio" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/b2869ff1-135f-4cd3-aeac-d3aff489e23b">

**Comment by airspacetech** [comment]
That’s awesome fingers crossed that fixes the problem

On 11 Feb 2024, at 8:35 pm, Massimo Saccani ***@***.***> wrote:

﻿

Hi
please look at this thread
#78 (comment)<https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/78#issuecomment-641957072>

You need to either update the firmware of your KNX/IP interface, or enable the "suppress ack". You can find this option here:
Node-RED___Avvio.png (view on web)<https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/b2869ff1-135f-4cd3-aeac-d3aff489e23b>

**Comment by Supergiovane** [comment]
Hi
have you managed to solve the issue?

**Comment by airspacetech** [comment]
Not quite sure yet, inconclusive. Will update you as soon as I know it’s ok. Thank you for reaching out!

Kind regards,
Jamie

[signatureImage]
________________________________

**Comment by Supergiovane** [comment]
Hi
please update to the last 2.4.5 version and let me know.

**Comment by airspacetech** [comment]
Is there a changelog for the update ?

On 17 Feb 2024, at 6:23 am, Massimo Saccani ***@***.***> wrote:

﻿

Hi
please update to the last 2.4.5 version and let me know.

**Comment by airspacetech** [comment]
Hi Massimo

Just a update it appears everything has been stable now thank you for your support very happy

On 24 Feb 2024, at 1:46 am, Massimo Saccani ***@***.***> wrote:

﻿

Closed #330<https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/330> as completed.
