### ISSUE TITLE
Can not bind to interface inside Docker container

### ISSUE THREAD

**Issue by 0per8or** [Supergiovane/node-red-contrib-knx-ultimate#331]
Hello,

I am running Node-RED inside a Docker container with multiple interfaces:

> ~ $ ip a
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
> 184: eth1@if185: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
>     link/ether 02:42:ac:10:00:0d brd ff:ff:ff:ff:ff:ff
>     inet 172.16.0.13/16 brd 172.16.255.255 scope global eth1
>        valid_lft forever preferred_lft forever
> 186: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
>     link/ether 02:42:c0:a8:0b:80 brd ff:ff:ff:ff:ff:ff
>     inet 192.168.11.128/24 brd 192.168.11.255 scope global eth0
>        valid_lft forever preferred_lft forever

To use Multicast I need to bind KNX Ultimate a specific interface. When I open the Gateway configuration I can chose between 'Auto' and 'Manually enter interface's name'. But unfortunately there is no text field to enter the name.

At the same time there is a exception in the log:

> ReferenceError: jListInterfaces is not defined
>     at /data/node_modules/node-red-contrib-knx-ultimate/nodes/commonFunctions.js:261:22
>     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
>     at next (/usr/src/node-red/node_modules/express/lib/router/route.js:144:13)
>     at Route.dispatch (/usr/src/node-red/node_modules/express/lib/router/route.js:114:3)
>     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
>     at /usr/src/node-red/node_modules/express/lib/router/index.js:284:15
>     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:346:12)
>     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:280:10)
>     at expressInit (/usr/src/node-red/node_modules/express/lib/middleware/init.js:40:5)
>     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:328:13)
>     at /usr/src/node-red/node_modules/express/lib/router/index.js:286:9
>     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:346:12)
>     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:280:10)
>     at query (/usr/src/node-red/node_modules/express/lib/middleware/query.js:45:5)
>     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:328:13)
>     at /usr/src/node-red/node_modules/express/lib/router/index.js:286:9
>     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:346:12)
>     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:280:10)
>     at Function.handle (/usr/src/node-red/node_modules/express/lib/router/index.js:175:3)
>     at Function.handle (/usr/src/node-red/node_modules/express/lib/application.js:181:10)
>     at mounted_app (/usr/src/node-red/node_modules/express/lib/application.js:237:10)
>     at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:328:13)
>     at /usr/src/node-red/node_modules/express/lib/router/index.js:286:9
>     at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:346:12)
>     at next (/usr/src/node-red/node_modules/express/lib/router/index.js:280:10)

**Knx-Ultimate Version**
 - 2.4.5-beta.1

**Docker Image**
- nodered/node-red

**Comment by Supergiovane** [comment]
Hi
The is unable to list the docker’s eth interfaces. 
Usually, the interfaces listing returns a list everytime. 
I’m taking a look and let you know…

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate-2.4.5-beta.2 is out in minutes, with the fix.
Thank you for reporting that.

**Comment by 0per8or** [comment]
Wow, thank you for your quick support! Works like a charm!
