### ISSUE TITLE
HUe not working

### ISSUE THREAD

**Issue by dembach** [Supergiovane/node-red-contrib-knx-ultimate#335]
HI there, 
i have got a slight problem with my Hue Bridge V2 using it in KNX-Ultimate.

I was Able to create a new configuration and add the Hue Bridge with the connect fuction.,

but afterwards, i.e. adding a HueLight , when i try to select the Light via the Name, i get an error on the debug page:

"Warn KNXUltimateGetResourcesHUE serverId is null"

![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/8998117/4ea86d3d-b7db-43e2-af21-7471b70e1cfe)

thanks

Markus

**Comment by Supergiovane** [comment]
Hi
have you tried restarting node-red?

**Comment by Supergiovane** [comment]
...and... on which node you see the problem?

**Comment by Supergiovane** [comment]
...and... what version of knx-ultimate are you running?

**Comment by dembach** [comment]
Perfect Support... how can i help you on the Project ?
got KNX Secure Router and Devices if needed. (but turned it of for testing reasons in search of the perfect solution)

**Comment by dembach** [comment]
Fastest Support ever !!!!!!

**Comment by Supergiovane** [comment]
Hi
thank you for the "Secure" offer, but we're already working on that.
