### ISSUE TITLE
Hue Temperature not set in night mode if brightness is 0% (off)

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#338]
Hi, I have a problem using night mode.

WHAT I SET
day: turn on at 100%, 3500K
night: turn on at 0%, 2200K
this because in the same GA some lights will turn on at 5%, other at 0% but ready (tempertature) to be dimmed up with the other at 5% if I need to increase the total light in a soft way.

WHAT I GET
day: turn on at 100%, 3500K
night: turn on at 0%, 3500K
I will start dimming and the 0% light will go to 5%, aligning the birghtness with the other in the same GA, but they will be at 3500K

It seems that if a brightness is set to 0, no temperature is passed. I don't know if Philips API want the light to be >0% for passing the temperature.
Thank you!

**Comment by Supergiovane** [comment]
Hi Enrico
I’ll take a look tomorrow…

**Comment by Supergiovane** [comment]
Hi Enrico
i don't have forgot... i'm just a little busy...

**Comment by evazzoler** [comment]
> Hi Enrico i don't have forgot... i'm just a little busy...

Absolutely no worries!
Have a nice day!

**Comment by Supergiovane** [comment]
Should be fixed with node-red-contrib-knx-ultimate@2.4.7 out now.
Bye.

**Comment by evazzoler** [comment]
> Should be fixed with node-red-contrib-knx-ultimate@2.4.7 out now. Bye.

Sorry but the behaviour is still unwanted: now the light set to "0% off" is turning on at 5%. The light is a GU10 white (Hue ambiance spot).

**Comment by evazzoler** [comment]
It happens with every kind of lamp, not only GU10 White.

**Comment by Supergiovane** [comment]
Hi
Setting color temp while lamps are off, is not allowed by the hue api’s, so i had to pass ON with 0% dimming and the Kelvin temp. 
If it is incasinating your lights, i need to follow another route…

**Comment by Supergiovane** [comment]
You can temporary revert back by intakling 2.4.8

**Comment by Supergiovane** [comment]
Hi Enrico
Are you able to paste some files into your Node-Red machine? If yes, please uzip the content of this ZIP
[knxUltimateHueLight.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/14755757/knxUltimateHueLight.js.zip)
into your **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder and restart node-red.
Then let me know. Thanks.

**Comment by evazzoler** [comment]
Ok, tomorrow I'll have all the time for doing this.

Il 26 marzo 2024 10:18:14 CET, Massimo Saccani ***@***.***> ha scritto:

**Comment by evazzoler** [comment]
Hi,
unfortunately the behaviour is returned as when the issue was opened.
But... If the API don't support that, don't worry. You don't should fix philips issues... ;-)

**Comment by Supergiovane** [comment]
Hi Enrico
Does your GU10 belonging to a group, or are they alone?

**Comment by Supergiovane** [comment]
Hi Enrico
I've tested again with grouped light and it works flawlessy.

**Comment by evazzoler** [comment]
> Hi Enrico Does your GU10 belonging to a group, or are they alone?

It is not a hue group, both ligts (5% and 0%) share the same GA.

**Comment by evazzoler** [comment]
> Hi Enrico I've tested again with grouped light and it works flawlessy.

Are you sure that I had to deploy only one file?

**Comment by Supergiovane** [comment]
Can U please upgrade to the latest 2.4.9?

**Comment by evazzoler** [comment]
You did It! You won!

(Please, contact me in pvt - I don't know how to do that - I promised some chinotto to you)

**Comment by Supergiovane** [comment]
maxsupergiovane chiocciola icloud.com
