### ISSUE TITLE
After the configuration is complete, the IP router connection is successful, but true or false is sent, debug can receive the data, but the module does not operate

### ISSUE THREAD

**Issue by ipbear** [Supergiovane/node-red-contrib-knx-ultimate#339]
[
    {
        "id": "3f592d2303081b6f",
        "type": "knxUltimate",
        "z": "9c5e78e10790bfc2",
        "server": "a20e280382e0ccd5",
        "topic": "1/0/0",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": "1",
        "notifyreadrequest": true,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "第一路",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "yes",
        "x": 710,
        "y": 280,
        "wires": [
            [
                "30cb8e90c7366c0c"
            ]
        ]
    },
    {
        "id": "b26fc251a8e33937",
        "type": "inject",
        "z": "9c5e78e10790bfc2",
        "name": "true",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "write",
        "payload": "true",
        "payloadType": "bool",
        "x": 450,
        "y": 240,
        "wires": [
            [
                "3f592d2303081b6f"
            ]
        ]
    },
    {
        "id": "9f8e9d875c9836b3",
        "type": "inject",
        "z": "9c5e78e10790bfc2",
        "name": "false",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "write",
        "payload": "false",
        "payloadType": "bool",
        "x": 490,
        "y": 340,
        "wires": [
            [
                "3f592d2303081b6f"
            ]
        ]
    },
    {
        "id": "30cb8e90c7366c0c",
        "type": "debug",
        "z": "9c5e78e10790bfc2",
        "name": "debug 1",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 1100,
        "y": 280,
        "wires": []
    },
    {
        "id": "a20e280382e0ccd5",
        "type": "knxUltimate-config",
        "host": "224.0.23.12",
        "port": "3671",
        "physAddr": "15.15.22",
        "hostProtocol": "Multicast",
        "suppressACKRequest": false,
        "csv": "\"Group name\"\t\"Address\"\t\"Central\"\t\"Unfiltered\"\t\"Description\"\t\"DatapointType\"\t\"Security\"\n\"回路测试\"\t\"1/0/-\"\t\"\"\t\"\"\t\"\"\t\"\"\t\"Auto\"\n\"switch 1\"\t\"1/0/0\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"switch 2\"\t\"1/0/1\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"回路3\"\t\"1/0/2\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"回路4\"\t\"1/0/3\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"回路5\"\t\"1/0/4\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"回路6\"\t\"1/0/5\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"回路7\"\t\"1/0/6\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\"回路8\"\t\"1/0/7\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\t\"Auto\"\n\n",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "error",
        "name": "",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "50",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "autoReconnect": "yes"
    }
]

**Comment by Supergiovane** [comment]
Hi
i think i've not understood what you said.
Please follow the rule in the issue page. I need that info.
<img width="1122" alt="New_Issue_·_Supergiovane_node-red-contrib-knx-ultimate" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/66039d1e-d5aa-4f36-a4c0-571eb95f4bd3">
