### ISSUE TITLE
DPT 9.007 Humidity

### ISSUE THREAD

**Issue by svenflender** [Supergiovane/node-red-contrib-knx-ultimate#34]
Hi,

i have a Problem with Humidty DPT 9.007. I got the raw value 0x70 but the payload is empty.
Is this my fault from knx or is it perhaps an calc error in the dpt sorcecode?

thx for your help an best Regards
Sven

**Comment by svenflender** [comment]
i have found my issue.

It is not DPT 9.007, ETS use the DPT 5.001.

**Comment by Supergiovane** [comment]
Ok 👍🏻

**Comment by svenflender** [comment]
Thx for the great Node! Its Awesome.
