### ISSUE TITLE
About Havc Modes

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#341]
Hi 

I would like to ask if the data content of DPT 238.102 and DPT 20.105 are the same?
Where can I view the data content of DPT 238.102?

Best Regards

**Comment by Supergiovane** [comment]
HI SONGZ!!!
The mail group address is the same "238", so they use the same encoding/deconding.
I've not understood your answer, sorry...

**Comment by songzh96** [comment]
Thanks !!
I just tested it and it works. The data content is the same as DPT 20.105
0-Auto
1-Heat
3-Cool
9-Fan
14-Dry

Best Regards
