### ISSUE TITLE
KNX TS support

### ISSUE THREAD

**Issue by robertsLando** [Supergiovane/node-red-contrib-knx-ultimate#342]
Hi everyone, I have been working on a PR to add TS support on knx.js. Would you mind to check it out and test it?

https://github.com/ekarak/knx/pull/2

**Comment by Supergiovane** [comment]
Hi
KNX-Ultimate isn't based on knxjs by Elias.
Thank you anyway.

**Comment by robertsLando** [comment]
Sorry for the mistake, I saw your repo listed on dependent repos but maybe you are using it on an example or elsewhere.
