### ISSUE TITLE
Send write TypeError: value.toFixed is not a function

### ISSUE THREAD

**Issue by andreklug** [Supergiovane/node-red-contrib-knx-ultimate#344]
Hi @Supergiovane 

I am using node-red-contrib-knx-ultimate  for a long time already, so first thank you for this very useful project! 

Recently I realised that some KNX values don't get updated anymore:

<img width="1824" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/e501afaf-e8a3-4f26-a62d-f192044f2ce3">

What all of them have in common is that they are using DPT 9.001 (Temperature °C)

As you see in the screenshot, the error message is the same for them: Send write TypeError: value.toFixed is not a function

**To Reproduce**

I am not sure if this can be reproduced but will be happy to provide any log files you need.

**Knx-Ultimate Version**
 - Currently 2.4.19
 - according to the data that hasn't been logged tos goes back to March 18, at which I believe I updated to the current version of that time.

**Are you running node-red behind homematic, docker or anything similar?**

Node-Red runs in a Proxmox LVM Container, for years (no recent change here)

**Additional context**
I believe the only change I did was updatingf a few weeks back, after not updating for a few weeks - months before that. The configuration of the data that is sent to node-red-contrib-knx-ultimate hasn't changed for a few years.

Thank you for looking into this!

**Comment by Supergiovane** [comment]
Hi i’ll take a look tomorrow morning!

**Comment by andreklug** [comment]
Wow, that was quick. Everything is green now. 

Thank you very much!!!
