### ISSUE TITLE
4-Byte Values from KNX are sent as 0 

### ISSUE THREAD

**Issue by andreklug** [Supergiovane/node-red-contrib-knx-ultimate#345]
Hi @Supergiovane 

**Describe the bug**
I am using the node-red-contrib-knx-ultimate node to read from the bus in Universal mode. The output is written to a log file (as decribed in #344)
It works fine so far, but the output for 4-Byte values is "0". As an example, "DPT13.013 Active energy (kWh)".

Here are some screenshots showing my configuration:

ETS:
<img width="754" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/c9eba497-8da6-4dda-a666-b0aee368276e">

Node config: 
<img width="504" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/6aa701a9-f823-4ec9-9b7e-9eb86285d5fa">

ETS import:
<img width="505" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/33b63978-6aef-4554-9863-b1e2370fca7b">
(I am not sure how "uncertain" affects the result)

knx log tail:
<img width="408" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/98c54abe-fc9d-4569-be52-f119d3f0d56a">

Logging config:
<img width="758" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/17cd2a31-90bf-4115-be1f-3cc89b26f47d">

The "alles loggen" sends directly to InfluxDB (same result), while everything below works towards the log file.

**Knx-Ultimate Version**
 - 2.4.20
 - **EDIT: I just updated to 2.4.21 with the same outcome**

**Are you running node-red behind homematic, docker or anything similar?**
LVM container in Proxmox

Thank you for looking into this!

**Comment by Supergiovane** [comment]
Hi!
Let me check... then i return to you as soon as possible.

**Comment by Supergiovane** [comment]
Hi,
do you have imported the ETS csv file?

**Comment by andreklug** [comment]
Hi, I was about to say yes because the (last used) export settings in ETS look exactly like the screenshot you put in the docs. But it also was a long time ago. 
However, after export the file looks different than what I have in the KNX Gateway config. I will import again and get back to you.

**Comment by andreklug** [comment]
When importing the content from the CSV "as is" I am getting a lot of errors:

<img width="293" alt="grafik" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/13343357/b1f94f68-126f-44e2-9c51-3c7f286ba7d5">

I think I have to go through them one by one and make sure the DPT is set. As the debuggin tab in NR keeps flushing periodically, is there another way to see a log for the import?

Not sure if any of the DPT13 lines is affected, because they are set correctly in KNX.

**Comment by Supergiovane** [comment]
**node-red-log -n 1000**
in a terminal window. You should see the log.

**Comment by Supergiovane** [comment]
I've tested now, and with the correct ETS csv file, it works.
You can try, by adding this row into the ETS field of your gateway config window
"BANANA"	"7/0/47"	""	""	""	"DPST-9-2"	"Auto"

**Comment by andreklug** [comment]
You are correct: My way of importing before was wrong. After this most recent import, the 4-Byte values show up as they should. 
The issue is solved, thank you very much!!!

**Comment by Supergiovane** [comment]
You're welcome.
