### ISSUE TITLE
Hue Button/Dimmer-Switch with integrated "inverter" option

### ISSUE THREAD

**Issue by cybersmart-eu** [Supergiovane/node-red-contrib-knx-ultimate#346]
Hi Max,

Thank you very much for the great node-red contribution.

I just started using it and a feature request came to my mind when I tried to use the Hue Button (in my case the Dimmer Switch with the Button node) to control my awning with two different Buttons (up and down).
The problem I faced was, that for each button I an only send a true but not a false (unless I switch toggle on, but I want seperate buttons where one only sends true, the other only sends false).

To overcome this I had to use an inverter and another KNX Ultimate node, but what would be great is if inside the Hue Button node (and maybe other nodes) I could just select to invert "internally" the boolean output if required.

Maybe worth to consider in an update.

Best Regards, Uwe
![KNX-HUE](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/77569473/bdff4745-1eca-495b-92c7-523639dfdb04)

**Comment by Supergiovane** [comment]
Hi,
Thanks for the hint and thanks for using my nodes. In the screenshot i see two nodes i developed, so thank you!
Will be out in next version...

**Comment by cybersmart-eu** [comment]
For donations: Is this paypal correct as the name seems different?
https://www.paypal.me/techtoday

**Comment by Supergiovane** [comment]
Yes that's mine!!

**Comment by cybersmart-eu** [comment]
Was my fault, I was checking for "Max" only :-)

**Comment by Supergiovane** [comment]
Thank you!! Appreciate that!

**Comment by cybersmart-eu** [comment]
Hi Max,

just updated and restarted node-red, but did not find the option to send false instead of true on button press with toggle "unchecked". I also tried the DataPoint "Invert" but still true is sent, not false.

Your documentation within node-red for the node also still says: 
"Enable or disable toggling values. If enabled, all values toggles, otherwise, **all values are sent as true or increase dim,** to the selected KNX group address".

Need a hint - what did I miss?

Uwe

**Comment by Supergiovane** [comment]
HI
ew you sure that the version is 2.4.22 ?

**Comment by cybersmart-eu** [comment]
Yes, showing 2.4.22 in the Palette.

**Comment by cybersmart-eu** [comment]
Ok, just reloaded the UI from Node-Red, it seems there was a browser cache issue, now I see the additional options underneath "toggle" check.box.

**Comment by Supergiovane** [comment]
<img width="646" alt="Node-RED___Avvio" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/42a8f27b-a71e-4822-bac7-baa856ef1991">

Good. You should see this.

**Comment by cybersmart-eu** [comment]
Exactly, this was (after Update and node-red restart) not visible in my browser before. 
I had to reload the UI again.

Working as expected, thanks for the quick implementation. 
Will also check more of your nodes now like TTS together with sonos. Great work.
