### ISSUE TITLE
Problem after Node-Red restart or deploy

### ISSUE THREAD

**Issue by VicoBox** [Supergiovane/node-red-contrib-knx-ultimate#352]
Hello Supergiovane! Thank you for developing powerful node.

I'm new to KNX router and node-red. recently, I noticed something strange.
When I redeploy or restart node-red, the knx device node connects normally(connected on duty), but it doesn't work well.
For the first 5 minutes, the telegram doesn't reach to knx bus, but I can get a telegram from knx.
After about 5 minutes, I can control the knx devices in the node red flow, the telegram will reach to knx, but I can't get any telegram from knx bus. There is no other warning or error log, only debug log. Do you know the solution for this problem?

I'm running node-red on the proxmox lxc and node-red version is up to date, knx ultimate node also is up to date.
If you need any futher information, please let me know.

**Comment by Supergiovane** [comment]
Hi
I’ve not enough infos, sorry. 
I need to know make/model of your knx gateway and your gateway config. A screenshot should be fine

**Comment by VicoBox** [comment]
Maybe it’s my proxmox setup problem. Running on raspberry pi is working well. Thank you for your supporting :)
