### ISSUE TITLE
KNX Scene n. 64 is missing in Hue Scene Node 

### ISSUE THREAD

**Issue by TechMoDev** [Supergiovane/node-red-contrib-knx-ultimate#353]
Hi Supergiovane,

You did a great job developing this software. Thanks for that !

Playing around with it, I noticed that the highest possible KNX Scene n. in the Hue Scene node is 63. Does that have a specific reason ?

In al lot of KNX installations I've seen lights dimming to 0% with scene 1 and to 100% with scene 64. As some kind of 'standard scene configuration'. Also in my personal KNX installation. To keep up with this 'scene standarisation' it would be nice to be able to select also scene 64 in the Hue Scene node.

Please let me know how you think about that.

Keep up the good work !

**Comment by Supergiovane** [comment]
Hi!
Thank you!
The max number of allowed scenes is 64.
Please let me some minutes to check it out...
