### ISSUE TITLE
KNX Gateway connection issue

### ISSUE THREAD

**Issue by TechMoDev** [Supergiovane/node-red-contrib-knx-ultimate#354]
Hi Supergiovane,

Thansk for solving issue #353 so quick :-)

Another issue I'm running into is that all from my KNX gateways devices the IP Tunneling connection is not stable.

Simple example.: When I send out a KNX telegram trough a KNX Device node, the send telegram becomes visible in ETS6 Diagnose. So far so good. But after I deploy some sketch changes the next send telegrams doesn't show up anymore in ETS6 Diagnose :-(

Sometimes it helps to change the KNX Physical Address according to another available one at the gateway. But not always.
Sometimes it helps to shutdown Node-RED for a while. But not always.
But what gives the best result is disabeling 'Echo sent message to all node with same Group Address'. But not always.

I've read a few other issues describing the same problem. You we're discussing about enabling/disabeling the 'Suppress ACK request in tunneling mode'. But that doesn't help also.

On the other hand, receiving telegrams from the bus to the gateway in Node-RED works in all the cases faultless.

I there a way to help you debugging this issue ?

My 3 possible gateways (all having the same issue):

- Weinzierl LineMaster 762
- 1Home Server
- iRidium Server UMC C3

Thanks !

**Comment by Supergiovane** [comment]
Hi
leave a part the multi purpose servers, like 1Home and iRidium... I've had multiple headache with such devices.
Can you please paste here your nodes? Are you able to do so?
