### ISSUE TITLE
Group Address Auto Fill not working with ETS3 CSV File Import

### ISSUE THREAD

**Issue by svenflender** [Supergiovane/node-red-contrib-knx-ultimate#36]
Hi,

for me the Autofill of Group Address is not working. DPT detection is working and the import has be done.
Any Idea?

Best Regards
Sven

**Comment by Supergiovane** [comment]
Hi Sven
Have you deployed using Full Deploy button in Node Red?

**Comment by svenflender** [comment]
Hi,

yes i have done a full deploy.

It is not the Full Code and i changed the group addresses due to Security ;)

Haus - Jalousien.KG - Jalousien.5/0/1	KG - Jalousie Kino - AUF/AB	EIS 1 'Switching' (1 Bit)	Low	5/4/50
Haus - Jalousien.KG - Jalousien.5/0/2	KG - Jalousie Kino - STOP	EIS 1 'Switching' (1 Bit)	Low	5/4/51
Haus - Jalousien.KG - Jalousien.5/0/3	KG - Jalousie Kino - AUF/AB M	Uncertain (1 Byte)	Low

**Comment by Supergiovane** [comment]
There are some issues in your file. 

Please try with mine here, then watch the video on how to export the ets file. The video is in the homepage of github knx ultimate. 

"Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security" "Attuatori luci" "0/-/-"	""	""	"Attuatori luci"	""	"Auto" "Luci primo piano"	"0/0/-"	""	""	"Luci primo piano"	""	"Auto" "Camera da letto luce"	"0/0/1"	""	""	"Camera da letto luce"	"DPST-1-8"	"Auto" "Loggia camera da letto" "0/0/2"	""	""	"Loggia camera da letto"	"DPST-1-1"	"Auto" "Camera armadi luce"	"0/0/3"	""	""	"Camera armadi luce"	"DPST-1-1"	"Auto" "Bagno grande luce"	"0/0/4"	""	""	"Bagno grande luce"	"DPST-1-1"	"Auto" "Loggia bagno grande"	"0/0/5"	""	""	"Loggia bagno grande"	"DPST-1-1"	"Auto" "Bagno grande specchio (switch)"	"0/0/6"	""	""	"Bagno grande specchio switch"	"DPST-1-1"	"Auto" "Lavanderia luce"	"0/0/7"	""	"" "Lavanderia luce"	"DPST-1-1"	"Auto" "Lavanderia specchio (switch)"	"0/0/8"	""	""	"Lavanderia specchio switch"	"DPST-1-1"	"Auto" "Studio luce"	"0/0/9"	""	""	"Studio luce"	"DPST-1-1"	"Auto" "Soggiorno luce (switch)"	"0/0/10"	""	""	"Soggiorno luce switch"	"DPST-1-1"	"Auto" "Soggiorno aplique (switch)"	"0/0/11" ""	""	"Soggiorno aplique switch"	"DPST-1-1"	"Auto" "Loggia soggiorno cucina"	"0/0/12"	""	""	"Loggia soggiorno-cucina"	"DPST-1-1"	"Auto" "Cucina luce"	"0/0/13"	""	""	"Cucina luce"	"DPT-1"	"Auto" "Cucina luce pensili"	"0/0/14"	""	""	"Cucina luce pensili"	"DPT-1"	"Auto" "Corridoio luce"	"0/0/15"	""	"" "Corridoio luce"	"DPST-1-1"	"Auto" "Scala LED"	"0/0/16"	""	""	"Scala LED"	"DPST-1-1"	"Auto" "Soggiorno aplique brighness value"	"0/0/17"	""	""	""	"DPST-5-1"	"Auto" "Bagno grande specchio (dim)"	"0/0/18"	"" ""	"Bagno grande specchio dim"	"DPST-3-7"	"Auto" "Soggiorno luce brighness value"	"0/0/19"	""	""	"" "DPST-5-1"	"Auto" "Lavanderia specchio (dim)"	"0/0/20"	""	""	"Lavanderia specchio dim"	"DPST-3-7"	"Auto" "Scala LED cambiacolori RGB"	"0/0/21"	""	""	""	"DPST-1-1"	"Auto" "Bagno grande specchio brightness value"	"0/0/22"	""	""	""	"DPST-5-1"	"Auto" "Soggiorno luce (dim)"	"0/0/23"	""	""	"Soggiorno luce dim" "DPST-3-7"	"Auto"

**Comment by svenflender** [comment]
In the ETS3 you have only these Options for a CSV Export

![image](https://user-images.githubusercontent.com/42860703/74364220-6a481f00-4dcc-11ea-9d5b-5de91b597bd8.png)

**Comment by svenflender** [comment]
I have found the way i can export the 1/1 csv in the ETS3 But it is still not working.

That is how the export look like from the ETS3.

"Group name"	"Address"
Haus - Jalousien	5/-/-
KG - Jalousien	5/0/-
KG - Jalousie WC - AUF/AB	5/0/1
KG - Jalousie WC - STOP	5/0/2
KG - Jalousie WC - AUF/AB M	5/0/3

**Comment by Supergiovane** [comment]
So that’s definately incompatible with ETS3. 
There is no “” in the device name and there’s no datapoint.

**Comment by svenflender** [comment]
I have updated to ETS5 and now i have some homework to do. I have to specify all the DTP in the GA.

I will close this Issue.

**Comment by Supergiovane** [comment]
Good! You’ll never regret!
Yes DpT are mandatory and you’ll enjoy how well your visualization and control devices performs, with right dpt!
