### ISSUE TITLE
Custom DPT support

### ISSUE THREAD

**Issue by ede1998** [Supergiovane/node-red-contrib-knx-ultimate#360]
Hello @Supergiovane,
Thanks for merging my PR recently.

**Is your feature request related to a problem? Please describe.**

Just noticed that I have an actuator (Hager TXA223/225) for roller shutters in my KNX network that uses a non-standard message format to report its position.
How can I handle parsing with `node-red-contrib-knx-ultimate`?

**Describe the solution you'd like**

Is there support for arbitrary custom DPTs? i.e. can I just provide my own DPT parser/serializer function somehow? What's your recommended approach? Didn't find anything like that at the first glance through the code/docs/issues.

**Describe alternatives you've considered**

Can I add my custom DPT to your DPT library? I see that there is another custom DPT already there (`6001.001` I think). Though I don't know if there is any special DPT value assigned in ETS for my custom message. In the CSV export it reports as `5.001`

**Additional context**
Details for the DPT (sorry, only found a German description):
![Table describing meaning of bit patterns](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/26464515/bfadea55-3827-4ef4-a558-b386195f820b)

- P: Position
  - 00 = in between
  - 01 = top-end
  - 10 = bottom end
- M: Operation Mode
  - 000 = Normal
  - 001 = Priority
  - 010 = Wind Alarm
  - 011 = Rain Alarm
  - 100 = Disabled

Screenshot from this PDF: <https://hager.com/intl-en/products/download/product/asset/file/TXA223_225_ETS_ROLLLADEN_IND_A_DE.PDF>

**Comment by Supergiovane** [comment]
Hi
Ylu can either use raw messages (please see the wiki), or add your own datapoint and make a PR
Thanks

**Comment by ede1998** [comment]
Thanks for the quick answer. I'll check it out tomorrow.
