### ISSUE TITLE
Support parameters from env variables

### ISSUE THREAD

**Issue by Alloc86** [Supergiovane/node-red-contrib-knx-ultimate#365]
Hi Massimo,

another thing that working on my changes brought up. I know you personally don't really like subflows (at least you stated that a few years in the past :D ), but at least for me that would be tremendously helpful. No idea how complex supporting this would be though.

**Is your feature request related to a problem? Please describe.**
Currently when I use subflows that take GA numbers as parameters I have to build "complex" structures in the subflow to get those GAs used by the KNX nodes inside.
Example:
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5400030/bb39a0df-9b06-41fa-9e47-8f58a9b4ba29)
The inject nodes make sure the KNX nodes get their config set properly (using `setConfig.setGroupAddress=env.get("GaStatusHelligkeit")`). The switch on the output of the lower one makes sure it drops the KNX node output for the config message (i.e. filters messages with `msg.event == "Update_NoWrite"`).

**Describe the solution you'd like**
I would love if the KNX node would support using the env variables directly like most other Node RED nodes do.
I.e. support selecting the kind of input on the "Group Addr." field in the node config like here:
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5400030/57ddc73e-2378-4f67-be3b-aefcea77b9d5)
So switch between string and env. var.

**Describe alternatives you've considered**
Alternative currently is as shown above: Add two nodes before each KNX node to set up config, one after to filter the Update message it causes. Works, but it's quite a lot of additional stuff :D 

Would be great if that could be added to v3, even though obviously I can work around if not :)

**Comment by Supergiovane** [comment]
Noted...

Do you know, there is a "Global Context Variable node" as well?
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/GlobalVariable
Maybe it can help you.

**Comment by Alloc86** [comment]
Yeah, using that for some other stuff. But it would not help here as I would have to poll that myself instead of getting notified for changes to a few specific GA :)

**Comment by Supergiovane** [comment]
Hi
do you know, environment variables are read at node-red start as readonly? You can set the env variables using at Flow level, for example, but then **you cannot** change it at runtime using, for example **env.set("MyVar","MyValue")**. Env.set doesn't' exists.

**Comment by Alloc86** [comment]
Yes, but for use with subflows that's perfectly fine as subflows get their env variables set by the subflow instance configuration. That's how one can make subflows reusable other than feeding everything into them from the outside.

**Comment by Supergiovane** [comment]
Hi
You'll be able to select env, global, flow beside string topic type.
When you select "env", "global" or "flow", the datapoint **will be automatically set**, based on ETS file.
It's ok for you?

<img width="477" alt="Node-RED___Flow_4" src="https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/37666636/50a77a77-902b-4acf-8b84-8e337e338061">

**Comment by Alloc86** [comment]
That looks really awesome!

**Comment by Supergiovane** [comment]
Hello,

[Archivio.zip](https://github.com/user-attachments/files/15918169/Archivio.zip)

if you feel comfortable, you can unzip this archive into your **.node-red/node_modules/node-red-contrib-knx-ultimate/** folder. 

Then, from a command line terminal, cd into *.node-red/node_modules/node-red-contrib-knx-ultimate* and type: `npm install`

**Comment by Alloc86** [comment]
Thank you a lot!
Actually right now I do not really have the spare time to do experiments (mother's birthday on sunday, but overall busy with work as we have a major release this weekend and bug fixing the following weeks most likely :D ), but I appreciate the option. Maybe I get around to it next weekend.

Curious, is that package based on the new "KNX engine"? Is that like a rewrite of the core code?

**Comment by Supergiovane** [comment]
Anyway, the new version 3.0.0 will be out today with your two issues addressed.
The "new" KNX engine is a port from javascript to typescript. Is not actually "new".
TypeScript should allow me to do less errors when adding new things. It should also (hope until the end of 2024) accomodate the KNX secure protocol.

**Comment by Supergiovane** [comment]
Hi
v3.0.0-beta1 is out.
I'm closing this issue. If you encounter problems, feel free to reopen it.

**Comment by Alloc86** [comment]
Confirmed working so far, thank you!

**Comment by Alloc86** [comment]
Actually ... looks like something got broken with the "old" way to set a nodes group address though.
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5400030/f4fec1f4-57a8-4488-b648-e0d1ee178284)
Sending that to a device node like this (unchanged from before the update):
![image](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/5400030/17564673-f29a-4e1b-961b-ddcf2ff19d0a)
And the node does no longer output anything when there is a write on the GA, no matter if from the bus or from Node RED itself.

**Comment by Supergiovane** [comment]
I’m checking…

**Comment by Alloc86** [comment]
Please don't hit me ... but it was my fault :D 
I forgot you told me to use setDPT = auto now :)

**Comment by Supergiovane** [comment]
Oh, good. I remember that it passed all unit tests. :-)

**Comment by Supergiovane** [comment]
It should be wrote in the node-red's help panel as well.

**Comment by Alloc86** [comment]
Indeed, you just don't think you'd done something wrong when not changing anything but updating the third-party node :D 
Thanks again for these changes, it really helped clean up a lot of my shit! And many thanks for all your hard work on this node in general!
