### ISSUE TITLE
Node-RED crashes when tryomg to connect to an interface with no more free connections

### ISSUE THREAD

**Issue by Demonyck92** [Supergiovane/node-red-contrib-knx-ultimate#368]
Hi,
I'm a systen integrator and I use KNX very often at work and at home.

As title describes, when I try to connect to an interface with no more free connections the whole Node-RED crashes. I've a Zennio ALLinBOX 1612 with 6 available tunnel connections simultaniously, each one with its own physical address; If I try to connect to the one used by ETS (for example) the whole Node-RED instance crashes.

**To Reproduce**
1. Get a KNX tunnel interface
2. Connect to it with ETS (Telegrams monitor for example)
3. Create a KNX Ultimate configuration node for the same interface with the same physical address
4. Create at least one node that uses the configuration node created at previous step (I used the Watchdog node with manual connection to control the error throw
5. Deploy the flow (connect the watchdog node if required)

**Expected behavior**
Error message on Node-RED console and nodes, not the whole Node-RED crashing, at least the rest can still run

**Screenshots**
![immagine](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/assets/67932432/d4355837-d4c9-4d12-aa23-42c1b95f807f)

**Knx-Ultimate Version**
3.0.2

**Are you running node-red behind homematic, docker or anything similar?**
The same issues appears on linux (Ubuntu), Windows (Win10), and docker

**Comment by Supergiovane** [comment]
Hi
your KNX/IP interface has ran out of free connections. Do you really need 6 open connections?

**Comment by Supergiovane** [comment]
V. 3.0.3 should have fixed that.

**Comment by Supergiovane** [comment]
3.0.3 is out. Thank you for pointing me this out.
