### ISSUE TITLE
HUE Bridge not Syncing initially

### ISSUE THREAD

**Issue by vinc32** [Supergiovane/node-red-contrib-knx-ultimate#371]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**
Hi Team ;) 
Thanks for the fantastic Job!

**Describe the bug**
When Connecting HUE Bridge with Node-Red it fails.

"Wait, i'm talking to your HUE bridge..."
"Something went wrong. Please make sure the HUE bridge connection is properly configured. For further info, see the node-red log. IF YOU ARE CREATING A NEW HUE CONFIGURATION NODE, PLEASE DEPLOY AND RETRY."

**To Reproduce**
Click on Add Bridge
Enter IP
Click Register
Click Button on Hue
Click OK
Click Add
-> "Wait, i'm talking to your HUE bridge..." -> after 1 min
-> "Something went wrong. Please make sure the HUE bridge connection is properly configured. For further info, see the node-red log. IF YOU ARE CREATING A NEW HUE CONFIGURATION NODE, PLEASE DEPLOY AND RETRY."

**Expected behavior**
Connect HUE Bridge with Node-RED

**Screenshots**
<img width="895" alt="Bildschirmfoto 2024-08-18 um 13 43 04" src="https://github.com/user-attachments/assets/853a1d8e-382e-4139-bd59-8319d50f5118">

**Knx-Ultimate Version**
 - 3.1.0

**Are you running node-red behind homematic, docker or anything similar?**
 - in HomeAssistant as AddOn

**Additional context**
Tried Reboot and adding it again.
Debug Log - empty

**Comment by vinc32** [comment]
Opening https://hue-ip/api/config it shows SSL Issue and config

{"name":"hueEG",
"datastoreversion":"168",
"swversion":"1965111030",
"apiversion":"1.65.0",
"mac":"xxxxxx",
"bridgeid":"xxxxxxx",
"factorynew":false,
"replacesbridgeid":null,
"modelid":"BSB002",
"starterkitid":""}

**Comment by Supergiovane** [comment]
Hi
If node-red can reach the 10.0.0.40, you shouldn’t have any issue. 
Have you tried restarting the pc?

**Comment by Supergiovane** [comment]
Hi
Does it work now?

**Comment by vinc32** [comment]
Reboot did not work -
It worked the following way - I’ve just pressed deploy and it started to work.
