### ISSUE TITLE
When I try npm install I get the warning: inflight@1.0.6: This module is not supported, and leaks memory. Do not use it.

### ISSUE THREAD

**Issue by Rubathas** [Supergiovane/node-red-contrib-knx-ultimate#372]
Hello there !

**Describe the bug**
I cannot install this Node Red library/palette ("node-red-contrib-knx-ultimate"). 

**To Reproduce**
I am trying to install the npm module through terminal
1. `sudo npm -g install node-red-contrib-knx-ultimate`

I receive the following error
`npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.`

`npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported`

Node-Red running on my Mac (Mac OS 14.4.1)

![image](https://github.com/user-attachments/assets/1960958f-97bf-4886-b791-5689731424a2)

**Comment by Supergiovane** [comment]
Hi
it should be an old dependency.
Please install node-red-contrib-knx-ultimate@3.1.6 as soon as you see it in the palette.
