### ISSUE TITLE
"Read status on start" -> "Read from KNX Bus" doesn't work with Version 3.2.1

### ISSUE THREAD

**Issue by Lorilatschki** [Supergiovane/node-red-contrib-knx-ultimate#374]
**First of all, thanks for your great work on this node-red module!**

**Describe the bug**
After updating from v3.2.0 to v3.2.1 I do not recieve any value on start of the node-red container. For my dashboard this is required, therefor I have configured the nodes to "Read status on start" -> "Read from KNX Bus".

**To Reproduce**
Add a debug node to the output of a KNX DEVICE. Setup the option "Read status on start" -> "Read from KNX Bus". Just update to v3.2.1 and restart node-red. After restarting the debug output isn't shown. 

**Expected behavior**
After some seconds the current value from the KNX BUS address shall be shown to the debug output.

**Knx-Ultimate Version**
 - Eg. 3.2.1

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red running on a RaspberryPi inside a docker container (nodered/node-red:latest)

**Additional context**
After reverting to 3.2.0 everything works as expected. I can try to post debug informations with the v3.2.1 today evening.

**Comment by Supergiovane** [comment]
Hi
I’m taking a look now. 
In the meantime, you can downgrade to 3.2.0

**Comment by Supergiovane** [comment]
Hi,
mine works.
https://github.com/user-attachments/assets/6ceaaed5-2a29-46df-97a7-408b1a568a20

Do you have set the nodes like this?

<img width="543" alt="Node-RED___Flow_1" src="https://github.com/user-attachments/assets/36a4f52c-ced1-46d6-a371-25b667e3271f">

**Comment by Lorilatschki** [comment]
Yes I did. Maybe it is related since I am running node-red inside a docker container rather than directly on a raspberry PI.
![image](https://github.com/user-attachments/assets/8f657c34-eb01-442c-b857-078053b43a99)

**Comment by Supergiovane** [comment]
Hmm... nope.
Please, try to disable the RBE filter..

**Comment by Supergiovane** [comment]
Or, as you're alredy downgraded, i need the node-red log (**node-red-log -n 2000**)
2000 rows should be enough to trap the log of the version 3.2.1

**Comment by Lorilatschki** [comment]
Will try it once I am back home today evening and post the log here.

**Comment by Lorilatschki** [comment]
Even after disabling the RBE filter, it doesn't work. Attached are the logs of both v3.2.0 and v3.2.1.
[knx_log_3.2.1.txt](https://github.com/user-attachments/files/17007001/knx_log_3.2.1.txt)
[knx_log_3.2.0.txt](https://github.com/user-attachments/files/17007002/knx_log_3.2.0.txt)

**Comment by Lorilatschki** [comment]
BTW: It might be related, I am wondering why the version 3.2.1 is shown as unused after installing it. For version 3.2.0 it doesn't show the remove button.
![image](https://github.com/user-attachments/assets/0a69ddc4-8e42-40ca-b199-b8d50430b236)

**Comment by Supergiovane** [comment]
Hmmmm. That’s strange. It seems some issues with node-red plugin registration. 
Nothing has changed in the “read” KNX process. 
Tomorrow i’ll check the logs better.

**Comment by Supergiovane** [comment]
I noticed this in the log: Delay handling queue. YOUR COMPUTER COULD BE TOO SLOW OR BUSY TO KEEP UP WITH THE STRICT TIMING, REQUIRED FOR KNX TO FUNCTION PROPERLY.

If you’ve installed the 3.2.1, please increase this, for example, set it at 50ms 
It seems that your knx gateway cannot stand up to the telegegram’s rate. 


![image](https://github.com/user-attachments/assets/0cc8739f-390a-4f5f-9e60-874a958f5d56)

**Comment by Lorilatschki** [comment]
It is already configured to 50ms, I will try to increase it to 100ms and see what happens.

**Comment by Lorilatschki** [comment]
I have tried to setup the delay between each telegram to 50, 100 and 200ms. Nothing worked with v3.2.1.

**Comment by Supergiovane** [comment]
Hi
i think i found the issue.
Can you check whether your enabled this?

<img width="635" alt="Node-RED___Avvio" src="https://github.com/user-attachments/assets/21b81742-845e-459d-afee-d224f6c7dcb9">

**Comment by Lorilatschki** [comment]
This are my current settings which runs well with v3.2.0.
![image](https://github.com/user-attachments/assets/120249f1-1ed2-466a-9238-92ee65b5fd54)

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate 3.2.2 is out.
There was an issue with the KNX telegram's queue processing; the replies to the telegrams coming from the KNX Gateway, are now processed with priority. 
Can you try this version please?

**Comment by Lorilatschki** [comment]
Outstanding support! With version 3.2.2 the issue is solved. The issue with the unregistered plugin does still exist.
Many thanks!

**Comment by Supergiovane** [comment]
Good. Thank you to you to pointing me out this issue!
The issue with unregistered plugin is out of my control, sorry!
