### ISSUE TITLE
Temperature Payload Rounding Issue: 0.29C Sent as 0.28C on KNX Bus

### ISSUE THREAD

**Issue by SBliveNL** [Supergiovane/node-red-contrib-knx-ultimate#377]
Hello Massimo Saccani,

**Describe the bug**
I am experiencing an issue with the node-red-contrib-knx-ultimate node when trying to send a temperature value of 0.29°C to the KNX bus. The value is automatically rounded to 0.28°C, and it immediately jumps between 0.28°C and 0.30°C, making it impossible to accurately transmit the temperature value of 0.29°C.

**To Reproduce**
1. Deploy node-red-contrib-knx-ultimate (version 3.2.7) on a fully updated Raspberry Pi.
2. Send a payload of 0.29 (temperature) to the KNX bus.
3. Monitor the KNX bus and observe the transmitted value.
4. Notice how the value is rounded to 0.28°C or jumps between 0.28°C and 0.30°C.

**Expected behavior**
I expect the temperature value of 0.29°C to be transmitted to the KNX bus accurately without rounding or jumping between other values.

**Screenshots**
Unfortunately, I don't have screenshots available, but the issue can be consistently reproduced by sending the payload 0.29.

**Knx-Ultimate Version**
Version 3.2.7 (latest at the time of writing), but the issue is also present in earlier versions.

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red is running standalone on a fully updated Raspberry Pi.

**Additional context**
This behavior occurs regardless of other configurations, and the rounding of values seems to be an internal issue with how the payload is processed before being sent to the KNX bus.

**Comment by Supergiovane** [comment]
Hi
what DPT are you using ?

**Comment by SBliveNL** [comment]
Hi Massimo,
DPT 9.001 Temperature

**Comment by Supergiovane** [comment]
Hi
I've no issue with DPT9.001. Are you sure not having some actuator sending out a rounded value to the BUS?

<img width="869" alt="Node-RED___Flow_1" src="https://github.com/user-attachments/assets/049dfe2b-5206-487c-ad1a-700a1ba888b1">

**Comment by SBliveNL** [comment]
Sorry, I meant from Node-RED to KNX.

**Comment by Supergiovane** [comment]
Fixed here #https://github.com/Supergiovane/KNXUltimate/issues/32#issue-2590946000

In the upcoming version, the problem should be fixed.
