### ISSUE TITLE
HUE very slow after upgrade

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#378]
Hi,
I've upgraded today from 3.1.ciapelo to 3.2.7
Since the upgrade the response to HUE is very slow: a light take about 6-9 seconds to light up.
If I control a WLED light (knx -> knx-ultimate ->a lot of stuff of mine -> wled node) I see no delay. So it seems the problem is not on the knx-node side but the hue-node side.

**Comment by evazzoler** [comment]
After a downgrade to 3.1.9 everything restart working properly.

**Comment by Supergiovane** [comment]
Hi
Please double check the delay in the KNX gateway config node/Advanced. Make sure it is 30
