### ISSUE TITLE
KNX DEVICE NODE don't remember a setting

### ISSUE THREAD

**Issue by evazzoler** [Supergiovane/node-red-contrib-knx-ultimate#379]
Since a lot of versions, I report that the setting "read status on start" is always set to "no" when I open the node config.
When I set it to a different config "read from KNX BUS" and deploy, the setting return to "no" again.
Before I update to the latest version from an old version, the setting was working as set although "no" was shown, now the node don't read anymore the GAs at the start. It is fundamental importance for me in order to sync the GUI with the state of the plant.

**Comment by Supergiovane** [comment]
Hi Enrico
This is a very basic function and it hasn't changed since a while. Tried now and it's working. Could you please export the node where you encounter the problem and paste it here? I wanna see the json config.

https://github.com/user-attachments/assets/0f0850d0-900c-42ab-9ad0-ebda41213f2c

**Comment by Supergiovane** [comment]
PS: try accessing node-red via an incognito mode (i mean the browser's incognito function) and check if it works.

**Comment by Supergiovane** [comment]
Hi Enrico,

> Could you please export the node where you encounter the problem and paste it here? I wanna see the json config.

can you send it? Thanks.

**Comment by Supergiovane** [comment]
I cannot see any option regarding reading the status. There should be somethings wrong... Let me indagate... 
https://github.com/user-attachments/assets/d5f63f19-57cb-40a8-a5b2-151af246f206

**Comment by Supergiovane** [comment]
Fixed in 3.2.8 out now.
