### ISSUE TITLE
Error sending data to group address

### ISSUE THREAD

**Issue by jimwest256** [Supergiovane/node-red-contrib-knx-ultimate#386]
Hey Supergiovane,

I noticed the following error message while sending data to the group address. 
It was working before the upgrade. Unfortunately, I don't know which version I installed before the latest version.

![image](https://github.com/user-attachments/assets/dfe160ee-c1df-469f-b09d-01457be129d2)

This error occurs once data has been sent to the node.

Config:
![image](https://github.com/user-attachments/assets/bd888c8e-8249-463d-aff3-9af52b7fcc74)

Any ideas? Thanks!

**Comment by Supergiovane** [comment]
Hi
Let me check immediately.
In the meantime, please check to have all "Format numeric values coming from the KNX BUS" selectboxes set to "Leave unchanged"

**Comment by Supergiovane** [comment]
PS: i think your node is receiving a non numeric value.

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate 3.2.12 is out with a fix for that.

**Comment by jimwest256** [comment]
> PS: i think your node is receiving a non numeric value.
Yes, you are right. I think it is a string value.

> node-red-contrib-knx-ultimate 3.2.12 is out with a fix for that.
Thank you! I just tested the new release and can confirm the fix works!
