### ISSUE TITLE
Update damaged KNX Ultimate installation

### ISSUE THREAD

**Issue by Podler** [Supergiovane/node-red-contrib-knx-ultimate#387]
Hi Supergiovane,

I updated the knx ultimate integration to 3.2.11 on my Node-RED installation a few days ago. Node-RED is running on top of Home Assistant.

Since the update to 3.2.11 the knx ultimate nodes are no longer working. Something went wrong during the update I guess. The latest update to 3.2.12 did not solve the problem.

When I manage the palette in Node-RED the knx-ultimate addon no longer says "in use" but only offers to be uninstalled. I tried to uninstall it (to reinstall it), but this also fails.

Is there any way to remove / reinstall knx-ultimate manually? Will the flows stay in place during that process and work fine after reinstalling knx-ultimate?

Warm regards, Thomas.

**Comment by Podler** [comment]
Hi Supergiovane, I made some progress. The update damaged the gateway configuration. I deleted the gateway and added a new one (with the execat same settings) and the nodes start to work again. Now I have to change the gateway setting in > 500 nodes. Is there a way to change them in one step or do I have to edit every single node manually? 

But this still leaves the quetion, why the add-on is no longer shows as "in use" in the palette...

Regards, Thomas.

**Comment by Supergiovane** [comment]
`
Is there a way to change them in one step or do I have to edit every single node manually?
`

Yes. You must open the projects’s json with a text editor and replace the node server’sID manually.

**Comment by Podler** [comment]
Unfortunately the new gateway did not survive a reboot of Node-RED. Same behaviour as before. All nodes flicker between "Connecting", "On Duty" and "Auto reconnect in progress". Do you have any idea?

> 10/12/2024, 6:41:09 PM [knxUltimate-config <Gira S1>] [ERROR] received KNXClientEvents.error: Not running
10/12/2024, 6:41:09 PM [knxUltimate-config <Gira S1>] [ERROR] Disconnected by: Not running
10/12/2024, 6:41:10 PM [KNXEngine] [ERROR] KNXClient: _setTimerWaitingForACK: Request timeout: seqCounter:1, DestAddr:4/4/12,  AckRequested:0, timed out waiting telegram acknowledge by 192.168.1.6 no ACK received. Retransmit datagram with seqNumber 1 from 15.15.22 to 4/4/12
10/12/2024, 6:41:16 PM [KNXEngine] [ERROR] KNXClient: into async closeSocket(): Error: Not running
    at new NodeError (node:internal/errors:405:5)
    at healthCheck (node:dgram:920:11)
    at Socket.close (node:dgram:745:3)
    at /config/node_modules/knxultimate/src/KNXClient.ts:1130:41
    at new Promise (<anonymous>)
    at KNXClient.closeSocket (/config/node_modules/knxultimate/src/KNXClient.ts:1116:10)
    at KNXClient.Disconnect (/config/node_modules/knxultimate/src/KNXClient.ts:1165:15)
    at knxUltimateConfigNode.node.initKNXConnection (/config/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:618:38)

**Comment by Podler** [comment]
Is it right, that there are no nodes displayed in the palette?

![image](https://github.com/user-attachments/assets/0412f30e-0eb3-4862-b46c-6369fded32a0)

**Comment by Supergiovane** [comment]
No.
Please be sure to have the latest nodered version 4.x.x and at least node v20.x

**Comment by Podler** [comment]
I spoke to the developer of the Node-RED integration on Home Assistant, as my NodeJS seems to be 18.20.4. This is what he replies:

"There is an upstream issue with NodeJS on armv7, preventing upgrading any NodeJS Docker container for this platform.

This is, unfortunately out of our control.

../Frenck"

So every installation of Node-RED beeing updated to Node_RED 18.1.x on Home Assistant  seems to have an issue right now. Just to let you know, if any other user experiences problems.

**Comment by Supergiovane** [comment]
Thanks for the info

**Comment by Podler** [comment]
I gathered further information on this. Frenck (the maintainer of the Home Assistant Node-RED Projekt writes:

**> _"Is it right, that this issue already exists for months?
> 
> Yes.
> 
> Do you have any information how long this state might last?
> 
> Nope. This is an issue upstream with the NodeJS project.
> 
> ../Frenck"_**

Is there any chance to get knx-ultimate working on NodeJS 18 again? I ask, because this issue breaks knx-ultimate on all Home Assistant installations. What was the last knx-ultimate release working with NodeJS 18?

Regrads, Thomas.

**Comment by Supergiovane** [comment]
Yes. It works on nodejs18
You must also check to have node-red 3.1.x at least.

**Comment by Podler** [comment]
I run 4.0.3.

**Comment by Supergiovane** [comment]
Hi
you could downgrade to a previous version.
Just CD into **./node-red** folder and issue a **npm install node-red-contrib-knx-ultimate@3.2.0** or any version listed here: https://www.npmjs.com/package/node-red-contrib-knx-ultimate?activeTab=versions
But your issue is very strange. There are many people out there using knx ultimate on node-red home assistant's plugin, without any issue.
Have you managed to assign the new knx configuration node to each of your 500 nodes? If not, please send me your project JSON. I'll do it for you.

**Comment by Supergiovane** [comment]
> Your help is very much appreciated. I am an IT-professional but in quite another knowledge area. I do not have deeper knowledge in linux. I depend very much on this installation, because it runs my complete property with hundreds of KNX group adresses. I would be happy to pay for your professional support if that is possible. Is it possible to arrange a Microsoft Teams remote session in the next days where you have a look at my installation an probably repair it? I am not familiar with the linux shell. I found the directory homeassistant/node-red but cannot see any files in there... I fear to destroy more than I repair. Warm regards, Thomas.

Hi Thomas
Please keep me updated on that.

**Comment by Podler** [comment]
Just in that moment I had sent an e-mail to you... :-)

**Comment by Podler** [comment]
3.2.13 fixed the issue for me. Thank you Supergiovane! Appreciate your work!

**Comment by Supergiovane** [comment]
Glad it worked!
