### ISSUE TITLE
KNX not working properly anymore after update from 3.2.10 -> 3.2.11

### ISSUE THREAD

**Issue by waldbaer** [Supergiovane/node-red-contrib-knx-ultimate#388]
Hello Super-Giovanni, thanks for maintaining this wonderful node driving my SmartHome since ~5years!

**Describe the bug**
I regularly update my Node-RED nodes. Yesterday from knx-ultimate version 3.2.5 -> 3.2.11.
After a restart of the Raspberry PI I noticed that KNX communication is not working propery anymore.

Most obvious malfunctions:
- Values are not read from KNX bus after startup ("Read from KNX bus")
- Sending new values (e.g. for light bulbs) to KNX does not work anymore.

From the logs I can see that the cron-plus node reports several "System Time Change Detected".
I had this already in the past when running for example a heavy database query which blocks the nodejs loop for too long time. Then after ~30sec a serious KNX error happens and the node does a reconnect

```
Oct 14 20:28:44 rpi0 Node-RED[1518]: 14 Oct 20:28:44 - [info] [cronplus:0:00 ] System Time Change Detected - refreshing schedules! If the system time was not changed then this typically occurs due to blocking code elsewhere in your application
Oct 14 20:28:44 rpi0 Node-RED[1518]: 14 Oct 20:28:44 - [info] [cronplus:Morning AutoOpen Trigger] System Time Change Detected - refreshing schedules! If the system time was not changed then this typically occurs due to blocking code elsewhere in your application
Oct 14 20:28:44 rpi0 Node-RED[1518]: 14 Oct 20:28:44 - [info] [cronplus:12:00:] System Time Change Detected - refreshing schedules! If the system time was not changed then this typically occurs due to blocking code elsewhere in your application
Oct 14 20:28:44 rpi0 Node-RED[1518]: 14 Oct 20:28:44 - [info] [cronplus:7:00] System Time Change Detected - refreshing schedules! If the system time was not changed then this typically occurs due to blocking code elsewhere in your application
Oct 14 20:28:44 rpi0 Node-RED[1518]: 14 Oct 20:28:44 - [info] [cronplus:goldenHour + 20m] System Time Change Detected - refreshing schedules! If the system time was not changed then this typically occurs due to blocking code elsewhere in your application


Oct 14 20:29:37 rpi0 Node-RED[1518]: 10/14/2024, 8:29:37 PM [KNXEngine] [ERROR] Error: Invalid Connection ID
Oct 14 20:29:37 rpi0 Node-RED[1518]:     at KNXClient.processInboundMessage (/home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:1618:9)
Oct 14 20:29:37 rpi0 Node-RED[1518]:     at Socket.emit (node:events:519:28)
Oct 14 20:29:37 rpi0 Node-RED[1518]:     at UDP.onMessage (node:dgram:946:8)
Oct 14 20:29:37 rpi0 Node-RED[1518]: 10/14/2024, 8:29:37 PM [knxUltimate-config <knx.homelab>] [ERROR] received KNXClientEvents.error: Invalid Connection ID
Oct 14 20:29:37 rpi0 Node-RED[1518]: 10/14/2024, 8:29:37 PM [knxUltimate-config <knx.homelab>] [ERROR] Disconnected by: Invalid Connection ID
Oct 14 20:29:38 rpi0 Node-RED[1518]: 10/14/2024, 8:29:38 PM [KNXEngine] [ERROR] Sending KNX packet: Send UDP Catch error: Not running object seqCounter:
Oct 14 20:29:38 rpi0 Node-RED[1518]: 10/14/2024, 8:29:38 PM [KNXEngine] [ERROR] Error: Not running
Oct 14 20:29:38 rpi0 Node-RED[1518]:     at healthCheck (node:dgram:924:11)
Oct 14 20:29:38 rpi0 Node-RED[1518]:     at Socket.send (node:dgram:651:3)
Oct 14 20:29:38 rpi0 Node-RED[1518]:     at KNXClient.processKnxPacketQueueItem (/home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:501:40)
Oct 14 20:29:38 rpi0 Node-RED[1518]:     at KNXClient.handleKNXQueue (/home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:561:16)
Oct 14 20:29:38 rpi0 Node-RED[1518]:     at runNextTicks (node:internal/process/task_queues:60:5)
Oct 14 20:29:38 rpi0 Node-RED[1518]:     at processTimers (node:internal/timers:516:9)
Oct 14 20:29:38 rpi0 Node-RED[1518]: 10/14/2024, 8:29:38 PM [knxUltimate-config <knx.homelab>] [ERROR] received KNXClientEvents.error: Not running
Oct 14 20:29:38 rpi0 Node-RED[1518]: 10/14/2024, 8:29:38 PM [knxUltimate-config <knx.homelab>] [ERROR] Disconnected by: Not running
Oct 14 20:29:44 rpi0 Node-RED[1518]: 10/14/2024, 8:29:44 PM [KNXEngine] [ERROR] KNXClient: into async closeSocket(): Error: Not running
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at healthCheck (node:dgram:924:11)
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at Socket.close (node:dgram:749:3)
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at /home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:1130:41
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at new Promise (<anonymous>)
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at KNXClient.closeSocket (/home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:1116:10)
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at knxUltimateConfigNode.node.initKNXConnection (/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/knxUltimate-config.js:618:38)
Oct 14 20:29:44 rpi0 Node-RED[1518]:     at KNXClient.Disconnect (/home/pi/.node-red/node_modules/knxultimate/src/KNXClient.ts:1165:15)
``` 

With version 3.2.10 or before I don't get such errors. Downgrading the knx-ultimate 3.2.10 resolves these errors completely.

After ~4-5min of Node-RED runtime these System Time Change Detected  error are actually stopping and the systems seems to recover. The "Read from KNX bus" gets the values from the bus and also sending values to the bus works again.

**To Reproduce**
- Install node-red-contrib-knx-ultimate from version 3.2.10 -> Everything works as expected
- Update to node-red-contrib-knx-ultimate to version 3.2.11
- Restart Node-RED
- "Read from KNX bus" or send to KNX bus works does not work anymore

**Expected behavior**
"Read from KNX bus" and send to KNX network works.

**Screenshots**
only the logs above might be helpful.

**Knx-Ultimate Version**
node-red-contrib-knx-ultimate version 3.2.11

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running alone on a Raspberry Pi 4 with the following software versions:
```
[info] Node-RED version: v4.0.5
[info] Node.js  version: v20.18.0
[info] Linux 6.6.51+rpt-rpi-v8 arm64 LE
```

**Additional context**
Issue also reproducible with node-red-contrib-knx-ultimate  3.2.12.
I am working with knxd and TUL stick.

Please let me know if I anyhow can help you analyzing this issue.

Maybe related to #387 also reporting issues with update to 3.2.11.

Thanks!
Sebastian

**Comment by Supergiovane** [comment]
Hi
Please check that the protocol is set to Auto, in the gateway node config.

**Comment by waldbaer** [comment]
> Hi Please check that the protocol is set to Auto, in the gateway node config.

@Supergiovane I just tried changing the IP Protocol from "UDP Tunneling" to "Auto". But this does not change anything.

**Comment by Supergiovane** [comment]
Hi
The cron issue is not related to knx-ultimate. You can downgrade to 3.2.10, but there are only minor changes from 3.2.11. 
cd into .node-red, the run:
npm install node-red-contrib-knx-ultimate@3.2.10

**Comment by Supergiovane** [comment]
PS: the latest version is 3.2.12, not 3.2.11

**Comment by waldbaer** [comment]
> PS: the latest version is 3.2.12, not 3.2.11

Yes I know. I step-by-step updated from version 3.2.5 until 3.2.10 without issues.
Only when updating from 3.2.10 to 3.2.11 the issues are appearing.
As states version 3.2.12 (yes, the latest one) does not change anything in the malbehavior.

**Comment by Supergiovane** [comment]
Please revert back. Tomorrow i’ll take a deep look into the 3.2.11. Usually, a step install is not required.

**Comment by Supergiovane** [comment]
Hi
please gather the debug infos from the gateway node config window and paste it here.
<img width="529" alt="Node-RED___Avvio" src="https://github.com/user-attachments/assets/a2f1f5b3-8cae-40dc-92c0-f6712c182d96">

**Comment by waldbaer** [comment]
@Supergiovane 
I just collected the troubleshoot info. Is there a secure way to send you these infos as I don't want to past a full dump of the KNX config in a public gitlab issue.

In my setup this troublshoot log is actually 1MiB in size, 6300 lines of output.
Could this be the reason why the system reports some long-running tasks blocking the nodejs runtime. 
Can this logging be turned off? 
Actually I also don't want to have 1MiB of log data written every time to the Raspberry PI SD card!

**Comment by Supergiovane** [comment]
maxsupergiovane@icloud.com
Thanks!!

**Comment by Supergiovane** [comment]
You can turn off knx-ultimate logging and also node-red logging (but i don't know where the option is).
<img width="516" alt="Node-RED___Avvio" src="https://github.com/user-attachments/assets/0132b10b-b680-41ae-82b2-b6658f29513e">

**Comment by Supergiovane** [comment]
Hi
i've noticed that you have a DNS name instead of an IP address. The auto protocol discovery works only if you set the IP.
According to your KNX Gateway, please set the protocol to Tunnel UDP (or multicast). Also please set the minimum delay between telegrams, to 30ms
https://github.com/user-attachments/assets/308b16c5-4021-44cb-ab52-35f3cfcb81cc

**Comment by waldbaer** [comment]
Actually I used the DNS name just for the name of the gateway config. IP/Hostname is actually an IP Address. Switched back IP Protocol to "Tunnel UDP". I adapted also the minimum delay time.

But: has not effect. Version 3.2.11 behaves strange.

**Comment by Supergiovane** [comment]
Please upgrade to 3.2.13 and let me know

**Comment by waldbaer** [comment]
Oh wow. With 3.2.13 the obvious symptoms are fixed!

Any idea what could be the issue with the logging feature?

**Comment by Supergiovane** [comment]
Yes
I had enabled a log to file function, but not all setups does have a write permission on the filesystem. With 3.2.13, i disabled the log to file (but the node-red log console works as usual).

**Comment by waldbaer** [comment]
Thanks for your support!

Some more hints from my side about writing files:
On Raspberry PI with an SD card storage I don't want to have such additional log files written into the .node-red directory.
Actually I am using [log2ram](https://github.com/azlux/log2ram) to move all service logging into RAM instead SD card.

If possible if would be good to have additional logs from knx-ultimate somewhere in the common log-location  `/var/log`.

**Comment by Supergiovane** [comment]
Thanks for the hint.
Yes, i understand. The future log implementation will be via an HTTP stream. You will need to manually and optionally enable it in case of problems, to help me debug. There are so many users here, not knowing where log files are located and how to retrieve it.

**Comment by Supergiovane** [comment]
PS: http stream to an open source log server of mine.

**Comment by Supergiovane** [comment]
Thank you for your donation!!!!!
