### ISSUE TITLE
KNX Data Secure - Error incoming messages

### ISSUE THREAD

**Issue by DenisMir** [Supergiovane/node-red-contrib-knx-ultimate#39]
I am using the new MDT SCN-IP100.03 including IP secure. I am able to use the KNX Ultimate node for writing telegrams.
But when having it in universal mode (including the imported ETS GAs) for listening for telegrams nothing is coming through to the debug node. 

When looking inside the log I can find the following lines:

```
[debug] 2020-02-15 17:52:41.602 Inbound multicast message from 192.168.2.114: 061009550024000001059bb2008370400a115f7df39a5962c84f12396086f1bce3749044
[warn] 2020-02-15 17:52:41.602 read KNXNetHeader: unhandled serviceType = undefined
```

Is the IP secure the reason that I'm not able to receive the telegrams coming from the bus?

**Comment by Supergiovane** [comment]
Please use the IP multicast address with knx routers. 
Ip secure tunneling is not yet implemented.

**Comment by DenisMir** [comment]
I will give it a try and report back if it works.

**Comment by Supergiovane** [comment]
Then please follow the FAQ and troubleshoot in the Wiki. Thanks.

**Comment by DenisMir** [comment]
Ok here we go: 

```
15 Feb 20:10:53 - [info] knxUltimate: csv ETS found !
15 Feb 20:10:53 - [info] knxUltimate: Bind KNX Bus to interface : en0 (Interface's name selected from dropdown list)
[debug] 2020-02-15 19:10:53.691 initializing multicast connection to 224.0.23.12
15 Feb 20:10:53 - [info] Started flows
[debug] 2020-02-15 19:10:53.700 IpRoutingConnection 192.168.2.104:3671, adding membership for 224.0.23.12
[debug] 2020-02-15 19:10:53.701 useTunneling=false
[debug] 2020-02-15 19:10:53.701 --- Connected in ROUTING mode ---
[debug] 2020-02-15 19:10:53.701 (idle):	 zzzz...
```

![Bildschirmfoto 2020-02-15 um 20 17 04](https://user-images.githubusercontent.com/157281/74593892-9a8ff780-5030-11ea-8ef9-771818792504.png)

So the multicast address should be ok. 

![Bildschirmfoto 2020-02-15 um 20 17 22](https://user-images.githubusercontent.com/157281/74593894-a5e32300-5030-11ea-82ac-d727cb0dc252.png)

The gateway config should be ok as well. 

![Bildschirmfoto 2020-02-15 um 20 18 07](https://user-images.githubusercontent.com/157281/74593910-c27f5b00-5030-11ea-848e-c57c9da20894.png)
![Bildschirmfoto 2020-02-15 um 20 17 51](https://user-images.githubusercontent.com/157281/74593912-c3b08800-5030-11ea-94e3-80ce32e1dca7.png)

Writing should be fine as well. 

![Bildschirmfoto 2020-02-15 um 20 18 19](https://user-images.githubusercontent.com/157281/74593918-cf03b380-5030-11ea-88d5-a39c53432aa3.png)

![Bildschirmfoto 2020-02-15 um 20 22 24](https://user-images.githubusercontent.com/157281/74593925-e80c6480-5030-11ea-9741-f162183a80c3.png)

And this is the listening part. It only receives the messages written by the ultimate node. But they do not reach the bus. 

The log is full of: 

```
[debug] 2020-02-15 19:22:41.125 Inbound multicast message from 192.168.2.114: 06100955002400000157ffa6008370400a11151df9a7f7ac8d801c8a667e001cee948073
[warn] 2020-02-15 19:22:41.125 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:22:53.781 Inbound multicast message from 192.168.2.114: 06100955002400000158314c008370400a11616068f9578c5d81f5a3bc179007bc10ae8e
[warn] 2020-02-15 19:22:53.781 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:22:53.782 Inbound multicast message from 192.168.2.114: 06100955002400000158314c008370400a11616068f9578c5d81f5a3bc179007bc10ae8e
[warn] 2020-02-15 19:22:53.782 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:22:53.782 Inbound multicast message from 192.168.2.114: 06100955002400000158314c008370400a11616068f9578c5d81f5a3bc179007bc10ae8e
[warn] 2020-02-15 19:22:53.782 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:22:53.782 Inbound multicast message from 192.168.2.114: 06100955002400000158314c008370400a11616068f9578c5d81f5a3bc179007bc10ae8e
[warn] 2020-02-15 19:22:53.782 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:05.084 Inbound multicast message from 192.168.2.114: 061009550024000001585d34008370400a1180bfcafe5967a648a2834ffba417261852de
[warn] 2020-02-15 19:23:05.084 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:05.085 Inbound multicast message from 192.168.2.114: 061009550024000001585d34008370400a1180bfcafe5967a648a2834ffba417261852de
[warn] 2020-02-15 19:23:05.085 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:05.085 Inbound multicast message from 192.168.2.114: 061009550024000001585d34008370400a1180bfcafe5967a648a2834ffba417261852de
[warn] 2020-02-15 19:23:05.085 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:05.085 Inbound multicast message from 192.168.2.114: 061009550024000001585d34008370400a1180bfcafe5967a648a2834ffba417261852de
[warn] 2020-02-15 19:23:05.085 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:16.553 Inbound multicast message from 192.168.2.114: 0610095500240000015889d0008370400a1172eab90046dd50a77f3080fa4691074fbf37
[warn] 2020-02-15 19:23:16.553 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:16.553 Inbound multicast message from 192.168.2.114: 0610095500240000015889d0008370400a1172eab90046dd50a77f3080fa4691074fbf37
[warn] 2020-02-15 19:23:16.553 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:16.553 Inbound multicast message from 192.168.2.114: 0610095500240000015889d0008370400a1172eab90046dd50a77f3080fa4691074fbf37
[warn] 2020-02-15 19:23:16.554 read KNXNetHeader: unhandled serviceType = undefined
[debug] 2020-02-15 19:23:16.554 Inbound multicast message from 192.168.2.114: 0610095500240000015889d0008370400a1172eab90046dd50a77f3080fa4691074fbf37
[warn] 2020-02-15 19:23:16.554 read KNXNetHeader: unhandled serviceType = undefined
```

Here is the setup of the router in the ETS: 

![Bildschirmfoto 2020-02-15 um 20 25 41](https://user-images.githubusercontent.com/157281/74593974-6537d980-5031-11ea-898a-3a7302155f2c.png)
![Bildschirmfoto 2020-02-15 um 20 25 16](https://user-images.githubusercontent.com/157281/74593975-66690680-5031-11ea-9e02-02e2290f0f8e.png)

I am now disabling the secure feature since I can't find the error even after walking through all the FAQ and troubleshooting. 

Or do you see any errors in my configuration?

**Comment by Supergiovane** [comment]
No, all seems ok. 
Please try also to:
Telegramweiterleitung: set all to **not to filter**. Allow all to **pass**, on every router configuration page.

**Comment by DenisMir** [comment]
Ok after some testing I am sure that it doesn't work with a secure configured router. Even without filtering it doesn't work at all.

When switching to non secure and disabling the filtering everything does work as expected.

**Comment by Supergiovane** [comment]
Hi Denis
Yes it makes sense.
I also have an enertex ip secure router, that works only if set to unsecure. 
My nodered has two eth cards, one connected directly with the knx router and the other with the lan, on two differents subnets.  So i have no problem with possible hacking, being the knx router not connected to lan at all.
