### ISSUE TITLE
Setting rgb to {red:255, green:255, blue:255} fails

### ISSUE THREAD

**Issue by RobertHerter** [Supergiovane/node-red-contrib-knx-ultimate#390]
Hallo,

to track down the Problem with hanging node-red,  treid to get rid of another Hue-Node.

i found that sending {red:255, green:255, blue:255} to the RGB-Node results in not setting white as color, an subsequent Color-Telegrams are not working.

Running latest Version.

**Comment by Supergiovane** [comment]
Hi,
are you able to unzip this file into your **./node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder and restart node-red?
knxUltimate-config.js.zip](https://github.com/user-attachments/files/17464329/knxUltimate-config.js.zip)

**Comment by RobertHerter** [comment]
Hello,

tried and found that 254,254,254 ist working, but not 255,255,255.

**Comment by Supergiovane** [comment]
Ok, will revert ASAP by you...

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate-3.2.16 is out with the fix.
Thank you for let me know about that!

**Comment by RobertHerter** [comment]
Thnak you, working with 3.2.16. As always great support.
