### ISSUE TITLE
Integration stops working

### ISSUE THREAD

**Issue by danube** [Supergiovane/node-red-contrib-knx-ultimate#394]
Hi Supergiovane!

I ask for help regarding my KNX integration suddenly stop working. This happens since about a week, without a known trigger event, once or twice a day. First, everything works fine. Actuators can be controlled as expected. Suddenly, no more KNX actuators can be controlled and it seems that no telegrams are being received from within Node-RED too.

Approximately at the same time the spook started, I installed Home Assistant with KNX integration on another computer. I've disabled the KNX integration there now to determine, if there is a relation. Hopefully, thigs stabilize again.

Still, two things to notice. One: When Node-RED with node-red-contrib-knx-ultimate seems to "hang", the KNX integration in Home Assistant was still able to read and write telegrams on the bus. Two: Re-deploying node-red-contrib-knx-ultimate seems to fix the "hang" and things start to work again.

In my understanding, working with multiple instances on one KNX gateway should basically be possible, am I right?

Can you help me achieve this? Am I running some misconfiguration? Or is there a bug in the fantastic node-red-contrib-knx-ultimate node? If so, I'd be glad to be of any assistance.

I've gathered a Node-RED log with knxultimate Loglevel "Debug" within a time window of five minutes, where the break happened (around 17:52). This can be found here: https://pastebin.com/Bb35510i

And I pulled the debug infos from within the configuration node, find that here: https://pastebin.com/LGgdZT0c

node-red-contrib-knx-ultimate version is 3.2.17.

Thank you for the support!
Tom

**Comment by danube** [comment]
Ah and by the way, the interface is SCN-IP000.03 from MDT.

**Comment by danube** [comment]
The knxultimate version in use is 3.2.17. The spook started about one week ago. I make mods all the time. The major change was the newcoming of Home Assistant, but (A) it's installed on a different computer and (B) I disabled it's KNX integration yesterday and discovered the break again today, so that may it not be. There was no major change I have in mind on the same computer than Node-RED is running. I just have no clue what could have started the breaks... 🙈

I had another break this morning between 9:44-10:14, logs can be found here: https://github.com/user-attachments/files/17790202/Node-RED_2024-11-14_09-40-00.log

As far as I see, knxultimate still receives telegrams as I still can control Zigbee devices with the installed KNX pushbuttons. But it is not possible anymore to control KNX devices as the KNX shading/dimming/switching actuators. So it seems that telegrams still can be received but not being sent. You see that also in the log, for example:

```
Nov 17 10:14:11 rpi4 Node-RED[10775]: 17 Nov 10:14:11 - [info] [shading:Wohnzimmer Fix] Close longclick detected
Nov 17 10:14:13 rpi4 Node-RED[10775]: 17 Nov 10:14:13 - [info] [shading:Wohnzimmer Fix] Button released
```
or
```
Nov 17 10:14:46 rpi4 Node-RED[10775]: 17 Nov 10:14:46 - [info] [shading:KÃŒche Schieb links] Window switch event detected: Opened -> Closed
```

**Comment by Supergiovane** [comment]
Hi
Again nothing strange in the log, that means that the node is able to send the knx telegram, but it doesn’t reach out the device. 
I suggest 2 things:
1) Check the “interface” in the knx gateway config node and set it to a fixed lan interface (do not set “Auto”, instead choose an interface from the dropdown select box, then restart node red ). 
2) If unsuccessful, update knxultimate to the latest version. 

Then let me lnow!

**Comment by danube** [comment]
1 was already set. Here's the complete actual setup:
![grafik](https://github.com/user-attachments/assets/f28493d0-0008-4246-869d-547e06db0533)

I will now update the node to 3.3.0. Let's see then. Thanks so far!!

**Comment by danube** [comment]
Just found 3.3.1 to be online 👍🏼‍ Updating to that version.

**Comment by danube** [comment]
Here's a screenshot of the actual advanced settings:
![grafik](https://github.com/user-attachments/assets/ea5a669e-7683-4138-afa4-3a6db2e8835f)

If you meant the option "Suppress ACK request in tunneling mode", then that was already set.

When you talk about OS routing, is there anything we could configure to work more reliable? It's a Raspberry Pi 4B with current OS version.

**Comment by Supergiovane** [comment]
Yes, that ACK, correct. Unset it, so the node can reply with an ACK to your mdt. 
And no, there is nothing you can hack in your system. Just also put  25 instead of 40 in that text box and restart node red.

**Comment by danube** [comment]
Okay Massimo, so I unchecked the ACK option and set delay to 25. Let's see!

**Comment by Supergiovane** [comment]
> Ah and by the way, the interface is SCN-IP000.03 from MDT.

Hi
Have you ever seen [this message?](https://github.com/home-assistant/core/issues/59170#issuecomment-998096338)
I know this MDT interface was misbehaving and a firmware update has solved it.
You may consider upgrading the firmware as well.

**Comment by danube** [comment]
Thanks Massimo for investigating. I made a firmware update on the interface from 3.0.6 to 3.0.8 and re-downloaded the ETS application to the device (which you have to do anyways after a FW-update).

You mention (not the first time) that the MDT interface has some glitches. Can you recommend a more reliable interface? I couldn't find that in your (splendid!) documentation.

**Comment by Supergiovane** [comment]
Hi
many vendors make a simple "rebranded" versions of these MDT interfaces. Weinzlier is also a main producer.
They are all good interfaces but the firmware must kept always up to date.
Personally, i use an Enertex IP/Router and a Eibmarkt IP Interface (i think this one is a rebrand of MDT).

**Comment by Supergiovane** [comment]
Hi
do you still have issues? Can i close?
Thanks.
