### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by 18802496555** [Supergiovane/node-red-contrib-knx-ultimate#395]
After node-red start or re-deploy, the KNX device node works fine, after a couple hours, it starts to report :
Received KNX packet: TUNNELING: Unexpected Tunnel Ack with seqCounter = xxx, expecting xxx, 
but the node still functions, couple hours later it reports :
KNXClient: _setTimerWaitingForACK: Request timeout: seqCounter:109, DestAddr:1/1/88,  AckRequested:0, timed out waiting telegram acknowledge by 192.168.1.201 no ACK received. Retransmit datagram with seqNumber 109 from 15.15.242 to 1/1/88

after this, it keeps reporting:
[KNXEngine] [ERROR] Received KNX packet: DISCONNECT_REQUEST, ChannelID:117 Host:192.168.1.201:3671
[KNXEngine] [ERROR] KNXClient: into async closeSocket(): Error: Not running

After restart node-red or redeploy, everything works fine again. I tried restarting the interface to free up tunnels, but makes no difference. 

I already update knxultimate to 3.3.2, and start the testing to check if it makes any difference 

Some info about my system:
Node-RED version: v4.0.3
Node.js  version: v18.20.4
Linux 6.6.54-haos x64 LE
knxultimate version 3.3.0

<img width="402" alt="setings" src="https://github.com/user-attachments/assets/41d69349-a79b-4819-b2ab-7e1452342f7a">

[log.txt](https://github.com/user-attachments/files/17826941/log.txt)

**Comment by Supergiovane** [comment]
Hi
please also do [this](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/392#issuecomment-2485839089) please?

**Comment by 18802496555** [comment]
![image](https://github.com/user-attachments/assets/3a9f7ae7-b421-4ff1-8f2a-3283ef6bb004)

**Comment by Supergiovane** [comment]
Then restart node-red and let it run for awhile

**Comment by 18802496555** [comment]
move node-red to docker, node-red version 4.0.5, Node.js version 18.20.5, knxultimate 4.3.2, run over night, it starts the same problem again. 
![image](https://github.com/user-attachments/assets/94387853-324e-4bde-9aa4-f507c4918644)
![image](https://github.com/user-attachments/assets/84fb19a8-75d1-4afb-8576-a0e73f362796)
![image](https://github.com/user-attachments/assets/5fd62ab6-a64f-4cb7-a67e-bffadcd6ca6d)
![image](https://github.com/user-attachments/assets/69a7bfe8-4297-4a55-ac51-eb3462142135)

[knx_log.txt](https://github.com/user-attachments/files/17840295/knx_log.txt)

**Comment by Supergiovane** [comment]
Hi
Is there a reason you disabled the "Echo sent messages to all node..."?

Please unzip this file into your **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder and restart node.red.

[knxUltimate-config.js.zip](https://github.com/user-attachments/files/17841223/knxUltimate-config.js.zip)

**Comment by Supergiovane** [comment]
PS: in the status of that node, i see "HAS BEEN DISABLED", but i cannot read why

**Comment by Supergiovane** [comment]
Have you looked at this? https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/Protections

I think you've issues with your flow.

**Comment by Supergiovane** [comment]
Please paste here , between the brackets <>, your flow, so i can check it.

**Comment by 18802496555** [comment]
> Please paste here , between the brackets <>, your flow, so i can check it.

[flows (2).json](https://github.com/user-attachments/files/17842861/flows.2.json)

**Comment by Supergiovane** [comment]
In the 40msg/s node, set the interval to 10msg/sec.
I've tested your flow and other things appear correct.

**Comment by 18802496555** [comment]
> 10msg/sec.

OK, and I will give it a try, thanks for helping

**Comment by Supergiovane** [comment]
Closing because the thread is becoming too mixed.
