### ISSUE TITLE
Edit Pane don't open

### ISSUE THREAD

**Issue by svenflender** [Supergiovane/node-red-contrib-knx-ultimate#40]
Hi,
version 1.1.36

When i add a new KNX Ultimate Node, the edit Pane don't open with double klick on the node.

best Regards
Sven

**Comment by Supergiovane** [comment]
Intake a look immediately

**Comment by Supergiovane** [comment]
Mine works. Are you sure?
Can you paste here the affected node's configuration?

**Comment by Supergiovane** [comment]
Ah, ok, got it!
It doesn't work if you haven't a gateway node configured. Sorry, a fix will be out shortly.

**Comment by Supergiovane** [comment]
V 1.1.37 is published. Thank you for your help!

**Comment by svenflender** [comment]
Sorry couldn't answer. Thx for the fast reply and fix!! I figured this out while working on translation enhancement for knx-ultimate ;)
