### ISSUE TITLE
problems with knx-alerter node

### ISSUE THREAD

**Issue by jomifa** [Supergiovane/node-red-contrib-knx-ultimate#402]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**
Hello,
the node-red “knx alerter” node does not read the specified GAs to be monitored when starting/restarting Node-red. Enclosed the node-red flow

**To Reproduce**
Write here the steps to reproduce the behavior, for example:

**Expected behavior**
Write here a clear and concise description of what you expected to happen.

**Screenshots**
Here, if applicable, add screenshots to help explain your problem.

**Knx-Ultimate Version**
node-red-contrib-knx-ultimate version 3.3.4

**Are you running node-red behind homematic, docker or anything similar?**
Node-Red running alone in RaspberryPi

**Additional context**
Write here any other context about the problem here.
[flows(14).json](https://github.com/user-attachments/files/17948610/flows.14.json)

**Comment by Supergiovane** [comment]
Hi
Do these GA have the "R" flag active? They should respond to read requests.

<img width="624" alt="Node-RED___KNX_Alerter_für_Fenster__Türen_und_Beleuchtung" src="https://github.com/user-attachments/assets/2f65f5c1-f2e9-4602-922b-ae8cc56f3987">

**Comment by jomifa** [comment]
Hi,
the read flags are of course set for the affected resources. After all, these are real KNX GAs that work perfectly. I cannot see in the bus monitor that the Alerter queries the GAs at startup.

However, if I define the GAs in the node red flow as KNX devices, then the whole thing works. How can that be?

Joachim

***@***.***

Von: Massimo Saccani ***@***.***>
Gesendet: Donnerstag, 28. November 2024 15:39
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] problems with knx-alerter node (Issue #402)


Hi
Do these GA have the "R" flag active? They should respond to read requests.
Node-RED___KNX_Alerter_fur_Fenster__Turen_und_Beleuchtung.png (view on web)<https://github.com/user-attachments/assets/2f65f5c1-f2e9-4602-922b-ae8cc56f3987>

**Comment by Supergiovane** [comment]
Have you imported the ETS group addresses file?

**Comment by jomifa** [comment]
I had initially imported this file. However, there were too many error messages because the parser had interfered with some of my definitions. All placeholders for undefined GAs were flagged and it didn't like some DPTs either.

If a GA changes to true in the course of operation, the alerter notices this.

Von: Massimo Saccani ***@***.***>
Gesendet: Donnerstag, 28. November 2024 16:04
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] problems with knx-alerter node (Issue #402)


Have you imported the ETS group addresses file?

**Comment by Supergiovane** [comment]
Hi
i’ll take a look at the code tomorrow and i’ll let you know.

**Comment by Supergiovane** [comment]
Hi
i'm working on that...

**Comment by Supergiovane** [comment]
Hi
node-red-contrib-knx-ultimate@3.3.5 is out with the fix. Please try it and let me know. Thanks.

**Comment by jomifa** [comment]
Hi,
thanks a lot. It works.
