### ISSUE TITLE
KNX Alerter does not consider the GAs when deploying node red

### ISSUE THREAD

**Issue by jomifa** [Supergiovane/node-red-contrib-knx-ultimate#404]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**
Write here a clear and concise description of what the bug is
Hello,
i had already reported this problem and thought that it had been solved by the fix in 3.3.5. I have now discovered that the problem still exists. I can see the read request of the affected GAs in the KNX diagnostics and also the responses from the actuator. However, the result is not reflected in the alert display. 

**To Reproduce**
Write here the steps to reproduce the behavior, for example:

**Expected behavior**
Write here a clear and concise description of what you expected to happen.

**Screenshots**
Here, if applicable, add screenshots to help explain your problem.

**Knx-Ultimate Version**
3.3.5

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Additional context**
Write here any other context about the problem here.

**Comment by Supergiovane** [comment]
Hi
I've tested again yet, and it works.
The GA should have DPT 1.x (boolean), for it to work.
Please see the video here:

https://github.com/user-attachments/assets/ff5ab756-d215-48f9-9bcc-5664ecd83c6e

**Comment by jomifa** [comment]
Hi,
sorry, the video does not show the problem described. If the flow is active and the GAs entered in the alerter change to the value 1/true, then the alerter will notice this. It does not notice when the flow is deployed. If you need more information about the analysis, please let me know.

Regards

Von: Massimo Saccani ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 09:59
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] KNX Alerter does not consider the GAs when deploying node red (Issue #404)


Hi
I've tested again yet, and it works.
The GA should have DPT 1.x (boolean), for it to work.
Please see the video here:

https://github.com/user-attachments/assets/ff5ab756-d215-48f9-9bcc-5664ecd83c6e

**Comment by Supergiovane** [comment]
Hi
yes it make sense. Anyway, node-red-contrib-knx-ultimate@3.3.6 is out with the "fix"

**Comment by jomifa** [comment]
Hi,
i can’t find the fix in my node red settings.


Von: Massimo Saccani ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 10:55
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] KNX Alerter does not consider the GAs when deploying node red (Issue #404)


Hi
yes it make sense. Anyway, ***@***.******@***.***> is out with the "fix"

**Comment by Supergiovane** [comment]
Hi
Just refresh the web page. You should see it in the palette menu.

**Comment by jomifa** [comment]
Hi,
unfortunately it still does not work after a deploy of the flow. For this reason I have attached screenshots. As you can see, the lamp 1/1/197 is on and the query with the corresponding response can be seen in the diagnostics. There is no corresponding marking in the Alerter.


Von: Massimo Saccani ***@***.***>
Gesendet: Mittwoch, 4. Dezember 2024 12:30
An: Supergiovane/node-red-contrib-knx-ultimate ***@***.***>
Cc: Joachim Fach ***@***.***>; Author ***@***.***>
Betreff: Re: [Supergiovane/node-red-contrib-knx-ultimate] KNX Alerter does not consider the GAs when deploying node red (Issue #404)


Hi
Just refresh the web page. You should see it in the palette menu.

**Comment by Supergiovane** [comment]
Hi
sorry, but i there is no attachment.
