### ISSUE TITLE
Optimization of the initial read

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#41]
Hello Massimo

Thanks again for the great library!

At the moment the nodes marked with "initialread" are passed directly to the main queue. If you now have a larger number of elements, you may want to read them with a lower priority. The idea of "initialread" is from my point of view that elements are not shown as unknown on a visualization and are updated bit by bit.

My suggestion:
A separate queue for "initialread" and start it with a delay time defined in the node settings.
Also the waiting time between the single "initialread" requests should be definable in the node settings.
This "initialread" queue pushes its requests into the main queue.

What do you think, would that be feasible?

Regards Reto

**Comment by Supergiovane** [comment]
Hi Reto.
"Initialread" is triggered whenever node-red restarts. The case of a restarting node-red is very limited and, normally, this doesn't happen so often.
When it happens, i've users saying the exact contrary as you states. They need a visualization touchscreen updated as soon as possibile, to avoid pushing a button while the status of the button is unknown.
I can for sure add a delay (currently, it's fixed at 5 seconds after knx-ultimate initialisation), but thinking to add a new timer and queue array may be a bit overwhelming.
Let me know if a simple "customizable initialread delay" can be useful for you.
:-)

**Comment by heleon19** [comment]
Hi Massimo

An adjustable delay would help a little bit, but it must also be ensured that this timer is cleared when deploying or disconnecting.

The initialread is not only used when restarting Node-RED, but also for deploy and reconnect.

In my opinion, a second queue would not be much more complex? By default the delays would be the same as before, but for larger projects you could set priorities accordingly.

**Comment by Supergiovane** [comment]
Hi Reto
Yes, the redeploy triggers the initialread as well, but if you select "deploy only changed nodes" it should not be triggered.
I'll think about double queue. Maybe i can move a "read" request from the "initialread" queue, to the main telegram queue only if the main telegram queue is empty.
About the timer "clear", i need to clear all timers everytime, most importantly, if i've a "initialread" queue that are "time to time" sending telegrams into the main queue.
Let me do a gurumeditation about that.

**Comment by heleon19** [comment]
Thanks for thinking about it ;-)

I would have a two more feature requests, are you open for it?

**Comment by Supergiovane** [comment]
Yes, but please create a new issue for each.

**Comment by Supergiovane** [comment]
Ok, solved in a very elegant way.
Out soon in v 1.1.40
If you wanna try, create a function node "Massive read request" and paste this code
for (let index = 0; index < 1000; index++) {
node.send({readstatus:true}); 
}
![Node-RED](https://user-images.githubusercontent.com/37666636/76096616-aaaf4d00-5fc6-11ea-8196-fd41fee07da7.png)

Then start the function and in the meantime, turn on/off any other knx-ultimate node.
The "write" and "response" does have the higher priority in the massive flooding "read" telegrams.

**Comment by heleon19** [comment]
Thank you for optimizing this!

Could you create node setting parameters for the read delay time and the delay between telegerams can be read/write?

**Comment by Supergiovane** [comment]
Hi Reto,
not now sorry, we've fighting with Coronavirus here.
We're very in trouble..
Hope in the next weeks...

**Comment by Supergiovane** [comment]
In the meantime, you can disable the automatic read and use an inject node with delay you want, that sends a read request to knx-ultimate.
Please see here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Read-value-from-Device
