### ISSUE TITLE
knxConnection interfaces[iface] is not iterable Node

### ISSUE THREAD

**Issue by qwertz79** [Supergiovane/node-red-contrib-knx-ultimate#413]
Hello folks,

i´m using knx-ultimate on a raspberry pi and a hyper-v debian machien, wich both works fine.
Now i wantetd to install annother pi with this setup and i´m getting permantly the message in the debug window :
"KNXUltimate-config: Error in instantiating knxConnection interfaces[iface] is not iterable Node Multicast Address".
So i tried a fresh installtion of node red and knx-ultimate on a third pi, it results to the same message.
I´ve waited some time for a reconnection, but it doesn´t get better.
Both methods are affected, tunnel and multcast. I´ve GIRA X1 and a GIRA IP-Router as interfaces, so there are enough tunnels, and multicast should work anyway.

What i´m doing wrong, what i´m overlooking? Why does it work on the first pi an the debian vm?

thx ...

**Comment by Supergiovane** [comment]
Please tell me the info requested on the bug report message, plus the IP of your knx gateway. Are you sure the knx gateway does still have avaiable tunnels? Maybe you opened too many connections? Have you read the FAQ page on the wiki?

**Comment by qwertz79** [comment]
FAQ doesn´t help, i´ll try to describe as clear as possible:

**To Reproduce**
1. Gateway Adress 192.168.0.186
2. Port 3671
3. Protocoll Tunnel UDP
4. KNX Adress 1.1.248
5. Bind "Auto"
6. Auto connect "yes"

**Expected behavior**
KNX connection, logger says "on duty"

**Screenshots**
![2024-12-29_220913](https://github.com/user-attachments/assets/f38a8d20-4d9a-40de-8920-7b4e976dcbcb)
![2024-12-29_221335](https://github.com/user-attachments/assets/24b315cf-550d-4f2d-9935-2168c5b399dd)
![2024-12-29_221653](https://github.com/user-attachments/assets/42149fdf-c85b-4a73-9d7b-7062220ba515)


**Knx-Ultimate Version**
 - 3.3.8

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red running alone in RaspberryPi

**Additional context**
the same onnection on windows pc at the same network with ets5 is working. Configuration with multicast also doesn´t work.

??

**Comment by Supergiovane** [comment]
Hi
The node cannot find a suitable ethernet interface. 
Please be sure you have installed node v.20 or above.
If yes, manually select an interface in the "Bind to local interface" field and restart node-red.
You should good to go then.

**Comment by qwertz79** [comment]
Node and Nodejs are both 20.18.1.
I´ve tried with binded interface and reboot - same fault. Is there a log or anything else, were we can see more details?

**Comment by qwertz79** [comment]
I´ve looked at the other pi and the Debian-Hyper V, which is has a working knx connection. On both there is node 20.18.0 installed, Could this be interesting? May i can downgrade node to 20.18.0 for testing, but i´m not sure how to do this properly.

**Comment by Supergiovane** [comment]
Hi
the error `interfaces [iface] is not iterable` is very very strange, never happened.
The node iterates to avaiables interfaces to bind to, but the "iface" not iterable error occurs. 
You could upgrade nodejs, instead of downgrading it to 20.18.0.
You could  try creating another knx config node and use this new one.

**Comment by qwertz79** [comment]
But what i´m wondering about: i´ve tried on two raspberry in two different networks, fresh image (bookworm), newest node.js with this script: https://nodered.org/docs/getting-started/raspberrypi. Both have the same issue.
The pi and the hyper-v debian are working properly, both installed two months ago. So what could be changed since then?

**Comment by Supergiovane** [comment]
What version of knx-ultimate is installed on the working pi and the VM?

**Comment by qwertz79** [comment]
Both have 3.2.16.

**Comment by Supergiovane** [comment]
I'm looking into it...

**Comment by Supergiovane** [comment]
Hi
can you do this? https://github.com/Supergiovane/node-red-contrib-knx-ultimate/discussions/414#discussioncomment-11696950

**Comment by qwertz79** [comment]
Great news ... IT WORKS! :)

Finally i´ve set up the next pi with fresh bookworm 64, but this time i´ve installed by hand from https://nodejs.org/en/download.
Then added the KNX-Ultimate-Node, configure connection and voila!
I think there is an version issue in the script i used before, now node says:

`pi@node22:~ $ node-red
30 Dec 14:29:47 - [info]

Welcome to Node-RED
===================

30 Dec 14:29:47 - [info] Node-RED version: v4.0.8
30 Dec 14:29:47 - [info] Node.js  version: v22.12.0
30 Dec 14:29:47 - [info] Linux 6.6.51+rpt-rpi-v8 arm64 LE
30 Dec 14:29:48 - [info] Loading palette nodes
30 Dec 14:29:52 - [info] Settings file  : /home/pi/.node-red/settings.js
30 Dec 14:29:52 - [info] Context store  : 'default' [module=memory]
30 Dec 14:29:52 - [info] User directory : /home/pi/.node-red
30 Dec 14:29:52 - [warn] Projects disabled : editorTheme.projects.enabled=false
30 Dec 14:29:52 - [info] Flows file     : /home/pi/.node-red/flows.json
30 Dec 14:29:52 - [info] Creating new flow file
30 Dec 14:29:52 - [warn]`

Node.js 22.12 is working. Mayby there is only a fault at version 20.18.1, i don´t konw, but maybe interesting for you.

**Comment by Supergiovane** [comment]
Ok, it make sense now! Interesting, thanks!

**Comment by qwertz79** [comment]
Thank you for your time! Would it be interesting for you to check with your suggested file change? I still have a none working pi ... 
But i´m not sure about your described path, where should it be copied?
![2024-12-30_145448](https://github.com/user-attachments/assets/fc6e64ad-d435-4a76-85a1-4ca5cf101cbd)

**Comment by Supergiovane** [comment]
In your case, the correct path should be: `.node-red/node_modules/knxultimate/build/util`

**Comment by qwertz79** [comment]
btw. the console output on non working pi:
![2024-12-30_150023](https://github.com/user-attachments/assets/b2936478-14b7-4409-bebc-76fbaf7f7beb)

**Comment by Supergiovane** [comment]
Have you already replaced the file? I've patched that.

**Comment by qwertz79** [comment]
I dont´t found it :( ... can you please take a look about the path?

**Comment by Supergiovane** [comment]
The path is the same as the error in red: /home/pi/.node-red/node_modules/knxultimate/build/util/ipAddressHelper.js
:-)

**Comment by qwertz79** [comment]
Too may folders ;-), found + replaced - IT WORKS!
Thank you, great support!

**Comment by Supergiovane** [comment]
Perfect, i'll release a new version as soon as possible.

**Comment by Supergiovane** [comment]
node-red-contrib-knx-ultimate@3.3.9 is out.
