### ISSUE TITLE
New Function

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#42]
Hi，
I have a few ideas. Can this plugin be implemented??

1.  Scene editing function（Sence Nodes）
The first space is filled to accept the matching address and matching value，Then fill in the equipment to be executed below, such as 1/1/2 true, 1/1/3 50%, 1/1/4 false.

when 1/1/0 = 1
execute
1/1/2=1（1bit）
1/1/3=50%（1Byte）
1/1/4=0 （1bit）

2.  Automation Nodes
For example, when the air-conditioning automation is enabled (heating), the device is turned on when the indoor temperature is lower than the set temperature, and the air conditioner is turned off when the indoor temperature is higher than the set temperature +1, so that the indoor ambient temperature is maintained within another interval.

AC(Heating)
if RoomTemp < SetTemp
Power On
else if RoomTemp > SetTemp + 1
Power Off

3. Logic Nodes
 AND, OR, NOT, NAND

Best Regards
songzh

**Comment by Supergiovane** [comment]
Hi Songz
thank you for your suggestions!
What is the difference between your suggestions and simply doing it via node-red, using functions and switch nodes?

**Comment by songzh96** [comment]
This will be more convenient when we want to modify the scene.

![sence nodes](https://user-images.githubusercontent.com/26770241/76141129-60989b00-609c-11ea-9c9c-a3fe03b86b60.png)

it will easier for users,，

Of course it takes a lot of your time, and you can also tell me if you can develop this scene node in your node. I can also help

(● '◡' ●)

**Comment by Supergiovane** [comment]
Yes this make sense and i’ll develop a way, to save the scene with current actuators value as well. So you can set the lights % and then save it in a scene, by long press of a knx button. 
Let me some time, because here we’re having teouble with coronavirus.

**Comment by songzh96** [comment]
Remember to wear a face mask and wash your hands frequently. Do not touch your eyes or mouth with your hands.

Each of us has been quarantined at home for almost a month, and the epidemic is now well under control.

I hope the epidemic will pass as soon as possible.

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hi Songzh,
the scene controller is in development...

![Node-RED](https://user-images.githubusercontent.com/37666636/76340152-64762880-62fb-11ea-8c7b-fd0de42d85a6.png)

**Comment by MGKQB** [comment]
Do you build a new node for this? 

I hope you do. Right now your node is powerful but relatively easy to use. If you keep adding features at this pace the node will become way to complex IMHO.

**Comment by Supergiovane** [comment]
Hi MG
Yes, in the middle of Coronavirus emergency, i’ve added another node for that! 😁

**Comment by songzh96** [comment]
> Hi Songzh,
> the scene controller is in development...
> 
> ![Node-RED](https://user-images.githubusercontent.com/37666636/76340204-7a83e900-62fb-11ea-8d0d-58de4f846b7a.png)

Good Job!

Do you have a beta version
I will help you to develop this.

**Comment by Supergiovane** [comment]
Hello,
no, it's too early for a beta.
The configuration window is ready.
Today i'll work on the javascript backend, to allow a correct handling of all devices in the scene and to allow a scene to be "recorded" and the respective device's values to be saved in the context datastore dynamically, exactly how a real KNX scene controller device works.

**Comment by songzh96** [comment]
Yeah

This will make it easier for users to write sences

Hope to use it soon, 😊
I‘ll help you to test it

**Comment by Supergiovane** [comment]
Hi Songzh
i think to release the new version already tomorrow. Coronavirus permitting.

**Comment by svenflender** [comment]
Perhaps i can have a look on the Code so i can implement the translations for i18n from the beginning!

**Comment by Supergiovane** [comment]
Hi Sven
the node will be out today. in about 1 hour. So you can use the github code.
Thank you very much.

**Comment by svenflender** [comment]
okay, i will try to translate everything today in the evening

**Comment by Supergiovane** [comment]
V. 1.1.42 is out in 1 hour.

**Comment by Supergiovane** [comment]
Hi Songzh
Here in Italy, has landed an airplane from China, full of 30 tons of aids for us, as well as specialised medics helping us to fight coronavirus.
We all in Italy appreciate that, sooooo much, and don't forget.
Thank you!!!

**Comment by songzh96** [comment]
> Hi Songzh
> Here in Italy, has landed an airplane from China, full of 30 tons of aids for us, as well as specialised medics helping us to fight coronavirus.
> We all in Italy appreciate that, sooooo much, and don't forget.
> Thank you!!!

Hi Supergiovane

Glad to receive your thank you letter to my country.

First of all, thank you very much for developing the senses node, which helped me a lot.

There is a famous saying in China: "We are waves of the same sea, leaves of the same tree, flowers of the same garden.", we are a "fate community", so let us win this battle together (coronavirus).

患难与共，同舟共济！💪

Best Regards
Songzh

**Comment by Supergiovane** [comment]
![89662333_10157747146026839_9048737223490404352_o](https://user-images.githubusercontent.com/37666636/76620589-ca49f680-652d-11ea-92aa-c09f821c2e2c.jpg)
