### ISSUE TITLE
Icon for scene node, request for @svenflender

### ISSUE THREAD

**Issue by Supergiovane** [Supergiovane/node-red-contrib-knx-ultimate#43]
Hello Sven @svenflender,
are you able to design a new icon for a new scene controller node?

**Comment by svenflender** [comment]
Sure, what do you thought would be nice for an Icon?

Im still refactoring the editor forms and translations. Its more work than i thought.

**Comment by Supergiovane** [comment]
Hi Sven,
thank you for your help. Yes i imagine the hard work to translate that!!!
Icon as you choice. You are great in doing that and i wish you decide!

**Comment by svenflender** [comment]
Yo have a new pull request ;)
