### ISSUE TITLE
838 kBerry

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-knx-ultimate#47]
Hi,

i'm using a 838 kBerry, i can only read telegram, but can't write.

The 838 interface work with knxd and knxjs without problem.

KnxUltimate work correctly with a normalt ip interface.

Tnx

**Comment by Supergiovane** [comment]
Hello Bolfox
the knx-ultimate node works only with IP Routers/Interfaces, it does not work with physical TP serial interfaces.

What precisely is your problem?
What is your setup?

**Comment by bolfox** [comment]
Hi,
but reading is working with 838, only writing is broken.

By the way, the 838 interface is simulated as an IP interface trough knxd.
The light node setting are default.

**Comment by Supergiovane** [comment]
Hi
yes, and because of reading works, i suspect the RBE kicks in. Please try to disable the RBE filter in the node. See the wiki (https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/2.-Node-Configuration) for fuhrter instructions.

**Comment by bolfox** [comment]
Already tried, it hang on "Writing"

**Comment by Supergiovane** [comment]
Hi
Please, check your knx-ultimate configuration node and set a local interface binding not "Auto", but instead on the Ethernet of RaspberryPI.

**Comment by bolfox** [comment]
Tried, no luck...

**Comment by Supergiovane** [comment]
Hi
Have you tried to select “Suppress ACK” in the config node?
If unsuccesful, Try to use another knx node, for example knxeasy.

**Comment by bolfox** [comment]
Yes, triend also "Suppress ACK", normally i use Knx 0.8.2, tried Knxjs but sometimes hang, knxeasy used a bit, yours seem to be more complete.

**Comment by Supergiovane** [comment]
I’ll take a look at knxjs tomorrow, to sort out why it is working. 
So you set your loopback interface 127.0.0.1 in the gateway config? Have you tried to instead set the current IP of your raspi (ex 192.168.1.3) or vice versa?

**Comment by bolfox** [comment]
Yes, triend with localhost and 127.0.0.1, nothing, if you need to test we can find some chat to use.
Italiano?

**Comment by Supergiovane** [comment]
Yes italian. No chat, sorry, i’m very busy with coronavirus. 
Have you tried with the address of your ethernet interface, example 192.168.1.20?

**Comment by bolfox** [comment]
Yes, with an ip interface weinzierl 730 it works

**Comment by Supergiovane** [comment]
Hi
Yes i know but:
Every interface of your Raspi has two ip: a localhost (or 127.0.0.1) and its own ip, for example 192.168.1.20. 
I’m speaking about Raspi IP, not the weinzierl IP. 
Have you tried to put the Raspi eth IP on the config window?

**Comment by Supergiovane** [comment]
Hello,
the node-red-contrib-knx uses an old knx.js (very old) version, that uses exclusively the tunnelling/unicast mode.
Today i'll ditch into the code to see, if i can make knx-ultimate compatible with this very old knx.js API.

**Comment by bolfox** [comment]
Yes, i have tried its own ip and localhost, only read.
If i can help you tell me. Tnx

**Comment by Supergiovane** [comment]
Yes, please, take a screenshot of config-node and paste it here. Thanks.

**Comment by bolfox** [comment]
[{"id":"50000e98.4578b","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"d83a3f5f.2c54d","type":"switch","z":"50000e98.4578b","name":"","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":750,"y":240,"wires":[[],[]]},{"id":"fa7148ae.b47818","type":"knxUltimate","z":"50000e98.4578b","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"1/4/246 - PROVA studio","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":560,"y":240,"wires":[["d83a3f5f.2c54d"]]},{"id":"11420667.017f0a","type":"inject","z":"50000e98.4578b","name":"","topic":"Off","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":300,"y":180,"wires":[["fa7148ae.b47818"]]},{"id":"940b7afe.dc77d8","type":"inject","z":"50000e98.4578b","name":"","topic":"On","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":310,"y":280,"wires":[["fa7148ae.b47818"]]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.22","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"}]

**Comment by bolfox** [comment]
![image](https://user-images.githubusercontent.com/35669017/76599042-67903500-6504-11ea-8d63-eb5b6ea53e36.png)

**Comment by bolfox** [comment]
![image](https://user-images.githubusercontent.com/35669017/76599057-737bf700-6504-11ea-8606-20f4f9fe0d19.png)

**Comment by Supergiovane** [comment]
Hi BolFox
tried with 127.0.0.1 and the code path is the same as node-red-contrib-knx, it goes into tunneling mode with loopback interface.
Are you sure that knxd (that i don't use because), is not filtering your KNX physycal address 15.15.22?

**Comment by Supergiovane** [comment]
What is the IP address of your raspi eth device? Not the loopback, the IP address.

**Comment by bolfox** [comment]
192.168.0.98

**Comment by bolfox** [comment]
YES man!!!!!!!!!!!!!!

Changing the physical adress to 14.14.22 it WORKS

**Comment by Supergiovane** [comment]
Good.
That's filtering.
Sono contento, ottimo.

**Comment by jojo1457** [comment]
Hallo zusammen, ich habe ebenfalls den 838 kBerry im Einsatz und habe KNXD auf meinem Raspberry 4 installiert. Ich möchte diesen gerne als Gateway für die node-red-contrib-knx-ultimate nutzen. Die Node zeigt zwar den Status grün an, jedoch gehen keine Befehle raus und ich kann keine lesen. Meine Konfig sieht so aus:

<img width="342" height="434" alt="Image" src="https://github.com/user-attachments/assets/98bcec2c-f2c1-4e6c-bb30-6a36dd8c38b6" />

In KNXD habe ich eigentlich nur das hinterlegt: KNXD_OPTS="-e 1.1.39 -E 1.1.40:8 -D -T -R -S -b ft12:/dev/serial0". Bluetooth etc. deaktiviert...

Ich hoffe mir kann einer weiterhelfen. 

VG!

**Comment by jojo1457** [comment]
Top Danke für den Hinweis. Ich habe die aktuelle SW von KNX Ultimate nicht genutzt, da ich damals mit einem anderen Gateway Probleme hatte. Mit dem KBerry läuft es jetzt:) Super!
