### ISSUE TITLE
Group Monitor Export for ETS

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#48]
Hi Massimo

For diagnostic purposes I want to record the KNX events as the ETS does with the group monitor. Can you imagine to implement this or to create the prerequisites?

The knx.js would have to transfer the raw values with the events.

Then you would have to write the data into an XML, see example of an ETS export. This XML can then be read into the ETS.

The path for the export should be freely definable. It should be written only every 15 minutes, so if you use a SD card as storage medium the lifetime will not be shortened unnecessarily.

The number of entries should be limitable, old entries are deleted.

Regards Reto

![image](https://user-images.githubusercontent.com/10326318/76600630-9360ea00-6507-11ea-9052-a2a13e4d02eb.png)

**Comment by Supergiovane** [comment]
Hi Reto
sames as before, not now sorry. We're in very trouble with Coronavirus now.

**Comment by heleon19** [comment]
Hello Massimo

How are you doing? The Corona virus has also reached us, we now also have restrictions on freedom of movement.

I've seen that you've made some progress lately. Is developing the group monitor an option for you? If so, you could make me an offer, we would also pay something. However, we would have to negotiate this by e-mail.
If you don't want to spend time on it, I understand.

Regards Reto

**Comment by Supergiovane** [comment]
Hello Reto
here it's a disaster. Luckily, the number of death people is not growing anymore, it stays to about 600 peoples at day, with a major spike of ca. 800 in one day, last week.
You should be able to do this via a simple function node, attached to knx-ultimate.
Knx-ultimate already outputs a RAW value with type of telegram (read, write, response). You need to put these data in an XML and you're done.
Or i'm missing something?

**Comment by heleon19** [comment]
Hopefully this will soon be over!

I would need the raw data frame, not only the value. Therefor a change in knx.js would be necessary.

Here it's what I got:
![image](https://user-images.githubusercontent.com/10326318/77450926-437dff00-6df4-11ea-988d-2f9e3615ece0.png)

But I would need like the RawData in the XML above.

I think this group monitor would be a very usefull thing.

**Comment by Supergiovane** [comment]
Hi Reto
I don't use knx.js anymore. At least until Ekarak has merged my pull request, because i need the changes go faster.
Let me ditch into the raw data frame. I'll let you know. 
Then we see if putting the raw dataframe in a knx-ultimate node output property is suitable for you, or if we must go for another way (maybe a separate monitor node, to keep the things simple for people not interested in that).

**Comment by MGKQB** [comment]
Please use an extra node. Multiple nodes for special functions make more sense and they make everything a lot easier to use and understand IMHO.

**Comment by Supergiovane** [comment]
Yes, it could be a logger node, able not only to do what heleon asked, but able to prepare the data for every type of logging.

**Comment by Supergiovane** [comment]
Hi Reto,
as far as i can see, the rawData exported by ETS is in a custom format. It has nothing to do with the raw telegram.
I must find documentation about how ETS generates the output rawData field.

**Comment by Supergiovane** [comment]
Hi Reto,
i managed to extract the CEMI raw telegram.
Now i must raise it from api to the node.

**Comment by Supergiovane** [comment]
Hello Reto.
Ok raised up to the node.
Now the simples things.
I'll presumably output the XML every xx minutes to the flow (in this case, you could save it with the "file" node, or send it to an FTP server, for example).
It's ok for you?

**Comment by heleon19** [comment]
Hi Massimo
First of all, thank you for working on it!
I can open it with ETS. I think it's an good idea to output it every xx minutes. So you are creating an extra node for it with an definable output interval?

**Comment by Supergiovane** [comment]
Yup. A logger node. 
Think to release it tomorrow, as well as the api.

**Comment by Supergiovane** [comment]
V.1.1.51 is out. 
Config: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/Logger-Configuration
Sample: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/Logger-Sample

**Comment by Supergiovane** [comment]
Hi Reto. 
Does it work?
Give me a feedback. I’m italian. We love feedbacks.

**Comment by heleon19** [comment]
Ciao Massimo

Grazie mille! I know, the Italians likes to talk a lot :-)

Works very well. I also like the settings!

Do you do this as a hobby or is it your profession?

Regards Reto

**Comment by Supergiovane** [comment]
Hi Reto
No this was my job, but now it’s my hobby!
Glad it works!
If you need something else, just ask. 
Thank you and have a nice weekend!
