### ISSUE TITLE
Events not triggered

### ISSUE THREAD

**Issue by heleon19** [Supergiovane/node-red-contrib-knx-ultimate#49]
Values which are written from the Node-RED do not trigger a "write" event within the Node-RED.

![image](https://user-images.githubusercontent.com/10326318/76601069-78db4080-6508-11ea-80d2-45a6837cd365.png)

**Comment by Supergiovane** [comment]
Hi Reto
can you paste here the code of these 5 nodes?

**Comment by Supergiovane** [comment]
As i can see, you have connection issue, because the first node is still in "Writing" status.
Once wrote, the "Writing" disappears.
Check your connection.

**Comment by Supergiovane** [comment]
I suggest you to slap a Watchdog node in your flow, to receive notification if you lost connection. See here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---WatchDog

**Comment by heleon19** [comment]
The value is written to KNX bus.

[
    {
        "id": "3cb4eacb.11bb26",
        "type": "knxUltimate",
        "z": "f8ba2f7.1f2b4d",
        "server": "6f05cdf2.6fd4bc",
        "topic": "1/1/10",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "x": 670,
        "y": 520,
        "wires": [
            []
        ]
    },
    {
        "id": "1f91ca8d.35a1c5",
        "type": "knxUltimate",
        "z": "f8ba2f7.1f2b4d",
        "server": "6f05cdf2.6fd4bc",
        "topic": "1/1/10",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "x": 670,
        "y": 580,
        "wires": [
            [
                "ea303917.fa6988"
            ]
        ]
    },
    {
        "id": "ea303917.fa6988",
        "type": "debug",
        "z": "f8ba2f7.1f2b4d",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 830,
        "y": 580,
        "wires": []
    },
    {
        "id": "ba99d8ad.55a118",
        "type": "inject",
        "z": "f8ba2f7.1f2b4d",
        "name": "",
        "topic": "",
        "payload": "false",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 570,
        "y": 420,
        "wires": [
            [
                "3cb4eacb.11bb26"
            ]
        ]
    },
    {
        "id": "53aa7a7a.fd5414",
        "type": "inject",
        "z": "f8ba2f7.1f2b4d",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 530,
        "y": 460,
        "wires": [
            [
                "3cb4eacb.11bb26"
            ]
        ]
    },
    {
        "id": "6f05cdf2.6fd4bc",
        "type": "knxUltimate-config",
        "z": "",
        "host": "192.168.2.250",
        "port": "3671",
        "physAddr": "1.1.250",
        "suppressACKRequest": true,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "eth0",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": true,
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "info"
    }
]

**Comment by Supergiovane** [comment]
Mine works.
Have you checked the config-node, "bind to local interface" option? Remember, if you have more than one eth, you need to select wich eth to bind to.

![Node-RED](https://user-images.githubusercontent.com/37666636/76604975-f8b8d900-650f-11ea-9bbf-663c03c20a06.png)

**Comment by Supergiovane** [comment]
PS: tried both with KNX Router and KNX Tunnel.
Is your 1/1/10, a real KNX device? Tunneling mode needs that.

**Comment by heleon19** [comment]
It is an real device.
If I try with an none real device it's working.

**Comment by Supergiovane** [comment]
It's working everytime yet?

**Comment by heleon19** [comment]
There is no filter option. I'm using an Theben IP Interface

**Comment by Supergiovane** [comment]
Hi Reto
since when, do you have this issue?

**Comment by svenflender** [comment]
I know that some IP/Interfaces don’t act like a router and have problems with KNX/IP Implementations other than ETS.

If you can try it with an KNX IP/Router, do it.

Good IP Routers are Gira IP/Router or Siemens. There are not that much known issues.

**Comment by Supergiovane** [comment]
I use Eibmarkt Router as well. Rock solid. I've an exertex secure router as well. Also rock solid.

**Comment by Supergiovane** [comment]
#53

**Comment by Supergiovane** [comment]
Hello Reto
please see [here](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/53#issuecomment-598813695)

**Comment by Supergiovane** [comment]
Reto,

i've checked all the things. With tunneling mode, the sent telegram isn't captured by other nodes with same group address.
This only happens with multicast.
Tried also with contrib-knx and contrib-knx-easy nodes. That's the same.

It works if you create two identical node gateways and assign one knx-ultimate device to one gateway, and the other knx-ultimate node, to the other gateway.

Try this. It'll work. Please see that each knx-ultimate node, has it's own gateway (they are identical, but they are two)

![Node-RED](https://user-images.githubusercontent.com/37666636/76642041-d5fbe400-6552-11ea-8973-ce0afc83ef6a.png)


`[
    {
        "id": "d4adad21.93e6b",
        "type": "knxUltimate",
        "z": "265f2290.1ce0fe",
        "server": "2affcb51.922cfc",
        "topic": "0/1/1",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Luce tavolo taverna",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "x": 480,
        "y": 320,
        "wires": [
            []
        ]
    },
    {
        "id": "e8d2150c.a9baa",
        "type": "knxUltimate",
        "z": "265f2290.1ce0fe",
        "server": "cdfa6aac.405588",
        "topic": "0/1/1",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Luce tavolo taverna",
        "outputtype": "write",
        "outputRBE": true,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "x": 510,
        "y": 380,
        "wires": [
            [
                "acf4b271.243188"
            ]
        ]
    },
    {
        "id": "acf4b271.243188",
        "type": "debug",
        "z": "265f2290.1ce0fe",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "x": 720,
        "y": 400,
        "wires": []
    },
    {
        "id": "4ed883d9.43ccc4",
        "type": "inject",
        "z": "265f2290.1ce0fe",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 210,
        "y": 320,
        "wires": [
            [
                "d4adad21.93e6b"
            ]
        ]
    },
    {
        "id": "6432fc17.54147c",
        "type": "inject",
        "z": "265f2290.1ce0fe",
        "name": "",
        "topic": "",
        "payload": "false",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 210,
        "y": 360,
        "wires": [
            [
                "d4adad21.93e6b"
            ]
        ]
    },
    {
        "id": "90f6db89.cdd3",
        "type": "comment",
        "z": "265f2290.1ce0fe",
        "name": "Tunneling sample.",
        "info": "",
        "x": 230,
        "y": 280,
        "wires": []
    },
    {
        "id": "2affcb51.922cfc",
        "type": "knxUltimate-config",
        "z": "",
        "host": "192.168.1.44",
        "port": "3671",
        "physAddr": "15.15.1",
        "suppressACKRequest": true,
        "csv": "",
        "KNXEthInterface": "en9",
        "KNXEthInterfaceManuallyInput": "eth0",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": true,
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "debug"
    },
    {
        "id": "cdfa6aac.405588",
        "type": "knxUltimate-config",
        "z": "",
        "host": "192.168.1.44",
        "port": "3671",
        "physAddr": "15.15.22",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "en9",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error"
    }
]`

**Comment by Supergiovane** [comment]
Hi Reto
This matter is not good. 
I’m working for a final solution, so the behaviour will be the same for multicast and unicast connections.

**Comment by Supergiovane** [comment]
This behaviour has been changed in the API.
Now, in case of unicast (for example KNX/IP Interfaces), it behaves like with a KNX/IP Router, by broadcasting a local "echo" of the sent message, to all nodes with same group address.
Out with v.1.1.44

**Comment by Supergiovane** [comment]
This behaviour has been changed in the API.
Now, in case of unicast (for example KNX/IP Interfaces), it behaves like with a KNX/IP Router, by broadcasting a local "echo" of the sent message, to all nodes with same group address.
Out with v.1.1.44

**Comment by heleon19** [comment]
Thank you, works very well!

**Comment by Supergiovane** [comment]
Hi Reto,
yes, i've modified the underlying APIs. In the week, i'll post a pull request to Ekarak as well.
