### ISSUE TITLE
i18n Translation discussion

### ISSUE THREAD

**Issue by Supergiovane** [Supergiovane/node-red-contrib-knx-ultimate#50]
Sven, we'll discuss here the translation.

**Comment by svenflender** [comment]
Hi,
great 👍🏻, hope your still good!
I think next week I will continue the form editor refactoring and i18n translations.

They plan to close the schools and kindergarden here in Germany so I don’t know how much time I will have!

best Regards
Sven

**Comment by Supergiovane** [comment]
Hi Sven
Thanks. I've wiped out the html help part, because it's redundant with the wiki. If you pull the code now, you'll see the changes.

And... yes, i know.
We all are at home. Groceries are still open and it doesn't close. Not a big issue, after a while.
Remember, wash your hands, never touch eyes, mouth or nose with your hands. Use facemask and leave at least 1 - 1,5 mt from other peoples.
NEVER EVER GO TO THE OSPITAL if you've some symptoms. Call 112 instead. They come and picks you up in security.

If you feel "ditching", call immediately the Krankenwagen. Don't wait.

**Comment by Supergiovane** [comment]
Hi Sven,
translating the wiki is a mess. The github wiki system is way too simple and don't support languages. I've issues in using subfolders for each language as well.
I'm condidering [docsify](https://docsify.js.org/#/) or a wordpress website.

**Comment by Supergiovane** [comment]
I ended up making all in wiki.
You can freely edit the wiki by yourself.
Sample of file naming:
english: Overview.md
deutsch: de-Overview.md
Italiano: it-Overview.md

ans so on.

**Comment by svenflender** [comment]
Hey,
thank you. I will have a look tomorrow!
I will continue translating and refactoring on Monday.
Have a nice weekend. 
Sven

**Comment by Supergiovane** [comment]
Hi Sven,
sorry to bother, but i'm testing i18n with node-red 0.19.4 and this is the result.

<img width="826" alt="Node-RED___192_168_1_42" src="https://user-images.githubusercontent.com/37666636/76687514-0ca22f00-6625-11ea-8241-47b43ccf4a5f.png">


With 1.0.3, it works instead.
I'm new on i18n on node-red. Do you know why this happens?

**Comment by Supergiovane** [comment]
Hi,
something should be wrong in my files, because auf Detusch, it works.

**Comment by svenflender** [comment]
Yeah that’s a bug from older versions. If you rename all folders in en-US it-IT or de-DE it should work.
If not that would be really bad. But you can’t support all Versions of Node-Red.

**Comment by svenflender** [comment]
A mix will not work I think. But I have not the possibility tobtest it out today. Sorry

**Comment by Supergiovane** [comment]
Hi Sven
no, i ended up with these folders:
it
de
en-US

Otherwise, with node-red v 1.0.3 and above, using it-IT and de-DE, the html part reverts to en-US, while the node is in italian or in deutsch.
What a mess.

V. 1.1.47 is out, you can view by yourself.

**Comment by svenflender** [comment]
i took a look and the json seem to be fine in IT. with Node-Red 1.03 all seem to work like intended.

Except the help File. There you have to remove the help section in the node.html

**Comment by Supergiovane** [comment]
You not, but many users are on older version. 
I’ve at least 2 companies that are selling they device that are using my node, with old node-red version. 
;-)

**Comment by svenflender** [comment]
They should rethink to update the Node-RED Version due to security issues ;)
But i understand. So you want that i continue to refactor and the i18n implementation?

I hope you and your family are doing well!

**Comment by Supergiovane** [comment]
Yes Sven! Continue! I’m translating in italian as well. 
Yes, until now, we are fine, but it’s hard. 
We are locked down. 
You’ll end up doing this as well, because it’s the only eay to get rid of the coronavirus. 
Please no fear. I know your frustration for yourself and for your family. I’ve frustraded for my wife and parents as well, but calm down and respect what your government tell you. 
Stay alone, avoid groups and avoid speaking with other peolpe less than 1 mt away from you.

**Comment by Supergiovane** [comment]
If i can help you with coronavirus, please feel fre to ask. We’re already since 15 days in full emergency.

**Comment by svenflender** [comment]
thank you a lot.

until now i think we are good prepared...the lock down is coming, yes! now all schools and kindergarden are closed, also the borders are closed now. I think its a needed to be so strict.
I have now fear for me, more for parents, grandma and so on. The only thing we can do is to watch out and follow the rules in that case of pandemic Viruses like  Corona.

Bless you and your family!

**Comment by Supergiovane** [comment]
It is VITAL that you and family stay at home. Go out only for buying things to eat, but go alone, with mounth mask and return home as soon as possible. 
Don’t use shoes at home, don’t touch eyes mounth and nose with your hand! Wash first your hands and use alchool solution to disinfect it. 
Stay calm and use your brain. This is very important.

**Comment by Supergiovane** [comment]
Hello @svenflender
how are you?
Are you proceeding in translation or are you stopped?

**Comment by svenflender** [comment]
Hi,

I’m sorry but I had so much to do for my normal Job. Hope I can do some work at the weekend.

**Comment by Supergiovane** [comment]
Hi Sven
no worries, just to know if i can push some changes in the help docs. I'll do.
;-)

**Comment by Supergiovane** [comment]
Hallo Sven,
hope you still fine. We in Italy are all closed in home and the situation is very tragic.
Yesterday we've had 700 deaths. Today the forecast is about 600.

Only to inform you, that i've translated all nodes (auch die fehlenden Knots) in english and italian.
You should only translate the json files auf Deutsch.
About wiki parts, i've also done translation in English and italian. I'll prepare the files for German as well (the files start with "de-"), then i'll inform you when done.
If you're overwhelmed by the Corona, let me know. I'll find a way to ask someone else to do the rest of german translation. 
Many thanks and again, thank you for your work, it has helped me a lot.

Stay at home.
Massimo

**Comment by svenflender** [comment]
Hey Massimo,

hope you are also still fine. Yes, i saw the news and it is shocking how fast everything is changing.
Wish you all the best! We pray for you all!

Thx and wow great work! I had a look and yes i will translate everything in the evening after work and will do some refactoring of html part as well.

We have also a lockdown now in Germany. I work from my homeoffice and try to be relaxed. 

Thx for your help and advises in very hard time for us all. I really appreciate this. Thank you!

best regards and stay healthy!
Sven

**Comment by Supergiovane** [comment]
Download link for the wiki: https://github.com/Supergiovane/node-red-contrib-knx-ultimate.wiki.git
The affected files that you should translate, are these starting with "de-".
There are corresponding files in italian ("it-") and english (without prefix).
You then can send it to me one by one either via mail or by pasting the content here, because i think you cannot edit the wiki directly on github.
;-)

**Comment by svenflender** [comment]
Hey Massimo,

i will first translate and refactor all the nodes. The i will have a look at the Wiki. I think to translate the Wiki is a lot of ongoing work.

Suggestions (step by step): 
 - put Change Log in the main Menu (only in english!)
 - only translations for real Wiki Content for the Nodes.
 - refactoring and simplying the Wiki.
 - Usage of Github Pages https://pages.github.com/ and a simple but usable Template (i will have a look if i can finde something easy to use and customizable)

**Comment by Supergiovane** [comment]
Hi Sven

- put Change Log in the main Menu (only in english!) YES ONLY IN ENGLISH
- only translations for real Wiki Content for the Nodes. YES. SAMPLES CAN REMAIN IN ENGLISH
- refactoring and simplying the Wiki. DONE, BUT YOU CAN PUT YOUR HANDS INTO IT IF YOU WISH!

The current online wiki is the definitive version. The sidebar and the "language flag" links, point already to the correct pages ("de" pages are still in italian).

**Comment by svenflender** [comment]
Yeah great!

I will continue my work tomorrow. I'm tired and i will keep my health.

**Comment by Supergiovane** [comment]
Great Job. Thank you. By translating the wiki, you'll become the second one (after me), knowing 100% how to use the knxultimate node ;-)

I'm currently at home, between job, wife, robots cleaning the home and a cup of tea.
Have a good afternoon you too.
Thank you again for your help.
Massimo.

**Comment by Supergiovane** [comment]
Hi Sven.
How are you doing? Hope well. Here we're very in trouble, but at least are stable. Yet "only" 700-800 deaths per day. Some friends of mine have lost their parents, without even see them, because you cannot go to the hospital. This is very sad.
Anyway.
Do you have found time to translate the wiki? If not, i've an user that will do the german translation. Can i ask him?
Cheers and stay clever.
