### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-knx-ultimate#51]
Hi,

i'm testing watchdog.

1: i can't check my 838 with localhost or direct ip address, same as rpi, the 730 it works correctly.
2: in case of fault don't switch to backup (using test inject note it switch)

Tnx

"Dimmi se preferisci in italiano, ma almeno in ENG capiscono tutti" Grazie per il tuo lavoro e supporto

**Comment by bolfox** [comment]
[{"id":"30e37430.b0a5bc","type":"switch","z":"c5a13e20.ce618","name":"","property":"type","propertyType":"msg","rules":[{"t":"eq","v":"BUSError","vt":"str"},{"t":"eq","v":"NodeError","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":830,"y":280,"wires":[["ab981eca.b3f63"],["4402444b.785c7c"]]},{"id":"73c8ca24.7590e4","type":"debug","z":"c5a13e20.ce618","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":360,"wires":[]},{"id":"a47b4fce.fd254","type":"inject","z":"c5a13e20.ce618","name":"Start Watchdog","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":420,"wires":[["473fbef.ba3894"]]},{"id":"db227c19.48018","type":"inject","z":"c5a13e20.ce618","name":"Switch to main","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"30","x":140,"y":280,"wires":[["621d2f3.eb9b9d"]]},{"id":"621d2f3.eb9b9d","type":"function","z":"c5a13e20.ce618","name":"Main KNX/IP Router","func":"// You can change the IP, Port, etc.. of the KNX/IP interface/router set in the config-node\n\n// IP: IP of your KNX/IP Router or Interface\n// Port: Port of your KNX/IP Router or Interface\n// PhysicalAddress: Physical address your KNX/IP Router or Interface (this is not a Group Address, this is a physical address indicating the physical device in your KNX installation)\n// BindToEthernetInterface: \"Auto\" (for automatic detection) or the ethernet interface name, for example \"en0\".\n// All parameters are OPTIONAL. If you don't change a parameter, it remain as originally set in the config-node.\n\nmsg.setGatewayConfig={IP:\"127.0.0.1\",Port:3671,PhysicalAddress:\"15.15.200\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":280,"wires":[["8d4cb7f4.1d1bf8"]]},{"id":"ed756c60.ffe2a","type":"comment","z":"c5a13e20.ce618","name":"Adjust the KNX/IP params in the functions, manually switch KNX/IP Router and see what appens","info":"","x":370,"y":240,"wires":[]},{"id":"927ad4f2.c9c508","type":"function","z":"c5a13e20.ce618","name":"Backup KNX/IP Router","func":"// You can change the IP, Port, etc.. of the KNX/IP interface/router set in the config-node\n\n// IP: IP of your KNX/IP Router or Interface\n// Port: Port of your KNX/IP Router or Interface\n// PhysicalAddress: Physical address your KNX/IP Router or Interface (this is not a Group Address, this is a physical address indicating the physical device in your KNX installation)\n// BindToEthernetInterface: If you've set the config node to bind to one of your local Ethernet cards, you can reset it to \"Auto\" select the ethernet interface.\n\n// All parameters are OPTIONAL. If you don't change a parameter, it remain as originally set in the config-node.\n// BindToEthernetInterface: Currently, you can only set it to \"Auto\".\nmsg.setGatewayConfig={IP:\"192.168.0.99\",Port:3671,PhysicalAddress:\"15.15.254\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":320,"wires":[["8d4cb7f4.1d1bf8"]]},{"id":"6842e22f.32874c","type":"inject","z":"c5a13e20.ce618","name":"Switch to backup","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"30","x":140,"y":320,"wires":[["927ad4f2.c9c508"]]},{"id":"1cdb5bce.a944c4","type":"comment","z":"c5a13e20.ce618","name":"Manually Start/Stop the Watchdog. Enjoy.","info":"","x":200,"y":380,"wires":[]},{"id":"8d4cb7f4.1d1bf8","type":"knxUltimateWatchDog","z":"c5a13e20.ce618","server":"129d7115.337b3f","topic":"12/0/0","maxRetry":"2","retryInterval":"5","name":"","autoStart":true,"checkLevel":"Ethernet","x":620,"y":280,"wires":[["30e37430.b0a5bc","73c8ca24.7590e4"]]},{"id":"7e6063e0.712dac","type":"inject","z":"c5a13e20.ce618","name":"Stop Watchdog","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":460,"wires":[["cac44561.e4fc68"]]},{"id":"473fbef.ba3894","type":"function","z":"c5a13e20.ce618","name":"Start","func":"return {start:true};","outputs":1,"noerr":0,"x":410,"y":420,"wires":[["8d4cb7f4.1d1bf8"]]},{"id":"cac44561.e4fc68","type":"function","z":"c5a13e20.ce618","name":"Stop","func":"return {start:false};","outputs":1,"noerr":0,"x":410,"y":460,"wires":[["8d4cb7f4.1d1bf8"]]},{"id":"ab981eca.b3f63","type":"function","z":"c5a13e20.ce618","name":"Notification for BUS Error","func":"// You can send an Email to your KNX installer\nreturn msg;","outputs":1,"noerr":0,"x":1030,"y":280,"wires":[["bf309aa1.963f58","eda676e2.145868"]]},{"id":"4402444b.785c7c","type":"function","z":"c5a13e20.ce618","name":"Notification for Nodes Error","func":"// You land here if sone kns-ultimate nodes reports an error\n// You can send an Email to your KNX installer\nreturn msg;","outputs":1,"noerr":0,"x":1040,"y":340,"wires":[[]]},{"id":"bf309aa1.963f58","type":"function","z":"c5a13e20.ce618","name":"Switch to Backup KNX/IP Router","func":"msg.setGatewayConfig={IP:\"192.168.0.99\",Port:3671,PhysicalAddress:\"15.15.254\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":1330,"y":280,"wires":[[]]},{"id":"eda676e2.145868","type":"pushover","z":"c5a13e20.ce618","name":"","device":"","title":"Bus KNX","priority":"0","sound":"","url":"","url_title":"","html":false,"x":1260,"y":220,"wires":[]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.200","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"}]

**Comment by Supergiovane** [comment]
Hi
yes, we can still use english, so others can read.
There are issues in your pasted code. I'm unable to paste it into node-red. Can you re-paste it, leaving it formatted?

**Comment by bolfox** [comment]
[{"id":"3c367ce8.b70394","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"4367abd8.c4a804","type":"switch","z":"3c367ce8.b70394","name":"","property":"type","propertyType":"msg","rules":[{"t":"eq","v":"BUSError","vt":"str"},{"t":"eq","v":"NodeError","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":830,"y":220,"wires":[["135375a3.2f2b8a"],["d2cf160b.443b88"]]},{"id":"10e366e0.543949","type":"debug","z":"3c367ce8.b70394","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":300,"wires":[]},{"id":"b95f71d5.fdcab","type":"inject","z":"3c367ce8.b70394","name":"Start Watchdog","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":360,"wires":[["665a678.b7a3898"]]},{"id":"bb264825.78f168","type":"inject","z":"3c367ce8.b70394","name":"Switch to main","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"30","x":140,"y":220,"wires":[["ce1a9798.f94458"]]},{"id":"ce1a9798.f94458","type":"function","z":"3c367ce8.b70394","name":"Main KNX/IP Router","func":"// You can change the IP, Port, etc.. of the KNX/IP interface/router set in the config-node\n\n// IP: IP of your KNX/IP Router or Interface\n// Port: Port of your KNX/IP Router or Interface\n// PhysicalAddress: Physical address your KNX/IP Router or Interface (this is not a Group Address, this is a physical address indicating the physical device in your KNX installation)\n// BindToEthernetInterface: \"Auto\" (for automatic detection) or the ethernet interface name, for example \"en0\".\n// All parameters are OPTIONAL. If you don't change a parameter, it remain as originally set in the config-node.\n\nmsg.setGatewayConfig={IP:\"127.0.0.1\",Port:3671,PhysicalAddress:\"15.15.200\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":220,"wires":[["511fe05e.9f5c3"]]},{"id":"d69f5747.70c548","type":"comment","z":"3c367ce8.b70394","name":"Adjust the KNX/IP params in the functions, manually switch KNX/IP Router and see what appens","info":"","x":370,"y":180,"wires":[]},{"id":"b60ed15d.602d1","type":"function","z":"3c367ce8.b70394","name":"Backup KNX/IP Router","func":"// You can change the IP, Port, etc.. of the KNX/IP interface/router set in the config-node\n\n// IP: IP of your KNX/IP Router or Interface\n// Port: Port of your KNX/IP Router or Interface\n// PhysicalAddress: Physical address your KNX/IP Router or Interface (this is not a Group Address, this is a physical address indicating the physical device in your KNX installation)\n// BindToEthernetInterface: If you've set the config node to bind to one of your local Ethernet cards, you can reset it to \"Auto\" select the ethernet interface.\n\n// All parameters are OPTIONAL. If you don't change a parameter, it remain as originally set in the config-node.\n// BindToEthernetInterface: Currently, you can only set it to \"Auto\".\nmsg.setGatewayConfig={IP:\"192.168.0.99\",Port:3671,PhysicalAddress:\"15.15.254\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":260,"wires":[["511fe05e.9f5c3"]]},{"id":"7ab55c34.cf1f34","type":"inject","z":"3c367ce8.b70394","name":"Switch to backup","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"30","x":140,"y":260,"wires":[["b60ed15d.602d1"]]},{"id":"552bd94.cd5ab28","type":"comment","z":"3c367ce8.b70394","name":"Manually Start/Stop the Watchdog. Enjoy.","info":"","x":200,"y":320,"wires":[]},{"id":"511fe05e.9f5c3","type":"knxUltimateWatchDog","z":"3c367ce8.b70394","server":"129d7115.337b3f","topic":"12/0/0","maxRetry":"2","retryInterval":"5","name":"","autoStart":true,"checkLevel":"Ethernet","x":620,"y":220,"wires":[["4367abd8.c4a804","10e366e0.543949"]]},{"id":"6ca55c72.63b1b4","type":"inject","z":"3c367ce8.b70394","name":"Stop Watchdog","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":400,"wires":[["c4178d5d.ea6ce"]]},{"id":"665a678.b7a3898","type":"function","z":"3c367ce8.b70394","name":"Start","func":"return {start:true};","outputs":1,"noerr":0,"x":410,"y":360,"wires":[["511fe05e.9f5c3"]]},{"id":"c4178d5d.ea6ce","type":"function","z":"3c367ce8.b70394","name":"Stop","func":"return {start:false};","outputs":1,"noerr":0,"x":410,"y":400,"wires":[["511fe05e.9f5c3"]]},{"id":"135375a3.2f2b8a","type":"function","z":"3c367ce8.b70394","name":"Notification for BUS Error","func":"// You can send an Email to your KNX installer\nreturn msg;","outputs":1,"noerr":0,"x":1030,"y":220,"wires":[["1d378fba.39e24","e2e5145a.58ef08"]]},{"id":"d2cf160b.443b88","type":"function","z":"3c367ce8.b70394","name":"Notification for Nodes Error","func":"// You land here if sone kns-ultimate nodes reports an error\n// You can send an Email to your KNX installer\nreturn msg;","outputs":1,"noerr":0,"x":1040,"y":280,"wires":[[]]},{"id":"1d378fba.39e24","type":"function","z":"3c367ce8.b70394","name":"Switch to Backup KNX/IP Router","func":"msg.setGatewayConfig={IP:\"192.168.0.99\",Port:3671,PhysicalAddress:\"15.15.254\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":1330,"y":220,"wires":[[]]},{"id":"e2e5145a.58ef08","type":"pushover","z":"3c367ce8.b70394","name":"","device":"","title":"Bus KNX","priority":"0","sound":"","url":"","url_title":"","html":false,"x":1260,"y":160,"wires":[]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.200","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"}]

**Comment by bolfox** [comment]
I try with CODE
`[{"id":"3c367ce8.b70394","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"4367abd8.c4a804","type":"switch","z":"3c367ce8.b70394","name":"","property":"type","propertyType":"msg","rules":[{"t":"eq","v":"BUSError","vt":"str"},{"t":"eq","v":"NodeError","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":830,"y":220,"wires":[["135375a3.2f2b8a"],["d2cf160b.443b88"]]},{"id":"10e366e0.543949","type":"debug","z":"3c367ce8.b70394","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":790,"y":300,"wires":[]},{"id":"b95f71d5.fdcab","type":"inject","z":"3c367ce8.b70394","name":"Start Watchdog","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":360,"wires":[["665a678.b7a3898"]]},{"id":"bb264825.78f168","type":"inject","z":"3c367ce8.b70394","name":"Switch to main","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"30","x":140,"y":220,"wires":[["ce1a9798.f94458"]]},{"id":"ce1a9798.f94458","type":"function","z":"3c367ce8.b70394","name":"Main KNX/IP Router","func":"// You can change the IP, Port, etc.. of the KNX/IP interface/router set in the config-node\n\n// IP: IP of your KNX/IP Router or Interface\n// Port: Port of your KNX/IP Router or Interface\n// PhysicalAddress: Physical address your KNX/IP Router or Interface (this is not a Group Address, this is a physical address indicating the physical device in your KNX installation)\n// BindToEthernetInterface: \"Auto\" (for automatic detection) or the ethernet interface name, for example \"en0\".\n// All parameters are OPTIONAL. If you don't change a parameter, it remain as originally set in the config-node.\n\nmsg.setGatewayConfig={IP:\"127.0.0.1\",Port:3671,PhysicalAddress:\"15.15.200\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":220,"wires":[["511fe05e.9f5c3"]]},{"id":"d69f5747.70c548","type":"comment","z":"3c367ce8.b70394","name":"Adjust the KNX/IP params in the functions, manually switch KNX/IP Router and see what appens","info":"","x":370,"y":180,"wires":[]},{"id":"b60ed15d.602d1","type":"function","z":"3c367ce8.b70394","name":"Backup KNX/IP Router","func":"// You can change the IP, Port, etc.. of the KNX/IP interface/router set in the config-node\n\n// IP: IP of your KNX/IP Router or Interface\n// Port: Port of your KNX/IP Router or Interface\n// PhysicalAddress: Physical address your KNX/IP Router or Interface (this is not a Group Address, this is a physical address indicating the physical device in your KNX installation)\n// BindToEthernetInterface: If you've set the config node to bind to one of your local Ethernet cards, you can reset it to \"Auto\" select the ethernet interface.\n\n// All parameters are OPTIONAL. If you don't change a parameter, it remain as originally set in the config-node.\n// BindToEthernetInterface: Currently, you can only set it to \"Auto\".\nmsg.setGatewayConfig={IP:\"192.168.0.99\",Port:3671,PhysicalAddress:\"15.15.254\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":360,"y":260,"wires":[["511fe05e.9f5c3"]]},{"id":"7ab55c34.cf1f34","type":"inject","z":"3c367ce8.b70394","name":"Switch to backup","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":"30","x":140,"y":260,"wires":[["b60ed15d.602d1"]]},{"id":"552bd94.cd5ab28","type":"comment","z":"3c367ce8.b70394","name":"Manually Start/Stop the Watchdog. Enjoy.","info":"","x":200,"y":320,"wires":[]},{"id":"511fe05e.9f5c3","type":"knxUltimateWatchDog","z":"3c367ce8.b70394","server":"129d7115.337b3f","topic":"12/0/0","maxRetry":"2","retryInterval":"5","name":"","autoStart":true,"checkLevel":"Ethernet","x":620,"y":220,"wires":[["4367abd8.c4a804","10e366e0.543949"]]},{"id":"6ca55c72.63b1b4","type":"inject","z":"3c367ce8.b70394","name":"Stop Watchdog","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":140,"y":400,"wires":[["c4178d5d.ea6ce"]]},{"id":"665a678.b7a3898","type":"function","z":"3c367ce8.b70394","name":"Start","func":"return {start:true};","outputs":1,"noerr":0,"x":410,"y":360,"wires":[["511fe05e.9f5c3"]]},{"id":"c4178d5d.ea6ce","type":"function","z":"3c367ce8.b70394","name":"Stop","func":"return {start:false};","outputs":1,"noerr":0,"x":410,"y":400,"wires":[["511fe05e.9f5c3"]]},{"id":"135375a3.2f2b8a","type":"function","z":"3c367ce8.b70394","name":"Notification for BUS Error","func":"// You can send an Email to your KNX installer\nreturn msg;","outputs":1,"noerr":0,"x":1030,"y":220,"wires":[["1d378fba.39e24","e2e5145a.58ef08"]]},{"id":"d2cf160b.443b88","type":"function","z":"3c367ce8.b70394","name":"Notification for Nodes Error","func":"// You land here if sone kns-ultimate nodes reports an error\n// You can send an Email to your KNX installer\nreturn msg;","outputs":1,"noerr":0,"x":1040,"y":280,"wires":[[]]},{"id":"1d378fba.39e24","type":"function","z":"3c367ce8.b70394","name":"Switch to Backup KNX/IP Router","func":"msg.setGatewayConfig={IP:\"192.168.0.99\",Port:3671,PhysicalAddress:\"15.15.254\",BindToEthernetInterface:\"Auto\"};\nreturn msg;","outputs":1,"noerr":0,"x":1330,"y":220,"wires":[[]]},{"id":"e2e5145a.58ef08","type":"pushover","z":"3c367ce8.b70394","name":"","device":"","title":"Bus KNX","priority":"0","sound":"","url":"","url_title":"","html":false,"x":1260,"y":160,"wires":[]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.200","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"}]`

**Comment by Supergiovane** [comment]
Hi
yes, because you need to link the output pin of the function, again with the input pin of the node.
I haven't that in the sample, because every user can have different configuration and i don't want to "incasinare" the user installation.

![Node-RED](https://user-images.githubusercontent.com/37666636/76611883-7f26e800-651b-11ea-9002-f1ec55c785d6.png)

**Comment by bolfox** [comment]
I like "incasinare"...

Perfect, now it works, but i can't check the localhost ip of 838... Also with direct IP

**Comment by Supergiovane** [comment]
Yes, this is a limitation in using tunneling (unicast) KNX/IP interfaces, like your knxd
Please use the FULL CHECK and point the Group address, to a real KNX device in your installation, capable to respond to a read request (for example a light status group address).
I'll add this note to the Wiki.

![Schermata 2020-03-13 alle 11 24 04](https://user-images.githubusercontent.com/37666636/76612822-569fed80-651d-11ea-81d5-d42b64418734.png)

**Comment by bolfox** [comment]
Perfect, with address group it works perfectly...
