### ISSUE TITLE
Circular protection, how to AVOID

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-knx-ultimate#52]
I'm unable to avoid Circular protection, tried with rbe filter with no luck.

Check also [https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Protections](url)

`[{"id":"5c5d8c2b.df2594","type":"tab","label":"Flow 5","disabled":false,"info":""},{"id":"28750c15.d27a54","type":"switch","z":"5c5d8c2b.df2594","name":"","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":570,"y":300,"wires":[["85d9a5e4.5c65d8"],["497be3ca.64bdac"]]},{"id":"85d9a5e4.5c65d8","type":"trigger","z":"5c5d8c2b.df2594","op1":"","op2":"false","op1type":"nul","op2type":"bool","duration":"5","extend":false,"units":"s","reset":"","bytopic":"all","name":"","x":720,"y":100,"wires":[["610ec55b.f8bb9c"]]},{"id":"497be3ca.64bdac","type":"function","z":"5c5d8c2b.df2594","name":"reset msg","func":"msg.reset = true;\nreturn msg;","outputs":1,"noerr":0,"x":740,"y":220,"wires":[["85d9a5e4.5c65d8"]]},{"id":"610ec55b.f8bb9c","type":"knxUltimate","z":"5c5d8c2b.df2594","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"1/4/246 - TESTt","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":960,"y":100,"wires":[[]]},{"id":"dd877fec.07133","type":"comment","z":"5c5d8c2b.df2594","name":"Circular reference protection sample. Click the Inject node.","info":"","x":470,"y":420,"wires":[]},{"id":"72b4539d.08ba5c","type":"inject","z":"5c5d8c2b.df2594","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":460,"wires":[["3c1e7727.1dfb28"]]},{"id":"3c1e7727.1dfb28","type":"knxUltimate","z":"5c5d8c2b.df2594","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Table Light","outputtype":"write","outputRBE":false,"inputRBE":false,"x":470,"y":460,"wires":[["dff0e87.9c1bb18"]]},{"id":"dff0e87.9c1bb18","type":"knxUltimate","z":"5c5d8c2b.df2594","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Table Light","outputtype":"write","outputRBE":false,"inputRBE":false,"x":690,"y":460,"wires":[[]]},{"id":"ced555fe.9993f8","type":"comment","z":"5c5d8c2b.df2594","name":"How to avoid Circular reference protection. Click the Inject node.","info":"","x":490,"y":540,"wires":[]},{"id":"db5d9e31.13ec3","type":"inject","z":"5c5d8c2b.df2594","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":580,"wires":[["cf6c6db5.f9eca"]]},{"id":"cf6c6db5.f9eca","type":"knxUltimate","z":"5c5d8c2b.df2594","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Table Light2","outputtype":"write","outputRBE":false,"inputRBE":false,"x":470,"y":580,"wires":[["ebe857ff.c77448"]]},{"id":"ebe857ff.c77448","type":"knxUltimate","z":"5c5d8c2b.df2594","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Table Light2","outputtype":"write","outputRBE":true,"inputRBE":false,"x":710,"y":580,"wires":[[]]},{"id":"7c91acb0.ae7754","type":"knxUltimate","z":"5c5d8c2b.df2594","server":"129d7115.337b3f","topic":"1/4/246","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"1/4/246 - TESTt","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":340,"y":300,"wires":[["28750c15.d27a54"]]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.200","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"}]`

**Comment by Supergiovane** [comment]
Hi
create a function with this code, and put it inbetween nodes, like in the picture:
`return {payload:msg.payload};`

![Node-RED](https://user-images.githubusercontent.com/37666636/76614503-8bfa0a80-6520-11ea-8938-47a7ce06be4d.png)
