### ISSUE TITLE
Hang on writing

### ISSUE THREAD

**Issue by bolfox** [Supergiovane/node-red-contrib-knx-ultimate#53]
Hi man,

always me (i'm converting all my logic knx to you ultimate)

If i use the 838 baos on the attached flow it hang on "writing" the output, with ip interface it works.

![image](https://user-images.githubusercontent.com/35669017/76625011-a939d380-6536-11ea-8f22-aff03f65c987.png)

**Comment by bolfox** [comment]
`[{"id":"9a40b8f4.a5fd48","type":"tab","label":"Tasti + Scene","disabled":false,"info":"Spegnimento di entrambe le luci (Rosse+Bianche)\nSOLO se premo OFF dal tasto FISICO in antibagno\n\nSpegnimento delle luci Lavandino\nSOLO se premo OFF dal tasto FISICO della Libreria\n\nControllo scenari ByMe"},{"id":"e229d8c5.906158","type":"function","z":"9a40b8f4.a5fd48","name":"Bianche spegne Rosse","func":"if (msg.payload.srcphy == \"1.0.20\" && msg.payload.dstgad == \"1/4/134\" && msg.payload.value == \"0\")\n{\n   msg.payload={\"dstgad\":\"1/4/135\",\"value\":\"0\",\"dtp\":\"1\"};\n   return msg;\n}","outputs":1,"noerr":0,"x":450,"y":140,"wires":[["754636d.fe1e9c8"]]},{"id":"fff15b2c.11f9d8","type":"function","z":"9a40b8f4.a5fd48","name":"Libreria spegne Lavandino","func":"if (msg.payload.srcphy == \"1.0.12\" && msg.payload.dstgad == \"1/5/205\" && msg.payload.value == \"0\")\n{\n   msg.payload={\"dstgad\":\"1/5/203\",\"value\":\"0\",\"dtp\":\"1\"};\n   return msg;\n}","outputs":1,"noerr":0,"x":460,"y":100,"wires":[["754636d.fe1e9c8"]]},{"id":"50e2c789.37b578","type":"link in","z":"9a40b8f4.a5fd48","name":"Tasti_IN","links":["df414b6d.6ff3b8","e21c591e.370fe8"],"x":95,"y":80,"wires":[["fff15b2c.11f9d8","e71fd066.0a925","e229d8c5.906158","25f3312f.34116e","a7ee8e2c.23607"]]},{"id":"754636d.fe1e9c8","type":"link out","z":"9a40b8f4.a5fd48","name":"Tasti_OUT","links":["2101b0f4.7de67","a9b99f9.dd7c46"],"x":880,"y":300,"wires":[]},{"id":"e71fd066.0a925","type":"timed-counter","z":"9a40b8f4.a5fd48","name":"double_T_ms","timelimit":"800","withhold":true,"fixedtimeout":false,"x":240,"y":300,"wires":[["4d02de84.2bc6d"]]},{"id":"4d02de84.2bc6d","type":"function","z":"9a40b8f4.a5fd48","name":"Doppia pressione ON Sala TV","func":"if (msg.count == 2 && msg.payload.srcphy == \"1.0.20\" && msg.payload.dstgad == \"1/4/134\" && msg.payload.value == \"1\")\n{\n    msg.payload={\"dstgad\":\"1/4/135\",\"value\":\"1\",\"dtp\":\"1\"};\n    return msg;\n}","outputs":1,"noerr":0,"x":470,"y":300,"wires":[["754636d.fe1e9c8"]]},{"id":"25f3312f.34116e","type":"function","z":"9a40b8f4.a5fd48","name":"Hue accende rele Rosse","func":"if (msg.payload.dstgad == \"1/5/177\" && msg.payload.value == \"1\")\n{\n   msg.payload={\"dstgad\":\"1/4/135\",\"value\":\"1\",\"dtp\":\"1\"};\n   return msg;\n}","outputs":1,"noerr":0,"x":450,"y":180,"wires":[["754636d.fe1e9c8"]]},{"id":"a7ee8e2c.23607","type":"function","z":"9a40b8f4.a5fd48","name":"Hue accende rele Angolo giochi","func":"if (msg.payload.dstgad == \"1/5/214\" && msg.payload.value == \"1\")\n{\n   msg.payload={\"dstgad\":\"1/5/213\",\"value\":\"1\",\"dtp\":\"1\"};\n   return msg;\n}","outputs":1,"noerr":0,"x":470,"y":220,"wires":[["754636d.fe1e9c8"]]},{"id":"837bbf8a.967a4","type":"knxUltimate","z":"9a40b8f4.a5fd48","server":"129d7115.337b3f","topic":"1/5/241","outputtopic":"","dpt":"5.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Matrimoniale - DIM","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":1150,"y":560,"wires":[[]]},{"id":"3f3b649d.672b6c","type":"inject","z":"9a40b8f4.a5fd48","name":"","topic":"","payload":"100","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":910,"y":580,"wires":[["837bbf8a.967a4"]]},{"id":"3b2d4eed.dda872","type":"inject","z":"9a40b8f4.a5fd48","name":"","topic":"","payload":"25","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":910,"y":540,"wires":[["837bbf8a.967a4"]]},{"id":"9931453a.b5a948","type":"function","z":"9a40b8f4.a5fd48","name":"25%","func":"if (msg.topic === \"1/4/126\" && msg.payload === true && msg.knx.source !== \"1.0.171\")\n{\n   msg.payload = 25;\n   return msg;\n}","outputs":1,"noerr":0,"x":910,"y":500,"wires":[["837bbf8a.967a4"]]},{"id":"be564a38.d5cb38","type":"ui_switch","z":"9a40b8f4.a5fd48","name":"","label":"Notte","group":"3f20912.2ff646e","order":3,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"notte","style":"","onvalue":"true","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"false","offvalueType":"bool","officon":"","offcolor":"","x":390,"y":500,"wires":[["d76c0fe0.3ebae"]]},{"id":"d76c0fe0.3ebae","type":"function","z":"9a40b8f4.a5fd48","name":"Check_Notte","func":"if (msg.topic === \"notte\") {\n    context.pass = (msg.payload === true) ? true : false;\n    return null;  // exit out early as it's just the control\n}\nif (context.pass) {\n    return msg; // if enabled pass msg\n}\nreturn null; // or drop it","outputs":1,"noerr":0,"x":750,"y":500,"wires":[["9931453a.b5a948"]]},{"id":"ff866f2d.78b64","type":"inject","z":"9a40b8f4.a5fd48","name":"","topic":"On","payload":"true","payloadType":"bool","repeat":"","crontab":"00 23 * * *","once":false,"onceDelay":0.1,"x":140,"y":580,"wires":[["be564a38.d5cb38","832c50.2348a3b"]]},{"id":"feb815ac.a60a38","type":"inject","z":"9a40b8f4.a5fd48","name":"","topic":"Off","payload":"false","payloadType":"bool","repeat":"","crontab":"00 08 * * *","once":false,"onceDelay":0.1,"x":140,"y":540,"wires":[["be564a38.d5cb38","832c50.2348a3b"]]},{"id":"d9aacfb1.4fc05","type":"function","z":"9a40b8f4.a5fd48","name":"100%","func":"if (msg.topic === \"1/4/126\" && msg.payload === true && msg.knx.source !== \"1.0.171\")\n{\n   msg.payload = 100;\n   return msg;\n}","outputs":1,"noerr":0,"x":910,"y":620,"wires":[["837bbf8a.967a4"]]},{"id":"832c50.2348a3b","type":"ui_switch","z":"9a40b8f4.a5fd48","name":"","label":"Giorno","group":"3f20912.2ff646e","order":3,"width":0,"height":0,"passthru":true,"decouple":"false","topic":"giorno","style":"","onvalue":"false","onvalueType":"bool","onicon":"","oncolor":"","offvalue":"true","offvalueType":"bool","officon":"","offcolor":"","x":390,"y":620,"wires":[["cbf5e025.ece8b"]]},{"id":"cbf5e025.ece8b","type":"function","z":"9a40b8f4.a5fd48","name":"Check_Giorno","func":"if (msg.topic === \"giorno\") {\n    context.pass = (msg.payload === false) ? true : false;\n    return null;  // exit out early as it's just the control\n}\nif (context.pass) {\n    return msg; // if enabled pass msg\n}\nreturn null; // or drop it","outputs":1,"noerr":0,"x":760,"y":620,"wires":[["d9aacfb1.4fc05"]]},{"id":"b68a382e.c99268","type":"knxUltimate","z":"9a40b8f4.a5fd48","server":"129d7115.337b3f","topic":"1/4/126","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Matrimoniale - ON","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":510,"y":560,"wires":[["d76c0fe0.3ebae","cbf5e025.ece8b"]]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.200","suppressACKRequest":true,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"},{"id":"3f20912.2ff646e","type":"ui_group","z":"","name":"Notifiche","tab":"729a664e.7d52c8","order":2,"disp":true,"width":"6","collapse":false},{"id":"729a664e.7d52c8","type":"ui_tab","z":"","name":"Home","icon":"dashboard"}]`

**Comment by Supergiovane** [comment]
Hi
the datapoint of the DIM is normally 3.007 and you need to control it in another way (https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Dimming)
DIM are used to send a dim telegram, not to send a absolutes %.
Please review your device config in ETS and use the "Absolute Brighntess Value" group address of your KNX device. For sure it has this type of group address (5.001).

**Comment by Supergiovane** [comment]
But please leave me some minutes to do other checks... i'll put up another KNX IP device to test.

**Comment by bolfox** [comment]
Tnx. the flow work with IP interface, the problem of writing is also on another flow.
Same problem, IP ok, 838 hang on writing
`[{"id":"c0bc624d.3a273","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"505e97cf.9f43f8","type":"knxUltimate","z":"c0bc624d.3a273","server":"129d7115.337b3f","topic":"1/4/138","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Poggiolo","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":260,"y":240,"wires":[["a005490f.fd5f98"]]},{"id":"a005490f.fd5f98","type":"switch","z":"c0bc624d.3a273","name":"","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":570,"y":260,"wires":[["4c60a925.017dc8"],["d54f34fc.b11bc8"]]},{"id":"b091df7.9a6d42","type":"trigger","z":"c0bc624d.3a273","op1":"","op2":"false","op1type":"nul","op2type":"bool","duration":"5","extend":false,"units":"s","reset":"","bytopic":"all","name":"","x":820,"y":200,"wires":[["7ea1c9cf.9d8f58"]]},{"id":"d54f34fc.b11bc8","type":"function","z":"c0bc624d.3a273","name":"reset msg","func":"msg.reset = true;\nreturn msg;","outputs":1,"noerr":0,"x":820,"y":260,"wires":[["b091df7.9a6d42","7ea1c9cf.9d8f58"]]},{"id":"4c60a925.017dc8","type":"function","z":"c0bc624d.3a273","name":"wipe origin","func":"return {payload:msg.payload};","outputs":1,"noerr":0,"x":570,"y":200,"wires":[["b091df7.9a6d42"]]},{"id":"7ea1c9cf.9d8f58","type":"knxUltimate","z":"c0bc624d.3a273","server":"129d7115.337b3f","topic":"1/4/138","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"Poggiolo","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"x":1040,"y":240,"wires":[[]]},{"id":"129d7115.337b3f","type":"knxUltimate-config","z":"","host":"127.0.0.1","port":"3671","physAddr":"15.15.200","suppressACKRequest":true,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error"}]`

**Comment by Supergiovane** [comment]
Ehm... Sorry, what make/model is your external IP Interface?

**Comment by bolfox** [comment]
Weinzierl 730

**Comment by Supergiovane** [comment]
#49 
There is a subtle strange behaviour in the underlying APIs. I'll investigate that.
If you use a switch true/false, it works. If you send a numeric value, the light is dimmed but the datagram is not raised to other nodes.

**Comment by Supergiovane** [comment]
Hi bolfox,
i've checked all the things. With tunneling mode, the sent telegram isn't captured by other nodes with same group address.
This only happens with multicast.
Tried also with contrib-knx and contrib-knx-easy nodes. That's the same.
The connection is unique for all nodes.

It works if you create two identical node gateways and assign one knx-ultimate device (Matrimoniale DIM) to one gateway, and the other knx-ultimate node, to the other gateway.
Try this:

`[
    {
        "id": "1f50a0a8.b5759f",
        "type": "knxUltimate",
        "z": "c99f97a9.51a42",
        "server": "1954a655.342f2a",
        "topic": "1/4/138",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Poggiolo",
        "outputtype": "write",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "x": 260,
        "y": 240,
        "wires": [
            [
                "c6cfd91c.f30c"
            ]
        ]
    },
    {
        "id": "c6cfd91c.f30c",
        "type": "switch",
        "z": "c99f97a9.51a42",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 570,
        "y": 260,
        "wires": [
            [
                "869c4247.4b641"
            ],
            [
                "6b71f155.dce08"
            ]
        ]
    },
    {
        "id": "d2056e2c.24ee58",
        "type": "trigger",
        "z": "c99f97a9.51a42",
        "op1": "",
        "op2": "false",
        "op1type": "nul",
        "op2type": "bool",
        "duration": "5",
        "extend": false,
        "units": "s",
        "reset": "",
        "bytopic": "all",
        "name": "",
        "x": 820,
        "y": 200,
        "wires": [
            [
                "8f76238a.6973e"
            ]
        ]
    },
    {
        "id": "6b71f155.dce08",
        "type": "function",
        "z": "c99f97a9.51a42",
        "name": "reset msg",
        "func": "msg.reset = true;\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 820,
        "y": 260,
        "wires": [
            [
                "d2056e2c.24ee58",
                "8f76238a.6973e"
            ]
        ]
    },
    {
        "id": "869c4247.4b641",
        "type": "function",
        "z": "c99f97a9.51a42",
        "name": "wipe origin",
        "func": "return {payload:msg.payload};",
        "outputs": 1,
        "noerr": 0,
        "x": 570,
        "y": 200,
        "wires": [
            [
                "d2056e2c.24ee58"
            ]
        ]
    },
    {
        "id": "8f76238a.6973e",
        "type": "knxUltimate",
        "z": "c99f97a9.51a42",
        "server": "fb6e203b.514888",
        "topic": "1/4/138",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Poggiolo",
        "outputtype": "write",
        "outputRBE": true,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "x": 1040,
        "y": 240,
        "wires": [
            []
        ]
    },
    {
        "id": "f74443c0.1aee68",
        "type": "comment",
        "z": "c99f97a9.51a42",
        "name": "This has gateway 1 assigned",
        "info": "",
        "x": 300,
        "y": 200,
        "wires": []
    },
    {
        "id": "cc31d018.4c204",
        "type": "comment",
        "z": "c99f97a9.51a42",
        "name": "This has gateway 2 assigned",
        "info": "",
        "x": 1060,
        "y": 200,
        "wires": []
    },
    {
        "id": "1954a655.342f2a",
        "type": "knxUltimate-config",
        "z": "",
        "host": "127.0.0.1",
        "port": "3671",
        "physAddr": "15.15.22",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error"
    },
    {
        "id": "fb6e203b.514888",
        "type": "knxUltimate-config",
        "z": "",
        "host": "127.0.0.1",
        "port": "3671",
        "physAddr": "15.15.200",
        "suppressACKRequest": true,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error"
    }
]`

**Comment by Supergiovane** [comment]
Hi
This matter is not good. 
I’m working for a final solution, so the behaviour will be the same for multicast and unicast connections.

**Comment by Supergiovane** [comment]
Hi!
Please upgrade to the latest version and enable the option “Echo sent message to all node with same Group Address“ in the gateway config.

**Comment by bolfox** [comment]
Man you are amazing... 
Now it works like a charm...
During the week (ferie forzate) i will convert all my sistem to your node, i keep you updated...

**Comment by Supergiovane** [comment]
Grazie!
Usciremo da sta menata spero il prima possibile!
