### ISSUE TITLE
Scene Controller doesn't react on DPT 17.001

### ISSUE THREAD

**Issue by mthauth** [Supergiovane/node-red-contrib-knx-ultimate#54]
I am running the KNX Scene Controller from the node-red-contrib-knx-ultimate 1.1.48 version.

Here i tried to make a scene recall on a group address (0/5/0) with the DPT 17.001 (scene number).

The Controller doesn't react.

If i use a KNX Device reading GA 0/5/0 from the same node-red-contrib-knx-ultimate package and connect the output with debug, i receive a scene number (but it is 1 smaller, then expected (f.e. 2 instead of 3)).

Otherwise if i make a scene recall triggered by a bool, the scene controller works.

Attached you find a screenshot of the node configuration.

Thanks a lot - and i hope you are fine!
![scenecontroller](https://user-images.githubusercontent.com/6154305/76985380-6c0f8000-6940-11ea-9d14-300e516702d6.png)

**Comment by Supergiovane** [comment]
Hello
I’ll investigate and let you know as soon as possible!

**Comment by Supergiovane** [comment]
Bug confirmed. Working on it.

**Comment by Supergiovane** [comment]
I assume, you are not using the ETS csv or esf file, right?

**Comment by Supergiovane** [comment]
Hello mthauth
fix is in progress.
Tomorrow i'll release a new version with this fix.

**Comment by mthauth** [comment]
Thank you very much! 
You are great!
Yes - currently i am in Evaluation, so no ets csv informations used.

**Comment by Supergiovane** [comment]
Thank you to you for the donation!

**Comment by Supergiovane** [comment]
V. 1.1.29 is out in ca. 30 minutes. Please refresh node-red palette from time to time.
Let me know if you have other troubles, thank you!

**Comment by mthauth** [comment]
Confirm! Problem solved!
Thanks alot!
