### ISSUE TITLE
GA import doesn't work

### ISSUE THREAD

**Issue by mthauth** [Supergiovane/node-red-contrib-knx-ultimate#55]
I have tried to import a simple KNX CSV formated export, generated as described in wiki and youtube video.

It looks like 

[...]
"Zentral"	 	 	"0/-/-"	""	""	""	""	"Auto"
 	"Zeit"	 	"0/0/-"	""	""	""	""	"Auto"
 	 	"Uhrzeit"	"0/0/1"	""	""	""	"DPST-10-1"	"Auto"
 	 	"Datum"	"0/0/2"	""	""	""	"DPST-11-1"	"Auto"
 	 	"Tag/Nacht"	"0/0/3"	""	""	"1=Tag, 0=Nacht"	"DPST-1-2"	"Auto"
 	 	"Uhrzeit anfordern"	"0/0/4"	""	""	""	"DPST-1-1"	"Auto"
[...]

On deploy the debug window states 
`
msg : string[175]
"knxUltimate: ERROR: Found an UNCERTAIN datapoint in ESF ETS. Please set the datapoint with ETS and export the group addresses again. ->. An ideal datapoint has been set: 5.004"
`

What is wrong?

**Comment by Supergiovane** [comment]
Hello Mthauth,
You have some datapoints not set in ETS. It is better to set the correct datapoints in ETS and redo the import.
If you wish anyway to proceed, you can do that, but i'ts not advisable.
Please see [here](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/1.-Gateway-configuration) below in the page,  and change the option *If Group Address has no Datapoint* to continue import on error by using fake datapoint.

**Comment by mthauth** [comment]
Hi,
every GA has a datapoint - it was not really visible due to the missing breaks.
Only the lines with "Hauptgruppe" and "Mittelgruppe" has no datapoint's - how should they...

**Comment by Supergiovane** [comment]
Hi 
Sorry... are you importing an ETS csv file format or an ESF format?

**Comment by mthauth** [comment]
Importing a ETS csv.

**Comment by Supergiovane** [comment]
Can you paste here the first 10-15 row please?

**Comment by Supergiovane** [comment]
As workaround, please paste the content of the file into the config-node, and replace "hauptgruppe" with "GROUP NAME"

**Comment by mthauth** [comment]
"Main"	"Middle"	"Sub"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Zentral"	 	 	"0/-/-"	""	""	""	""	"Auto"
 	"Zeit"	 	"0/0/-"	""	""	""	""	"Auto"
 	 	"Uhrzeit"	"0/0/1"	""	""	""	"DPST-10-1"	"Auto"
 	 	"Datum"	"0/0/2"	""	""	""	"DPST-11-1"	"Auto"
 	 	"Tag/Nacht"	"0/0/3"	""	""	"1=Tag, 0=Nacht"	"DPST-1-2"	"Auto"
 	 	"Uhrzeit anfordern"	"0/0/4"	""	""	""	"DPST-1-1"	"Auto"
 	"Anwesenheit"	 	"0/1/-"	""	""	"1=anwesend / 0 = abwesend"	""	"Auto"
 	 	"Anwesenheit Mike"	"0/1/0"	""	""	"1=Anwesend, 0=Abwesend"	"DPST-1-2"	"Auto"
 	 	"Anwesenheit Birgit"	"0/1/1"	""	""	"1=Anwesend, 0=Abwesend"	"DPST-1-2"	"Auto"
 	"Beleuchtung"	 	"0/2/-"	""	""	""	""	"Auto"
 	 	"Aktuelle Standard Farbtemperatur in Prozent"	"0/2/0"	""	""	""	"DPST-5-1"	"Auto"
 	 	"Aktuelle Standard Helligkeit in Prozent"	"0/2/1"	""	""	""	"DPST-5-1"	"Auto"
 	"Sicherheit"	 	"0/3/-"	""	""	""	""	"Auto"
 	 	"Brandalarm"	"0/3/0"	""	""	""	"DPST-1-2"	"Auto"
 	"Abwesenheit"	 	"0/4/-"	""	""	""	""	"Auto"
 	 	"Display ent-/sperren"	"0/4/0"	""	""	"1=sperren, 0=entsperren"	"DPST-1-1"	"Auto"
 	"Szenen"	 	"0/5/-"	""	""	""	""	"Auto"
 	 	"Stimmung"	"0/5/0"	""	""	""	"DPST-17-1"	"Auto"
 	 	"Beleuchtung"	"0/5/1"	""	""	""	"DPST-17-1"	"Auto"
 	"Fenster"	 	"0/7/-"	""	""	""	""	"Auto"
 	 	"Anzahl offener Fenster"	"0/7/0"	""	""	""	"DPST-16-0"	"Auto"
 	 	"Anzahl gekippter Fenster"	"0/7/1"	""	""	""	"DPST-7-1"	"Auto"
 	 	"Status Fensterstellung Offen"	"0/7/2"	""	""	""	"DPST-1-2"	"Auto"
 	 	"Status Fensterstellung Gekippt"	"0/7/3"	""	""	""	"DPST-1-2"	"Auto"
 	 	"Status Fensterstellung"	"0/7/4"	""	""	""	"DPST-1-2"	"Auto"
 	 	"Statustext Fensterstellung"	"0/7/5"	""	""	""	"DPST-16-0"	"Auto"

**Comment by Supergiovane** [comment]
Please paste the content of the file into the config-node, and replace "Main" with "GROUP NAME"

**Comment by Supergiovane** [comment]
PS: Are you on ETS version 5? Maybe not...

**Comment by mthauth** [comment]
I am on ETS 5.7.2 Build 743

**Comment by Supergiovane** [comment]
Please paste the content of the file into the config-node, and replace "Main" with "GROUP NAME"
Does this workaround work?

**Comment by mthauth** [comment]
There is no error message on deploy. But the node also has no autocompletion.
Before there was a not correct autocompletion.

**Comment by Supergiovane** [comment]
Do you have exported the CSV with TABULATOR as separator?

**Comment by mthauth** [comment]
Yes.
I found a difference between yours and mine.
In your video you only exported the groupaddress lines. Not the lines with main- and middlegroups.

**Comment by Supergiovane** [comment]
Strange. I pasted exactly your file 

"Main"	"Middle"	"Sub"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Zentral"	"0/-/-"	""	""	""	""	"Auto"
"Zeit"	"0/0/-"	""	""	""	""	"Auto"
"Uhrzeit"	"0/0/1"	""	""	""	"DPST-10-1"	"Auto"
"Datum"	"0/0/2"	""	""	""	"DPST-11-1"	"Auto"
"Tag/Nacht"	"0/0/3"	""	""	"1=Tag, 0=Nacht"	"DPST-1-2"	"Auto"
"Uhrzeit anfordern"	"0/0/4"	""	""	""	"DPST-1-1"	"Auto"
"Anwesenheit"	"0/1/-"	""	""	"1=anwesend / 0 = abwesend"	""	"Auto"
"Anwesenheit Mike"	"0/1/0"	""	""	"1=Anwesend, 0=Abwesend"	"DPST-1-2"	"Auto"
"Anwesenheit Birgit"	"0/1/1"	""	""	"1=Anwesend, 0=Abwesend"	"DPST-1-2"	"Auto"
"Beleuchtung"	"0/2/-"	""	""	""	""	"Auto"
"Aktuelle Standard Farbtemperatur in Prozent"	"0/2/0"	""	""	""	"DPST-5-1"	"Auto"
"Aktuelle Standard Helligkeit in Prozent"	"0/2/1"	""	""	""	"DPST-5-1"	"Auto"
"Sicherheit"	"0/3/-"	""	""	""	""	"Auto"
"Brandalarm"	"0/3/0"	""	""	""	"DPST-1-2"	"Auto"
"Abwesenheit"	"0/4/-"	""	""	""	""	"Auto"
"Display ent-/sperren"	"0/4/0"	""	""	"1=sperren, 0=entsperren"	"DPST-1-1"	"Auto"
"Szenen"	"0/5/-"	""	""	""	""	"Auto"
"Stimmung"	"0/5/0"	""	""	""	"DPST-17-1"	"Auto"
"Beleuchtung"	"0/5/1"	""	""	""	"DPST-17-1"	"Auto"
"Fenster"	"0/7/-"	""	""	""	""	"Auto"
"Anzahl offener Fenster"	"0/7/0"	""	""	""	"DPST-16-0"	"Auto"
"Anzahl gekippter Fenster"	"0/7/1"	""	""	""	"DPST-7-1"	"Auto"
"Status Fensterstellung Offen"	"0/7/2"	""	""	""	"DPST-1-2"	"Auto"
"Status Fensterstellung Gekippt"	"0/7/3"	""	""	""	"DPST-1-2"	"Auto"
"Status Fensterstellung"	"0/7/4"	""	""	""	"DPST-1-2"	"Auto"
"Statustext Fensterstellung"	"0/7/5"	""	""	""	"DPST-16-0"	"Auto"

and it worked for me.

I wish to fix it for all other users.
Can you please attach your csv file (prior to the removing of main- and middlegroups) to this post?

**Comment by Supergiovane** [comment]
Main- and middlegroups lines are automatically discarded. That's strange. 
I'll post a fix with a change for the automatic recognition of the file type. V1.1.51 will be out shortly.

![Node-RED](https://user-images.githubusercontent.com/37666636/77092959-9e85af80-6a0a-11ea-9699-0dde6a7aa695.png)

**Comment by mthauth** [comment]
I have found the reason. :-)
In your video you exported the CSV with "1/1 Name/Address".
This will result in prepended Tabs.
![GA_export_video](https://user-images.githubusercontent.com/6154305/77093021-b5c49d00-6a0a-11ea-9f7b-cda5d0d227fc.png)

If you use "1/3 Group address name / Main - middle - Sub Group" those prepended Tabs won't exist.
![GA_export](https://user-images.githubusercontent.com/6154305/77092774-60888b80-6a0a-11ea-83d1-99cae64eafd6.png)

Give me one minute, i will test it.

**Comment by Supergiovane** [comment]
Ah, yes, see [here](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/1.-Gateway-configuration)

* **ETS CSV Group Addresses List import**

**If Group Address has no Datapoint**
> If a Group address has no Datapoint set in the ETS, you can select to stop and abort the entire import process, or to add the the affected Group Address with a fake datapoint 1.001 and continue import.<br/>

**How to export the ETS -> CSV <- Group Addresses List**
> On ETS, click the group addresses list, then right click, then select 'export group addresses'. On the export window, select these options: <br />
> **Output Format**: CSV <br />
> **CSV Format**: 1/1 Name/Address <br />
> **Export with header line**: checked <br />
> **CSV Separator**: Tabulator.  <br />
> Then paste the file content here. <br />
> Note that the ETS CSV FILE must contain the Datapoints for each Group Address.  <br />
> The node parses your ETS CSV FILE prior to use it and will tell you the results in the DEBUG TAB of Node-Red page. <br />
> The result can be of two types: **ERROR** and **WARNING** <br />
> **ERROR** occurs when a Datapoint is not specified for a Group Address. This is a critical error and stops the process of importing the ETS CSV FILE. <br />
> **WARNING** occurs when a Datapoint's subtype is not specified. In this case the node parser will append a default one, but warns you that you shoult watch and correct the Datapoint, by adding a subtype. A Subtype is the number staying at the right of the "." in a Datapoint (ex: 5.001).

**Comment by mthauth** [comment]
Sorry - i was wrong.
The issue is still.

In 1/1 Export the prepending tabs are disturbing. In 1/3 Export the group addresses are not in format x/y/z.

**Comment by Supergiovane** [comment]
Please attach or paste here the complete exported file.

**Comment by mthauth** [comment]
I can't attach a csv. Can i send it to your e-Mail address? i think i have one.

**Comment by Supergiovane** [comment]
info@supergiovane.it

**Comment by Supergiovane** [comment]
Ok, received.

**Comment by Supergiovane** [comment]
Hello
it worked, with GA_1_1.csv

![Node-RED](https://user-images.githubusercontent.com/37666636/77095847-c119c780-6a0e-11ea-9848-64830e1e8003.png)




## But i had to select the second option here

![Node-RED 2](https://user-images.githubusercontent.com/37666636/77095915-ddb5ff80-6a0e-11ea-8e0d-af4adbaf47ef.png)

**Comment by mthauth** [comment]
OK - perfect - yes - now it works! :-)

**Comment by Supergiovane** [comment]
No problem. I'm here to help.
I love too much the KNX world.

**Comment by matteofranceschini** [comment]
Hey @Supergiovane , I might have an issue, too.
I'm using ETS5.5 and I exported all the addresses as mentioned in the documentation. 
![image](https://user-images.githubusercontent.com/3541957/112734583-fb357780-8f46-11eb-95d7-024a82dceb72.png)

```
"Group name"	"Address"	"Central"	"Unfiltered"	"Description"	"DatapointType"	"Security"
"Varie"	"0/-/-"	""	""	""	""	"Auto"
"Allarmi"	"0/0/-"	""	""	""	""	"Auto"
"St pompa wc"	"0/0/1"	""	""	""	"DPST-1-1"	"Auto"
"St allarme ascensore"	"0/0/2"	""	""	""	"DPST-1-1"	"Auto"
"Carichi"	"0/1/-"	""	""	""	""	"Auto"
"Potenza attiva totale"	"0/1/0"	""	""	""	"DPST-14-56"	"Auto"
"Energia attiva totale"	"0/1/1"	""	""	""	"DPST-13-10"	"Auto"
"Tensione L1"	"0/1/2"	""	""	""	"DPST-14-27"	"Auto"
"Tensione L2"	"0/1/4"	""	""	""	""	"Auto"
"Tensione L3"	"0/1/5"	""	""	""	""	"Auto"
"Power Factor L1"	"0/1/6"	""	""	""	""	"Auto"
"Power Factor L2"	"0/1/7"	""	""	""	""	"Auto"
"Power Factor L3"	"0/1/8"	""	""	""	""	"Auto"
"Power Meter Status"	"0/1/20"	""	""	""	""	"Auto"
"Blocchi"	"0/2/-"	""	""	""	""	"Auto"
"Blocco Motion"	"0/2/0"	""	""	""	"DPST-1-3"	"Auto"
"Illuminazione"	"1/-/-"	""	""	""	""	"Auto"
"Cmd ON-OFF Luci"	"1/0/-"	""	""	""	""	"Auto"
"Cmd luce specchio bagno"	"1/0/0"	""	""	""	"DPST-1-1"	"Auto"
"Cmd luce specchio antibagno"	"1/0/1"	""	""	""	"DPST-1-1"	"Auto"
"Cmd  pensilina cucina"	"1/0/2"	""	""	""	"DPST-1-1"	"Auto"
"Cmd luci colonne 1"	"1/0/3"	""	""	""	"DPST-1-1"	"Auto"
"Cmd presa comandata"	"1/0/4"	""	""	""	"DPST-1-1"	"Auto"
"Cmd luci esterne"	"1/0/5"	""	""	""	"DPST-1-1"	"Auto"
"Cmd luci colonne bar"	"1/0/6"	""	""	""	"DPST-1-1"	"Auto"
"Cmd luce armadio ping pong"	"1/0/7"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Trafo DMX"	"1/0/8"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Rele DMX"	"1/0/9"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Lavastoviglie"	"1/0/10"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Calorifero"	"1/0/11"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Boiler"	"1/0/12"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Induzione"	"1/0/13"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Grill"	"1/0/14"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Forno"	"1/0/15"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Luci Esterne Notturne"	"1/0/16"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Ronzatore"	"1/0/17"	""	""	""	"DPST-1-1"	"Auto"
"Cmd cappa"	"1/0/18"	""	""	""	"DPST-1-1"	"Auto"
"Cmd luce cucina led sotto"	"1/0/19"	""	""	""	"DPST-1-1"	"Auto"
"Cmd Luci Colonne"	"1/0/20"	""	""	""	"DPST-1-1"	"Auto"
"St ON-OFF Luci"	"1/1/-"	""	""	""	""	"Auto"
"St luce specchio bagno"	"1/1/0"	""	""	""	"DPST-1-1"	"Auto"
"St luce specchio bagno"	"1/1/1"	""	""	""	"DPST-1-1"	"Auto"
"St pensilina cucina"	"1/1/2"	""	""	""	"DPST-1-1"	"Auto"
"St luci colonne Sala Pranzo"	"1/1/3"	""	""	""	"DPST-1-1"	"Auto"
"St presa comandata"	"1/1/4"	""	""	""	"DPST-1-1"	"Auto"
"St luci esterne"	"1/1/5"	""	""	""	"DPST-1-1"	"Auto"
"St luci colonne bar"	"1/1/6"	""	""	""	"DPST-1-11"	"Auto"
"St luce armadio ping pong"	"1/1/7"	""	""	""	"DPST-1-1"	"Auto"
"St Trafo DMX"	"1/1/8"	""	""	""	"DPST-1-11"	"Auto"
"St Rele DMX"	"1/1/9"	""	""	""	"DPST-1-11"	"Auto"
"St Lavastoviglie"	"1/1/10"	""	""	""	"DPST-1-11"	"Auto"
"St Calorifero"	"1/1/11"	""	""	""	"DPST-1-1"	"Auto"
"St Boiler"	"1/1/12"	""	""	""	"DPST-1-1"	"Auto"
"St Induzione"	"1/1/13"	""	""	""	"DPST-1-11"	"Auto"
"St Grill"	"1/1/14"	""	""	""	"DPST-1-11"	"Auto"
"St colonna Forno"	"1/1/15"	""	""	""	"DPST-1-11"	"Auto"
"St Luci Esterne Notturne"	"1/1/16"	""	""	""	"DPST-1-11"	"Auto"
"St Ronzatore"	"1/1/17"	""	""	""	"DPST-1-11"	"Auto"
"St cappa"	"1/1/18"	""	""	""	"DPST-1-1"	"Auto"
"St luce cucina led sotto"	"1/1/19"	""	""	""	"DPST-1-1"	"Auto"
"St Luci Colonne"	"1/1/20"	""	""	""	"DPST-1-1"	"Auto"
[...] etc

```
I've just pasted it it the import form but I only managed to make it work selecting "importa con un finto datapoint 1.001". Why is it not recommended? Can I edit someting in my configuration on ETS to make it work without this option?

BTW, great lib!

**Comment by Supergiovane** [comment]
Hi Matteo
I see you’ve different datapoints type, for example dmx. 
To allow knx-ultimate to automatic decode your telegrams, you must set the right datapoint in ETS. 
Setting the right datapoint is required for all supervisor, for example for homeassistant too. 
If you leave knx-ultimate import all group addresses with a default datapoint 1.001(boolean), you won’t be able to dim a light, to read a % or to set anything other than a boolean value true/false. 
Put your Headphones, plays some gorgeous music playlist and set the right datapoints in ets. 
Ciao!!!!
