### ISSUE TITLE
GA import fail 

### ISSUE THREAD

**Issue by croghostrider** [Supergiovane/node-red-contrib-knx-ultimate#56]
Hi Supergiovane,

I tried to create a KNX monitor with your node.
The project has 7302 group addresses, but if I trie to import the CSV file.
It fails on many addresses with the message:

> [error] knxUltimate: ERROR: Found an UNCERTAIN datapoint in ESF ETS. Please set the datapoint with ETS and export the group addresses again. ->. An ideal datapoint has been set: 5.004

all the group addresses has selected a datapoint in the ETS project
and I think all the addresses where fails have the datapoint 1.001.

do you know why this happens?

My setup is:
OS: balenaOS 2.47.1+rev1
Node RED: 1.0.2
yours node: 1.1.48

here the [csv ](https://filebin.net/5hwmpn4tzr1hw54q)file 

wish you all the best and thanks for the help.

**Comment by Supergiovane** [comment]
Hello Crog.
Have you exported the csv file as stated here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/1.-Gateway-configuration ?
The settings for file export are extremely important.

**Comment by croghostrider** [comment]
sorry I forgot to select export with header line.
I see in the #50 discussion that your node is used in two commercial products, which ones are they?

do you have a recommendation for a KNX visualization?

I have experience with Gira Home Server and EisBär and I'm disappointed by both.

I try now to create a balenaOS image with pre-installed nodeRED, influxdb, grafana, and your node for a nice KNX logger.

**Comment by Supergiovane** [comment]
Hi Crog
Glad that now it’s working. 
One producer is proKnx in his RealKNX server. 
I cannot unfortunately tell you the other. 
I had Gira as well. 
Yet i use nodered with Smartvisu.de visualization. That’s very good.
