### ISSUE TITLE
Explicit trigger KNX read request

### ISSUE THREAD

**Issue by waldbaer** [Supergiovane/node-red-contrib-knx-ultimate#60]
First I want to say a big thank you for this node. I love it.

But one thing I could not realize up to now: I want to send an explicit KNX read request to get current state of an actuator (e.g. is the light currently on or off)

There is the option to trigger read requests on startup automatically (super cool feature!), but I could not find a way to trigger the request explicitely.
I would suggest the following enhancement:
- Add the output type "Read" to the drop-down menu
- To handle the potential response from the actuator I would prefer if I could enable the option "React to event GroupValue response" in the same node.

Please let me know what you think. I could also help implementing this feature if you agree with my thoughts.

Best regards
Sebastian

**Comment by Supergiovane** [comment]
Hello Sebastan
Thank you for using my node. 
See here. 
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Read-value-from-Device

**Comment by waldbaer** [comment]
Hello Supergiovane,
thank you for your fast response. I tried as described and it works.
But I think it would increase the usability if a new output type 'Read' is introduced instead using this hidden flag msg.readstatus=true.
I think reading the current status is a common usecase and the current setup is a little bit confusing (and requires more nodes than actually necessary in my opinion).
In the knx-ultimate node the output type is still 'write' but on KNX actually the message type 'GroupValue_Read' is used (as intendend). To make this transparent and clean for the user I would suggest to introduce the output type 'read' in the knx-ultimate node.
What do you think?
Best regards
Sebastian

**Comment by Supergiovane** [comment]
Hi Sebastian,
yes you're right. I'll setup it in the next upcoming version.
Thank you.

**Comment by Supergiovane** [comment]
PS: What's the right word in German for "Read" ?

**Comment by waldbaer** [comment]
Thanks! 
Read is "Lesen" in german ;)

**Comment by Supergiovane** [comment]
V 1.1.64 with this change will be out in about 1 hour.
Cheers.

**Comment by Supergiovane** [comment]
Please follow this example to use the new "Lesen" thing.
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Read-value-from-Device

**Comment by waldbaer** [comment]
Wow this was an amazing fast feature request.
I just tested it with a light (DPST-1-1) and blind position (DPST-5-1). Works perfect!
Thank you.
