### ISSUE TITLE
How to send a scene number (DPT 18.001) to a KNX Group

### ISSUE THREAD

**Issue by digiwhite1980** [Supergiovane/node-red-contrib-knx-ultimate#63]
Hi,

First I want to thank you for the good work. I have a big KNX stack and your tool allows me to automate tons of things.
To point out this is probably not an issue but more a question:
I would like to send a scene number (control) to a group DPT 18.* When sending a number,  the correct scene is not set. Looking in the KNX diagnostics, you see de value of "Activate 3" for scene number 3. 
I tried to change the object to { "Activate": 3 } and some other stuff but nothing seemed to work.

Could you please help me out.

Thank you in advance,

Ray

**Comment by Supergiovane** [comment]
Hi Ray,
thank you for using one of my nodes.
Can you please paste here your flow, so i can test directly with it?
Thank you.

**Comment by digiwhite1980** [comment]
[
    {
        "disabled": false,
        "id": "a39e2c59.607b9",
        "info": "",
        "label": "Schakelen",
        "type": "tab"
    },
    {
        "fri": true,
        "id": "68eb3de.19b0fc4",
        "lat": "",
        "lon": "",
        "mon": true,
        "name": "Opladers",
        "offoffset": 0,
        "offpayload": "0",
        "offrandomoffset": 0,
        "offtime": "01:00",
        "offtopic": "0",
        "onoffset": 0,
        "onpayload": "1",
        "onrandomoffset": 0,
        "ontime": "07:00",
        "ontopic": "",
        "outputLabels": [
            "Uit"
        ],
        "passthroughunhandled": false,
        "sat": true,
        "sun": true,
        "suspended": false,
        "thu": true,
        "tue": true,
        "type": "schedex",
        "wed": true,
        "wires": [
            [
                "b6616a77.774cc8",
                "bbf1b6cd.00f198"
            ]
        ],
        "x": 160,
        "y": 420,
        "z": "a39e2c59.607b9"
    },
    {
        "dpt": "1.001",
        "formatdecimalsvalue": 999,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "id": "eefb90d8.bd903",
        "initialread": false,
        "inputLabels": [
            "Nachtstand algemeen"
        ],
        "inputRBE": false,
        "listenallga": false,
        "name": "Nachtstand algemeen",
        "notifyreadrequest": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "notifyresponse": false,
        "notifywrite": false,
        "outputRBE": false,
        "outputtopic": "",
        "outputtype": "write",
        "passthrough": "no",
        "server": "4278206b.b66f2",
        "topic": "0/0/6",
        "type": "knxUltimate",
        "wires": [
            []
        ],
        "x": 500,
        "y": 180,
        "z": "a39e2c59.607b9"
    },
    {
        "fri": true,
        "id": "3e6b4ab7.c33ec6",
        "lat": "51.99545",
        "lon": "4.18053",
        "mon": true,
        "name": "Nachtstand",
        "offoffset": 0,
        "offpayload": "0",
        "offrandomoffset": 0,
        "offtime": "05:30",
        "offtopic": "",
        "onoffset": 0,
        "onpayload": "",
        "onrandomoffset": 0,
        "ontime": "",
        "ontopic": "",
        "passthroughunhandled": false,
        "sat": true,
        "sun": true,
        "suspended": false,
        "thu": true,
        "tue": true,
        "type": "schedex",
        "wed": true,
        "wires": [
            [
                "bbf1b6cd.00f198",
                "eefb90d8.bd903",
                "5727b4cc.c0179c"
            ]
        ],
        "x": 150,
        "y": 260,
        "z": "a39e2c59.607b9"
    },
    {
        "dpt": "1.001",
        "formatdecimalsvalue": 999,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "id": "b6616a77.774cc8",
        "initialread": false,
        "inputRBE": false,
        "listenallga": false,
        "name": "BBK-S003 - A11",
        "notifyreadrequest": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "notifyresponse": false,
        "notifywrite": false,
        "outputRBE": false,
        "outputtopic": "",
        "outputtype": "write",
        "passthrough": "no",
        "server": "4278206b.b66f2",
        "topic": "6/1/71",
        "type": "knxUltimate",
        "wires": [
            []
        ],
        "x": 490,
        "y": 420,
        "z": "a39e2c59.607b9"
    },
    {
        "active": true,
        "complete": "false",
        "console": false,
        "id": "bbf1b6cd.00f198",
        "name": "",
        "tosidebar": true,
        "tostatus": false,
        "type": "debug",
        "wires": [],
        "x": 470,
        "y": 340,
        "z": "a39e2c59.607b9"
    },
    {
        "id": "9e2d0305.f2a07",
        "info": "Indien de nachtstand aan staat dan zetten de deze uit",
        "name": "Nachtstand uit",
        "type": "comment",
        "wires": [],
        "x": 160,
        "y": 40,
        "z": "a39e2c59.607b9"
    },
    {
        "id": "e66dde74.87779",
        "info": "Snachts gaan de opladers uit",
        "name": "Oplader NIS",
        "type": "comment",
        "wires": [],
        "x": 150,
        "y": 360,
        "z": "a39e2c59.607b9"
    },
    {
        "crontab": "",
        "id": "28f4a72.7bfda58",
        "name": "",
        "once": false,
        "onceDelay": 0.1,
        "payload": "0",
        "payloadType": "num",
        "repeat": "",
        "topic": "",
        "type": "inject",
        "wires": [
            [
                "eefb90d8.bd903"
            ]
        ],
        "x": 170,
        "y": 180,
        "z": "a39e2c59.607b9"
    },
    {
        "crontab": "",
        "id": "806dffc1.2deba",
        "name": "",
        "once": false,
        "onceDelay": 0.1,
        "payload": "1",
        "payloadType": "num",
        "repeat": "",
        "topic": "",
        "type": "inject",
        "wires": [
            [
                "eefb90d8.bd903"
            ]
        ],
        "x": 170,
        "y": 120,
        "z": "a39e2c59.607b9"
    },
    {
        "id": "5952ac2e.a337c4",
        "name": "",
        "testmode": false,
        "topic": "",
        "type": "sun events",
        "verbose": true,
        "wires": [
            [
                "42965d3b.fb1954",
                "48c4feae.6f0e8",
                "e344f2de.8fd89"
            ]
        ],
        "x": 140,
        "y": 680,
        "z": "a39e2c59.607b9"
    },
    {
        "checkall": "true",
        "id": "42965d3b.fb1954",
        "inputLabels": [
            "Sunevent"
        ],
        "name": "sunset",
        "outputLabels": [
            "Scene"
        ],
        "outputs": 1,
        "property": "payload",
        "propertyType": "msg",
        "repair": false,
        "rules": [
            {
                "t": "eq",
                "v": "sunset",
                "vt": "str"
            }
        ],
        "type": "switch",
        "wires": [
            [
                "c98fdb66.94e628"
            ]
        ],
        "x": 430,
        "y": 740,
        "z": "a39e2c59.607b9"
    },
    {
        "action": "",
        "from": "",
        "id": "c98fdb66.94e628",
        "name": "To scene",
        "property": "",
        "reg": false,
        "rules": [
            {
                "p": "payload",
                "pt": "msg",
                "t": "set",
                "to": "3",
                "tot": "num"
            }
        ],
        "to": "",
        "type": "change",
        "wires": [
            [
                "e344f2de.8fd89",
                "4dd5e8cc.ea9428"
            ]
        ],
        "x": 580,
        "y": 740,
        "z": "a39e2c59.607b9"
    },
    {
        "active": true,
        "complete": "true",
        "console": false,
        "id": "e344f2de.8fd89",
        "name": "",
        "targetType": "full",
        "tosidebar": true,
        "tostatus": false,
        "type": "debug",
        "wires": [],
        "x": 430,
        "y": 620,
        "z": "a39e2c59.607b9"
    },
    {
        "id": "2b8918b1.d4e7d8",
        "info": "",
        "name": "Licht in hal aan (twilight)",
        "type": "comment",
        "wires": [],
        "x": 120,
        "y": 500,
        "z": "a39e2c59.607b9"
    },
    {
        "crontab": "",
        "id": "8e62aabe.41ce58",
        "name": "sunset",
        "once": false,
        "onceDelay": 0.1,
        "payload": "sunset",
        "payloadType": "str",
        "repeat": "",
        "topic": "",
        "type": "inject",
        "wires": [
            [
                "42965d3b.fb1954"
            ]
        ],
        "x": 150,
        "y": 620,
        "z": "a39e2c59.607b9"
    },
    {
        "checkall": "true",
        "id": "48c4feae.6f0e8",
        "name": "sunrise",
        "outputs": 1,
        "property": "payload",
        "propertyType": "msg",
        "repair": false,
        "rules": [
            {
                "t": "eq",
                "v": "sunrise",
                "vt": "str"
            }
        ],
        "type": "switch",
        "wires": [
            []
        ],
        "x": 440,
        "y": 800,
        "z": "a39e2c59.607b9"
    },
    {
        "action": "",
        "from": "",
        "id": "5727b4cc.c0179c",
        "name": "To scene",
        "property": "",
        "reg": false,
        "rules": [
            {
                "p": "payload",
                "pt": "msg",
                "t": "set",
                "to": "61",
                "tot": "num"
            }
        ],
        "to": "",
        "type": "change",
        "wires": [
            [
                "bbf1b6cd.00f198"
            ]
        ],
        "x": 460,
        "y": 260,
        "z": "a39e2c59.607b9"
    },
    {
        "dpt": "18.001",
        "formatdecimalsvalue": 999,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "id": "3514b2e0.1e904e",
        "initialread": false,
        "inputRBE": false,
        "listenallga": false,
        "name": "",
        "notifyreadrequest": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "notifyresponse": false,
        "notifywrite": true,
        "outputRBE": false,
        "outputtopic": "",
        "outputtype": "write",
        "passthrough": "no",
        "server": "4278206b.b66f2",
        "topic": "1/6/1",
        "type": "knxUltimate",
        "wires": [
            [
                "e344f2de.8fd89"
            ]
        ],
        "x": 150,
        "y": 560,
        "z": "a39e2c59.607b9"
    },
    {
        "dpt": "18.001",
        "formatdecimalsvalue": 999,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "id": "c766d029.1295d",
        "initialread": false,
        "inputRBE": false,
        "listenallga": false,
        "name": "Scene 61",
        "notifyreadrequest": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "notifyresponse": false,
        "notifywrite": false,
        "outputRBE": false,
        "outputtopic": "",
        "outputtype": "write",
        "passthrough": "no",
        "server": "4278206b.b66f2",
        "topic": "1/6/1",
        "type": "knxUltimate",
        "wires": [
            []
        ],
        "x": 660,
        "y": 260,
        "z": "a39e2c59.607b9"
    },
    {
        "id": "461e28a3.73cc78",
        "info": " * Scene 3  = Sfeer\n * Scene 61 = Twilight ochtend\n * Scene 62 = Twilight avond\n * Scene 63 = Thuiskomen\n * Scene 64 = Nacht",
        "name": "Scenes",
        "type": "comment",
        "wires": [],
        "x": 790,
        "y": 80,
        "z": "a39e2c59.607b9"
    },
    {
        "dpt": "18.001",
        "formatdecimalsvalue": 999,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "id": "4dd5e8cc.ea9428",
        "initialread": false,
        "inputRBE": false,
        "listenallga": false,
        "name": "",
        "notifyreadrequest": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "notifyresponse": false,
        "notifywrite": false,
        "outputRBE": false,
        "outputtopic": "",
        "outputtype": "write",
        "passthrough": "no",
        "server": "4278206b.b66f2",
        "topic": "1/6/1",
        "type": "knxUltimate",
        "wires": [
            []
        ],
        "x": 760,
        "y": 700,
        "z": "a39e2c59.607b9"
    },
    {
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "csv": "",
        "host": "1.1.1.1",
        "id": "4278206b.b66f2",
        "localEchoInTunneling": true,
        "loglevel": "error",
        "name": "Jung gateway",
        "physAddr": "1.1.231",
        "port": "3671",
        "statusDisplayDataPoint": false,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayLastUpdate": true,
        "stopETSImportIfNoDatapoint": "stop",
        "suppressACKRequest": false,
        "type": "knxUltimate-config",
        "z": ""
    }
]

**Comment by digiwhite1980** [comment]
All scene writes to KNX are disconnected atm

**Comment by Supergiovane** [comment]
Hi Ray,
what happens if you put in DPT 17.001 (Scene number) instead of 18.001?

**Comment by digiwhite1980** [comment]
Also did not work but to be absolutely sure i can test it again

**Comment by Supergiovane** [comment]
Ok, let me check the matter....

**Comment by Supergiovane** [comment]
Hi Ray,
seems a problem with the index of the scene.
Please, pass as payload, instead of 3, **2** and let me know.

**Comment by digiwhite1980** [comment]
What would be the payload then?

**Comment by Supergiovane** [comment]
`[
    {
        "id": "4dbfd5b4.de9a8c",
        "type": "inject",
        "z": "764badf.d348654",
        "name": "",
        "topic": "",
        "payload": "2",
        "payloadType": "num",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 130,
        "y": 100,
        "wires": [
            [
                "35d7d4f5.61a1e4"
            ]
        ]
    }
]`

**Comment by Supergiovane** [comment]
Hey Ray,
does it work?

**Comment by digiwhite1980** [comment]
Hi,

No, doesnt look like it. I changed it in to a 3 (because scene 3 is an actual scene) but no lights on.

**Comment by Supergiovane** [comment]
Please use 2 instead of 3
You need to use (scenenumber - 1)
In your case, (3-1) = 2

**Comment by digiwhite1980** [comment]
Ah ok

**Comment by digiwhite1980** [comment]
Yes! that does the job. So the key is scene -1

**Comment by Supergiovane** [comment]
That's a workaround.
I'll post a fix as soon as possible, instead, use this workaround!

**Comment by digiwhite1980** [comment]
Yes thats ok, for now I can proceed.
thank you so much for the fast support!

**Comment by Supergiovane** [comment]
Hi Ray
V. 1.1.56 is out in about 20 minutes. Please check this sample on how to use the datapoint 18.001
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Control-a-scene-actuator

**Comment by digiwhite1980** [comment]
Hi!

Thnx for the update. I will try it tonight and will let you know.

Thnx again.

Cheerio

Ray

**Comment by digiwhite1980** [comment]
Works like a charm :)
