### ISSUE TITLE
Support for unicast / TUNNEL connection to IP router

### ISSUE THREAD

**Issue by stieler-it** [Supergiovane/node-red-contrib-knx-ultimate#64]
Hello,

it seems I cannot use this promising node with my GIRA KNX/IP router in it's current configuration.

In general there are two modes connecting KNX to IP:

1. Tunnel mode (unicast)
2. Router mode (multicast)

node-red-contrib-knx-ultimate seems to only support router mode. My IP router supports both modes, however in router mode by default all group addresses with main group 0-13 are filtered out. That's why I have to use Tunnel mode e.g. in OpenHAB. Unfortunately I don't have an ETS license and cannot change this setting.

Apart from that, I think tunnel / unicast mode would be a nice addition as multicast ist not always possible (e.g. in Docker containers).

**Comment by Supergiovane** [comment]
Hi Stieler
knx-ultimate do supports tunneling. Simple enter the IP address of your Gira.

**Comment by stieler-it** [comment]
I just wanted to add that it is supported by `knx.js`. I didn't expect that the same field could be used for the mutlicast and the unicast address because it's so different in my head. I tried it and it works and could have looked into the FAQ before, sorry. Maybe a hint could be added to the UI, though?

**Comment by Supergiovane** [comment]
Hi Stieler,
i'ts already in the config node wiki, but yes, it could be a good idea to hint this in the UI as well.
