### ISSUE TITLE
How to send datatype 232.600 RGB

### ISSUE THREAD

**Issue by tobi-coder** [Supergiovane/node-red-contrib-knx-ultimate#65]
Thank you for all your work!

Can you please tell me how to send a rgb value with your node? I tried:

#FFFFFF
0xFF 0xFF 0xFF 

etc.

**Comment by Supergiovane** [comment]
Hi
Please see here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---RGB-Color
