### ISSUE TITLE
Import of GA names/description "#" sign not working correctly

### ISSUE THREAD

**Issue by s1x** [Supergiovane/node-red-contrib-knx-ultimate#66]
Hey,

when importing following GA into node-red there is a minor bug which causes the autocomplete function not to work fully.

**Line from csv**
`"Elternzimmer #Ist-Temperatur"	"10/1/6"	""	""	""	"DPST-9-1"	"Auto"`

**Screenshot**
![image](https://user-images.githubusercontent.com/1734844/79639628-3f43c800-818d-11ea-9f33-e67297de9482.png)

So when selecting this entry the fields for "Datapoint" and "Node-Name" are not filled correctly or not at all. Hence everything after the **#** is ignored.

**Comment by Supergiovane** [comment]
Hi
Yes. The “#” character is a reserved one. 
Please pste the csv into notepad and replave all # with blank space or anynother character, then paste again the changed csv into The config-node. 
I’ll fix that in the next version. 
Thank you for signaling me that.

**Comment by Supergiovane** [comment]
V.1.1.65 is out with a fix. Cheers
