### ISSUE TITLE
Problems with forced local echo

### ISSUE THREAD

**Issue by stieler-it** [Supergiovane/node-red-contrib-knx-ultimate#67]
Hi Supergiovane,

thank you very much for this great library. I also hope you keep up fighting Covid in Italy. I migrated my whole home from OpenHAB to Node-RED + knxultimate during the Easter break and so far I think it was a good idea.

Unfortunately, after upgrading knxultimate yesterday, my switches stop working and create endless loops switching the lights on and off all the time. This is definitely because I have an unusual setup but I want to understand if there is reason why you changed the behaviour.

What I do in rooms is:
- There are multiple switches that are mapped to scenes
- Only one scene can be active and this one is shown with a status light
- Scenes can also be activated by switches in dashboard
- I have a logic in Node-RED that turns off all other scenes (= sends OFF to all KNX GAs) if another scene is triggered
- If a person turns off a switch manually (this happend only if touching a switch with status ON), it indicates one is leaving the room and everything is turned off

![image](https://user-images.githubusercontent.com/2007728/79725207-2ea86480-82e9-11ea-809f-f257c89c13ed.png)

You can see that I use the node as input (receive command from switch) and output (update current scene/status to switch).

Now the problem seems to be:
- I use a switch to activate scene 1, scene 1 input receives ON
- Node-RED logic updates scene 2 to OFF
- New: Scene 2 input receives a OFF which turns everything off again
- I did not understsand how this could create a loop with switches and lights flickering yet

I think this is related to your latest changes about forced local echo. I also think I understand why local echo makes sense if you have multiple flows with the same GA. And probably this is closer to the behaviour of a multicast based interface?

With the latest version, how can I achieve updating a switch status light without triggering the logic behind this switch? I am pretty sure I can solve this but it would require very complicated logic (e.g. using rbe filters somewhere).

In OpenHAB there was the difference of `knx.sendCommand()` which would trigger actions, and `knx.postUpdate()` which was a status update (turn light on/off on switch) without triggering the action. I thought that I could achieve the same if I did not check "Passthrough input msg".

**Comment by Supergiovane** [comment]
Hello Stieler
Are you maybe using an IP interface, instead of an IP router?

**Comment by Supergiovane** [comment]
If you'r more confortable without local echo, let me know, but the absence of the local echo in tunneling was an old issue that make the behaviour non standard.
Please let me know.

**Comment by stieler-it** [comment]
Yes, I am using an IP interface / tunnel connection. (I cannot switch to routing because there is a configuration in the router that blacklists GAs with main group from 0-12 or so and I cannot change that on my own.)

I could live with local echo but then I need a way on my inputs to distinguish if a write on the bus has been triggered by Node-RED logic (status update for switch LEDs) or by a switch (someone trying to turn on or off lights). So far I did not find a way to solve that in the new version.

**Comment by stieler-it** [comment]
Update: I tried your suggestion. Activating RBE filters on input also prevents my commands to be received as inputs again. So this would solve it for me. (However, this is what I expected what the passthrough checkbox would do...)

**Comment by Supergiovane** [comment]
Hello
you cann allow incoming message to pass to the output messages (passthrough) and check for an expected input property.
But again, if you're more comfortable, i can re-add the echo option.

**Comment by Supergiovane** [comment]
I've re-added the echo option. This will allow you to handle the changes quieter. New version will be out in about 1 hour.

**Comment by stieler-it** [comment]
Ok, I guess that might be helpful for other use cases as well. Thank you!

**Comment by Supergiovane** [comment]
Hi Stieler
i saw you're smarter enough to replace some files by hands, because i'm stuck on another issue.
Please copy these two files into the /.node-red/node_modules/node-red-contrib-knx-ultimate/nodes path and restart node-red.
Sorry for that!
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/4503268/Archivio.zip)

**Comment by Supergiovane** [comment]
V. 1.1.67 is out with echo and some other things.

**Comment by Supergiovane** [comment]
PS: thank you for the donation!

**Comment by stieler-it** [comment]
Thank you, I already installed the new version and could turn off the rbe on input flag again. My wife will be happy she that can use the light switches again ;-)
