### ISSUE TITLE
problem with not connected Tags after 1 write

### ISSUE THREAD

**Issue by dad-of-ma-gr** [Supergiovane/node-red-contrib-knx-ultimate#68]
Hi,

I started to use your plugin to controll my KNX stuff at Home. Now I see a Problem that sometimes some nodes looks like not connected (see picture)

![knx_not connected](https://user-images.githubusercontent.com/17053772/79852958-b2d11980-83c7-11ea-970c-22ad3785d9e1.png)

After a new deploy everything is fine up and running. But somehow when I set this value once, then afterwards it is not available anylonger.

I don't write often to this tag. I also checked my networksetup I have a netgear switch and a fritzbox, but I couldn't find anything in relation to DDOS or UDP flood that needs to be disabled.

The very strange thing is that sometimes it gets broken, but sometimes not.

**Comment by Supergiovane** [comment]
Ho Dad
RBE filter?
Please take a look at the configuration instructions in the wiki.

**Comment by dad-of-ma-gr** [comment]
ohh yes sorry, i didn't see this. Thx for the info
