### ISSUE TITLE
Question Lost KNX Msg

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#69]
Hi @Supergiovane 

How are you? Wish you are always healthy.

I recently discovered a very strange problem.

I used the node-red-knx-ultimate plugin to write data to the knx bus, but the related devices did not respond.
gateway: 224.0.23.12
but I found the corresponding data through the knx groupaddress monitor(ETS 5)

If I use the ETS group monitor to send data, the device will get a response. (Multicast)

Then I use IP tunneling, it works.
However, it will always go offline and report ECONNECT_ID error

Is this a problem caused by multicast packet loss?

** Device **
Raspberry(knxd)
KNX Device: Deseo basalte

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hello Song
Yes, for now, well. Thanks. 
Do you maybe have more than one ethernet interface on the pc running nodered?

**Comment by songzh96** [comment]
No&nbsp;
Only one interface eth0 on my pi







------------------ Original ------------------

**Comment by Supergiovane** [comment]
Please try to disable the wifi on your rPI.
Do you maybe have fgroup address filters set on uour knx router?
Since when, do you have this issue?

**Comment by songzh96** [comment]
Yes&nbsp;


But you suggested that I use the multicast address 224.0.23.12，and then solved the problem&nbsp;


But now when I use multicast address, if I send a temperature value to knx bus, my device nothing to change&nbsp;
When I use ip tunneling, my devices will show the value that I send, but&nbsp;After a while, the connection will be lost……


What is fgroup?




------------------ Original ------------------

**Comment by Supergiovane** [comment]
Fgroup is a syntax error. I mean group. Sorry. 
Are you suee that knxd is not filtering group addresses?
Do you have issue only on the group address of the temperature device, or on other group as well?

**Comment by huangshenyuan-unice** [comment]
> Hi @Supergiovane
> 
> How are you? Wish you are always healthy.
> 
> I recently discovered a very strange problem.
> 
> I used the node-red-knx-ultimate plugin to write data to the knx bus, but the related devices did not respond.
> gateway: 224.0.23.12
> but I found the corresponding data through the knx groupaddress monitor(ETS 5)
> 
> If I use the ETS group monitor to send data, the device will get a response. (Multicast)
> 
> Then I use IP tunneling, it works.
> However, it will always go offline and report ECONNECT_ID error
> 
> Is this a problem caused by multicast packet loss?
> 
> ** Device **
> Raspberry(knxd)
> KNX Device: Deseo basalte
> 
> Best Regards
> Songzh

Hi Song,
I encountered the same problem last week when using multicast, it may be caused by the use of multiple knx plugins at the same time. 
In my case, I used both node-red-contrib-knx and node-red-contrib-knx-ultimate, the problem was solved after I removed node-red-contrib-knx and its configuration.
祝好

**Comment by Supergiovane** [comment]
Hi Huang,
thank you for the advice. I've addded that on the FAQ page.

**Comment by songzh96** [comment]
Hi @Supergiovane 

I think this is a problem of KNXD.
I turned off the multicast function of knxd today and then tested it. It has been running steadily until now, using the KNX IP tunnel

The knxd multicast function seems to coexist well with knx.js

Best Regards
Songzh
