### ISSUE TITLE
Multi-node response is slow

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#7]
I use node-red-contrib-knx-ultimate almost 223 nodes,

My control interface is node-red-dashboard.

when I send msg to knx bus,Sometimes it doesn't work，The interface has not been updated.

But sometimes it can work well。

I use msg.payload debug it,but the msg.payload did not show anything.ETS5's group address monitoring also does not display the commands I sent.

Is it too many nodes I created?

Best Regards
songzh

**Comment by Supergiovane** [comment]
Hello songzh
No, the number of node should not be a problem, because the connection to the knx bus is only one, independently from the number of nodes. 
You have some sort of  on your network or your ip interface may reject ip telegrams sometime for an unknown reason. 
I have nearly as 310 nodes and i haven’t had a single issue. 
Can you try using an ip router instead of an ip interface?

**Comment by songzh96** [comment]
Ok，Let me try it.

**Comment by Supergiovane** [comment]
Please keep me informed. I'm very interested in your issue and if i can help you to solve that, i'll be happy. Thank you.

**Comment by songzh96** [comment]
Hi @Supergiovane 

Thank you for your answer. I was used ip router yesterday.It’s run not bad until now.

I send the message from the dashboard, and the knx bus can also listen to it at any time.

I don't understand why the tunnel has a series of problems.Can you explain it to me if you know it?

Best Regards
songzh

**Comment by Supergiovane** [comment]
Hello
No, i can’t!! I ever had issue with tunnel, with ETS and with knx falcon api as well. 
Tunnel mimics the TCP stack and it needs packet acknowledgment, session ID and so on. 
If something in the lan interferes with this “mimic”, you’ll have problems. 
Yet, with the invention of SSL secure tunnels, the situation should become better, but until SSL tunnels are mature, i’ll stay with IP routing!
