### ISSUE TITLE
It seems msg.knx.destination override doesn't work.

### ISSUE THREAD

**Issue by denis-isaev** [Supergiovane/node-red-contrib-knx-ultimate#70]
It seems `msg.knx.destination` override doesn't work.
I made test flow (see screenshot) with override, but as you can see in second debug message, destination address remained unchanged.

![screenshot](https://i.imgur.com/jcxnmmy.png)

<details><summary>Here flow export</summary>
<p>
[{"id":"5b03e745.772e08","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"881063f9.27c66","type":"inject","z":"5b03e745.772e08","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":160,"wires":[["645448bb.0e82b8"]]},{"id":"5f03011d.24b78","type":"knxUltimate","z":"5b03e745.772e08","server":"7a6d7ca7.515fc4","topic":"0/0/0","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":610,"y":160,"wires":[[]]},{"id":"692d9961.7be4c8","type":"debug","z":"5b03e745.772e08","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":240,"wires":[]},{"id":"bb30455.1e3edb8","type":"knxUltimate","z":"5b03e745.772e08","server":"7a6d7ca7.515fc4","topic":"","outputtopic":"","dpt":"","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":true,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":true,"name":"","outputtype":"write","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":390,"y":240,"wires":[["692d9961.7be4c8"]]},{"id":"645448bb.0e82b8","type":"change","z":"5b03e745.772e08","name":"","rules":[{"t":"set","p":"knx.destination","pt":"msg","to":"0/0/51","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":160,"wires":[["5f03011d.24b78","692d9961.7be4c8"]]},{"id":"7a6d7ca7.515fc4","type":"knxUltimate-config","z":"","host":"192.168.100.109","port":"3671","physAddr":"15.15.22","suppressACKRequest":false,"csv":"\"Group name\"\t\"Address\"\t\"Central\"\t\"Unfiltered\"\t\"Description\"\t\"DatapointType\"\n\"Lighting\"\t\"0/-/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Switching\"\t\"0/0/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Light Entrance Ceiling Switching\"\t\"0/0/51\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\n\"Switching Feedback\"\t\"0/1/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Light Entrance Ceiling Switching Feedback\"\t\"0/1/51\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-1\"\n\"Dimming\"\t\"0/2/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Dimming Value\"\t\"0/3/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Dimming Value Feedback\"\t\"0/4/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Shutters / Blinds\"\t\"1/-/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Heating\"\t\"2/-/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Cooling\"\t\"3/-/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Ventilation\"\t\"4/-/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Health Check\"\t\"31/-/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Line 1.1\"\t\"31/1/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n\"Device 1.1.1\"\t\"31/1/0\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-2\"\n\"Device 1.1.2\"\t\"31/1/1\"\t\"\"\t\"\"\t\"\"\t\"DPST-1-2\"\n\"Line 1.2\"\t\"31/2/-\"\t\"\"\t\"\"\t\"\"\t\"\"\n","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"Gateway","localEchoInTunneling":true}]
</p>
</details>

**Comment by Supergiovane** [comment]
Hi Denis
please see here: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/4.-Messages-to-the-node

```
// Example of a function that sends a message to the KNX-Ultimate
msg.destination = "0/0/1"; // Set the destination 
msg.payload = false; // issues a write or response (based on the options Output Type above) to the KNX bus
return msg;
```

**Comment by denis-isaev** [comment]
Thanks!

I took it from here:
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/2.-Node-Configuration

**Comment by Supergiovane** [comment]
Thank you! I've fixed the page in alla languages.
