### ISSUE TITLE
Missing KNXnet/IP connection state requests

### ISSUE THREAD

**Issue by ms20de** [Supergiovane/node-red-contrib-knx-ultimate#71]
I'm working Elaborated Networks GmbH. We develop a product called Timberwolf Server which includes a certified KNX interface.
Our customers are able to run docker containers on this machine, like Node-Red.

We got complains that knx ultimate is not working correctly with our KNXnet/IP tunnels.
One problem is a regular restart of the tunneling connection every two minutes.
We investigated the problem and found the knx ultimate sends only one connection state request after establishing the connection.
I was told the KNX specification requires at least one state request all 120 seconds.
For example knxd sends one connection state request every 30 seconds and is therefore compliant.

After 120 seconds without state request we have to close the connection.
Sadly we are not able to change this behavior on our side, or we would lose our certification.
I hope you can add the periodic state requests as requested by the KNX specification.

Best Regards,
Matthias Schmidt

**Comment by Supergiovane** [comment]
Hi Matthias
i'll investigate that and i'll revert to you as soon as possible.
Thanks for the hint.

**Comment by Supergiovane** [comment]
Hi Matthias
do you have traffic on the KNX bus, if you don't touch anything?
The node will send a connect state request once a time, if it detects traffic on the KNX bus, but i need to test if the automatic state request is sent, if there's no traffic on the KN Bus..

**Comment by Supergiovane** [comment]
Ok, maybe i found something interesting. After a disconnection (by pulling knx cable, or eth cable), the node reconnects but seems not sending the state requests at regular intervals anymore.

**Comment by ms20de** [comment]
Thanks for looking into this issue and the fast response.

![KNX-Traffic](https://user-images.githubusercontent.com/57409043/80718696-c46a9d80-8afa-11ea-9772-24a113fa8b81.png)
I have regular KNX traffic on the bus at least one telegram each 2-4 seconds.

**Comment by ms20de** [comment]
I tried to toggle the group adresse my test node a lot, but I still see only one connection state request after the connection is established.

**Comment by Supergiovane** [comment]
Hi Matthias
yes, maybe i've found why.
If i send you a .js file, are you able to paste it in your node-red?

**Comment by ms20de** [comment]
I will try your patch.

**Comment by ms20de** [comment]
Looks good now!
Is see a connection state request every 10 seconds.
The connection is now up for 9 minutes without any problem.

**Comment by Supergiovane** [comment]
Ok, leave it running for a while. If it's still ok, i'll release a clean new version in the evening or tomorrow morning.

**Comment by Supergiovane** [comment]
Hi Matthias
the new version is 1.1.68 and is out. You and your users should see that in ca. 1 hour in the node-red palette.
Cheers and if you've some other issues, let me know.
