### ISSUE TITLE
Adjustable read request delay

### ISSUE THREAD

**Issue by Namakemono93** [Supergiovane/node-red-contrib-knx-ultimate#72]
Hi Supergiovane
First of all, thank you for this nice KNX node.
I had a problem recently, where i had to read over 200 group address at the start of Node Red.
Some of the read request were not send. I figured that maybe my IP Interface is the problem here and that it can't handle that much requests in such a short time.
Normally the KNX System should be able to handle more than 20 messages per second, but on big installation with a lot of bus traffic that might be a problem?
Therefore it would be nice to have an adjustable read delay in your library. 

Is this something you are interested to add as a feature?

Thanks!

Simon

**Comment by Supergiovane** [comment]
Hi Simon
I think you refer to delay between each telegram, right?
If you’re alble to do so, i can dend you a patch to try. You need to paste a file into node-red path. Later i’ll send you that.

**Comment by Namakemono93** [comment]
Hi Supergiovane
That's correct. 
Thanks for the quick reply.

**Comment by Supergiovane** [comment]
Hi Simon, 
Thinking about that, you may have the ethernet IP interface coming up too late, once node-red restarts. 
Can you try to manually issue a read request, for example 5 minutes after node-red has been restarted, by following this example and let me know if the problem still persist?
Use the code related to the second image  "Issue a read request using "universal mode" node.
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Read-value-from-Device
Thanks.

**Comment by Namakemono93** [comment]
Hi Supergiovane
Right now i have no access to the installation, but i can try it as soon as possible (This or next week).
Here some more information:
I noticed that node red starts to read the first couple of group address and the suddenly stops.
I retried this a couple of times and it seems that always the same group address didn't received a request. I switched the connection to an empty KNX line and there all group address request were sent.
All of this i was observing with the ETS bus monitor. I also found no error in the KNX Ultimate log.
My guess is that my IP Interface drops old messages (Maybe an overflow?) when its on hold because other subscribers are sending (In this case the read request answers).

**Comment by Supergiovane** [comment]
Hi Simon
all KNX messages are sent into a "send queue", that sends the telegram at fixed intervals.
The "read" telegram does have the lower priority, that means, that while sending some "read" requests, if you send a "write" command to the bus (for switching a light, for example), the "write" command take the precedence in the queue. The remaining "read" requests in the queue will be transmitted only thereafter.
Read requests can take a long time and this is to avoid "flooding" the BUS with read request and to avoid delaying the "write" telegrams (imagine if you need to wait for the read requests to finish, before a light can be turned on).
Are your sure that your KNX/router/interface doesn't have a group address filtering active? Some devices does have it active out of the box. This can explain why some telegrams arrives, while other not.

**Comment by Namakemono93** [comment]
I used the same KNX IP interface for both, the normal setup where some requests getting lost and the test setup where no KNX devices are connected. Also there's nothing more that i can setup than the IP Settings. Its a "Weinzierl KNX Interface 731".
Your library does handle the requests correct as far as i can see. 
My guess is, that the IP Interface has some problems on a high bus load and maybe drops some telegrams.
If i could extend the delay in your library then the IP Interface does not receive that many telegram in a second on a startup.
I think it would be worth a try ;)

**Comment by Supergiovane** [comment]
Hi Simon,
Yes, i can do that, no problems, but first i need you to test what i've told you.
Do you maybe have some other KNX contribution nodes installed? Please see here, in the FAQ
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/5.-FAQ-Troubleshoot
the point "I SEE THE TElEGRAM IN ETS, BUT MY ACTUATOR WON'T REACT".
Maybe it's related to this...

**Comment by Namakemono93** [comment]
Hi Supergiovane
Sure, i will test that first. 
I let you know as soon as i know more.
Thanks!

**Comment by Namakemono93** [comment]
Hi Supergiovane
Sorry for the late replay but finally i could do some tests. This time its a different Project with even more Datapoints. The problem is the same, some Group address don't receive a read command, sometimes they do (After a deploy). When i inject a read request for all group address after the deploy the result is still the same. When i do a read request by inject on those specific nodes i get a read request on the ETS Bus monitor.

**Comment by Supergiovane** [comment]
Hi Simon
if you handle different projects, it means you use different KNX/IP interfaces and different LAN topography, so there's must be something in the handling of read requests. I think that's not related to telegram-delay.
Let me do some checks...

**Comment by Namakemono93** [comment]
Hi Supergiovane
Yes, the LAN topography is different, but the KNX/IP Interfaces are the same. Sadly, i don't have any other Interfaces here...

**Comment by Supergiovane** [comment]
Ok Simon, 
do not worry, i'll find a solution for you. I'm investigating into the code and, if i cannot find issues, i'll set up an option to define the delay between telegrams and i'll attach the patch here for you to test.

**Comment by Supergiovane** [comment]
Hi Simon,
are you able to unpack this file into the .node-red/node_modules/node-red-contrib-knx-ultimate/nodes folder and restart node-red?
Then let me know. I've set a fixed delay to 150ms, only for testing purposes. I cannot find anything wrong in the code, mine works well.
[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/4642990/knxUltimate-config.js.zip)

**Comment by Namakemono93** [comment]
Hi Supergiovane,
with 150ms the situation was almost the same. I set the Time to 1 second and after a while all group address were read out. I guess the problem is the KNX Interface but still an adjustable delay would solve the problem in my case.

**Comment by Supergiovane** [comment]
Hi Simon, 
ok, will do it, but the more the delay is, the more all telegrams are delayed, not only the "read".
The telegram queue is common for all "read", "response", and "write", with the latter two having priority over the "read".
Is it ok for you?
I suspect the KNX interface is limiting the telegram coming from the LAN, or that it has a too little buffer to accomodate all the telegrams.

**Comment by heleon19** [comment]
Hello Massimo

I think the interface of Simon has a problem if there are too many requests in a certain time. What if you introduced a limit per minute besides the minimum delay between two telegrams. Maybe it's ok if a request is sent every 60ms, but not if there are more than 150 in one minute?
Do you know what I mean? Would this be worth another test?

Regards Reto

**Comment by Supergiovane** [comment]
Hi Reto
not knowing the specs of such interface, is not simple to guess what it really happens.
I need to keep the things simple, thus allowing some degrees of customisation/adaptation.
It whould be useful, if Simon can ditch into the specs and tell me if ther's a limitation on "telegram per minutes as well".

**Comment by Namakemono93** [comment]
Hi Supergiovane

Its a Weinzierl 731 IP Interface. Theres no specs of telegram per minutes, but i could make a support request.

https://www.weinzierl.de/index.php/de/alles-knx1/knx-devices/knx-ip-interface-731-de

**Comment by Supergiovane** [comment]
Hmmmm... 
i suppose, it has no limitation about telegrams/minute.
I'll proceed with this

> i can do that: option for "between telegram" delay and another option to multiply this delay (1x, 2x, 3x, 4x...) only for "read" request telegrams. So you can leave 50ms and set for example 10x to the "read", to obtain 500ms.

I'll let you know as soon as the new version is out.

**Comment by Namakemono93** [comment]
Sounds good, thank you!

**Comment by Supergiovane** [comment]
Hi Simon,
speaking with some italian installers about your issue, they pointed me to this document, where at page 34, there are some troubleshoots you can take a look at.
https://www.weinzierl.de/images/download/products/731/Weinzierl_KNX_and_IP.pdf?fbclid=IwAR0C9Tmwcbo1Sc91pJJ2BH7u0OizmaLP0aINKGVa1NYd4cvaDEEDaIS9btw
Please let me know if it helped you, otherwise, i'll do the modifications.
Thanks

**Comment by Supergiovane** [comment]
Hi Simon,
here the zip to be unzipped in the  **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder.
[Archivio.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/4644849/Archivio.zip)

And here the explanation of this new option.
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/de-1.-Gateway-configuration

Please try it and let me know. If it works, i'll release the V.1.1.70 with this changes.
Thanks.
