### ISSUE TITLE
Sending value with DPT 12.1201 (Volume m3) is not possible

### ISSUE THREAD

**Issue by cawGitHub** [Supergiovane/node-red-contrib-knx-ultimate#73]
Hi 
I want to send a value with DPT 12.1201 (volume m3) to the bus....
This dpt is not available in the dpt-selector.
Original DPT in ETS
<img width="286" alt="Screen 2020-05-06 um 11 33 10" src="https://user-images.githubusercontent.com/51526769/81162402-6bcd5180-8f8d-11ea-96a6-64b2e402e21a.png">
Available values in KNX-Ultimate 
<img width="375" alt="Screen 2020-05-06 um 11 34 03" src="https://user-images.githubusercontent.com/51526769/81162546-a800b200-8f8d-11ea-9675-915704fb3d80.png">

Node is stuck in "writing"
<img width="249" alt="Screen 2020-05-06 um 11 34 14" src="https://user-images.githubusercontent.com/51526769/81162578-b51da100-8f8d-11ea-90db-8e1252297ca6.png">

**Comment by Supergiovane** [comment]
Hi Caw,
this DPT ist not use so often, so i've not decoded it yet.
Are the other knx nodes stuck in "writing" as well?

**Comment by cawGitHub** [comment]
HI 

all other nodes are working great


Viele Grüße / Best regards

C.Weisgerber


solutio IT- und mediendienste | Schulstrasse 25 | 66793 Saarwellingen	
Tel: +49 6838 980 667, smtp: c.weisgerber@solutio-it.de <mailto:c.weisgerber@solutio-it.de>, http: www.solutio-it.com <http://www.solutio-it.com/>

Diese E-Mail enthaelt u. U. vertrauliche und/oder rechtlich geschuetzte Informationen. 
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich erhalten haben, 
informieren Sie bitte sofort den Absender und vernichten Sie diese E-Mail. 
Das unerlaubte Kopieren sowie die unbefugteWeitergabe dieser E-Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you are not the intended 
recipient (or have received this e-mail in error) please notify the sender immediately and 
destroy this e-mail. Any unauthorised copying, disclosure or distribution of the material in this
e-mail is forbidden.

**Comment by Supergiovane** [comment]
So please leave me some time to work on the DPT12.1201
I'll let you know....

**Comment by Supergiovane** [comment]
Hi Caw,
a new version with this datapoint will be out in about 1 Hour.
Hope you enjoy it.
