### ISSUE TITLE
dpt 9.007 (humidity gived undefined)

### ISSUE THREAD

**Issue by cawGitHub** [Supergiovane/node-red-contrib-knx-ultimate#74]
Hi
when I'm trying to write a value wit dpt 9.007 humidity i get "undefined"
<img width="245" alt="Screen 2020-05-06 um 19 32 50" src="https://user-images.githubusercontent.com/51526769/81209143-69d8b200-8fd0-11ea-9007-17145d2b562b.png">

**Comment by Supergiovane** [comment]
Hi Carsten
Thanks for Paypal. 
Strange. I’ll take a look tomorrow....

**Comment by Supergiovane** [comment]
Hi Carsten
does the node output the value regularly?
I suspect that's only an issue with the status indication.

**Comment by cawGitHub** [comment]
Hi Massimo

no it doesn’t …

Maybe the problem is on my end …
What would be the proper input (Example Format number -> 99) ?

**Comment by Supergiovane** [comment]
Hi Carsten
it's a simple numeric value. 
For example, in a function node:
```
mg.payload=40;
return msg;
```

The Group Address is 8/0/151, are you sure that's correct?

**Comment by cawGitHub** [comment]
Hi Massimo

That‘s exactly how I did it.
8/0/151 is correct

**Comment by Supergiovane** [comment]
![Istantanea_07_05_20__16_17](https://user-images.githubusercontent.com/37666636/81305161-4b30f480-907e-11ea-8d69-24ca582e28f0.png)

Don't really know what the problem could be. Mine works. 
What version of node (please issue a **node -v** command in a console terminal) and node-red are you running?

**Comment by cawGitHub** [comment]
Node: v12.16.3
Node-Red 1.0.6

**Comment by Supergiovane** [comment]
You're up to date.
Please paste here the code of your affected node chain. Please use the "insert code <>" option here, otherwise the JSON will mess up.

**Comment by cawGitHub** [comment]
error on my side ….
msg.dpt was set by an previous node to the wrong dpt.
