### ISSUE TITLE
One Read/Response request only

### ISSUE THREAD

**Issue by s1x** [Supergiovane/node-red-contrib-knx-ultimate#75]
Hey,

is it possible that I can only trigger once a read/response request rather than the node responding to every response on the BUS? 

Use Case: I want that when a specific event is triggered, it onces reads the bus and the payload is the value. No further responses from the bus should be tracked. Hence, I dont care what happens on that specific group address after that event.

Thanks for all the effort, fast updates and this great node.

Regards,
Julian

**Comment by Supergiovane** [comment]
Hi Julian
not directly, but you can use some sort of filtering using a function node.
The BUS communication is asynchronous, so you can send a read request yet and receive a response 3 or 4 seconds later, depending on the BUS congestion.
You can also use Interruptflowultimate (one of other my nodes) 
https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate
to allow the flow message to pass only if the topic corresponds to the Group Address you want to read, then after the first response from this group address, you can stop the flow again.

**Comment by s1x** [comment]
Hey,
why wouldn't it make sense to implement such a function? Based on the concept of the knx library I assume from an architectural point of view this might be a problem as the library is based on "listing" on the KNX bus? How did you solve such use cases with a read request instead of listining to a group address. Do you use a broker?

**Comment by Supergiovane** [comment]
Hi Julian
What do you mean with “listing”?
