### ISSUE TITLE
knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE"

### ISSUE THREAD

**Issue by waldbaer** [Supergiovane/node-red-contrib-knx-ultimate#76]
Hello,

since my last update of the knx-ultimate from version 1.1.64 to 1.1.69 
I get after almost every deployment the following error:

`"knxUltimate-config: knxConnection error: timed out waiting for CONNECTIONSTATE_RESPONSE"`
and sometimes
`"knxUltimate-config: knxConnection error: E_CONNECTION_ID"`

Nonetheless everything KNX related seems to still work smoothly. I am using knxd.

Do you have any idea what could cause these error outputs?

Thanks!
Sebastian

**Comment by Supergiovane** [comment]
Hi Sebastian
Seems that knxd doesn’t respond to a connection status request from knxultimate. Knxultimate send a status request every 10 seconds, to mantain the connection alive, as per KNX specs. 
That’s not a big issue. You can live with that, you can disable these logging into the config-node.

**Comment by Supergiovane** [comment]
... and yes the behaviour of sending status request has been introduced in the latest versions to respond to a request coming from Timberwolf server staff.

**Comment by waldbaer** [comment]
OK, thanks for clarification!
