### ISSUE TITLE
Weinzierl 732 IP Interface not working

### ISSUE THREAD

**Issue by choppychop** [Supergiovane/node-red-contrib-knx-ultimate#78]
Hi there, I've just swapped a Weinzierl 731 for a 732 and it seems to have stopped the commands working from node-red. The telegrams are turning up in the ETS monitor but nothing responds, just like you describe would happen with another KNX node-red node installed (which I had, but I've removed that and it hasn't fixed it).
I see online someone saying the 732 needs normal not low priority telegrams but I'm not sure if this is true.
Any ideas or should I try to return this and get something else?

**Comment by Supergiovane** [comment]
Have many users complaining with weinzierls. 
Please update to the latest knx ultimate version and check if the 732 has filters on group addresses.

**Comment by choppychop** [comment]
Thanks for the quick reply, done that already - 1.1.72 and rebooted the pc (its a rpi3) loads. I'll just reboot it one more time to make sure I'm telling the truth.....nope still broken
Any recommendations for a replacement? We just bought this today so should be able to get a refund. Gira ones are about $30 more but need aux power not just bus

**Comment by choppychop** [comment]
and I can't see any filter settings, its just got secure on/off (its off) and ip settings

**Comment by Supergiovane** [comment]
Hi Choppy
do you maybe have WIFI and Ethernet active on the rPi?
If yes, try first to either switch off the WiFi or to manually select the binding interface in the knx ultimate config node.
We'll try to make the 732 work first.
Gira should be fine, as well as Eibmarkt IP Router, or any non-cheapy interface or router. Is even better to buy router over interface, where the budget for the installation permits.

**Comment by choppychop** [comment]
Ok done all that, triple-checked for any other knx nodes and its clear, wifi has always been disabled in iwconfig but I locked it to the ethernet interface in the node config, rebooted, checked everything again, rebooted, still no joy.
Not sure if its helpful but heres a shot of a command that works (sent from ets group monitor) and one that doesn't from node-red. The only difference I can see is the message from ets MessageCode is LDataCon and from node-red its LDataInd and it adds a repeated flag

![ets](https://user-images.githubusercontent.com/28819179/83073905-55667180-a0c5-11ea-8abd-eed28395a068.png)
![node-red](https://user-images.githubusercontent.com/28819179/83073913-5a2b2580-a0c5-11ea-9337-9075fee6ae99.png)

**Comment by Supergiovane** [comment]
Hi Choppy
Good. I saw you’re a pro, we can speak in that way.
ETS is picking up the ETH side of the telegram you sent from nodered, not the actual telegram received from the KNX bus. 
Can you tru to do this, as stated in the FAQs?
_If you have an IP interface try to disable the ACK by selecting Suppress ACK request in the Gateway configuration node._

**Comment by choppychop** [comment]
Just heard back from our supplier and they say Weinzierl have admitted there's an issue with the processor on the 732 and should be releasing a fix

**Comment by Supergiovane** [comment]
Ah, good to know.
I've often users complying with Weinzierl. For a reason or another, they have issues.
That's strange, because Weinzierl should be one of the top players in KNX.

**Comment by choppychop** [comment]
Nice one, that fixed it. Sorry should have read your FAQ's more closely.

Thanks heaps for the help and keep up the good work

**Comment by Supergiovane** [comment]
The ACK thing fixed the issue?
The ACK option was intended for a very old interfaces, not implementing the acknowledgment of telegrams, not for a modern one, that should already have that implemented.

**Comment by choppychop** [comment]
Yeah I had two units totally fail and the third is now working thanks to your help. I borrowed a Gira today just to check and it all worked perfectly straight away

**Comment by choppychop** [comment]
Yes fixed it straight away, seems to be working great now

**Comment by Supergiovane** [comment]
Thank you for your hint.
If you need further assistance, feel free to ask again.
Bye!

**Comment by choppychop** [comment]
Thanks, will do

**Comment by KHBuchner** [comment]
Hi, I'm working for Weinzierl support. We will try to reproduce the issue, please post an ETS log of the telegrams and the configuration of node red.

**Comment by KHBuchner** [comment]
Hi, we could reproduce the issue, it seems that it has to do with the flag Acknowledge-Request in the Controlfield 1 of L_Data.req. We are investigating the behaviour.

**Comment by lapo-luchini** [comment]
I have a `CONTROLtronic IPI.1.8.2 KNX IP Interface secure` and I have the _same identical_ bug: nothing is actually sent on the bus when `suppress_ack_ldatareq: false`, while it does seem to show up on bus (I am listening via a different USB interface) when `suppress_ack_ldatareq: true`.
