### ISSUE TITLE
Trigger a read operation by bus event and pass result

### ISSUE THREAD

**Issue by beejones** [Supergiovane/node-red-contrib-knx-ultimate#79]
Hi Giovane

Thank you for the beautiful work. I have implemented a lot of devices with knx ultimate and it works very stable.
I am now trying something more advanced and do not get this working. I would love to hear your advice on this.
I tried your read samples, but it does not work with my scenario.
This is my use case
1.	Read value from the bus on GA 0/8/0. This is a trigger value which appears a few times per day.
2.	When this value appears on the bus, trigger a read operation on device 0/6/6.
3.	Pass the value of the read on 0/6/6 to a function (here is my problem, the value is never passed)
Looking forward to your advice how to solve this.

Thanks
Ronny

**Comment by Supergiovane** [comment]
Hi Bee,
about point 3, you need to set the node to react to "response" telegrams.
The output will be the value you need.
If you paste here your flow, i can make the adjustments for you.

**Comment by beejones** [comment]
This was my last test

[{"id":"4c59e66b.716528","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/8/0","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":false,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"dummy","outputtype":"response","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":240,"y":480,"wires":[[]]},{"id":"3a60c1d.296523e","type":"inject","z":"1e34628f.90f59d","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":480,"wires":[["4c59e66b.716528"]]},{"id":"729b347b.5758ac","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/8/0","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":true,"notifywrite":false,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"dummy","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"yes","x":90,"y":640,"wires":[["94b51be6.55ab08"]]},{"id":"5c2348fb.c876a8","type":"inject","z":"1e34628f.90f59d","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":90,"y":540,"wires":[["4c59e66b.716528"]]},{"id":"94b51be6.55ab08","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/6/6","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":true,"notifyresponse":true,"notifywrite":false,"notifyreadrequestalsorespondtobus":true,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"","listenallga":false,"name":"Door Status","outputtype":"write","outputRBE":false,"inputRBE":false,"passthrough":"yes","x":390,"y":640,"wires":[[]]},{"id":"aeaffafa.e874d8","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/6/6","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":true,"notifywrite":false,"notifyreadrequestalsorespondtobus":true,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"","listenallga":false,"name":"Door Status","outputtype":"response","outputRBE":false,"inputRBE":false,"passthrough":"yes","x":90,"y":720,"wires":[["edac167f.734a78"]]},{"id":"edac167f.734a78","type":"debug","z":"1e34628f.90f59d","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","x":290,"y":720,"wires":[]},{"id":"48c5d3b5.ab900c","type":"knxUltimate-config","z":"","host":"192.168.1.4","port":"3671","physAddr":"15.15.22","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"Gateway","localEchoInTunneling":true}]

Thanks

**Comment by beejones** [comment]
This was my original approach.

[{"id":"729b347b.5758ac","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/8/0","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":true,"notifywrite":false,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"dummy","outputtype":"write","outputRBE":true,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"yes","x":150,"y":360,"wires":[["94b51be6.55ab08"]]},{"id":"5c2348fb.c876a8","type":"inject","z":"1e34628f.90f59d","name":"","topic":"","payload":"false","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":260,"wires":[["4c59e66b.716528"]]},{"id":"94b51be6.55ab08","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/6/6","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":true,"notifyresponse":true,"notifywrite":false,"notifyreadrequestalsorespondtobus":true,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"","listenallga":false,"name":"Door Status","outputtype":"write","outputRBE":false,"inputRBE":false,"passthrough":"yes","x":450,"y":360,"wires":[["d4292503.09b818"]]},{"id":"4c59e66b.716528","type":"knxUltimate","z":"1e34628f.90f59d","server":"48c5d3b5.ab900c","topic":"0/8/0","outputtopic":"","dpt":"1.001","initialread":false,"notifyreadrequest":false,"notifyresponse":false,"notifywrite":false,"notifyreadrequestalsorespondtobus":false,"notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized":"0","listenallga":false,"name":"dummy","outputtype":"response","outputRBE":false,"inputRBE":false,"formatmultiplyvalue":1,"formatnegativevalue":"leave","formatdecimalsvalue":999,"passthrough":"no","x":300,"y":200,"wires":[[]]},{"id":"3a60c1d.296523e","type":"inject","z":"1e34628f.90f59d","name":"","topic":"","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":150,"y":200,"wires":[["4c59e66b.716528"]]},{"id":"d4292503.09b818","type":"debug","z":"1e34628f.90f59d","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","x":650,"y":360,"wires":[]},{"id":"48c5d3b5.ab900c","type":"knxUltimate-config","z":"","host":"192.168.1.4","port":"3671","physAddr":"15.15.22","suppressACKRequest":false,"csv":"","KNXEthInterface":"Auto","KNXEthInterfaceManuallyInput":"","statusDisplayLastUpdate":true,"statusDisplayDeviceNameWhenALL":true,"statusDisplayDataPoint":false,"stopETSImportIfNoDatapoint":"stop","loglevel":"error","name":"Gateway","localEchoInTunneling":true}]

**Comment by Supergiovane** [comment]
Hi
i'm little confused, because on the "door" node, you're using the virtual device (send value automatically to the bus...)
Can you please simply explain, what you wish to obtain and if the "door" node represents a real device or not?
Thanks

**Comment by Supergiovane** [comment]
`[
    {
        "id": "751b2c4b.f254dc",
        "type": "knxUltimate",
        "z": "b16dfffc.0f4838",
        "server": "9f389f48.e1c0c",
        "topic": "0/8/0",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": true,
        "notifyresponse": false,
        "notifywrite": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "dummy",
        "outputtype": "read",
        "outputRBE": true,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "yes",
        "x": 70,
        "y": 340,
        "wires": [
            [
                "1aaaff85.c9e21"
            ]
        ]
    },
    {
        "id": "1aaaff85.c9e21",
        "type": "knxUltimate",
        "z": "b16dfffc.0f4838",
        "server": "9f389f48.e1c0c",
        "topic": "0/6/6",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": true,
        "notifywrite": false,
        "notifyreadrequestalsorespondtobus": true,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "",
        "listenallga": false,
        "name": "Door Status",
        "outputtype": "read",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": "1",
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": "999",
        "passthrough": "no",
        "x": 270,
        "y": 340,
        "wires": [
            [
                "f363b805.17614"
            ]
        ]
    },
    {
        "id": "b03d50d9.0a6bd",
        "type": "knxUltimate",
        "z": "b16dfffc.0f4838",
        "server": "9f389f48.e1c0c",
        "topic": "0/8/0",
        "outputtopic": "",
        "dpt": "1.001",
        "initialread": false,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": false,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "dummy",
        "outputtype": "read",
        "outputRBE": false,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 220,
        "y": 180,
        "wires": [
            []
        ]
    },
    {
        "id": "f9958154.08be3",
        "type": "inject",
        "z": "b16dfffc.0f4838",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 70,
        "y": 180,
        "wires": [
            [
                "b03d50d9.0a6bd"
            ]
        ]
    },
    {
        "id": "f363b805.17614",
        "type": "debug",
        "z": "b16dfffc.0f4838",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": true,
        "complete": "true",
        "targetType": "full",
        "x": 450,
        "y": 340,
        "wires": []
    },
    {
        "id": "8809103c.8a7788",
        "type": "comment",
        "z": "b16dfffc.0f4838",
        "name": "Here you're simulating a READ coming from 0/8/0",
        "info": "",
        "x": 190,
        "y": 140,
        "wires": []
    },
    {
        "id": "47d879f6.28563",
        "type": "comment",
        "z": "b16dfffc.0f4838",
        "name": "The Dummy, issues a READ to the door status device",
        "info": "",
        "x": 200,
        "y": 300,
        "wires": []
    },
    {
        "id": "fbb106e.be4faf8",
        "type": "comment",
        "z": "b16dfffc.0f4838",
        "name": "The door status reacts to response coming from the door device.",
        "info": "",
        "x": 390,
        "y": 400,
        "wires": []
    },
    {
        "id": "9f389f48.e1c0c",
        "type": "knxUltimate-config",
        "z": "",
        "host": "192.168.1.4",
        "port": "3671",
        "physAddr": "15.15.22",
        "suppressACKRequest": false,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error",
        "name": "Gateway",
        "localEchoInTunneling": true
    }
]`

Hope i've understood what you need. Try to paste this code and let me know.

**Comment by beejones** [comment]
It is the same. The result is not send to msg.
See screenshot

![screen capture1](https://user-images.githubusercontent.com/10303990/83398669-a5d71b00-a3b4-11ea-876e-64a3a01a1824.png)

**Comment by Supergiovane** [comment]
But the "door" physical device, does respond to read requests? That's a must have. You should check this with ETS.

**Comment by beejones** [comment]
The read failed indeed. I should have checked this first. Sorry and thanks for your help.
