### ISSUE TITLE
Missing DPT 7.600 (absolute color temperature in K)

### ISSUE THREAD

**Issue by rlindner** [Supergiovane/node-red-contrib-knx-ultimate#80]
Would it be possible to add DPT 7.600? I've used DPT 7.013 as a replacement when writing, but unfortunately thats not working when listening for status values.

**Comment by Supergiovane** [comment]
Hi Roland
I’ll take a look.

**Comment by Supergiovane** [comment]
Hi Roland
V. 1.1.74 is out in about 30 minutes with dpt 7.600.
Cheers.

**Comment by rlindner** [comment]
Thank you so much! 🚀

**Comment by Supergiovane** [comment]
Thank you for your donatoon!
