### ISSUE TITLE
Group Addresses with only two parts?

### ISSUE THREAD

**Issue by t-oster** [Supergiovane/node-red-contrib-knx-ultimate#81]
Hi,

It seems as if this does not work if you are using 2-Part group addresses like "1/54". Or did I miss something?

**Comment by Supergiovane** [comment]
Hi Oster
no, 2 part addresses is not supported, sorry.

**Comment by t-oster** [comment]
Do you accept pull requests in order to change that?

**Comment by Supergiovane** [comment]
Hi,
I can evaluate that, but ther’s a lot of changes involved, including import and check fot ets import files. Maybe you can think to change your setup with 3 level?:-)

**Comment by t-oster** [comment]
Well... it's a big house and I have a ton of addresses.... Maybe I'll have time to setup a dev-env for this package and submit a PR. I don't know how the addresses are transported on the KNX layer, but for the javascript part there should be only a handful of checks to be adapted...

**Comment by Supergiovane** [comment]
I'll take a look at your PM. But i warn you: it's a complicated effort! If i was in you (and i have near 450 group addresses), i'll go for 3 level group, that's more common and compatible with all. Put a headphone on your head, relax and do it. You'll have the chance to cleanup some old dirty things you may have leaved in this years. :)

**Comment by t-oster** [comment]
Well... I researched a bit and since the GA is always 16-bit, the difference between two and three folded is just a matter of representation.
So I can already use your implementation, I just have to compute the three-folded addresses from the two-folded.

The problem with supporting both is, that it has to be a general setting, because you cannot determine it from the bus message.
A quick and dirty way would be to just update the CSV import so that it recognizes two-fold addresses and computes the three-fold one.

However. Since I was not higher than 64 in any group I could just change the representation in the ETS from 2 to 3 fold without changing anything, so this can be closed.

**Comment by Supergiovane** [comment]
Thanks for the clarification.
