### ISSUE TITLE
properties of msg entering the knx node should be preserved when exiting the node

### ISSUE THREAD

**Issue by tilleul** [Supergiovane/node-red-contrib-knx-ultimate#82]
Great work on this KNX node !

Issue:

Just like the official http request node, the properties of `msg `should be preserved when the response `msg `is sent through the exit of the knx node.

In a function node, if you have
`return {readstatus: true, my_property: "test"}`

sent to a knx-read node, then the output response `msg` should preserve my_property, just like the http request node does.

The expected `msg `should be like:
`{
readstatus: true,
my_property: "test",
topic: (an address group),
payload: (the result of the read),
knx: {object},
... }`

**Comment by Supergiovane** [comment]
Hello Tilleul
It's already so.
Please set the knx-ultimate node to respond to "read" requests and enable the "Input msg passthrough". Please see here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/2.-Node-Configuration

**Comment by tilleul** [comment]
straordinario! hai pensato a tutto! molto bene ! :D

I'm gonna test that ASAP ! Sorry for bothering you ...

**Comment by Supergiovane** [comment]
No problema. Your italian is very good. :-)
