### ISSUE TITLE
when closing ETS, no connection KNX Ultimate

### ISSUE THREAD

**Issue by benf16** [Supergiovane/node-red-contrib-knx-ultimate#83]
Supergiovane, I'm using KNX Ultimate. It works fine, aslong as my ETS application is running. When closing the applycation on my PC the nodes doesn't working anymore. I'm using the Router from Weinzierl (762 linemaster). How can I make a connection that stays connected when I close my ETS program?

**Comment by Supergiovane** [comment]
Hello Ben
There’s no logical connection between ets and knx-ultimate. 
What i can think, is that you’ve filter rules set in the Wienzierl. Please check that and disable all filters, from LAN as well from TP sections. 
If you’ve no filter rules... Please follow the FAQ and Teoubleshot pge in the Wiki.

**Comment by benf16** [comment]
tnx for the quick reaction.
I've did allready the things you proposed. 
I just did a 'Full deploy" of my nodes and thereafter the connection stays steady. hopely it stays this way.
Thanks for your contribution for Node Red :)

**Comment by Supergiovane** [comment]
Good!
