### ISSUE TITLE
Log overflow after inserting KNX Logger

### ISSUE THREAD

**Issue by Namakemono93** [Supergiovane/node-red-contrib-knx-ultimate#84]
Hi Supergiovane,

once again, thank you for those awesomenodes. Recently i found a problem in the newest Version:
After i insert a KNX Logger, my System Log fills with hunderts of warnings and errors:

![image](https://user-images.githubusercontent.com/52327137/89982544-3e6ffe00-dc76-11ea-8dfd-5ce2fbf7cbe2.png)

I have not uploaded an group adress list to the Config Node.
The logs are from knx.js, but why do i get them?

Thanks!
Simon

**Comment by Supergiovane** [comment]
Hello Simon,
this should be an informative log only. 
You can disable such as logging by setting the 

**Loglevel**
Define the log level of the underling KNX library. Useful for debugging in case of problem. Normally, you don't need to change this. Normally, it's set to "Info"

Are you able to import the XML into ETS?

**Comment by Namakemono93** [comment]
Hi Supergiovane,
The Loglevel was already set to error (default). I set it to debug and back to error again and still i get the logs on every deploy.

I can't open the xml, almos every second line is like that:
<Telegram Timestamp="2020-08-12T11:08:59.034Z" Service="L_Data.ind" FrameFormat="CommonEmi" RawData="undefined" />

**Comment by Supergiovane** [comment]
Hi Simon,
ok i'm able to reproduce the issue.
I'll work on a fix.

**Comment by Supergiovane** [comment]
Hello Simon
are you able to paste the content of the zip into the **.node-red/node_modules/node-red-contrib-knx-ultimate/nodes** folder and restart node-red?
[knxUltimateLogger.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5062499/knxUltimateLogger.js.zip)

**Comment by Supergiovane** [comment]
Simon,
As soon as you confirm me that it works, i'll release the fixed version. Thanks.

**Comment by Namakemono93** [comment]
Hi Supergiovane,

the xml does look good now, i can open it within the ETS and theres non undefined anymore. But the Log is still overflowing.

**Comment by Supergiovane** [comment]
Hi Simon,
yes, the log is there but if i change it to "error", mine disappears.
Have you maybe more than one Gateway Node?

**Comment by pyrler** [comment]
Hello

same problem here, Logfile is full of info and warn entries, but my settings is error. 

i dont't have a logger node in my Project, only KNX Devices.. 
Any idea?

i have chance the settings to warn, reboot docker with node red inside, change to error and reboot docker again, same problem.

**Comment by Supergiovane** [comment]
Hi
Do you have more than one knx gateway node?
Please don’t revive a closed issue. Thanks.
