### ISSUE TITLE
Error connecting with IP Interface.

### ISSUE THREAD

**Issue by marco-dmaa** [Supergiovane/node-red-contrib-knx-ultimate#85]
Hi, I often use your node with IP Router and it works perfectly. 
Today is the first time I use it with an IP interface. I have correctly set the ip address of the interface in the configuration node. 
With the debug node I can read the values ​​from the KNX bus. 
But in debugging it keeps showing this error: "KNXUltimate-config: Error in instantiating knxConnection Error: ipaddr: the address has neither IPv6 nor IPv4 format. Node Multicast KNX Gateway".
What could it be ?

Thanks Marco.

**Comment by Supergiovane** [comment]
Hello Marco
please double check how you wrote the IP Address. Please remove all blank spaces as well.

**Comment by marco-dmaa** [comment]
I checked but there are no empty spaces. In fact, if I put a node to read a value from the bus it reads it correctly ...
Some idea?

Thanks Marco.

**Comment by Supergiovane** [comment]
Please post here the screenshot of your gateway config.
Please be sure not to have two gateway nodes :-)

**Comment by marco-dmaa** [comment]
![Cattura1](https://user-images.githubusercontent.com/69626652/90121448-486c2c80-dd5c-11ea-9a77-ca039e1f37a1.PNG)

**Comment by marco-dmaa** [comment]
![Cattura2](https://user-images.githubusercontent.com/69626652/90121605-781b3480-dd5c-11ea-93ba-4c88a1670a06.PNG)

**Comment by Supergiovane** [comment]
Hmmm..
For me, this is something that can be fixed by a restart of node-red. Have you tried to reboot?

**Comment by marco-dmaa** [comment]
No, I'll try now!

**Comment by marco-dmaa** [comment]
After restarting the RPI the error disappeared!

Thanks a lot, Marco.

**Comment by Supergiovane** [comment]
Perfect. Thankyou.
