### ISSUE TITLE
16 Aug 12:09:44 - [error] knxUltimate: Lost link due to a connection error

### ISSUE THREAD

**Issue by pyrler** [Supergiovane/node-red-contrib-knx-ultimate#86]
Hi There

I become this message by every Deploy. What does it mean? Everything is working, but in the console and Message section in Node-red this appears.. 

How i can solve this?

**Comment by Supergiovane** [comment]
Hi pyrel. 
This is normal. Whenever you deploy, the knx connection resets itself. No worry.

**Comment by pyrler** [comment]
Hi, thanks for the quick response.  
Can't you prevent that when deploying?  It is a bit unsightly (and unsettling) to find the log file "full" of errors which are not errors ..

**Comment by Supergiovane** [comment]
Hello
No, because i’m unable to detect the deploy command, sorry.
