### ISSUE TITLE
Settings Loglevel don't work

### ISSUE THREAD

**Issue by pyrler** [Supergiovane/node-red-contrib-knx-ultimate#87]
Hello

Logfile is full of info and warn entries, but my settings is error.

i dont't have a logger node in my Project, only KNX Devices..
Any idea?

i have chance the settings to warn, reboot docker with node red inside, change to error and reboot docker again, same problem.

**Comment by pyrler** [comment]
i have Only one KNX Gateway in my hole Project

**Comment by Supergiovane** [comment]
Will work on it. What's your name?

**Comment by Supergiovane** [comment]
Please paste here a screenshot with the log your'e talking about. I need to view what the problem is. Thanks.

**Comment by pyrler** [comment]
Hello

Im Kevin

For example: 
[debug] "2020-08-16T12:27:05.247Z"'./knx/src/dpt20.js : input value = 4   apdu_data = \u0004'
16 Aug 14:27:10 - [info] KNXUltimate-config: Do readInitialValues

**Comment by Supergiovane** [comment]
Hello Kevin.
a reboot should apply the new debug level selection.
Changing the debug level is applied only after node-red restart.
If you're sure not to have other KNX Gateway nodes, you should solve the issue by restarting docker. I don't now why it's not working for you.
The upcoming version of lix-ultimate (1.1.80) applies the change to the debug's level immediately, without the need to restart node-red.
Please update to 1.1.80 as soon as you see the new version (in about 1 hour), then let me know.

**Comment by Supergiovane** [comment]
Hello Kevin
can you please give me a feedback?

**Comment by pyrler** [comment]
Hello

Sorry for the Delay, im @work..

I updated to 1.1.80, change the loglevel to information and back to error and have the same situation.  (I see debug messages in the console)

Without restart docker. But i have see more entrys when i have loglevel info. So i think the change has work

**Comment by Supergiovane** [comment]
Hi Kevin
better to be @home with node red, than @work!
At loglevel "error", only severe errors are logged.
My 3 installations, with loglevel set to "error", doesn't log anything.
Do you maybe have some other KNX nodes installed but not used? For example knx-easy ? That may interfere.

**Comment by pyrler** [comment]
Hi

I have testet this at home: doesnt work. Loglevel error
![image](https://user-images.githubusercontent.com/46838665/90403343-239bf000-e0a1-11ea-8072-866f786cf841.jpg)

I have installed earlier an other knx lib, i have removed it with the same result... (npm remove ..)

**Comment by Supergiovane** [comment]
Hi 
Have you rebooted node-red?
Please reboot, the issue should disappear.

**Comment by pyrler** [comment]
I wish i can give you a better Feedback. But no, it is the same. But it is primary at the deploy and read values.. after the initial read i think its ok... ?

**Comment by Supergiovane** [comment]
Hmm... please copy the code of one of your knx-ultimate nodes and paste it here. I need to view your things.

**Comment by pyrler** [comment]
`[
    {
        "id": "c1485a3d.92eb38",
        "type": "knxUltimate",
        "z": "8567e889.3961a8",
        "server": "5cdc003e.7c137",
        "topic": "1/4/63",
        "dpt": "1.001",
        "initialread": true,
        "notifyreadrequest": true,
        "notifyresponse": true,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "",
        "outputtype": "response",
        "outputRBE": false,
        "inputRBE": false,
        "x": 70,
        "y": 90,
        "wires": [
            [
                "b816f369.35e278",
                "b1260b40.87bcb",
                "98cacd85.6ddb8"
            ]
        ]
    },
    {
        "id": "5cdc003e.7c137",
        "type": "knxUltimate-config",
        "z": "",
        "host": "192.168.49.171",
        "port": "3671",
        "physAddr": "0.0.251",
        "suppressACKRequest": true,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": false,
        "statusDisplayDeviceNameWhenALL": false,
        "statusDisplayDataPoint": true,
        "stopETSImportIfNoDatapoint": "skip",
        "loglevel": "error",
        "name": "192.168.49.171",
        "localEchoInTunneling": false,
        "delaybetweentelegrams": "100",
        "delaybetweentelegramsfurtherdelayREAD": ""
    }
] `

**Comment by Supergiovane** [comment]
Hi Kevin.
No warnings shows up, even with your code.
Please see here and check that you don't have ghost knx-gateways node that you don't use.
Your log problem is related either to this, or to other nodes in your node-red using knxjs apis.

![Schermata 2020-08-18 alle 16 18 40](https://user-images.githubusercontent.com/37666636/90524628-96bf6800-e16e-11ea-87f9-19db921a01af.png)

**Comment by Supergiovane** [comment]
PS: Please upgrade to 1.1.81 and restart node-red. I've added a string to identify from where the warning logs comes.

**Comment by pyrler** [comment]
Hi

also with 1.1.81 the same :-( without string infos (docker is restarted)


`18 Aug 19:07:16 - [info] KNXUltimate-config: Do readInitialValues
18 Aug 19:07:55 - [info] KNXUltimate-config: Total knx-ultimate nodes: 90
[debug] "2020-08-18T17:11:25.109Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:16:25.074Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:21:25.039Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:26:25.005Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:31:24.970Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:36:24.935Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:41:24.901Z"  '               dpt20.js   fromBuffer : 4'
[debug] "2020-08-18T17:46:24.867Z"  '               dpt20.js   fromBuffer : 4' `

i cant see any dead config nodes.. hmm.. i try to uname the node_modules directory and make npm install.. well see.. i update you later..

**Comment by Supergiovane** [comment]
That’s clearly not a knx-ultimate log!!
The time is in zulu and there is no “KnxUltimate-API” text in the log.

**Comment by heleon19** [comment]
Hi Supergiovane

I have knx-ultimate v1.1.810 installed and no other knx libs. To confirm that i added "test in knxultimate-api >>>>" in dpt1.js.

Find my log:
Welcome to Node-RED
===================

19 Aug 10:12:32 - [info] Node-RED version: v1.1.3
19 Aug 10:12:32 - [info] Node.js  version: v12.16.1
19 Aug 10:12:32 - [info] Linux 4.19.75-v7+ arm LE
19 Aug 10:12:34 - [info] Loading palette nodes
[info] "2020-08-19T08:12:55.905Z"  'Loading knxultimate-api: node-red-contrib-KNX-Ultimate KNX API (https://flows.nodered.org/node/node-red-contrib-knx-ultimate), version: 2.3.21'
19 Aug 10:12:56 - [info] Context store  : 'persist' [module=localfilesystem]
19 Aug 10:12:56 - [info] Context store  : 'default' [module=memory]
19 Aug 10:12:56 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
19 Aug 10:12:56 - [info] Flows file     : /data/flows.json
19 Aug 10:12:56 - [info] Server now running at http://127.0.0.1:xxxx
19 Aug 10:12:56 - [info] Starting flows
19 Aug 10:12:56 - [info] KNXUltimate-config: csv ETS found !
19 Aug 10:12:57 - [info] KNXUltimate-config: Bind KNX Bus to interface (Auto). Node UV UG Media
19-08  10:12:58 - [INFO] [datalogger] [4dc2fb67056674] create a new queue
19 Aug 10:13:00 - [info] Started flows
19 Aug 10:13:05 - [info] KNXUltimate-config: Do readInitialValues
[warn] "2020-08-19T08:13:05.568Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:05.934Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:06.354Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:06.715Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:07.104Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:07.467Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:07.833Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:08.557Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:08.920Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:09.303Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:09.687Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined
[warn] "2020-08-19T08:13:10.079Z"  'test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)' undefined

![image](https://user-images.githubusercontent.com/10326318/90610347-958d4a00-e205-11ea-8570-a5143a615632.png)

Any idea where to look at?

Regards Reto

**Comment by heleon19** [comment]
In dptXY.js should ...

`const KnxLog = require('./KnxLog');` 

... be used instead of ...

`const log = require('log-driver').logger;`

With require log-drive you get a new instance of a logger, you should use the KnxLog with the desired log level.

**Comment by heleon19** [comment]
Example for dpt1.js:

**const knxLog = require('./../KnxLog');**
exports.formatAPDU = function(value) {
  var f = parseFloat(value);
  if (!isNaN(f) && isFinite(value)) {
    // numeric values (in native and string form) are truthy if NOT zero
    return new Buffer([Boolean(f) ? 1 : 0]);
  } else {
    // non-numeric value truthiness is Boolean true or the string 'true'.
    return new Buffer([(value == true || value == 'true') ? 1 : 0]);
  }
}
exports.fromBuffer = function(buf) {
  if (buf.length != 1) {
    **knxLog.get()**.warn("test in knxultimate-api >>>> DPT1.fromBuffer: buf should be 1 byte (got %d bytes)", buf.length);
  } else return (buf[0] != 0);
}

**Comment by Supergiovane** [comment]
Hi Reto,
Yes, you're right. This is an odd "surplus" of the old knx.js API.
Do you want to make a PR of knxultimate-api in GitHub, or must i do it by myself?

**Comment by heleon19** [comment]
I do a PR :-)

**Comment by Supergiovane** [comment]
Sorry @pyrler Kevin, you was (partially) right :-)
As soon as Heleon10 do a PR, i'll publish the V. 1.1.82 that should definitely fix this thing.

**Comment by heleon19** [comment]
PR is done, please double check.

Thank you for your support!

**Comment by Supergiovane** [comment]
Thank you Reto.
I'm running the changes on my primary node-red (my home). 
This seems to work OK but i'm continuing the tests.
The v. 1.1.82 will be tomorrow. We have no hurry for this issue.

**Comment by heleon19** [comment]
Thats right, thank you Supergiovane.
