### ISSUE TITLE
Compatibility with Siemens N148/22 IP interface ?

### ISSUE THREAD

**Issue by mattvbv** [Supergiovane/node-red-contrib-knx-ultimate#89]
Hello, 
I'm in the typical FAQ scenario where I receive all KNX messages using this IP interface, but whenever I send one, nothing happens (light does not go on), although the node is updated correctly and I see a correct GroupWrite debug message.
Could it be that this interface is not supported ? I don't have any filtering on it in ETS (feature not even supported).
I tried all what is suggested in the checklist in the FAQ.
Thanks for the help

**Comment by Supergiovane** [comment]
Hi Matt
I owned a n148 and then i throw it away. The firmware was buggy and there’s no firmware upgrade anymore for this device, that’s very old.
If you’ve tried to enable the “suppress ack” option in the gateway and it does not work, i suggest you to try another knx/ip interface or router.

**Comment by mattvbv** [comment]
Thank you.
Do you have any recommendation for another knx ip interface that is known to work your nodered plugin ? I just need a basic one, no special needs.

**Comment by Supergiovane** [comment]
Hi Matt
i used with success, the eibmarkt knx router and an enertex kn interface as well as knx router. 
Any make does work. Some users reported issues with Weinziel interfaces, but with newer firmware, they should be gone. 
If possible, always buy knx/ip routers. They are more robust and flexible than knx/ip interfaces.
