### ISSUE TITLE
Support tp-uart??

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#9]
Hi @Supergiovane 

Can I use the serial port and tp-uart for communication in the future?
I looked at the source code of knx.js, which only supports knx-ip.

The Raspberry Pi can be connected directly to tp-uart. This makes it possible to make a programmable knx gateway.

Best Regards
songzh

**Comment by Supergiovane** [comment]
Hello songzh96,
Currently not. I don't know when the knx.sj will support that (if it will do), because i think the priority is to give access to the new "secure tunnel IP connection" first.
