### ISSUE TITLE
Missing DPT 222.100 (3x set of RoomTemperature Setpoint  16-Float Values)

### ISSUE THREAD

**Issue by Raph-hsyuan** [Supergiovane/node-red-contrib-knx-ultimate#90]
Hi,
Could you please add DPT 222.100/222.101, it is a 3*16-float value. 
We can decode the data from rawValue, but we can't find a replacement when writing.

**Comment by Supergiovane** [comment]
Hi Raph. 
Thank you for your kind words about my node. 
I appreciate that. 
Please leave me some days, because i’m currently on vacation.

**Comment by Supergiovane** [comment]
Hi Raph,
DPT222.x is almost ready.
I should be able do release an update version, with samples as well, latest tomorrow morning.

**Comment by Raph-hsyuan** [comment]
Great, it works perfectly, thank you very much for your work !

I try to send an already encoded data to the KNX Bus with knx-ultimate, but I don't know how to do that... 
So I modified [knxultimate-api/index.js](https://github.com/Supergiovane/knxultimate-api/blob/b910ac1a51b89ee83cb2a31d2ce398100c54c24d/src/dptlib/index.js#L83) in order to write the payload directly into the KNX bus as encoded data when dptid is "unknown" 😂. 

Maybe you have some better solutions when some new dpts are temporarily missing ?

**Comment by Supergiovane** [comment]
Hi Raph,
Thank you. I normally add datapoints the same day someone ask for. Yet i’m on vacation with very poor internet connection, so it takes more time. 
I don’t remember if you can already send a raw data to the node, you should look at the wiki in the github page of lnx-ultimate, and search for the page explaining the accepted input msg.
