### ISSUE TITLE
Two times the same numerik value don't get on the KNX bus

### ISSUE THREAD

**Issue by De-Frank** [Supergiovane/node-red-contrib-knx-ultimate#91]
Hello Supergiovane,

I'm new at this.

I am using KNX ultimate for the first time and it works beautifully.
I use a ARCUS-EDS / KNX-IP-GatewayII v. 2.01 / Article No.  40400003
I've now established something that I don't know what to do with.

If I send a numerical value to the KNX bus twice in a row, this value does not get through on the bus the second time.

Below the flow with debug

![image](https://user-images.githubusercontent.com/71901152/94314746-76f73d00-ff81-11ea-9f24-c6246a6fb903.png)
Here you can see the properties of the variable.

![image](https://user-images.githubusercontent.com/71901152/94314818-9bebb000-ff81-11ea-9698-de7d2ff8b0d1.png)
Here I increase the value to 3 and it comes on the bus.

![KNX ultimate](https://user-images.githubusercontent.com/71901152/94315123-2e8c4f00-ff82-11ea-9db9-18d789cf06a2.jpg)
Here I re-inject the value 3 and it is no longer on the bus. I can repeat this 10 times without any result on the bus.

![image](https://user-images.githubusercontent.com/71901152/94315876-a7d87180-ff83-11ea-878e-21e0a9f1538a.png)
If I inject the value 3.1 it will be immediately on the KNX bus.

I hope I have documented this sufficiently?

Regards

**Comment by Supergiovane** [comment]
Hi Frank
Please read the wiki carefully, because the node is very powerful and it has many options. 
In your case, simply disable the rbe filter.
