### ISSUE TITLE
can not writing

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#92]
Hi

After a period of testing, I found a new problem.
Cannot write data on the bus, But when I restart node-red, it is ok.

Raspberry 4B 2G
knxd 0.14.39
node-red-contrib-knx-ultimate 1.1.85

![image](https://user-images.githubusercontent.com/26770241/94358479-e8470500-00d3-11eb-8fa5-4b29d5c506de.png)

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hi Songz
It seems loosing the connection with knxd 
Are you sure, knxd still work?
Can you manually restart only the knxd, whenever the node fails?

**Comment by songzh96** [comment]
Yeah KNXD is ok

when i restart knxd, it is not working yet,only restart node-red
![image](https://user-images.githubusercontent.com/26770241/94360216-5c86a600-00de-11eb-8960-15f93732e5a5.png)
![image](https://user-images.githubusercontent.com/26770241/94360232-72946680-00de-11eb-979f-b1e6800b262c.png)

![image](https://user-images.githubusercontent.com/26770241/94360181-22b59f80-00de-11eb-84ad-24e04da88ab9.png)

**Comment by Supergiovane** [comment]
Hi
Do you maybe have both wifi and ethernet enabled on raspberry? If yes, either disable one of them, or select a specific ethernet to bind to, in the config node. Even inf lnxd runs on the same machine, it matters. 
If that doesn’t work, can you please downgrade the node to 1.1.83 or below?
Do you know how to downgrade?

**Comment by Supergiovane** [comment]
..and... it will be useful to see some node-red log, so i can see what happens.

**Comment by songzh96** [comment]
only ethernet
have updated 1.1.88,testing
I think is knxd lost and then node-red-contrib-knx-ultimate can not reconect.
this is log
[node-red-error.log](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5287990/node-red-error.log)

```
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:11 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:33 - [info] KNXUltimate-config: Do readInitialValues
27 Sep 15:01:58 - [error] knxUltimate-config: knxConnection error: E_CONNECTION_ID
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:01:58 - [error] knxUltimate: Lost link due to a connection error
27 Sep 15:02:20 - [info] KNXUltimate-config: Do readInitialValues
27 Sep 15:02:45 - [error] knxUltimate-config: knxConnection error: E_CONNECTION_ID
27 Sep 15:03:07 - [info] KNXUltimate-config: Do readInitialValues
27 Sep 16:23:26 - [info] KNXUltimate-config: Total knx-ultimate nodes: 11
27 Sep 16:26:06 - [error] knxUltimate-config: knxConnection error: E_CONNECTION_ID
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
27 Sep 16:26:06 - [error] knxUltimate: Lost link due to a connection error
```

**Comment by Supergiovane** [comment]
Mmmmm. Let me do some checks. I revert to you asap.

**Comment by songzh96** [comment]
Thank you very much !!! ~~~///(^v^)\\\~~~

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hi Songzh
Can you please unzip the attached file and copy the content in your 
**/home/pi/.node-red/node_modules/node-red-contrib-knx-ultimate/nodes/ folder**, then restart node-red?
Thanks.
[knxUltimate-config.js.zip](https://github.com/Supergiovane/node-red-contrib-knx-ultimate/files/5288030/knxUltimate-config.js.zip)

**Comment by songzh96** [comment]
it is ok now

when i stop knxd,  ultimate can not send msg to bus. now when i start knxd, it will send msg to bus.

thank you again

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Good.
I'll post a new version with this fix. Thank you for raising the issue.
Let me know if i can do something else for you.
Cheers!

**Comment by songzh96** [comment]
[Cheers]~(￣▽￣)~*
This project is really great，Help me a lot
I develop a knx pcb based raspberry and knxd, if you need ,  you can tell me， I can send it to you（free）.
![image](https://user-images.githubusercontent.com/26770241/94361848-e851ff80-00e9-11eb-9fb2-1a77821c36a3.png)

**Comment by Supergiovane** [comment]
Good job!

**Comment by songzh96** [comment]
knx-ultimate 1.1.89
knxd
raspberry

Hi

I found 3 new errors
1. when i stop knxd， wait 10s and then start knxd.  knx-ultimate can writing but will lost msg. seems like msg blocked.
![image](https://user-images.githubusercontent.com/26770241/94646790-9e535e80-0321-11eb-89d0-7871f6eba7d3.png)
![image](https://user-images.githubusercontent.com/26770241/94646874-d3f84780-0321-11eb-9c19-ae1f04a57c52.png)

2. knx-ip tunnel can not run with router. 2 gateway nodes in the same flow. the tunnel will show disconnected. ets5 can not connect the tunnel link. but can connect the router link.

3. when I use KNX-IP router nodes send msg, I can see the msg in ETS5 Group Monitor. but my device no action. when I use ETS5 group monitor send the same msg, my device has action. so I think it is not knxd problem.


of course knxd have a problem.
```
Sep 29 17:27:03 raspberrypi systemd[1]: knxd.service: Service RestartSec=10s expired, scheduling restart.
Sep 29 17:27:03 raspberrypi systemd[1]: knxd.service: Scheduled restart job, restart counter is at 852.
Sep 29 17:27:03 raspberrypi systemd[1]: Stopped KNX Daemon.
Sep 29 17:27:03 raspberrypi systemd[1]: Starting KNX Daemon...
Sep 29 17:27:03 raspberrypi knxd[8089]: KOMEN: E00000064: [28:router] router: setup router: failed
Sep 29 17:27:03 raspberrypi knxd[8089]: KOMEN: F00000105: [16:server] Link down, terminating
Sep 29 17:27:03 raspberrypi systemd[1]: Started KNX Daemon.
Sep 29 17:27:03 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
Sep 29 17:27:03 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'
```

Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hi Songzh,
although i've not fully understood your KNX topology, nor i've understood if you have other physical KNX Router/Interfaces in your installation, i assume you're running only knxd.
For point 2, be sure not to have occupied all free tunnels. In that case, you may run out of free tunnel and the  node cannot connect anymore.
For point 3, the ETS picks up the "Ethernet telegram part" of what you've sent. You should check whether knxd is still sending the telegram via KNX bus. I think it stops sending data to the KNX bus. 
In "Router" mode, there is no alive connection between knxd and knx-ultimate, because it's all via UDP. Knx-ultimate is unable to understand, if knxd is up or not, unless you use the watchdog node. Other than that, pleas double check that knxd doesn't filter KNX physical addresses, because KNX Router does this by default and you need to disable such filter.
In "Tunnel" mode, knx-ultimate should be able to detect if knxd is up or not (assuming that knxd correctly handles the connection status).

**Comment by Supergiovane** [comment]
..and what about using a physical KNX interface for your project? You can put the board and KNX Interface in one single housing. You can use the Ethernet port of the RaspberryPI for KNX and an adapter USB-Ethernet for connecting Raspberry PI to the internet (or simply use the WiFi, without further hardware).
This will cost a little more, but you won't run in any issue more.

**Comment by songzh96** [comment]
em....
I am on testing knxd and knx-ultimate nodes.  
my topology only a power, dimmer module , knxd gateway(raspberry)

2. I think it is not to have occupied all free tunnels. because only ETS5 and knx-ultimate use that.

3. may be I can give some logs. it needs you tell me how to get the debug logs.

I also found this problem before， when knxd conf is -DTS it is ok. when use -DTRS , knx-ulimate can not use router function.
But this time I want to find out the cause of this problem, so I need your help，please understand。

**Comment by Supergiovane** [comment]
Hi Songzh, 
Ok, thank you. 
I was not sure if you added, in the meantime, some other things to your setup, so i asked again for that.
I'm really ignorant about hot knxd works, i never used it.
I need more time to learn knxd, to build a VM with knxd and to do some testing....

**Comment by songzh96** [comment]
i will give you a ssh link.

may be you can remote it and check it

**Comment by songzh96** [comment]
ssh
account: ssh -oPort=12001 pi@47.102.214.210
pwd: admin123

node-red
47.102.214.210:12002

**Comment by Supergiovane** [comment]
Thank you.
It gives me "connection refused"

**Comment by songzh96** [comment]
Can you ping 47.102.214.210?





------------------ Original ------------------

**Comment by songzh96** [comment]
> Thank you.
> It gives me "connection refused" on ssh

sorry,it is offline now. when i fixed it,i will tell you

**Comment by songzh96** [comment]
remote is ok now.

![image](https://user-images.githubusercontent.com/26770241/94794787-f4520000-040e-11eb-9ae1-c0ba0c8a209c.png)

**Comment by Supergiovane** [comment]
Ok, so please stop knxd for 10 seconds and restart it. I don't know how to do. I need to check the matter, whenever it doesn't work. Thanks

**Comment by songzh96** [comment]
stop:sudo systemctl stop knxd
start:sudo systemctl start knxd
check log: sudo journalctl -f -u knxd -n 10000

node-red: 47.102.214.210:120002
node-red-log: cd .pm2/logs/node-red-error

**Comment by Supergiovane** [comment]
Hi Songhz
i replay tried hang the node, without success.
Even with a sudden restart of knxd, or waiting 10 seconds, or longer... it makes no difference.
KNX-Ultimate regain the connection everytime.
I've set the debug level of knx-ultimate to "debug" (advanced options in the config node). I see the knxd disconnection, but then it reconnects without issues. Obviously, at the reconnection, some telegrams are loose, but that's normal.
Please write me again when you see the "writing" steady on the screen, because for now, i cannot solve an issue that doesn't appear.
Thanks.

**Comment by songzh96** [comment]
Hi  Supergiovane
the node is show "writing" now
because I set the inject node send messages periodically 2s;
when knxd stop. and the start again.  the "writing" will show.

**Comment by songzh96** [comment]
Hi  Supergiovane
the node is show "writing" now
because I set the inject node send messages periodically 2s;
when knxd stop. and start again.  the "writing" will show.

**Comment by Supergiovane** [comment]
Hi Songzh
i made some changes.
Can you try it now? Unfortunately, i cannot see if your KNX actuators are responding properly or not... Maybe a webcam can help... ;-)

**Comment by songzh96** [comment]
Hi &nbsp;Supergiovane
Thanks for your help&nbsp;
There is no webcam but 1/1/1 is a real switch,1/2/1 is active feedback&nbsp;
You can use the group address











------------------ Original ------------------

**Comment by Supergiovane** [comment]
Ok. 
I go to sleep now. 
Will test tomorrow.

**Comment by Supergiovane** [comment]
Hi Songzh
Are you sure about 1/2/1 as active feedback? 
It doesn't change and if i issue a READ request, it doesn't respond.

**Comment by songzh96** [comment]
Hi @Supergiovane 
yeah,also I open a remote port 12003， it is the knx nat mode.
![image](https://user-images.githubusercontent.com/26770241/94903253-1a89a580-04cc-11eb-86f9-536c0966fa73.png)

![image](https://user-images.githubusercontent.com/26770241/94903426-62103180-04cc-11eb-9c9e-4ffb861eb41c.png)

**Comment by Supergiovane** [comment]
Is the 1/2/1 set to respond to read requests (in ETS)?

**Comment by Supergiovane** [comment]
Ah, ok, yet it responds. Thanks.

**Comment by Supergiovane** [comment]
Hi Songzh,
i've maybe found the issue with knxd.
I'm working on it, but it takes me some time and some tests. In the meantime, i'll use your node-red to test it.

**Comment by Supergiovane** [comment]
I'm unable to connect

**Comment by songzh96** [comment]
Because knx &nbsp;use frp udp.&nbsp;
It’s unstable&nbsp;
Maybe need restart&nbsp;
Cmd:sudo systemctl restart frp&nbsp;





------------------ Original ------------------

**Comment by Supergiovane** [comment]
It works.

**Comment by Supergiovane** [comment]
Hello Songzh
There was 2 problems:

1) with knxd, you should use 127.0.0.1 in the config node, instead of 172.16.0.2.  if you use eibd or knxd as your IP router, and you have it running on the same box as your NodeJS app, then eibd/knxd will DROP multicast packets coming from the same source IP address. This is meant to prevent endless loops: if by error knxd is configured also as a client (that will join the same multicast group), then a multicast storm will flood your LAN.

2) For some reasons, there is an issue in handling knxd connection status. Knx-ultimate was accepting input messages even if the connection was broken, by filling a transmit queue. Once the connection was re-established, knx-ultimate was starting to send all messages in the queue (we speak of a lot of messages), for a long period of time, until the queue was empty.

I've fixed both points (remember to use 127.0.0.1 on point 1!).
Please try your system for some time and let me know if you see something wrong or if it's all OK.
Then i'll release a new version of knx-ultimate with the patch for knxd.

**Comment by songzh96** [comment]
Hi Supergiovane 

Thank you for your help, I will remember that
Error:
when I use the Multicast gateway node, the Tunnel node will be disconnected.
maybe the error related to KNXD, you can use your IP router to try.

![image](https://user-images.githubusercontent.com/26770241/94929194-58e88a00-04f7-11eb-9da4-4c30cf887f73.png)


Best Regards
Songzh

**Comment by Supergiovane** [comment]
Hi 
mine works, with both on multicast and unicast on the same machine.
Have you restarted node.red?

**Comment by Supergiovane** [comment]
Mmmmm..... wait a moment. I revert to you asap.

**Comment by Supergiovane** [comment]
Hi Songhz
You're running in the "maximum tunnel connection" error.
You reached the maximum tunnel allowed.
I confirm you, that i've no issues running multicast and unicast connections at the same time.

![Schermata 2020-10-02 alle 16 12 33](https://user-images.githubusercontent.com/37666636/94933058-27a59500-04ca-11eb-92a3-0d39b527d811.png)

**Comment by songzh96** [comment]
Ok&nbsp;

Thanks for your help&nbsp;
Have a nice day&nbsp;


------------------ Original ------------------

**Comment by Supergiovane** [comment]
The new official version 1.1.90 is out.
