### ISSUE TITLE
RBE-Output filter is not working

### ISSUE THREAD

**Issue by Eraser-1** [Supergiovane/node-red-contrib-knx-ultimate#94]
Hello,

I successfully use the knx ultimate for sending values to the KNX.

Now I wanted to just add a RBE-output filter to one node, so that just changed payloads will be sent to the KNX-bus.

Unfortunately the node still always sends the message.

Is there a instruction somewhere how to properly configure it?
It looks like that it isn't done by just ticking "Send payload to BUS only if changed (RBE filter)".

Thanks
Wolfgang

**Comment by Supergiovane** [comment]
Hi Wolfgang
It should work. Mine works as expected. 
What type of payload are you sending to the bode?
Can you post here the screenshot of the config window of the affected node?

**Comment by Eraser-1** [comment]
![image](https://user-images.githubusercontent.com/72003053/95486772-bcf5cd00-0993-11eb-856d-c0ebc06456de.png)

**Comment by Supergiovane** [comment]
Mmmmmm.... please allow me some time to check the matter. For sure, it works with boolean but i need to test it with numeric values as well. 
In the meantime, you can slap a standard RBE node in front of the knx-iltimate node.

**Comment by Supergiovane** [comment]
As soon as i find the issue, i’ll fix it. Yet i haven’t access to my mac, because i’m out to do some thinks, but tomorrow morning you’ll have it fixed, if i find the problem.

**Comment by Eraser-1** [comment]
Yes that's what I have done now.

I just thought about it and I realized, that I additionaly want a value on the KNX-bus once every hour, because otherwise with the rbe filter I didn't get any values for a longer period of time when there is no change in the values. This would be a better style for using diagrams.
I don't think this function is implemented in your nodes or?

Otherwise I have to use the seperate rbe filter nodes with some additional nodes for the cyclic sending.

Thanks for your help

**Comment by Eraser-1** [comment]
I have just recognized, that the value 0 is functioning with the internal rbe filter.
Maybe this helps you for finding the problem.

**Comment by Supergiovane** [comment]
Yes it works with true and false. That’s incredible. No one has ever raised such an issue. Thank you. 
And no, that function to suspend the rbe filter once a time, is beyond the node’s scope.

**Comment by Eraser-1** [comment]
OK thanks, my bypass solution works perfectly.

Thank you for sharing the KNX nodes !!

**Comment by Supergiovane** [comment]
Hi Wolfgang
i tested yet the RBE filter and it does work as expected, even with numeric or string values.

![Node-RED](https://user-images.githubusercontent.com/37666636/95546760-b56d0d00-0a01-11eb-8b81-05739ec7ed11.png)

Are you sure, that this **msg.payload.dxsEntries[0].value** is not an object?

# Second question:
To send the value every hour, you can:

- Set the **DC-Spannung** to react to READ request and to automatically respond with the current value.

![Node-RED 2](https://user-images.githubusercontent.com/37666636/95546957-2ca2a100-0a02-11eb-9408-0951a513d915.png)


- Then, put a knx-ultimate node into your flow, and set it to output a READ request on the same group address of **DC-Spannung** and put an inject before it. The inject can output whatever payload you want.

![Node-RED 3](https://user-images.githubusercontent.com/37666636/95546992-3e844400-0a02-11eb-9034-3d578de1a616.png)

With this solution, every actuator or node, that needs to read the DC-Spannung value, can simply issue a READ request to the DC-Spannung's group address and it will respond.
This solution is called "Virtual Device" and is documented here: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---Virtual-Device

**Comment by Eraser-1** [comment]
Here is the debug output of the message which is going to the KNX-node.

![Unbenannt](https://user-images.githubusercontent.com/72003053/95558188-24ecf780-0a16-11eb-8543-faad312addf1.png)

There the format is written as number (but as float and not integer).

When I tested the RBE-function, I manually send the HTTP request a few timer in the time period of 5sec., so that the value stayed the same (HTTP site is refreshing every 5 seconds).

Maybe it has something to do with float numbers?

For me my solution works fine and is simple to understand for me (I'm a NodeRed-Beginner).

Thanks

**Comment by Supergiovane** [comment]
Hello Wolfgang
Yes, you're right. That's the float.
The datapoint you're using in the DC- Spannung, doesn't allow so much decimals.
The value sent to the bus is rouded, so it differs from the value you sent to the input message.

Simply round the value output from **DC - Spannung 1** function node, to 2 or 1 decimals and user proper datapoint for knx-ultimate node **DC - Spannung**
This will round the value to 2 decimals:

```
var dVal = msg.payload;
// Divido per 1000 per trovare i Kw
dVal=dVal/1000;
// Arrotondo i Kw a 2 decimali
var dArrotondato = Math.round(dVal * 100)/100;
msg.payload=dArrotondato;
return msg;
```

**Comment by Supergiovane** [comment]
PS: ich bin auch auf knx-user-forum, als TheMax74, falls du etwas mehr benötigst.

**Comment by Eraser-1** [comment]
OK danke
