### ISSUE TITLE
Dont have any response from the devices

### ISSUE THREAD

**Issue by AbelSantos32** [Supergiovane/node-red-contrib-knx-ultimate#97]
Good morning, i'm doing a school project to integrate KNX, IBM and node red, i have instaled the application of node red directly on the cloud of IBM and i do the programming of ETS and it works with IP (MDT IP router) through the ETS. But with node red it doesnt work, can you please Help me.
Best regards

**Comment by Supergiovane** [comment]
Hi
Installing node-red on IBM cloud and trying to command a KNX installation is an unsecured practice, unless you've a VPN.
You need to forward the port 3671 from your firewall to node-red IP.

**Comment by AbelSantos32** [comment]
Hello,

Thank you for your response , it was a malfunction of the school computer, now its all working and running smothly, just changed the computer instaled node-red and your node and its all done. thank you for your hard work on maintaining the code

Best regards

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
