### ISSUE TITLE
Access gateway via hostname instead of IP address

### ISSUE THREAD

**Issue by MCsnuffBobbyK** [Supergiovane/node-red-contrib-knx-ultimate#98]
In dynamic environments it is preferable to use DNS for hostname resolution instead of static IP addresses. I would like to configure the KNX gateway via hostname instead of changing the IP address from time to time.

**Comment by Supergiovane** [comment]
Hi MC
how do you mean by dynamic environments?
A KNX Installation should ever have a well known and reachable KNX IP/Router interface. If you use KNX Router, by setting up the standard multicast ip you're done.
If you use a KNX IP Interface, this should also set as fixed IP. What if your DNS is temporarily not reachable, or you're under dns spoofing attack?
If you have more than one KNX/IP Interface and intend to switch between these if one goes down, you can ever use the Watchdog node.
Or i am missing something?

**Comment by MCsnuffBobbyK** [comment]
Hi,
I do not use multiple KNX interfaces for redundancy - If it breaks down, it gets replaced. And I do not use KNX routers. But I do use KNX interfaces in auto scaling VLAN environment. Therefor I do not use static IP addresses.
KNX is running basically on its own. If DNS would not be available I have bigger problems than reaching KNX interfaces. But I do not see any devices spoofing or DDOSing my DNS in the closed VLAN environment.

**Comment by Supergiovane** [comment]
Hi MC
You could do a dns lookup with some js function, then set the gateway’s IP of the knxultimate gateway by using the watchdog. 
See here. 
https://github.com/Supergiovane/node-red-contrib-knx-ultimate/wiki/-Sample---WatchDog
