### ISSUE TITLE
KNX IP Router Multicast Function Does Not Work

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-knx-ultimate#99]

**Comment by songzh96** [comment]
Hi
I found My Ip Router(Schneider) Multicast Doesn't work.
I can see knx msg on the ETS group monitor, But the device not work.
Do you know what the problem is？

Best Regards
Songzh

**Comment by az4l88** [comment]
hello, post your problem in KNX global group on Facebook. they will help
Nasser Ahmed
(+81)80-4885-9890
az4l88@gmail.com

**Comment by Supergiovane** [comment]
> Hi
> I found My Ip Router(Schneider) Multicast Doesn't work.
> I can see knx msg on the ETS group monitor, But the device not work.
> Do you know what the problem is？
> 
> Best Regards
> Songzh

Hi Songz
It could be some addresses filtering set in the router. Check it and disable all filter rules.

**Comment by songzh96** [comment]
Hi @Supergiovane 
thank you for your answer.
no filtering. I think it is my network problem.

Best Regards
Songzh
